### ISSUE TITLE
`Konva` may lost ids reference while react reconciler works

### ISSUE THREAD

**Issue by lavrton** [konvajs/react-konva#119]
Caught on a large production web app.

Try update this structures:
```
layer
 -> shape with id1
 -> shape with id2
```

To this:
```
layer
  group
    -> shape with id1
    -> shape with id2
```
Then try to find a node by id from a stage.

In this case, React will:
1. create new elements (group and shapes)
2. delete old shapes
3. insert new group and shapes

So new shapes will be created BEFORE old shapes are destroyed. That means same `id` will be used twice. In this scenario, `Konva` will lose references to new shapes by ids.
So this code `stage.find('#id1')` will return undefined. That is the bug.
So direct searching of nodes is broken.

**Comment by kevgathuku** [comment]
Might this be the cause of this error I keep getting:
```
safe-string.js:10 Uncaught TypeError: Cannot read property '_idCounter' of undefined
    at ReactDOMEmptyComponent.mountComponent (safe-string.js:10)
    at Object.mountComponent (safe-string.js:10)
    at ReactCompositeComponentWrapper.performInitialMount (safe-string.js:10)
    at ReactCompositeComponentWrapper.mountComponent (safe-string.js:10)
    at Object.mountComponent (safe-string.js:10)
    at Object.updateChildren (safe-string.js:10)
    at ReactKonvaComponent._reconcilerUpdateChildren (safe-string.js:10)
    at ReactKonvaComponent._updateChildren (safe-string.js:10)
    at ReactKonvaComponent.updateChildren (safe-string.js:10)
    at ReactKonvaComponent.receiveComponent (safe-string.js:10)
```
Or do you think this should be a separate issue altogether?

**Comment by lavrton** [comment]
@kevgathuku this is not related. Please create another issue with the steps to reproduce.

**Comment by kevgathuku** [comment]
Hi @lavrton I created a test repo to try to reproduce the error. However, the [`Stage` event listeners ](https://github.com/kevgathuku/konva-error-repro/blob/master/src/App.js#L85) don't seem to be working. I have no idea why. I'll investigate some more and comment here once I'm able to reproduce

**Comment by lavrton** [comment]
@kevgathuku probably because of: https://konvajs.github.io/docs/events/Stage_Events.html

**Comment by kevgathuku** [comment]
Thanks. That fixed the events, but I'm still not able to reproduce the bug. I'll try once more to make my test and the actual environment more similar.

**Comment by rabiulislamanik** [comment]
what should we use then ? instead of id ?

**Comment by lavrton** [comment]
@rabiulislamanik current recommendation is to use `name` instead of `id`.

**Comment by rabiulislamanik** [comment]
`let renderableItems = this.props.canvasItems.map((e, i) => {
      if (e.type == "image") {
        return (
          <Image
            key={i}
            draggable
            image={e.image}
            name={`image_${i}`}
            width={e.width}
            height={e.width}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      } else {
        return (
          <Text
            key={i}
            draggable
            text={e.textContent}
            name={`text_${i}`}
            fill={e.fill ? e.fill : "green"}
            fontSize={e.fontSize ? e.fontSize : 10}
            className="text"
            fontFamily={e.fontFamily}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      }
    });`
can i use names like this ?

**Comment by rabiulislamanik** [comment]
```let renderableItems = this.props.canvasItems.map((e, i) => {
      if (e.type == "image") {
        return (
          <Image
            key={i}
            draggable
            image={e.image}
            name={`image_${i}`}
            width={e.width}
            height={e.width}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      } else {
        return (
          <Text
            key={i}
            draggable
            text={e.textContent}
            name={`text_${i}`}
            fill={e.fill ? e.fill : "green"}
            fontSize={e.fontSize ? e.fontSize : 10}
            className="text"
            fontFamily={e.fontFamily}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      }
    });```
can i use names like this?

**Comment by rabiulislamanik** [comment]
`let renderableItems = this.props.canvasItems.map((e, i) => {
      if (e.type == "image") {
        return (
          <Image
            key={i}
            draggable
            image={e.image}
            name={`image_${i}`}
            width={e.width}
            height={e.width}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      } else {
        return (
          <Text
            key={i}
            draggable
            text={e.textContent}
            name={`text_${i}`}
            fill={e.fill ? e.fill : "green"}
            fontSize={e.fontSize ? e.fontSize : 10}
            className="text"
            fontFamily={e.fontFamily}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      }
    });
`

**Comment by rabiulislamanik** [comment]
> let renderableItems = this.props.canvasItems.map((e, i) => {
      if (e.type == "image") {
        return (
          <Image
            key={i}
            draggable
            image={e.image}
            name={`image_${i}`}
            width={e.width}
            height={e.width}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      } else {
        return (
          <Text
            key={i}
            draggable
            text={e.textContent}
            name={`text_${i}`}
            fill={e.fill ? e.fill : "green"}
            fontSize={e.fontSize ? e.fontSize : 10}
            className="text"
            fontFamily={e.fontFamily}
            x={e.x}
            y={e.y}
            scaleX={e.scaleX}
            scaleY={e.scaleY}
            rotation={e.rotation}
          />
        );
      }
    });

**Comment by rabiulislamanik** [comment]
![screenshot from 2018-12-27 12-48-01](https://user-images.githubusercontent.com/35958228/50469261-d2c01b00-09d5-11e9-82e6-d91a78555905.png)

how about using 'name' like this ?

**Comment by lavrton** [comment]
Yes, that is the correct way.

**Comment by lavrton** [comment]
Should be fixed. `konva@3.2.2` is using a new `container.find('#id')` algorithm that should not produce such weird results.
