### ISSUE TITLE
react-reconciler failing when using react-konva

### ISSUE THREAD

**Issue by mberry73** [konvajs/react-konva#189]
I'm trying to use react konva in one of my projects but unfortunately it fails with the following error in the development version.

```
react-reconciler.development.js?dbf7:497 Uncaught TypeError: Cannot set property 'getCurrentStack' of undefined
    at Object.setCurrentFiber (react-reconciler.development.js?dbf7:497)
    at performUnitOfWork (react-reconciler.development.js?dbf7:6007)
    at workLoop (react-reconciler.development.js?dbf7:6074)
    at HTMLUnknownElement.callCallback (react-reconciler.development.js?dbf7:1613)
    at Object.invokeGuardedCallbackDev (react-reconciler.development.js?dbf7:1652)
    at invokeGuardedCallback (react-reconciler.development.js?dbf7:1509)
    at renderRoot (react-reconciler.development.js?dbf7:6152)
    at performWorkOnRoot (react-reconciler.development.js?dbf7:6800)
    at performWork (react-reconciler.development.js?dbf7:6753)
    at requestWork (react-reconciler.development.js?dbf7:6664)
```

The easiest way to reproduce it for me was to:
#1 install the react webpack typescript starter kit from
https://github.com/vikpe/react-webpack-typescript-starter
#2 Add the ColoredRect example from https://github.com/lavrton/react-konva into my app.tsx
#3 Start the dev build. (npm run start-dev)

Some additional things:
- It works on the prod build (npm run start-prod)
- I did try it on React 15 & 16.2 & 16.3
- Konva rect version: 1.7.1
- Konva version: 2.0.2

Looking at the place it fails it seems that in the dev version of the react-reconciler resolved this call to undefined:
var ReactDebugCurrentFrame = ReactInternals.ReactDebugCurrentFrame;

While this is failing in the react-reconciler, I'm still wondering if this is because of the usage of the react-reconciler library within Konva, as it works in the prod version.

**Comment by lavrton** [comment]
Probably there is a mismatch in `react` and `react-konva` versions. Can you try the latest versions of `react` and `react-konva`?

**Comment by mberry73** [comment]
Arn't the versions I mention in my post the latest versions?

**Comment by crossSulation** [comment]
I got the same issue, it say when call  function 'isFiberMountedImpl' , arguments 'fiber' is undefined

**Comment by crossSulation** [comment]
I am using react-konva 16.5.2

**Comment by lavrton** [comment]
@crossSulation can you make a small demo to reproduce the issue? what are versions of `react` and `react-dom`. Try to reinstall dependencies. Does it help?

**Comment by KLewin23** [comment]
I just had this issue and didnt find this https://stackoverflow.com/questions/64519916/typeerror-fiber-is-undefined-react-konva-rollupjs/64520232#64520232 reinstalling react konva and konva to the latest version worked for me

**Comment by ghandic** [comment]
I'm having similar issues, even when upgrading `react`, `react-dom`, `konva`, and `react-konva`

**Comment by donixo** [comment]
I installed react-konva and konva without specific version and got `konva 7.1.4` and `react-konva 17.0.0-0` and having same fiber error, then I tried downgrading react-konva to `16.13.0-0` and it worked for me

**Comment by lavrton** [comment]
Probably we should add the more explicit warning because looks like npm warnings are not enough.
