### ISSUE TITLE
Testing with enzyme: Konva._nodeCanvas is not a constructor

### ISSUE THREAD

**Issue by kkarkos** [konvajs/react-konva#190]
Hi, first: thanks for this lib! 

I'm currently writing unit tests for a CRA using "react-konva": "^1.7.2". I always run into the same error when "mount"ing the component which includes the Konva Stage with enzyme.

>  TypeError: Konva._nodeCanvas is not a constructor
> 
>       at Object.createCanvasElement (node_modules/konva/konva.js:749:11)
>       at getDevicePixelRatio (node_modules/konva/konva.js:1250:29)
>       at Object.<anonymous>.Konva.SceneCanvas.init (node_modules/konva/konva.js:1291:48)
>       at Object.<anonymous>.Konva.SceneCanvas.Object.<anonymous>.Konva.Canvas (node_modules/konva/konva.js:1283:10)

together with
```
  console.error node_modules/react-dom/cjs/react-dom.development.js:9627
      The above error occurred in the <Stage> component:
          in Stage (at index.js:682)
          in div (at index.js:678)
          in main (created by styled.main)
          in styled.main (at index.js:605)
          in div (at index.js:599)
          in ConceptMap (created by Connect(ConceptMap))
          in Connect(ConceptMap) (created by WrapperComponent)
          in WrapperComponent
```
Test:
```
  it("render ConceptMap without crashing", () => {
    const wrapper = mount(<ConceptMap store={store} match={match} />);
    const instance = wrapper.instance();
    const stage = instance.stage.getStage();
    const stageRef = instance.stage;
    expect(stageRef.getStage() instanceof Konva.Stage).to.equal(true);
  });
```
It's a connected component with mockStore. This part is working.

The component is way to huge to post here so the skeleton looks like:
   ```
   <div
        ref={c => {
          this.container = c;
        }}
        style={{ paddingLeft, width: "100%", height: "100%" }}
      >
            <Stage
              ref={node => {
                this.stage = node;
              }}
              width={stageWidth}
              height={stageHeight}
              draggable={true}
              onContentMouseMove={this.handleStageMouseMove}
              onContentClick={this.handleStageClick}
              onContentDblClick={this.handleStageDoubleClick}
            >
                <Layer
                  ref={node => {
                    this.drawingLine = node;
                  }}
                >
                  <Line
                    points={[
                      drawingStartPoint.x,
                      drawingStartPoint.y,
                      drawingEndPoint.x,
                      drawingEndPoint.y
                    ]}
                    fill="#000"
                    stroke="#000"
                    strokeWidth={2}
                  />
                </Layer></Stage
</div>
```
setupTests.js
```
import { configure } from "enzyme";
import Adapter from "enzyme-adapter-react-16";
import "jest-enzyme";
import "jest-canvas-mock";

configure({ adapter: new Adapter() });
```
The problem seems to be <Stage> (line 682). Maybe the ref? I added "jest-canvas-mock" for canvas support but the same error comes up, with or without. I looked at the react-konva tests and tried to replicate as much as possible. The error does not disappear.

I commented out <Stage> and the component is mounting correctly and test runs successful. 

Any idea?

**Comment by lavrton** [comment]
It will be really good if you can create super small repo with the issue, so we can play with it.

The root of the error is that `Konva` is detecting nodejs env and trying to use `node-canvas` module.

**Comment by chrismacp** [comment]
Hello, I have the same issue and created a repo here: 

https://github.com/chrismacp/react-konva-problem

I created an app using create-react-app and I have only added one single component to the app. The pre-existing App test fails. I removed the MyComponent test as that failed in exactly the same way.

**Comment by lavrton** [comment]
I published a new version. It will skip canvas rendering if the environment is not a browser (like node + jsdom). It fix the fail. Not sure about more complex tests like snapshots.
