### ISSUE TITLE
Uncaught TypeError: this.getContainer(...).removeChild is not a function when running jest storyshot with react-konva

### ISSUE THREAD

**Issue by adamchenwei** [konvajs/react-konva#200]
I used storybook to build demo, and when i switch bewteen two different stories, which load same component but with different props, this comes up. Also when jest is running the storyshot test, it shows error with `Error: Uncaught 'Stage has no container. A container is required.'`

What could be the cause?

I declared my Stage like following

```
<Stage
              container={(node) => {
                this.containerNode = node;
              }}
              width={stage.width}
              height={stage.height}
              ref={(node) => {
                this.stageNode = node;
              }}
```

and I see that because of this, seems the container is not set correctly....

It does not help even if I replace what inside `container` to be a React Component that is a pure styled-component like `container={<FullView />}`

I see this.container should be really something else that has `.removeChild()` function... is there something need to be fixed inside lib or my config?

here is a screenshot of where went wrong
<img width="707" alt="screen shot 2018-04-26 at 11 04 38 am" src="https://user-images.githubusercontent.com/4201698/39314388-20f03d3c-4942-11e8-8689-4f4590420055.png">

Any help on this?

 

Is this because I use a newer version of react .16?

**Comment by lavrton** [comment]
Should be fixed with the last versions.
