### ISSUE TITLE
canvas disappear after fontSize and width change for Text component, why?

### ISSUE THREAD

**Issue by adamchenwei** [konvajs/react-konva#208]
I have a component will pure props and state controlled by upper component passed down (i.e. redux store), and seems the changing of width and fontSize will make the canvas group just somehow disappear once I start dragging it (It was set draggable), and it will come back if I set it to another width and fontSize, and then disappear again once I start dragging it....

I tried to do this.xxxNode.draw() in componentDIdUpdate life cycle, it did not help.

Anyone aware what could be the cause of this issue?

**Comment by adamchenwei** [comment]
dont know why. but `setTimeout` fixed it, took me few hours to realize...

**Comment by lavrton** [comment]
@adamchenwei can you create a small demo of your issue?

**Comment by adamchenwei** [comment]
@lavrton
I never did, but try my playground repo! The timeout there is the same setup how I setup my actual project!
