### ISSUE TITLE
dragBoundFunc problem

### ISSUE THREAD

**Issue by domehead100** [konvajs/react-konva#221]
Just trying out react-konva, and it seems very good, but I'm having a strange situation and could use some direction.

I'm rendering an array of Group components (each of which has several Rect components inside the Group) and using dragBoundFunc to constrain the dragging of the Group elements so that they cannot intersect. 

Using the dragBoundFunc, the pos.x is locked at 0 to only allow dragging in the y direction.

In order to constrain the dragging in the y direction, I get the bottom of the Group above the dragged group (the previous Group) and the top of the Group below it (the next Group), and then constrain the returned pos.y so that the dragged group doesn't intersect with the previous or next Group.

In the onDragEnd handler, I'm updating the absolute coordinates of the dragged Group so that they will be up to date if group above or below it is then dragged.

I'm seeing a couple of oddities:

1) The documentation says ```"Note: dragBoundsFunc is working with absolute position of a node. So it has a new absolute position as argument and you need to return a new absolute position."```  In fact this is not true and the x and y are relative to the starting position of the node and seem to represent the distance the node has been dragged, not the current absolute position of the node.  For example, when dragging downward, the first pos.y is 0, then 1, then 2, etc., even though the absolute y position of the Group is, for example, 239.  I can get the absolute position by keeping a ref to every node and calling getAbsolutePosition(), but this is not how the docs say it works.

2) If I drag a node and release the mouse, drag another node and release the mouse, and come back and drag the first node again, I would expect that the pos.y starts out at 0 since this is a new drag operation on this node.  In fact, it starts out at whatever the pos.y was the last time the node was dragged (so, it seems to represent the current position relative to the first time the node was ever dragged).  In other words, drag a node the first time and the first pos.y is 0.  Drag it 25px down and release the mouse (the pos.y on the last dragBoundFunc call was 25).  Now drag the node again, the first pos.y passed to dragBoundFunc is 25, when I would expect it to be 0 since this is a new drag operation.

Is there something I need to do to "end" the drag operation and "reset" the pos passed to the dragBoundFunc when a new dragging operation starts?

**Comment by lavrton** [comment]
> In fact this is not true and the x and y are relative to the starting position of the node and seem to represent the distance the node has been dragged, not the current absolute position of the node

Do you have a demo? In this demo, I see absolute position: http://jsbin.com/bihuliwowu/1/edit?js,output

**Comment by lavrton** [comment]
Closing for now. Add more info if you still have issues.

**Comment by domehead100** [comment]
Sorry for the noise and for not responding sooner.  Looks like in my case I was rendering Group components around collections of Rect components and making the Groups draggable so that all of the child components would drag as one unit.  Maybe this is not the right way to do things, I'm just getting started looking at Konva.

Here's a tweak to the jsbin you provided (thanks for that) where a Group is used.  When the dragBoundFunc is attached to the Group, seems to me that the x/y in the passed-in pos are relative to the starting position of the Group, not absolute within the canvas element.

**Comment by lavrton** [comment]
It logs the absolute position of the group. You set `x = 0` and `y = 0`. And that is the absolute position of the group, not absolute position of circle.

**Comment by domehead100** [comment]
Ah.  Thanks, makes sense.
