### ISSUE TITLE
Is it possible to use webGL context?

### ISSUE THREAD

**Issue by Victordmdb** [konvajs/react-konva#222]
Hi,

I need to have multiple layers, one which loads images very quickly (using webgl preferably),

And the other, overlaid on top to draw graphics.

I've tried hacking the canvas created in the Layer object to a new canvas so the webgl context can be created, but still doesn't seem to work.

**Comment by lavrton** [comment]
No, currently it is not possible. Konva supports only 2d context.
If you need WebGL layer, take a look into http://pixijs.io/
