### ISSUE TITLE
Transformer does not gets destroyed, I have to put it on a new layer and destroy that layer!!!

### ISSUE THREAD

**Issue by bushra376** [konvajs/react-konva#223]

**Comment by lavrton** [comment]
@bushra376 how did you try to destroy it?

**Comment by bushra376** [comment]
`  transformHide = e => {
    this.tr.destroy()
    this.layer2.destroy()
  }`
Here, this.tr has the transformer saved in it. But when i destroy it, it remains there

**Comment by lavrton** [comment]
In `react-konva` you don't need to destroy nodes manually. You just need to remove it from `render` function.
