### ISSUE TITLE
use React.Portal to render DOM with konva

### ISSUE THREAD

**Issue by setdvd** [konvajs/react-konva#231]
Hi!

Both konva and reac-konva is super cool. thanks for sharing and suporting.

I'm trying to create some re-usable react components that support text input and edits (smth like https://konvajs.github.io/docs/sandbox/Editable_Text.html)

It will be cool if it will be possible to use React Portal to render DOM input (textarea, content editable etc) in separate div. Currently, it throws an error in renderer as not supported konva element.

Is it possible and what should be done to support Portal API to render DOM elements outside of canvas?

**Comment by lavrton** [comment]
Currently, I don't see ways to implement it. So there is only one way around - render your DOM nodes out of `Konva` nodes tree.

**Comment by ejarzo** [comment]
@setdvd I was running into this issue as well after attempting to upgrade `[react-portal](https://github.com/tajo/react-portal)` to the latest version. I have not looked into the implementation, but if you want something that works (portal nested in the react Konva tree) then try using `react-portal@^3.2` (docs: https://github.com/tajo/react-portal/blob/master/READMEv3.MD). This version was before `React.Portal` was added to the React spec and it works for me!

Example of how I used it inside a Konva layer: https://github.com/ejarzo/Shape-Your-Music/blob/master/src/components/Shape/Component.jsx#L142

**Comment by lavrton** [comment]
@ejarzo thanks for the tips, it really works good:

```js
import React, { Component } from "react";
import ReactDOM from "react-dom";
import Konva from "konva";
import Portal from "react-portal";
import { Stage, Layer, Rect, Text } from "react-konva";

class App extends Component {
  render() {
    return (
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <Portal isOpened={true}>
            <input
              style={{ position: "absolute", top: 0, left: 0 }}
              placeholder="DOM input from Konva nodes"
            />
          </Portal>
          <Rect
            x={20}
            y={20}
            width={50}
            height={50}
            fill="red"
            shadowBlur={5}
          />
        </Layer>
      </Stage>
    );
  }
}

ReactDOM.render(<App />, document.getElementById("root"));
```
demo: https://codesandbox.io/s/r7omxq9nzn

**Comment by ejarzo** [comment]
No problem, thanks for putting the demo together @lavrton!

**Comment by emorling** [comment]
I am curious. How are you placing the Portal in relationship to editable elements in Konva? E.g. a text in the middle of the Stage?

**Comment by ejarzo** [comment]
IIRC the only way to do so is to use `absolute` positioning to place the portal. I passed in the mouse position as props to my portal component and used that to position the portal next to the mouse. If you are not using the mouse, you probably have to get the x/y coordinates of the Konva element you want to use as a reference and pass those to your text component.

**Comment by lyleunderwood** [comment]
Just as a data point, I did this by rendering my div outside of the konva tree. Is there a reason react-portal stopped supporting this?

**Comment by lavrton** [comment]
I created this demo: https://konvajs.github.io/docs/react/DOM_Portal.html
I think it works very well.

**Comment by jquense** [comment]
This way of implementing Portals isn't ideal, `context` for instance, is lost in the new tree. Is there a way of using react's `createPortal` implementation to do this? @gaearon are non-dom portals currently possible?

**Comment by canastro** [comment]
I'm also facing the same issue as @jquense. Using the approach in react-konva documentation makes my components lose access to context. I tried something like this:

```js
class Portal extends React.Component<PortalProps> {
  render() {
    return (
      <MazeContext.Consumer>
        {value => (
          <InnerPortal>
            <MazeContext.Provider value={value}>{this.props.children}</MazeContext.Provider>
          </InnerPortal>
        )}
      </MazeContext.Consumer>
    );
  }
}
```

But with this approach I get the following error: 

```
Warning: Detected multiple renderers concurrently rendering the same context provider. 
This is currently unsupported.
```

Anyone faced this before? How can we address this issue? 

@lavrton  do you have any suggestion that I can try?

**Comment by lavrton** [comment]
@canastro can you make a small codesandbox demo to play with it?

**Comment by canastro** [comment]
@lavrton when I faced this bug I ended up analysing the app and figured out that everything I was calling in a portal I could just have in a div sibling to the canvas, so I ended up refactoring away from the portal and don't have the code to replicate it anymore. If I face the same issue again in the future, I'll make sure to replicate it in a codesandbox. Sorry.
