### ISSUE TITLE
How to use clearRect

### ISSUE THREAD

**Issue by kairi1227** [konvajs/react-konva#234]
How to use `clearRect()` function ?

**Comment by lavrton** [comment]
@kairi1227 why you may need to use it?

**Comment by kairi1227** [comment]
I want to implement the following effect, clear a part of Rect.
![clearrect](https://user-images.githubusercontent.com/4525647/43884549-fc98fbaa-9be8-11e8-9501-f4f427054bb0.png)

**Comment by kairi1227** [comment]
`<Rect  sceneFunc={context => {context.clearRect(x, y, width, height)}}/>`  can implement, but no description in the document.
