### ISSUE TITLE
Event handling out of place after transforming scale

### ISSUE THREAD

**Issue by lunzhang** [konvajs/react-konva#236]
None of the events are working like clicks after i transform scale a wrapper element

https://codesandbox.io/s/7zjv863r9q

**Comment by lavrton** [comment]
That is a limitation of a current hit detection. Do not transform container elements with CSS.

**Comment by grydstedt** [comment]
i have a parent container that is forcing a transform unfortunately. are there any work arounds to make this work? by applying some offset or something?

**Comment by lavrton** [comment]
@grydstedt what transform it have?

**Comment by grydstedt** [comment]
I figured I could apply the opposite `scale` value to stage. So if outside is scaling by `0.5` I could scale `Stage` with `1.5` to correct, but I don't think it's working.

**Comment by lavrton** [comment]
Moved the issue to here: https://github.com/konvajs/konva/issues/500
