### ISSUE TITLE
How to set Stage size to 100% of parent HTML element?

### ISSUE THREAD

**Issue by balintn22** [konvajs/react-konva#238]
In the examples I found two ways of setting the canvas size:
- specific in pixels
- or setting to full windows size: width={window.innerWidth} height={window.innerHeight

Now I'm creating a component, that would be overlaid on the parent HTML element, to draw on it, say a large X of two lines. I'd like to set the size of the canvas (React Stage component) to the size of the parent.
I tried these:
- Set Stage width and height to 100%
- Set parent style.position: relative (to create a positioning anchor), set Stage style.position: absolute and width, height to 100%

But whatever I do, the underlying HTML component class="konvajs-content" has position: relative, and width and height 0.

Any ideas?

**Comment by lavrton** [comment]
I think this will help you: https://stackoverflow.com/a/49973571/512042

If not - add your comment.

**Comment by balintn22** [comment]
That was quick :-)
In the end I did something similar, so in the case of the mentioned "cross example"

    constructor(props) {
        super(props);
        this.state = {
            width: props.width,
            height: props.height,
            parentNode: undefined
        }
    }

    componentDidMount() {
        // Remember the parent node.
        this.setState({
            parentNode: ReactDOM.findDOMNode(this).parentNode
        });
    }

    render() {
        // Use parent node dimensions to calculate drawing sizes.
        var parentRect = this.state.parentNode && this.state.parentNode.getBoundingClientRect();
        var parentWidth = parentRect ? parentRect.width : 0;
        var parentHeight = parentRect ? parentRect.height : 0;
        var crossLeft = parentWidth * 0.1;
        var crossRight = parentWidth * 0.9;
        var crossTop = parentHeight * 0.1;
        var crossBottom = parentHeight * 0.9;
        return (
            <Stage className="Crossout-overlay" width={parentWidth} height={parentHeight} >
                <Layer className="Crossout-layer" >
                    <Line points={[crossLeft, crossTop, crossRight, crossBottom]} stroke="red" strokeWidth={5} />
                    <Line points={[crossLeft, crossBottom, crossRight, crossTop]} stroke="red" strokeWidth={5} />
                </Layer>
            </Stage>
        );
    }
