### ISSUE TITLE
Is it possible to style graphics elements from css?

### ISSUE THREAD

**Issue by balintn22** [konvajs/react-konva#239]
What I found is that each graphics component has their set of properties, like stroke="red" strokewidth={5} for a Line component.
Is it possible to set them from css?
The reason for asking is that the visual appearance of the graphics could be driven by a designer, rather then a developer.

**Comment by lavrton** [comment]
No. `react-konva` is using canvas rendering that is out of CSS styling and DOM structure. You may try to use SVG instead of `react-konva`.

Or you can ask the designer to edit render function. Or move all styling variables into a separate file.
