### ISSUE TITLE
Z-order issue with modals

### ISSUE THREAD

**Issue by balintn22** [konvajs/react-konva#240]
I created some overlay graphics on some of my page elements.
Now I'm adding a modal on top of the page (React Modal), but the graphics from the overlay show in an incorrect z-order (on top of the modal).
How do I specify the correct z-order?

![image](https://user-images.githubusercontent.com/11978299/44275114-d380bd80-a23b-11e8-8ecd-02314c491f3b.png)

**Comment by lavrton** [comment]
I think it is not related to `react-konva`, so I am closing the issue. If you think it is related, please provide a demo.
