### ISSUE TITLE
Is `anchorSize` supported for Transformer?

### ISSUE THREAD

**Issue by kouariga** [konvajs/react-konva#241]
Below is a code snippet from the [GETTING STARTED](https://konvajs.github.io/docs/react/Transformer.html).
 
```
<Transformer
    ref={node => {
        this.transformer = node;
    }}
/>
```
I expected that I can change the anchor size by adding `anchorSize={20}` prop to the Transformer component, but it didn't work. It doesn't give any error either. Just FYI, I confirmed that `rotateEnabled` works and `enabledAnchors` doesn't.

Am I using the props incorrectly, or are there some props that aren't supported? Thank you in advance.

**Comment by lavrton** [comment]
You need to update `Konva` to the latest version. It will work just fine: https://codesandbox.io/s/v6qjl0lrj5
