### ISSUE TITLE
Example usage of Konva.Animation?

### ISSUE THREAD

**Issue by marcofugaro** [konvajs/react-konva#243]
Hi, does this support  Konva.Animation also? Is there an example?

**Comment by lavrton** [comment]
Yes, you can access Konva nodes as `ref` of React components. Then just follow `Konva.Animation` logic as in tutorials. What is your use case?

**Comment by lavrton** [comment]
Simething like this:

```js
class App extends Component {
  componentDidMount() {
    var amplitude = 1;
    var period = 500;

    var anim = new Konva.Animation(frame => {
      this.rect.opacity((Math.sin(frame.time / period) + 1) / 2);
    }, this.rect.getLayer());

    anim.start();
  }
  render() {
    return (
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <Rect
            x={20}
            y={20}
            width={50}
            height={50}
            fill="green"
            shadowBlur={5}
            ref={node => {
              this.rect = node;
            }}
          />
        </Layer>
      </Stage>
    );
  }
}
```
https://codesandbox.io/s/1oml6z6524

Also you can try to use `react-spring`: https://konvajs.github.io/docs/react/Complex_Animations.html

**Comment by marcofugaro** [comment]
Cool, thanks for the example!

**Comment by marcofugaro** [comment]
Oh weird I've used react-konva for months and didn't notice it had documentation on the konva website,  always relied on the readme

**Comment by lavrton** [comment]
Yeah. It is a new section made recently.
