### ISSUE TITLE
TypeError: ReactInternals is undefined

### ISSUE THREAD

**Issue by HachimDev** [konvajs/react-konva#246]
Hi, When i import react-konva this is the error I get : TypeError: ReactInternals is undefined

```
import Konva from 'konva';
import {Stage} from 'react-konva';
```
Im working with react 15.6.1
those are the dependencies :
    "react": "^15.6.1",
    "konva": "^1.7.6",
    "react-konva": "^1.1.6",

any help please ?

**Comment by lavrton** [comment]
Make sure `react-konva` has exactly version `1.1.6`.

```
npm install react-konva@1.1.6
```

But it is better to just update `react` and `react-konva` to the latest versions.

**Comment by HachimDev** [comment]
Thanks ! this seem to work perfectly.
I can't update to the latest version though.
