### ISSUE TITLE
Should we use refs

### ISSUE THREAD

**Issue by emorling** [konvajs/react-konva#247]
I want to change the fill color of a Rect upon drag-n-drop collision. All examples seem to involve changes made through updating the state and render() method.

Is it an alternative to use something like this

`group.findOne('.fillShape').fill('red');
`
As in this example
https://konvajs.github.io/docs/sandbox/Collision_Detection.html

And should we in that case store refs to the Rect we want to change the fill in?

**Comment by lavrton** [comment]
You can change attributes of nodes (such as `fill`) manually. But it is not declarative "react-way". So I suggest to avoid manual access. 

There is one case where you can see the unexpected result. If you try to set `fill` in both manual way and inside `render()` function. `react-konva` controls atributes of nodes. It match them exactly as described in `render()` function. So if you change `fill` manually, later on component rerender `react-konva` will see that its value is not the same as in `render()`, so it will change it. It may be unexpected change for you.

You can use `group.findOne('.fillShape').fill('red');`. But in this case it is better not to set `fill` in `render()`.

**Comment by emorling** [comment]
So what do you suggest to be the best practice way to do it? Always via state and render?

**Comment by lavrton** [comment]
> Always via state and render?

Yes. I think that is the best practice if you use `react-konva`.
