### ISSUE TITLE
Expected subtree parent to be a mounted class component error with React 16.5

### ISSUE THREAD

**Issue by blooddrunk** [konvajs/react-konva#250]
I've got below error after upgrading React to 16.5

```
Uncaught Error: Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.
```

Downgrade  React solves it.

This can be reproduced simply by upgrading react-dom in one of the official examples on [codesandbox](https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/images?from-embed)

Thanks for your help!

**Comment by lavrton** [comment]
I updated all dependencies to the latest versions and published. Tests are ok.  Can you try to update and see the result?

https://codesandbox.io/s/6vk7wy0xzn

**Comment by lavrton** [comment]
Seems to work ok now. I will close the issue. Thanks for the report! Let me know if it still doesn't work for you.

**Comment by blooddrunk** [comment]
It works now, thanks a lot for the quick fix.
