### ISSUE TITLE
v1.7.15 causes: "Expected subtree parent to be a mounted class component"

### ISSUE THREAD

**Issue by leap29** [konvajs/react-konva#251]
I've just come across Konva and react-konva today.  It's really cool and exactly what I needed but have found an issue with the latest version.

When upgrading from v1.7.14 to v1.7.15 the following exception is thrown in my React / redux application:

"Expected subtree parent to be a mounted class component.  This error is likely to be a bug in React. Please file an issue."

Stops happening when I change the package.json's react-konva version back to 1.7.14.

I used the code sandbox at https://codesandbox.io/s/xv8kmkjkwp to swap out versions until it broke / worked again.

**Comment by lavrton** [comment]
Update to latest deps: https://github.com/konvajs/react-konva/issues/250
