### ISSUE TITLE
How is Layer.add accessed?

### ISSUE THREAD

**Issue by wadeanthony0100** [konvajs/react-konva#252]
I've been trying to add a new shape object to an existing Layer in response to a click event. (Feel free to tell me that's not how this package works 🤣) Just a quick sample to demonstrate what I've tried:

```js
import React from 'react';
import { render } from 'react-dom';
import { Stage, Layer, Circle } from 'react-konva';

const myLayer = <Layer />;

const App = () => <Stage>{myLayer}</Stage>;

render(<App />, document.getElementById('root'));

// Later when the user clicks on something, but we can try this now why not
const myNewRuntimeElement = <Circle/>;

myLayer.add(myNewRuntimeElement);
```

BUT, this yeilds an error: ` TypeError: myLayer.add is not a function`

"Okay, well if its not here, where do I go?"

I tried reaching into the Layer ref...

```js

let myLayerRef;
const myLayer = <Layer ref={node => myLayerRef = node}/>;
...
myLayerRef.add(myNewRuntimeElement);

```

...Which has the `add` function defined, but gives an error: `TypeError: child.getParent is not a function`.

I get the same error if I pass the circle's ref to `add`, but that feels like a react anti-pattern rabbit hole I'd prefer not to go down. Is this something I can accomplish with this tool, and if so, how?

Thanks! 😄

**Comment by lavrton** [comment]
If you are using `react-konva` you don't need to add nodes into `Layer` (or `Group` or `Stage`) manually.

Similar like in `react` you don't need to touch DOM manually and you don't need to use `element.appendChild(anotherElement)`.


If you want to add circle into the layer on user's click you need to have a state that determanates that the circle is visible or not. Then in render you should do something like this:

```jsx
<Layer>
   {this.state.shouldShowCircle && <Circle />}
</Layer>
```

On click you can do something like this:

```javascript
handleClick = () => {
    this.setState({
       shouldShowCircle: true
    })
}
```

Does it help?

**Comment by wadeanthony0100** [comment]
Yes, thanks

**Comment by victormanuelfrancodev** [comment]
good question.. I think this need a example.. thanks!

**Comment by victormanuelfrancodev** [comment]
I want to add Transform in my Rect , but I don't know how
`  render() {
    return (
      <Rect
       name = "rectangulo"
        ref={node => {
          this.rect = node;
          this.transformer = node;
        }}
        x = {this.props.rectangulo.x}
        y = {this.props.rectangulo.y}
        width= {this.props.rectangulo.width}
        height= {this.props.rectangulo.height}
        fill= {this.props.rectangulo.fill}
        onClick = {this.prueba}
      />
    );
  }`

**Comment by lavrton** [comment]
@victormanuelfrancodev did you look at this demo: https://konvajs.org/docs/react/Transformer.html ?

**Comment by edemlock** [comment]
How can I add for example a Rect to the layer multiple times. I mean... I have an image that has an onClick function. Sooo If I click on the image it draws the rectangle to the layer/stage/canvas (I don't know how to say that). So if I want to add 3 or 4 rectangle to my canvas, I click on the image 3 or 4 times. I work in react konva and hope you understand what I want to say.

**Comment by victormanuelfrancodev** [comment]
Hello @edemlock try to do a Array 

```
  this.state = {
        rects: []
  }  
```

```
  const shapes = [...this.props.rects];
           const shape = shapes.find(shape => shape.name === name);
            if (shape) {
              this.props.selectShapeName(name);
            } else {
              this.props.selectShapeName('');
            }
```
In your component you need declare a name 
```
  render() {
    return (
      <Rect
        name = {this.props.name}
        x = {this.props.x}
        y = {this.props.y}
        width= {this.props.width}
        height= {this.props.height}
        fill= {this.props.fill}
        stroke={this.props.stroke}
        strokeWidth={this.props.strokeWidth}
        draggable
      />
    );
  }
}
```

**Comment by edemlock** [comment]
Hello @victormanuelfrancodev okay, thanks it is clear! The rect is drawn on the layer by an array, but I want to draw it as many times as I click on my image
Or how do I write the function that I call on onClick()?
So what do I write to my onClick function? 

render() {
    return (
<td id="headerL">
                  {" "}
                  <img
                    src={LineImg}
                    alt="line"
                    onClick="LineDraw()" //Yeah I know it's bad, but in earlier it was perfect without react
                    style={{
                      width: 50,
                      height: 50,
                      border: 1
                    }}
                  />
                </td>
)}

Because I tried some solutions, but none of them worked and I confused. This is my first program in react. I'm implementing an earlier code that I wrote in pure javascript and konva.

**Comment by Rakotoarisoa** [comment]
> ```js-jsx
> <Layer>
>    {this.state.shouldShowCircle && <Circle />}
> </Layer>
> ```
@lavrton  Thanks for your reply. 
What if I have a many component to manage and add dynamically new components? 
![test1](https://user-images.githubusercontent.com/12233088/63858735-b59d7b00-c9ae-11e9-9251-0ffa2de07c9e.png); 
I've created some Table class which render a group of shapes(table[rect], chairs[circle] )...

**Comment by Rakotoarisoa** [comment]
Thanks . But adding them through some create button ... and eventually remove table, etc... .
![Sans titreu](https://user-images.githubusercontent.com/12233088/63860933-a5879a80-c9b2-11e9-965c-a19d0d2a0ba0.png)

**Comment by Rakotoarisoa** [comment]
Okay. Thanks.
