### ISSUE TITLE
Konva instance is already exist in current eviroment. Please use only one instance.

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [konvajs/react-konva#253]
why？？
![image](https://user-images.githubusercontent.com/11493796/45869944-54435400-bdbc-11e8-84c2-3c331cda8081.png)

![image](https://user-images.githubusercontent.com/11493796/45869955-5c02f880-bdbc-11e8-8c6b-7d4355ebe290.png)

**Comment by lavrton** [comment]
That may happen if you (or your bundler) added konva source into page twice. Can you check it?
