### ISSUE TITLE
Expected mounted comlponent ...

### ISSUE THREAD

**Issue by GetRobb** [konvajs/react-konva#257]
![capturecode](https://user-images.githubusercontent.com/43639590/46140451-7112d800-c251-11e8-97c6-99e7b60cd5d5.PNG)
![captureerror](https://user-images.githubusercontent.com/43639590/46140453-72dc9b80-c251-11e8-8343-2890eb44d53f.PNG)

The error seems to come from the `<Stage>` component. I already tried to use a "mounted" boolean that updates to true when `CompoenentDidMount` is triggered and then initiates to return the react-konva part of the code, but didin't work...

**Comment by lavrton** [comment]
What versions of `react`, `react-dom` and `react-konva` are you using?

**Comment by lavrton** [comment]
Or can you provide `package-lock.json`?

**Comment by GetRobb** [comment]
React-Dom version 16.4.2
React-konva version 1.7.15
React version 16.5.2

**Comment by GetRobb** [comment]
OK i've just updated my React Dom package and it seems to work now ... Thanks anyway for your suggestion and the fast reply !
