### ISSUE TITLE
Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by wss534857356** [konvajs/react-konva#263]
**Description**
Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue

**Steps to reproduce**
1.
```javascript
import React, { Component } from 'react';
import { render } from 'react-dom';
import { Stage, Layer, Rect, Text } from 'react-konva';
import Konva from 'konva';

class ColoredRect extends React.Component {
  state = {
    color: 'green',
  };
  handleClick = () => {
    this.setState({
      color: Konva.Util.getRandomColor(),
    });
  };
  render() {
    return (
      <Rect
        x={20}
        y={20}
        width={50}
        height={50}
        fill={this.state.color}
        shadowBlur={5}
        onClick={this.handleClick}
      />
    );
  }
}

class App extends Component {
  render() {
    return (
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <Text text="Try click on rect" />
          <ColoredRect />
        </Layer>
      </Stage>
    );
  }
}

render(<App />, document.getElementById('root'));
```

2.Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue

Additional info
react-konva: "^1.7.16",
React: "^16.5.0",
ReactDOM version:16.5.0
konva: "^2.4.1",

**Comment by lavrton** [comment]
That is a version mismatch between `react-konva` and `react`. The issue will be fixed if you update `react` and `react-dom` to the latest version.
I am thinking,  `react-konva` version should exactly match versions of `react`. So `react-konva` version should be `16.5.2` if it works ok with `react v 16.5.2`

**Comment by wss534857356** [comment]
It works, thank for u help.
