### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [konvajs/react-konva#269]
I just saw the package is updated from `v1.7.16` to `v16.5.2` which implies breaking changes, but I can't find any CHANGELOG to check them out.

Would you guys be so kind to provide us with a decent CHANGELOG for every package, please? 🙂

Thanks for all your hard work! 🙂

**Comment by lavrton** [comment]
Sure the changelog will be here https://github.com/konvajs/react-konva/releases

`v16.5.2` doesn't have breaking changes. The version is changed to match `react` version.
