### ISSUE TITLE
[SOLVED] Error running tests: Cannot read property 'webkitBackingStorePixelRatio' of null

### ISSUE THREAD

**Issue by pleopardi** [konvajs/react-konva#270]
I have a create-react-app project, not ejected, no custom setup.

When I run `npm run test` I get the following error:

> TypeError: Cannot read property 'webkitBackingStorePixelRatio' of null

The only test running is the one included with create-react-app, that is:

```
it("renders without crashing", () => {
  const div = document.createElement("div");
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

Test aside, the app renders properly, no warnings or errors in console.

In the error stack in the console I see three distinct blocks, here's the first two lines for each:

> console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

>  console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Uncaught [TypeError: Cannot read property 'webkitBackingStorePixelRatio' of null]

> console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Uncaught [TypeError: Cannot read property 'current' of undefined]

The error seems related to jsdom limitations, so I also tried to install canvas and canvas-prebuilt as dev-dependencies with no luck.

Any idea on how to solve this?

**Comment by lavrton** [comment]
`create-react-app` uses `jest` and node environment to run tests. Currently `react-konva` doesn't support nodejs env. As a workaround, you can try to run tests with karma (in browsers env).

I will try to find a solution to run tests under nodejs.

**Comment by lavrton** [comment]
Try to do this before all tests `Konva.isBrowser = false;`. The simple test works ok for me.

**Comment by lavrton** [comment]
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

Konva.isBrowser = false;

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

**Comment by pleopardi** [comment]
It worked!

Amazing simple solution, many thanks for the help @lavrton
