### ISSUE TITLE
Update stage width & height while download final canvas image

### ISSUE THREAD

**Issue by nzhtrtlc** [konvajs/react-konva#272]
Hi, i did something like that;

https://codesandbox.io/s/wkzpz40217

1- Choose an image
2- Move red object into image
3- Export final image

Final image will download for you but problem is width and height of the final image. 
I want to the get exact same width & height of image which you choose at the first step.
Otherwise final image includes unnecessary blank spaces.
Any solution ?

**Comment by lavrton** [comment]
Do you want to export an image or a stage?

**Comment by nzhtrtlc** [comment]
Actually i figured it out. I implemented redux and i pass the width and height values into redux. When i download the final image i updated stage component's width and height. It seems works now.
Thank you anyway. we can close this one.
