### ISSUE TITLE
Define tweens/animations in jsx

### ISSUE THREAD

**Issue by danbriggs5** [konvajs/react-konva#273]
The current method of applying an animation or tween is to manually apply it using a ref. Would it be possible to add the ability to define a tween in jsx? For example:

```
class MyRect extends React.Component {
	state = {
		scaleX: 1,
		scaleY: 1,
	};

	changeSize = () =>
		this.setState({
			scaleX: Math.random() + 0.8,
			scaleY: Math.random() + 0.8,
		});

	render() {
		const { scaleX, scaleY } = this.state;

		return (
			<Rect
				width={50}
				height={50}
				fill="green"
				draggable
				onDragEnd={this.changeSize}
				onDragStart={this.changeSize}
				to={{
					scaleX,
					scaleY,
					duration: 0.2,
				}}
			/>
		);
	}
}
```

That seems more declarative. Is there anything that prevents this from being possible? I'm not super familiar with konva yet so it's quite possible I'm missing something!

**Comment by lavrton** [comment]
You already can do this with external animation library `react-spring`. See demo here: https://konvajs.github.io/docs/react/Complex_Animations.html
