### ISSUE TITLE
Do react-konva make canvas use “reactive”?

### ISSUE THREAD

**Issue by callagga** [konvajs/react-konva#277]
Just a basic question if I may on react-konva (/konva).  Does using react-konva make use of HTML5 canvas “reactive”, or is it more just a means to use a react “component” approach to laying out your code?   

For example, with react-konva can you just create a render function that draws your canvas shapes etc how you want to see them, then if you change the size or position of one shape, then react-konva arranges under the bonet for a refresh to the canvas but only to this shape?  (Or perhaps there’s also konva itself, or canvas getting in the mix here?).   So I guess if in your react-konva shape definitions you have javascript variables from the state (e.g. this.state.nextTime) then is this all that is need to trigger the “reactiveness” of react-konva.

Overally consideing using Canvas, and via react-konva, but wanting to understand how “reactive” it would be.  In other words how much (if any) manual tracking of management of canvas refreshes would I have to do myself.

**Comment by lavrton** [comment]
You don't need to think about management of canvases refreshes. All you need is to define node's tree of your canvas (Stage, Layers, Groups, Shapes). `react-konva` and `Konva` will create virtual nodes of all objects and draw everyting on canvas. If you change some props `react-konva` will update them too and redraw the canvas.

On canvas you can't realy redraw just one shape, if you update any shape, `Konva` will clear the canvas and draw all the shapes into canvas from scratch.

I hope it helps to clarify.
