### ISSUE TITLE
(React 16.6) Expected subtree parent to be a mounted class component.

### ISSUE THREAD

**Issue by schester44** [konvajs/react-konva#278]
Upgrading to 16.6 seems to cause the below error.

Example usage:
```
<ReactKonva.Stage scale={scale} width={width} height={width}>
    <ReactKonva.Layer>
        <ReactKonva.Image x={0} y={0} width={width} height={height} image={this.props.image} />
    </ReactKonva.Layer>
</ReactKonva.Stage>
```

Error 
Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.

**Comment by Proavus** [comment]
Hi schester44, please take a look at package.json and make sure you've updated all of these packages to 16.6: react, react-dom, react-konva. Let me know if this helps.

**Comment by lavrton** [comment]
I think we need to add a runtime error (or a warning) if there is a version mismatch between `react` and `react-konva`. There are too many related issues.

**Comment by lavrton** [comment]
I made a release `16.6.1` with the working. I hope it will be clear now what is going on.
