### ISSUE TITLE
react-konva may not display Image at the specific x,y coordinates on the Canvas

### ISSUE THREAD

**Issue by audricFeuyan** [konvajs/react-konva#279]
All Image objects displayed in a react-konva layer stay at the top right corner ignoring the x,y coordinates specified.
 @lavrton  @tyler-johnson  @jamiemchale  @markov00

**Comment by audricFeuyan** [comment]
![demo](https://user-images.githubusercontent.com/11914213/47501267-fb545900-d85c-11e8-88f0-a10139805b89.gif)
Here is a demo.

**Comment by lavrton** [comment]
I mean code sample or online demo made in something like codesanbox?  https://codesandbox.io/s/nn9p9plkw4

**Comment by audricFeuyan** [comment]
The problem was mine sorry. I was not specifying the right coordinates in my Image React component. Thank a lot for your prompt reaction !
