### ISSUE TITLE
Testing react-konva code with Enzyme: bugs / best practices?

### ISSUE THREAD

**Issue by davidsoergel** [konvajs/react-konva#282]
react-konva is largely working great for me-- thank you!  But I want to test it using Enzyme (e.g., simulating clicks and drags on the Konva objects), and am running into some trouble.

I tried a bunch of things in a minimal example at https://github.com/davidsoergel/react-konva-enzyme-borked.  You can 'yarn test' that to reproduce.  The interesting bits are all in `src/react_konva_test.tsx`, copied below.

The main issues are: 
 * `mount()`-ing react-konva components produces errors, and 
 * it's not clear how best to send simulated events, because the usual Enzyme mechanisms don't seem to work, or at least I haven't understood the right way to do it.

Thanks much for any help & ideas!

```typescript
import * as React from 'react';

import {mount} from './enzyme';
import {Rect} from 'react-konva';

describe('<Rect />', () => {

  it('is testable', () => {

    let clickCount = 0;
    const handleClick = () => {
      clickCount++;
      console.log('click');
    }

    // This produces the 'PascalCase' error and the 'tag unrecognized' error
    const rect = mount(<Rect id='test' onClick={handleClick} />);

    // the wrapper looks OK, with capitalized name 'Rect'
    console.log('Wrapper debug:', rect.debug());
    console.log('Wrapper props:', rect.props());

    // Unclear to me what the instance is, but anyway it has no props.
    // I think it's supposed to be a React Component, but the Konva binding
    // doesn't quite provide that (??).
    console.log('Instance:', rect.instance());
    console.log('Instance props:', rect.instance().props);
    console.log('Instance state:', rect.instance().state);

    // the DOM node has no onClick handler, and the name is 'rect' (lowercase)
    console.log('DOMNode:', rect.getDOMNode());

    // This does not work because props is undefined
    // rect.instance().props['onClick']();

    // this does not work
    const clickEvent = new MouseEvent('click');
    rect.getDOMNode().dispatchEvent(clickEvent);
    console.log('Click count: ', clickCount);  // still 0

    // this does not work, despite @Anupheaus suggestion at
    // https://github.com/airbnb/enzyme/issues/1357#issuecomment-404665936
    const clickEvent2 = new (window as any)['MouseEvent']('click');
    rect.getDOMNode().dispatchEvent(clickEvent2);
    console.log('Click count: ', clickCount);  // still 0

    // this works, but is disindicated by
    // https://github.com/airbnb/enzyme/issues/1357
    rect.simulate('click')
    console.log('Click count: ', clickCount);  // prints 1

    // This works, but I'm not sure it tests enough.
    // This is different but related, arguing that this 'direct' test is good:
    // https://bambielli.com/til/2018-03-04-directly-test-react-component-methods/
    rect.prop('onClick')();
    console.log('Click count: ', clickCount);  // prints 2
  });
});
```

**Comment by lavrton** [comment]
We need to think about how to approach that. Currently you can take a look how tests are organized for that repo: https://github.com/konvajs/react-konva/blob/master/tests/index-test.js

I think it will be not simple to integrate with the enzyme. Because Konva nodes are not DOM nodes. As I know the enzyme is designed to test DOM nodes. So some adapter will be required.

**Comment by davidsoergel** [comment]
Thanks for the super fast and helpful reply!  Sorry I somehow overlooked that your tests are already using Enzyme!  The approach there of simulating mouse events on the stage, without reference to the components inside, makes sense to me-- I'll try that now & will report back.

**Comment by davidsoergel** [comment]
It took me a while to get back to this, but anyway: testing by simulating mouse activity on the stage mostly works great!

To make that easier, I wrote a [\<MouseableKonvaStage\>](https://github.com/davidsoergel/react-konva-enzyme-borked/blob/master/src/mouseable_konva_stage.tsx) element that acts like a regular Konva stage but adds methods like `simulateMouseDrag()` (adapted from Konva's [mocking.js](https://github.com/konvajs/react-konva/blob/master/tests/mocking.js)).

One remaining hiccup: when I mount new components within the Stage by updating its props, the new components do not become clickable until I forcibly redraw the layer hit graphs.  [Here's a test](https://github.com/davidsoergel/react-konva-enzyme-borked/blob/master/src/react_konva_test.tsx) that demonstrates this effect.  I *think* this problem occurs only in tests, not in production, but I don't understand why.  

Thanks for any insights!

**Comment by lavrton** [comment]
@davidsoergel `react-konva` do not immediately update a layer. For performance reasons, it will do it asynchronously. So you have to wait for a redraw (hit graph update) or force draw manually as you do!

**Comment by davidsoergel** [comment]
Oh of course, that makes perfect sense.  This explains why the problem showed up in synchronous tests, but not in production where there's plenty of time for the async redraw to fire before the user clicks.

I just updated my \<MouseableKonvaStage\> to make all the simulate* methods async.  Now they just sleep for 1ms before doing anything, to make sure that the layer hit graph redraw has already fired.  This slows our tests down a bit, but not enough to matter yet.  (Using a timeout of 0 instead of 1 produces flaky tests).

Thanks for the explanation!  We're good to go now-- resolving.
