### ISSUE TITLE
Incorrect versioning of latest release (v16.6.1-1)

### ISSUE THREAD

**Issue by pleopardi** [konvajs/react-konva#286]
I just wanted to highlight that `npm install` and `npm update` still point to version 16.6.1, not 16.6.1-1, for those who have a dependency range like `"react-konva": "^16.x.x"`

For example, in my specific case I have `"react-konva": "^16.6.0"` and `npm install` is installing version 16.6.1 (along with the ref bug).

In fact this is what I get when I run `npm outdated`:
![version](https://user-images.githubusercontent.com/22129342/48283615-54c3a700-e45d-11e8-8a52-b71458559eb1.PNG)

**Comment by lavrton** [comment]
Ah. Following react versions is harder, then I thought. Looks like I have to make `16.6.2` release.

**Comment by lavrton** [comment]
Just made a `16.6.11` release. Should be ok now.
