### ISSUE TITLE
Uncaught TypeError: this.props.forwardedRef is not a function

### ISSUE THREAD

**Issue by rasheedb** [konvajs/react-konva#287]
Receive the following error after updating to react version 16.6.1

Uncaught TypeError: this.props.forwardedRef is not a function
    at Stage.componentDidMount (ReactKonva.js:53)
   ...

Here's a link to a sample sandbox that reproduces the issue.

[https://codesandbox.io/s/l96vx6w62z](https://codesandbox.io/s/l96vx6w62z)

**Comment by lavrton** [comment]
Just make a `16.6.11` release. Should be fixed there. Thanks fro the report
