### ISSUE TITLE
this.props.forwardedRef is not a function exception with 16.6.11

### ISSUE THREAD

**Issue by blooddrunk** [konvajs/react-konva#289]
Setting a `ref` for `Stage` using `React.createRef()` causes the same exception as  https://github.com/konvajs/react-konva/issues/287

```
ReactKonva.js:93 Uncaught TypeError: this.props.forwardedRef is not a function
    at Stage.componentDidMount (ReactKonva.js:93)
    at commitLifeCycles (react-dom.development.js:16710)
    at commitAllLifeCycles (react-dom.development.js:18146)
```

`this.props.forwardedRef` actually equals `{ current: null }`  when the exception is thrown as the debugger tells

This can be reproduced by https://codesandbox.io/s/147mol8r6j

Thanks for your help!

**Comment by lavrton** [comment]
Thanks for the report. The issue should be fixed in the new version. https://codesandbox.io/s/k05qovnw33
