### ISSUE TITLE
Allow Image children, unattached Layers

### ISSUE THREAD

**Issue by jquense** [konvajs/react-konva#294]
Hey there, thanks a ton for this library, really making me more productive 👍 

I had a question and maybe a feature request. One pattern we use with plain canvas, is to render a drawing into an unattached canvas element and then `drawImage` onto our main canvas, so things like `globalCompositeOperation` work for the layer, but we don't end up rendering more than one `canvas` into the DOM. I guess similar to the https://konvajs.github.io/docs/sandbox/Free_Drawing.html example. What would be great tho is if we could use all the same konva nodes and react-konva to do this. In my head the API might like

```js
<Image>
   <Line points=[]>
  <Circle />
</Image>
```

Where `Image.props.children` ends up passing an unattached layer to `image`. 

Is something like this feasible now, or would you be open to it as a feature?

**Comment by lavrton** [comment]
Hmmm. What is the use case for that example? I am using unattached canvases sometimes for manual access. But for the code sample, you provided it is enough to use just `Group`.

**Comment by jquense** [comment]
I think the free-hand drawing example is a good use-case? The example as is is weird, its not really about using konva, but how to draw something manually with canvas and then append it to a konva stage. It seems better to be able to use konva nodes there yeah?

For us the problem is we don't want multiple canvas elements, but do want the benefit of layers. Very specifically i want to be able to have an image backdrop and draw lines over it, but we able to use `globalCompositeOperation('destination-out')` to erase lines but not the image behind it. Perhaps that's possible already?

**Comment by lavrton** [comment]
> we don't want multiple canvas elements, but do want the benefit of layers

Why? Do you think it is slow? Usually, it is very safe to use 3-5 layers on one stage.

**Comment by lavrton** [comment]
Closing this for now, because currently, I don't see how we can implement it in a simple way. But still, any suggestions and use cases are welcome.
