### ISSUE TITLE
TextPath.getKerning() does not get called

### ISSUE THREAD

**Issue by janrop** [konvajs/react-konva#295]
Hi there,

if I try to fine tune kerning with getKerning on a TextPath Component. The function does not get called.

react 16.0.0
react-dom 16.0.0
konva 1.7.6
react-konva 1.6.4

runnable Demo:

https://codesandbox.io/s/mq88q4766y

**Comment by lavrton** [comment]
Also you need to update Konva. Konva 1.6.4 doesn't support kernings.

As a temporary workaround you can set `getKerning` directly: https://codesandbox.io/s/l92wj748mq

**Comment by lavrton** [comment]
I updated `Konva` API. `getKerning` is renamed to `kerningFunc` in `konva@2.6.0`.
https://codesandbox.io/s/vy9oj2zj95
