### ISSUE TITLE
Question: onWheel x ref why not both?

### ISSUE THREAD

**Issue by MichelDiz** [konvajs/react-konva#298]
I'm working on a small idea and I'm struggling with this little interference.

On my Stage I'm using `onWheel={e => configs.handleWheel(e)}`, but I'm populating an set of arrows (with map) on a layer using `ref={node => execthis(node)}`. Using both as this way I do not have access to "getStage()" it does not pass `node =>` to the arrows. React Konva just breaks.

The point is, I do not want to use "state" (react) I want to do "`.setPoints()`" to the arrows, as it is already working. However, with onWheel it bugs/breaks. Works perfectly without onWheel. But then I lose the scrolling functionality.

Using  "`.setPoints()`" I have less renders and gets more fluid.

What should I do?

Cheers.

**Comment by lavrton** [comment]
Can you make a demo of what you are trying? I didn't get what is the issue with `onWheel`.

**Comment by MichelDiz** [comment]
Well, I think I did reproduce it https://codesandbox.io/s/61j3v8jv7k

I'm using Mobx, but I tried to do the closest thing I'm doing here. Sorry for the mess, it was in a hurry. xD

**Comment by MichelDiz** [comment]
ah!
if you deactivate the ref in Arrow
`//s ref={node => execthis(node)}`
you gonna see that the line will be erased on each wheel and the circles positions.

**Comment by lavrton** [comment]
React will reset reference to `null` on every update. So I guess in you `execthis` you will need something like this:

```javascript
if (!node) {
  return;
}
```

**Comment by lavrton** [comment]
@MichelDiz to what default? when? After drag&drop?

**Comment by MichelDiz** [comment]
After the onWheel. I've updated the sandbox.

**Comment by lavrton** [comment]
You may try to update `react-konva` to the latest version. It has changes in internal updating implementation https://github.com/konvajs/react-konva/issues/271.

Probably you will have the expected result. https://codesandbox.io/s/4jxyywwx4

**Comment by MichelDiz** [comment]
Oh god, what is this magic trick? works like a charm.

Thank you!
