### ISSUE TITLE
Unexpected context found on stack. This error is likely caused by a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by Milos5611** [konvajs/react-konva#300]
Strange issue, only happen in IE11:
`Unexpected context found on stack. This error is likely caused by a bug in React. Please file an issue.`
```
"react": "^16.6.3",
"react-dom": "^16.6.3",
"react-konva": "^16.6.31",
```

Anyone was an idea what could be the problem ?

**Comment by lavrton** [comment]
@Milos5611 can you make an online demo? What components do you have?

**Comment by Milos5611** [comment]
Hi @lavrton, i can't...it's pretty huge app. I have `Path, Circle, Group, Layer, Text, Line and Arc`
All was good with react 15. We just upgrade it, it works as it should on all device except IE.

**Comment by Milos5611** [comment]
@Milos5611 ok it happen in `Stage` component, just found that

**Comment by Milos5611** [comment]
Problem was in `babel-polyfill` not in lib it self. Really weird error.

**Comment by weiyingbin** [comment]
I have the same problem.

**Comment by weiyingbin** [comment]
Because I used `style={styles.base}`,You should use `className={styles.base}`.

**Comment by oliversisson** [comment]
I changed <View> to <Animated.View> and it worked.
