### ISSUE TITLE
drawHitFromCache

### ISSUE THREAD

**Issue by spassvogel** [konvajs/react-konva#302]
Great work on the library so far. One gripe I have found is that there is no native implementation of `drawHitFromCache` (or even `cache` for that matter) on Image. You can work around it by storing a reference and setting the properties directly on the konva object but wouldn't it be much nicer to have this inside *react-konva* ?

**Comment by lavrton** [comment]
We need to think how to implement it. Probably we can do this:

```javascript
<Image
   {...someProps}
   applyCache
   applyHitFromCache
/>
```

`react-konva` will try to automatically cache a node when possible.

**Comment by spassvogel** [comment]
That would be super nice (y)

**Comment by spassvogel** [comment]
If it's any help this is what I'm doing now:

                   <Image
                        ref={ (node: Konva.Image) => { drawHitFromCache(node); }}
                     />
```
const drawHitFromCache = (img: Konva.Image) => {
    if (img) {
        img.cache();
        img.drawHitFromCache(0.5);
    }
};
````

**Comment by lavrton** [comment]
I am thinking there are many edge cases when it is hard to apply a cache to the node in an automatic way. Also when the new React hooks it is much simpler to apply caches in functional style. So, for now, I will close the issue.

**Comment by heaversm** [comment]
Sorry - was this ever implemented in Konva? I need to be able to drag transparent images with a hit area drawn only from non-transparent pixels.

**Comment by lavrton** [comment]
@heaversm yeh, you just need to call that method manually when a component is mounted.
