### ISSUE TITLE
Passing name attribute to array of Konva nodes crashes application

### ISSUE THREAD

**Issue by flurmbo** [konvajs/react-konva#304]
My render function looks something like this:

```
render() {
  var myCircles = [10, 20, 30].map(function(x, index) {
    return (<Circle radius={x} key={index} name={index}/>)}, this)

  return (
    <Stage>
      <Layer>
        {myCircles}
      </Layer>
    </Stage>)
}
```
This causes the application to crash and leaves the following error message in the console:
```
TypeError: (intermediate value).split is not a function
```

I originally was passing in a value to 'id' but received a warning that doing so could cause buggy behavior and that I should assign to 'name' instead. Also important to note, no crash or error message occur for an array of length 1.

Of course this is not a huge problem for me because I can just come up with a different attribute name, but I thought you should know!

Browser: Firefox 64.0 64-bit
OS: Ubuntu 18.04.1
React Konva 16.6.31

**Comment by lavrton** [comment]
That example doesn't work because `name` should be a string. But `index` is a number. This code should fix the issue:
```
name={index.toString()}
```
