### ISSUE TITLE
react-konva: stage.toDataURL(), the base64 image is unclear

### ISSUE THREAD

**Issue by luckystar12** [konvajs/react-konva#305]
when use stage.toDataURL({quality:1, pixelRadio:2}), the base64 image is very unclear, how to solve it ? Anyone could help me?

 const image = this.stageRef.toDataURL({
          mimeType: 'image/png',
          width: window.innerWidth,
          height: window.innerHeight,
          quality: 1,
          pixelRadio: 2,
 })

**Comment by lavrton** [comment]
Please, make an online demo.  Do you have images with a fractional position?

**Comment by luckystar12** [comment]
@lavrton sorry, I don't have a online demo, it just be very simple demo. Not with a fractional position. It seems that change the "quality" parameter, the image size effect a little and unclear, just more than several kb.

**Comment by lavrton** [comment]
I don't know how to reproduce the issue. Please provide a demo. You can use this as a template https://codesandbox.io/s/6vq1j0zq43

I will close the issue. Feel free to add more info to the issue, so we can reopen and fix it.

**Comment by samdeesh** [comment]
I am also facing a similar issue, could not get base64 for Stage. It gives a blank. find my demo at https://codesandbox.io/s/zr3r3lr3l4

**Comment by lavrton** [comment]
@samdeesh  You have CORS issue. Try to google error message. You will see that is the issue.

**Comment by samdeesh** [comment]
Thanks @lavrton Using the images from same domain solves this issue

**Comment by eLcaF** [comment]
I am also facing a similar issue, but I typed `pixelRadio` in mistake for `pixelRatio`, like @luckystar12 .

This code done well, and the image is enough clear.
```javascript

const KonvasStage = props => {
  const {
    stageWidth,
    stageHeight
  } = props;

  const downloadURI = (uri, name) => {
    const link = document.createElement("a");
    link.download = name;
    link.href = uri;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleSaveImage = event => {
    event.preventDefault();
    const dataURL = stageRef.current.toDataURL({
      mimeType: "image/jpeg",
      quality: 0,
      pixelRatio: 2
    });
    downloadURI(dataURL, "test");
  };

  const stageRef = useRef();

  return (
    <>
      <button onClick={handleSaveImage}>Save Image</button>
      <Stage width={stageWidth} height={stageHeight} ref={stageRef}>
        <Layer>
          {/* some Konva Object */}
        </Layer>
      </Stage>
    </>
  );
};

```
