### ISSUE TITLE
Text decoration does not work

### ISSUE THREAD

**Issue by gal1419** [konvajs/react-konva#312]
Hello, 

I'm using react-konva and I love it so far.
I've tried to set add underline to a Text component with no luck.
The way that it is being done in the Konva.js docs, is by manually add it to the Text element.
I can do it manually, but naturally, it will not trigger a render so it will not show in the canvas. 
Am I missing something? is it supported? 

Many thanks

**Comment by lavrton** [comment]
```javascript
        <Text
            textDecoration="underline"
            x={20}
            y={20}
            text="some text"
          />
```

https://codesandbox.io/s/qk301x3034

**Comment by gal1419** [comment]
@lavrton  I see. Since I'm using typescript, the textDecoration property was invalid for me since it is declared at the konva-react type probably.
Anyway, thanks

**Comment by lavrton** [comment]
Ah, right. It is missed in ts types. I will fix it now.

**Comment by gal1419** [comment]
Many thanks
