### ISSUE TITLE
Cannot get real text height

### ISSUE THREAD

**Issue by pleopardi** [konvajs/react-konva#313]
I'm rendering strings with different font families and I need the dimensions of each to center the text.

I can get the correct width of the rendered text while the height always equals to the font size prop value, which is clearly not correct.

So far I tried `getSelfRect().height`, `getTextHeight()` and ` height()` with no luck: I always get back the font size.

What am I missing?

**Comment by lavrton** [comment]
```javascript
    // logs font size:
    console.log(this.text.getTextHeight());

    // logs total height of text:
    console.log(this.text.height());

    // logs bounding height
    // it is basicly height * scaleX
    console.log(this.text.getClientRect().height);
```

I think I will deprecate `getTextHeight` in the next release.

https://codesandbox.io/s/l5014r8rzl

Works ok.

**Comment by pleopardi** [comment]
I modified your code, have a look at this example: https://codesandbox.io/s/5wyx27l16x

 With different font families the pixel occupation is visibly different, but I get the same height for both texts: the font size. 
My question is: is this the correct behavior? I assumed the text height should be equal to the real height of text in pixel, as it is for width.

**Comment by lavrton** [comment]
Even the browser's `context.measureText()` gives the same result.

```javascript
console.log(this.text2._getTextSize(this.text2.text()));
```

https://codesandbox.io/s/m37oww6r4j

I am not sure we can do anything here.

**Comment by pleopardi** [comment]
OK, that's what I wanted to know. To me this is not the expected behavior but now I know this is how canvas works.

Thanks Anton!
