### ISSUE TITLE
Portal causes errors

### ISSUE THREAD

**Issue by developdeez** [konvajs/react-konva#314]
I was trying to use this with react-avatar-editor. I also tried a simple input and it fails everytime.

Error:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by lavrton** [comment]
Do you mean `React.createPortal `? If so, they don't work with `react-konva` right now. 

As workaround you can create portal manually: https://konvajs.github.io/docs/react/DOM_Portal.html
