### ISSUE TITLE
useImage React hook

### ISSUE THREAD

**Issue by lavrton** [konvajs/react-konva#315]
I am thinking to implement `useImage` hook with the simple API:

```javascript
import React from 'react';
import { Image, useImage } from 'react-konva';

export default function App() {
  const url = 'some-image-url';
  const image = useImage(url);
   // it will be undefined while image is loading
   // and it will be instance of window.Image when it is loaded


  return (
    <Stage width={300} heihgt={300}>
        <Layer>
            <Image image={image} />
        </Layer>
    </Stage>
  );
}
```

That hook will simplify current image usage https://konvajs.github.io/docs/react/Images.html

**Comment by levrik** [comment]
Why don't implement a better `Image` component for that?
I use the following code in my application.
```js
class UrlImage extends Component {
  static propTypes = {
    imageUrl: PropTypes.string.isRequired
  }

  state = {
    image: null
  }

  componentDidMount() {
    this.loadImage();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.imageUrl !== this.props.imageUrl) {
      this.loadImage();
    }
  }

  loadImage = () => {
    const image = new window.Image();
    image.src = this.props.imageUrl;
    image.onload = () => {
      this.setState({
        image
      });
    }
  }

  render() {
    const { imageUrl, ...props } = this.props;
    return <Image image={this.state.image} {...props} />
  }
}
```

**Comment by lavrton** [comment]
We can add a custom component as well. I like the name `UrlImage`.

**Comment by levrik** [comment]
Why can't this be included in the `Image` component itself? Why does it need to be a separate component?

**Comment by lavrton** [comment]
For several reasons:

1. Consistent behavior with core Konva shapes.  `react-konva` just maps properties into a node (`Konva.Image` in that case) without additional logic or transform. Currently `Konva.Image` has no `url` (or `src` or `imageUrl`) property.

2. `Konva.Image` can use not only images, but also canvas elements and video elements. So with current API you have full control over logic flow.

3. Even simple image loading is not so simple. In many cases we may need to: (1) show something while image is loading (like a placeholder), handle network loading errors.

**Comment by zivni** [comment]
I don't think this hook should be part of react-konva. It could be in a separate package

**Comment by lavrton** [comment]
Probably, but I am not sure it will be useful outside of `react-konva`.

**Comment by lavrton** [comment]
https://github.com/konvajs/use-image

```
export default function App() {
  const url = 'https://konvajs.github.io/assets/yoda.jpg';
  const [image] = useImage(url);

  return (
    <Image image={image} />
  );
}
```
