### ISSUE TITLE
Can't use React hooks inside Konva component tree

### ISSUE THREAD

**Issue by levrik** [konvajs/react-konva#317]
If I use a React hook inside the Konva component tree I'm getting the following error:
```
Hooks can only be called inside the body of a function component.
```
I'm using `16.8.0-alpha.1`.

**Comment by lavrton** [comment]
I am going to wait for a public release of React, so we can update dependencies and have hooks support too. Please just wait.

**Comment by levrik** [comment]
@lavrton I'm currently building a library with React-Konva and I want to use React Hooks since it would simplify a lot. The React release with Hooks isn't that far away anymore so I don't want to waste my time with a rewrite later...

**Comment by levrik** [comment]
@lavrton Hooks are released as stable now. Can this issue be re-opened, please?
See: https://reactjs.org/blog/2019/02/06/react-v16.8.0.html

**Comment by lavrton** [comment]
Just made a prelease `16.8.0-1` with the support of Hooks.

```
npm install react-konva@next
```

Please try it. Will publish with `latest` tag later.

**Comment by levrik** [comment]
@lavrton `react-konva@next` installs `react-konva@16.6.0-1` instead of `react-konva@16.8.0-1`.

**Comment by lavrton** [comment]
Sorry, please try again.

**Comment by ebello** [comment]
I had this exact same problem and using `react-konva@next` solved it. Thanks so much @lavrton.

**Comment by alina16** [comment]
I still have this problem with useDispatch hook

**Comment by lavrton** [comment]
@alina16  can you make a demo?

**Comment by alina16** [comment]
@lavrton react-dom.development.js:55 Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

have such error

**Comment by lavrton** [comment]
I mean can you create a codesanbox demo? Like this: https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/shapes?from-embed
