### ISSUE TITLE
Methodology of refactoring into separate components

### ISSUE THREAD

**Issue by fxdave** [konvajs/react-konva#318]
With all the konva distributions, I have the same problem. Let a group of a rectangle and a text. This is a logically separable component, so I make new react component for it. My problem is that, this will not be a react-konva component too, so I can not put reference on it, I can not change it's position. Moreover, it is completely independent, because It is a react component. 

If I can use rect object as `<Rect />` , and text as `<Text />` I would use for example deleteButton object as `<DeleteButton />` in the same way. Yes, I can make the props myself (for e.g `x={this.props.x}`), but without reference I can't query it's 'getClientRect', and so on...

The only I can reach is to drop it into another group:
`<Group><DeleteButton /></Group>`
And The Group outside will represent the DeleteButton object. 

Sorry, I am very sensitive for inconsistency, but this is a bit hacky, isn't it? 
It's like, I want to make a rectangle so I write:
`<Group><Rect /></Group>`
Doesn't seem familiar right?

So can I extend ReactKonva.Group in order to get a similar usage?

**Comment by lavrton** [comment]
Why do you need to access an element directly? I recommend two ways:

1. Use `forwardRef` API of react:

```javascript
const DeleteButton = React.forwardRef((props, ref) => (
  <Group ref={ref}>
    <Rect width={100} height={100} fill="red"/>
  </Group>
));

class App extends Component {
  componentDidMount() {
    console.log(this.deleteButton);
  }
  render() {
    return (
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <DeleteButton ref={node => { this.deleteButton = node}}/>
        </Layer>
      </Stage>
    );
  }
}
```

2. Or use selectors to find required Konva nodes:

```javascript
const DeleteButton = (props) => (
  <Group name="delete-button">
    <Rect width={100} height={100} fill="red" />
  </Group>
);

class App extends Component {
  componentDidMount() {
    const deleteButton = this.stage.findOne('.delete-button');
    console.log(deleteButton);
  }
  render() {
    return (
      <Stage
        width={window.innerWidth}
        height={window.innerHeight}
        ref={node => {
          this.stage = node;
        }}
      >
        <Layer>
          <DeleteButton          />
        </Layer>
      </Stage>
    );
  }
}
```

https://codesandbox.io/s/wkl919nj2l

**Comment by fxdave** [comment]
Thanks for the answer. I need references for making anchors. For example "position anchor" could be used for enforcing a text to stay at the middle of a rectangle, or "width anchor" for setting the width matching to another object's width with a padding value. These will ease up my work. I publish it for the community when I finished it.

I think I am able to make this with `forwardRef`. I will read about it more. Thank you again!
