### ISSUE TITLE
Typescript: missing filters prop

### ISSUE THREAD

**Issue by optimistiks** [konvajs/react-konva#319]
`Rect`, `Image`, and most likely other components that support filters via `filters` prop are missing that prop definition, as well as all filter-specific value props (`brightness`, `contrast`, etc).

```
<Rect
  filters={[]}
/>

Error: Property "filters" does not exist on type ...
```

**Comment by lavrton** [comment]
Should be fixed with the recent `konva` version. Try to update it.
