### ISSUE TITLE
StageProps should allow nonContent version of events

### ISSUE THREAD

**Issue by ericdnielsen** [konvajs/react-konva#320]
I've been trying to suppress events from bubbling up to the stage.  However StageProps only accepts the onContent* version of click handlers, so there doesn't seem to be a TypeScript friendly way to assign an onClick handler to the stage that could be intercepted by an entity above it.

From reading other bugs/postings its sounds like the onContent* were (primarily?) needed to fire when clicks occurred blank places of the stage/canvas, but those bugs are (mainly?) fixed it sounds like.

Is there a reason that the nonContent handlers aren't exposed on StageProps?

**Comment by lavrton** [comment]
Can you give more info about your issue? Why can't you use `onClick`?

**Comment by ericdnielsen** [comment]
In react.konva.d.ts:
export interface StageProps
  extends Konva.NodeConfig,
    Pick<
      React.HTMLProps<any>,
      'className' | 'role' | 'style' | 'tabIndex' | 'title'
    > {
  onContentMouseOver?(evt: any): void;
  onContentMouseMove?(evt: any): void;
  onContentMouseOut?(evt: any): void;
  onContentMouseDown?(evt: any): void;
  onContentMouseUp?(evt: any): void;
  onContentClick?(evt: any): void;
  onContentDblClick?(evt: any): void;
  onContentTouchStart?(evt: any): void;
  onContentTouchMove?(evt: any): void;
  onContentTouchEnd?(evt: any): void;
  onContentTap?(evt: any): void;
  onContentDblTap?(evt: any): void;
  onContentWheel?(evt: any): void;
  onContentContextMenu?(evt: any): void;
}

StageProps does not contain the regular onClick, etc events.  Typescript is rejecting them them I try to use them.

**Comment by ericdnielsen** [comment]
Yes, adding 
"  onClick?(evt: any): void;
  onContextMenu?(evt: any): void;
"
to StageProps manually allowed me to set those properties and use them as desired.

**Comment by ericdnielsen** [comment]
And now tried the real thing you asked me to do, sorry, didn't understand the first time around.

Grabbed the version of the file you just pushed, manually overwrote mine in node-modules, and yes, everything works.

**Comment by ericdnielsen** [comment]
What sort of timeline are we looking at before this commit is in a released version?

**Comment by lavrton** [comment]
Released.
