### ISSUE TITLE
How to add background image in stage?

### ISSUE THREAD

**Issue by bhumi0901** [konvajs/react-konva#321]
Hello, I am using react-konva in my project in which I need to make an online t-shirt customization demo using react js for a project. I want to draw different objects like images and texts over the t-shirt image and in the last export that image as jpg or png image. So for that, I need to set the t-shirt image as stage background image. I have searched about it but nothing worked for me. What is the way the set the background image for the stage? Please give me solution as soon as possible.

It will be helpful for me if you provide the list of all attributes I can use inside react-konva components also because I am not able to find all attributes to customize any component.

**Comment by lavrton** [comment]
What did you try?

Just insert image to the bottom. https://konvajs.github.io/docs/react/Images.html

**Comment by bhumi0901** [comment]
Okay @lavrton but can you provide the list of attributes which I can use for customizing different components.

**Comment by lavrton** [comment]
What attributes do you need? Take a look into konva docs for all properties. https://konvajs.github.io/docs/overview.html

**Comment by lavrton** [comment]
Just for reference: https://konvajs.org/docs/sandbox/Canvas_Background.html
