### ISSUE TITLE
weird behavior drag n drop images and scroll zooming

### ISSUE THREAD

**Issue by gc** [konvajs/react-konva#326]
Code: https://github.com/gc/omm/blob/master/src/index.js
Demo: https://zen-curran-497243.netlify.com/

There are 2 tree images below the canvas, when dragged onto the canvas they will be loaded into where you dropped it.

To reproduce my issue: drag a tree onto the canvas anywhere, then zoom in on it and try to add another tree directly next to it, and it will appear away from it. The same happens when zoomed out.

I'm not sure why this is happening. Any idea?

**Comment by lavrton** [comment]
It is happening because your stage is transformed. You need to find relative coordinates manually.
This demo should help you: https://konvajs.github.io/docs/sandbox/Relative_Pointer_Position.html
