### ISSUE TITLE
Support React 16.8.1

### ISSUE THREAD

**Issue by himynameisdave** [konvajs/react-konva#327]
Bumped to the latest React, still getting console errors.

![image](https://user-images.githubusercontent.com/4298089/52573248-96524e00-2dce-11e9-9693-91ecee4679e4.png)

Canvas stuff seems to still work fine.

Not sure why we need to be pinned to such a specific version of React. Why can't we support all patch versions like `~16.8.x` ([kind of like we do with `konva`](https://github.com/konvajs/react-konva/blob/master/package.json#L25)).

**Comment by himynameisdave** [comment]
In addition, I [don't support this being a hard error](https://github.com/konvajs/react-konva/blob/c04f86b98854991df62bbfe6df9a2eea4f7ff1e0/src/ReactKonva.js#L22-L28) and think it should be a warning instead. I think it's on the developer/consumer to understand their own dependency tree and investigate when things aren't working as expected.

**Comment by lavrton** [comment]
I tried to include patch versions in previous releases. But sometimes it was not working. `react-konva` depends on some internal packages of React that may change on patch versions.

I agree we can show warning instead of the error and probably we can hide it at all on production build.

**Comment by VividWombat** [comment]
please either keep up with same version as react, OR dont generate errors for minor version change

**Comment by switz** [comment]
This versioning system seems so bizarre to me. You could in theory use [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies) to solve this "problem".

If I understand correctly, this also means you can never release an update to react-konva unless react has also released an update?

Sorry if this come across as rude, but it's an odd system that I've never seen before (outside of companies who have first-party control over version numbers, e.g. React & React-DOM or Babel).

**Comment by lavrton** [comment]
`peerDependencies` already in use. But developers ignore the warning from `npm` during the install.
`¯\_(ツ)_/¯`


So I decided that it still makes sense to show an error into the console, so users will see WHY their app may not work. We can change that error into the warning. But it will just change the color of the message, so I don't think it is very important what to use `console.error` or `console.warn`.

From my point of view, it is very comfortable when versions of `react` and `react-konva` are visually matched. Like `react` and `react-dom` are always published together. So for both of them, you have exactly the same version, like `16.8.0`. So if you see `react` and `react-konva` both have the same version you may assume they will work just fine.


I can't predict on which `react` update the app will still work, and on which update it will not. So it is better to assume that it will not work always. That is why `peerDependency` pinned strictly, like `16.8.0` and not `16.8.x`.


> If I understand correctly, this also means you can never release an update to react-konva unless react has also released an update?

Yes and no. It is not very comfortable to always match react version and follow its release cycle. But `react-konva` depends on react and its internals. So at any `react` update we have to update `react-konva` too (update its dependencies and rebuild). `react-konva` is stable and usually, it doesn't need many patch releases.
If I have some minor changes that don't need urgent publish it is ok to wait for a new react release. If we have something urgent we will have a patch release and for a period of time `react` and `react-konva` version will not visually matched.


Let me know if you have any suggestions for that flow.

**Comment by lavrton** [comment]
Published `16.8.1` and `16.8.2-0` (for the last version of react)
