### ISSUE TITLE
Stage not updating properly

### ISSUE THREAD

**Issue by aishmitk** [konvajs/react-konva#328]
I have a cylinder which fills its volume according to the data provided. When I change data, the stage does not update properly: 
![image](https://user-images.githubusercontent.com/24919332/52804401-1d632880-3052-11e9-8fa7-82d0488125f4.png)

This is the code which is being drawn onto stage by calling a function
```
return (
      <React.Fragment>
        <Layer>{stacks}</Layer>
        <Layer>
          <Shape
            sceneFunc={(context, shape) => {
              context.clear();
              console.log(emptinessAnchor, emptinessPalette, emptinessTop);
              context.moveTo(left, emptinessTop);
              context.bezierCurveTo(
                left + emptinessAnchor,
                emptinessTop - emptinessAnchor,
                right - emptinessAnchor,
                emptinessTop - emptinessAnchor,
                right,
                emptinessTop
              );
              context.bezierCurveTo(
                right - emptinessAnchor,
                emptinessTop + emptinessAnchor,
                left + emptinessAnchor,
                emptinessTop + emptinessAnchor,
                left,
                emptinessTop
              );
              context.closePath();
              shape.setAttr('fill', emptinessPalette);
              context.fillStrokeShape(shape);
            }}
          />
        </Layer>
      </React.Fragment>
    );
```

The second layer (supposed to be the green lid of the highest cylinder) redraws over and over, but since it is top layer there is nothing to overwrite it I assume. I am not sure why the rest of them do not mess up. The stacks are the cylinders which are being mapped onto the first layer via `array.map` I tried clearing the stage by sending the prop: `sceneFunc={context => {context.clear()}}` but nothing seems to work

**Comment by lavrton** [comment]
I guess you need to add `context.beginPath();` into `sceneFunc`.

Can you make a demo?

**Comment by aishmitk** [comment]
That helped thanks. However, I am getting an issue where the update does not happen properly when data is changed. Here is the video I have attached to show that demo: 

https://drive.google.com/file/d/1J1WWtxoVIoBYH_7G4DEEatNlSsAx1SxN/view

The modal is removing the whole green cylinder and increasing the yellow cylinder. The shell cylinder (white one) is drawn after the yellow cylinder, so I added the top of the yellow cylinder after all the cylinders were drawn (the first code snippet I posted). 

It seems that prop change does not properly repaint the cylinders, until I force trigger it by using my mouse to hover over it, causing a tooltip (third-party) to render above it. 

Then the second issue is that if I try to change data sets again, the yellow cylinder is missing from the whole stage.

**Comment by lavrton** [comment]
Please make a small online demo. Try to make a reproducible issue on a small code.

**Comment by aishmitk** [comment]
Here is the [codesandbox](https://codesandbox.io/s/n5pwn79pzl) for the whole file.

Please click the yellow legend box first to remove green cylinder, then click the red to switch to a new data set. This is mirrored functionality on my original code

**Comment by lavrton** [comment]
There are many parts in `sceneFunc` that are not ok:

```
this.state.emptinessTop = top;
this.state.emptinessAnchor = anchorTop;
this.state.emptinessPalette = palette[idx];
```

Do not change state in scene function. `sceneFunc` is just for drawing a shape on the canvas. It should not have any other side effects.

```
if (idx === startOfEmptiness) {
  shape.moveToTop();
}
```

Same here. `sceneFunc` can be called many times per second. It should not change the nodes tree. If you need to move shape - change order in render function.

**Comment by aishmitk** [comment]
Hey, thank you so much. It worked. Thanks for going through my code. I'll keep that in mind next time!

Hope your day is as fantastic as mine is gonna be after fixing this bug. Cheers.
