### ISSUE TITLE
Draw and Select Region of Interest on Canvas Images

### ISSUE THREAD

**Issue by wadehenning** [konvajs/react-konva#330]
Could you please provide guidance on how to draw on and select regions of images that have been added to the canvas?  In [this example](https://codesandbox.io/s/vyrvjxpmy5), I can free draw in the canvas regions that do not contain the lion image, but I would like to be able to draw over the lion.  I would also like to be able to use my selection rectangle over the lion.  Thank you.

**Comment by lavrton** [comment]
> I would like to be able to draw over the lion

Just put lion at the bottom of the canvas.

Can you give more info about your issues?

**Comment by lavrton** [comment]
Closing as no info provided. 

**Note:** it is better to use StackOverflow for questions.
