### ISSUE TITLE
How to use Transformer with Arrow?

### ISSUE THREAD

**Issue by KLC215** [konvajs/react-konva#333]
Hi, I would like to ask how to use transformer with arrow. 
I forked the React Transformer Demo and tried but the transformer does not attach to the selected arrow.

Here is my code: [https://codesandbox.io/s/n0z25ponz4](https://codesandbox.io/s/n0z25ponz4)

Thanks :)

**Comment by victormanuelfrancodev** [comment]
Did you resolve bro?, I have the same.

**Comment by lavrton** [comment]
At the current moment, I don't recommend to use `Transformer` with an arrow. It may be better to make your own transformer with just two anchors for `points` property.

**Comment by lavrton** [comment]
Here is the example: https://stackoverflow.com/a/55707822/512042
