### ISSUE TITLE
Support Konva 3.x

### ISSUE THREAD

**Issue by levrik** [konvajs/react-konva#335]

**Comment by lavrton** [comment]
You can just update `konva` in your project and it should work just fine. You will see `peerDependency` warning for `konva`, but for now, you can ignore it. I will update this dep soon.

**Comment by levrik** [comment]
@lavrton Okay. Awesome. The warning confused me a bit but also that on the PR that updates Konva to 3.x the CI failed in the tests.

**Comment by lavrton** [comment]
You can use Konva `v3` with `react-konva@16.8.4` without peer warnings.

**Comment by epatters** [comment]
I could be mistaken, but it seems that the latest versions of Konva and react-konva do not work together on TypeScript. The file `react-konva.d.ts` references interfaces `Konva.NodeConfig` and `Konva.ContainerConfig` that no longer exist.

**Comment by lavrton** [comment]
@epatters you are right. We need better types for `Konva` asap.
