### ISSUE TITLE
Demos are broken, nothing is rendered

### ISSUE THREAD

**Issue by simjes** [konvajs/react-konva#337]
Demos using `React 16.8.3`, `react-konva 16.8.3` and `konva 3.1.3` seems to be broken. Nothing is rendered in the view, same behavior when starting a new project using `create-react-app`.

[The intro](https://konvajs.org/docs/react/index.html) demo seems to at least get an error, while the other demos, like [the drag and drop](https://konvajs.org/docs/react/Drag_And_Drop.html) doesn't render anything.

Tested in Firefox and Chrome.

Update: Downgraded to `Konva 3.1.1` and then it renders as expected

**Comment by lavrton** [comment]
Thanks a lot of the report! It should be fixed now. 👍
