### ISSUE TITLE
Allign Path elements in center of another path element.

### ISSUE THREAD

**Issue by Bobvantpadje** [konvajs/react-konva#339]
Hey,

I've been working with konva for a while now and we're currently starting on the styling part. The decision we made regarding the styling is creating svg's for all the elements we have and loading them in by using the `Path` component. One problem i'm having at the moment is that I can't find a way to horizontally align one `Path` element tot another `Path` element. 

for example, one node looks as following:

```
<Group
    onContextMenu={this.openContextMenu}
    draggable
    dragBoundFunc={position => this.onDrag(position, node)}
    onDragEnd={this.saveNode}
    onClick={this.onNodeCLick}
    onTap={this.onNodeCLick}
    y={node.y}
    x={node.x}
    opacity={node.selected || node.focus ? 0.7 : 1} >
    <Path fill="blue" data={wrapperSvgDataPath} />
    <Path
      fill="white"
      data={childSvgDataPath}
      x={10}
      y={20} />
</Group>
```

The Problem i'm facing it that the `childSvgDataPath` is dynamic and can load different icons (with different widths). Because the icons have different widths and I use the `x` prop to position the element it won't be centered when i'm working with different sizes of elements. Isn't there a way to align one element to another one like following? 

```
<Group
    onContextMenu={this.openContextMenu}
    draggable
    dragBoundFunc={position => this.onDrag(position, node)}
    onDragEnd={this.saveNode}
    onClick={this.onNodeCLick}
    onTap={this.onNodeCLick}
    y={node.y}
    x={node.x}
    opacity={node.selected || node.focus ? 0.7 : 1} >
    <Path fill="blue" data={wrapperSvgDataPath}>
        <Path
          fill="white"
          data={childSvgDataPath}
          align="center"
          />
    </Path>
</Group>
```

**Comment by lavrton** [comment]
You can't add a `Path` into another `Path` shape. I think the workaround is to use `node.getClientRect()` to calculate the size of the path, then adjust position manually.

You can use `ref` to get access to Konva nodes.
