### ISSUE TITLE
Transformer "boundBoxFunc" does not limit the shape size

### ISSUE THREAD

**Issue by fehimismailov** [konvajs/react-konva#341]
I am trying to attach a transformer to a shape I create and use "boundBoxFunc" to limit the width to a specified MAX_WIDTH. But it seems the "boundBoxFunction" callback is not being called when resizing. 

Here is the code:

     const shape = new Konva.Rect({
          x: options.x || 0,
          y: options.y || 0,
          width: options.width || 0,
          height: options.height || 0,
          fill: options.fill || this.getRandomColor(),
          name: options.name || 'fillShape',
          draggable: true,
          opacity: 0.75,
          removable: false
        })

    store.dispatch(setSelectedShape({ id: shape._id, type: shape.className }))

    this.renderedShapes.push(shape)

    this.stage.on('touchstart mousedown click', this.dragNewShapeStartPoint)

    this.layer.add(shape)

    const MAX_WIDTH = 200
    const transformer = new Konva.Transformer({
      boundBoxFunc: function(oldBox, newBox){
        console.log("oldBox: ", oldBox)
        console.log("newBox: ", newBox)
        if (newBoundBox.width > MAX_WIDTH) {
          newBoundBox.width = MAX_WIDTH;
        }

        if (newBoundBox.width < -MAX_WIDTH) {
          newBoundBox.width = -MAX_WIDTH;
        }
        return newBoundBox
      }
    })
    this.layer.add(transformer)
    transformer.attachTo(shape)
    this.layer.draw()

When I run the code about not even the console.log statements are being printed.

**Comment by lavrton** [comment]
Can you make a demo? This demo works just fine: https://konvajs.org/docs/select_and_transform/Resize_Limits.html#How-to-limit-size-changes-of-a-shape

**Comment by VividWombat** [comment]
are you using react ? your code indicates not.

FYI I've recently tested boundboxfunc, and it does seem to work OK.

transformer is new, and still experimental it seems. I can break it easily, so its very code dependent. hence needing a demo to see it working or not working.

**Comment by lavrton** [comment]
Closing the issue for now. Please add more info if you still have issues.
