### ISSUE TITLE
Best approach for responsive React-Konva?

### ISSUE THREAD

**Issue by PolGuixe** [konvajs/react-konva#343]
What is the best way to make a canvas responsive with React-Konva?

I need to make the size of the canvas the same as another element e.g. image, pdf, etc. so the user can overlay elements on top.

I am considering two approaches:
1. Add some initial dimensions to `Stage` and use CSS to adapt it to the size and position I need. ### **Problems:** The initial dimensions will define the Aspect Ratio of the canvas so it needs to be the same all the time and can't be guaranteed. Modifying the canvas with CSS is not always the ideal way. `Stage` component doesn't accept scale props.

2. Having an event listener that triggers every time the windows is resized determines the size of the container and feeds the information to the `Stage` component. ### **Problems:** not sure if this can hit performance.

Is there a better approach?

**Comment by lavrton** [comment]
1. You can adjust the style of the stage container and then just resize stage into the size of that container. Don't change the size of the stage (canvas) with CSS. It may break hit detection.

> Stage component doesn't accept scale props.

It should accept it just fine. `scaleX` and `scaleY`.

2. That is a totally valid approach. Usually, users don't resize windows frequently, so you don't need to care about the performance in that case.  But if you have issues with it you can throttle listener and update the size only after some timeout.

**Comment by Tokenyet** [comment]
I found one solution that allow you modifying CSS, without losing hit detection. [ghost post a code on Pixi](https://github.com/pixijs/pixi.js/issues/4757), and that code perfectly resize the canvas!

``` javascript
function resize() {
    if (window.innerWidth / window.innerHeight >= ratio) {
			ancho = ~~(window.innerHeight * ratio);
			alto= window.innerHeight;

			app.view.style.position = 'absolute';
			app.view.style.width = ancho + 'px';
			app.view.style.height = alto + 'px';
			//console.log("A");
			
			app.view.style.left = ~~((window.innerWidth-ancho)/2) + 'px';
			app.view.style.top = '0px';
			
    } else {
			
			ancho = window.innerWidth;
			alto = ~~(window.innerWidth / ratio);

			app.view.style.position = 'absolute';
			app.view.style.width = ancho + 'px';
			app.view.style.height = alto + 'px';
			//console.log("B");
			app.view.style.left = 0 + 'px';
			app.view.style.top = (window.innerWidth-(alto/2)) + 'px';
			
    }
	//console.log(ancho,alto);
    
		
}
window.onresize = function(event) {
    resize();
};
```

And for a few hours trying, I got the solution for this...
``` javascript
        const canvasWrapper = document.getElementsByClassName("konvajs-content")[0];
        canvasWrapper.style.overflow = "hidden";
        if(!init)
        {
            setScale(resize(canvasWrapper/*app.view*/, 1.6/*your ratio*/)); // scaleX, scaleY
            init = true;
        }
```

You need to tweak PixelSize to return correct ratio difference, ex. return `return window.innerWidth / 1280.0;` when Width > Height. 1280x800 is my source ratio(1.6), so this is the second tweak part.

**Comment by eoghanmccarthy** [comment]
@PolGuixe Hi, is there a chance you could share your solution to this if you got it working? I'm struggling with this at the moment. We're making an image annotation tool so the canvas needs to be the size of the image but scale down if the image is larger than the container.

**Comment by deadcoder0904** [comment]
I want to do the same thing & I'm unable to figure out the "correct approach" with making it responsive.

I am making a Chrome Extension that will take screenshot of a tab & then put it in the center while having a sidebar with controls like padding like Figma/Sketch/Photoshop.

I want to decorate the image with a rectangle, which means the rectangle will act as a border to the image. Now I can't figure out how to make the rectangle centered & responsive while having a sidebar like https://codepen.io/chriscoyier/pen/BZNoev? I also saw Pixteller & want to have the rectangle like https://youtu.be/mXFgcq0Od9A?t=198 (timestamp 3:18)

Unrelated but I am unable to set `id` on Stage but `className` works just fine :)

Any help appreciated 🙏

**Comment by lavrton** [comment]
> Unrelated but I am unable to set an id on Stage 

Almost all properties that you use on `<Stage />` component will be passed directly into `Konva.Stage` instance. `className` is an exception. If you need to set id you can use this:

```html
<div id="your-id">
  <Stage />
</div>
```

I am not sure what help else do you need.
