### ISSUE TITLE
edit HSL with REact

### ISSUE THREAD

**Issue by thailh12** [konvajs/react-konva#346]
<img width="763" alt="Screen Shot 2019-03-25 at 10 03 16" src="https://user-images.githubusercontent.com/32217550/54892736-42ff0f80-4ee5-11e9-88db-3be28fa32ef1.png">
i want to do this feature with react but i can apply HS to the image

**Comment by lavrton** [comment]
@thailh12 what did you try?

**Comment by thailh12** [comment]
Is this the way to apply HSL filter to image?
How could i change HSL value (hue, saturation, luminance) by the slider
<img width="373" alt="Screen Shot 2019-03-26 at 08 48 47" src="https://user-images.githubusercontent.com/32217550/54965728-64730080-4fa4-11e9-8106-2563646d221c.png">

Here's my code
https://codesandbox.io/s/9z9v3255wo

**Comment by lavrton** [comment]
Yes. Also you have to cache the image, so filters can be applied. Here you can see a demo how cache is applied to `<Rect />`. You can do the same for `<Image />`.

**Comment by thailh12** [comment]
Sorry, but i can't find out your demo?

**Comment by lavrton** [comment]
It can be something like this:

```javascript
const LionImage = ({ hue }) => {
  const [image] = useImage("./lion.png", "Anonymous");
  const ref = React.useRef(null);

  React.useEffect(
    () => {
      if (image) {
        ref.current.cache();
      }
    },
    [image]
  );
  return (
    <Image image={image} ref={ref} hue={hue} filters={[Konva.Filters.HSL]} />
  );
};

class App extends Component {
  state = {
    hue: 150
  };
  render() {
    return (
      <>
        <input
          id="hue"
          type="range"
          min="0"
          max="259"
          step="1"
          value={this.state.hue}
          onChange={e => {
            this.setState({ hue: parseInt(e.target.value, 10) });
          }}
        />

        <Stage width={window.innerWidth} height={window.innerHeight}>
          <Layer>
            <LionImage hue={this.state.hue} />
          </Layer>
        </Stage>
      </>
    );
  }
}
```

https://codesandbox.io/s/1o4oq39p33
