### ISSUE TITLE
How to transform text and image?

### ISSUE THREAD

**Issue by KonstantinZhukovskij** [konvajs/react-konva#347]
How can I transform the text and the uploaded picture? From all that I have tried, it works only with a rectangle, in your example on the site.

**Comment by VividWombat** [comment]
create a demo of your code to look at

a suggestion. add a group. then add shapes to the group. attach transformer to the group. then transformer will transform all the shapes in the group. group and transformer need to have the same parent, usually the layer.

limitation - transformer can scale the group. but you cant then change the scale of the group later.

**Comment by borm** [comment]
what about multiple nodes?
