### ISSUE TITLE
In React dev tools the Layers are outside the main App. Is this expected?

### ISSUE THREAD

**Issue by eoghanmccarthy** [konvajs/react-konva#350]
As you can see in the screenshot below, the Layers are outside the main App. Is this as expected? (I'm using Redux for other tools in the wider application so the top most component is a Provider).

![Screenshot 2019-03-31 at 14 38 07](https://user-images.githubusercontent.com/21990778/55289761-b2cc3900-53c2-11e9-8a1e-861b04ac41af.png)

**Comment by lavrton** [comment]
It is not really "expected" but I don't know how to really fix it from `react-konva` side.

**Comment by MatteoGauthier** [comment]
Got the same issue... Any solution ?
