### ISSUE TITLE
Broken Typescript typings

### ISSUE THREAD

**Issue by vojty** [konvajs/react-konva#353]
Hi, I am unable to use react-konva with Typescript (TS 3.4.2, react-konva 18.6.8, konva 3.2.4)

```
TypeScript error: Property 'children' in type 'Stage' is not assignable to the same property in base type 'Container'.
  Type 'Collection<BaseLayer>' is not assignable to type 'Collection<Node<NodeConfig>>'.
    Type 'BaseLayer' is not assignable to type 'Node<NodeConfig>'.
      Types of property 'setZIndex' are incompatible.
        Type '(index: any) => BaseLayer' is not assignable to type '(zIndex: any) => false | Node<NodeConfig>'.
          Type 'BaseLayer' is not assignable to type 'false | Node<NodeConfig>'.  TS2416

    19 |     dblTimeout: any;
    20 |     tapStartShape: Shape;
  > 21 |     children: Collection<BaseLayer>;
       |     ^
    22 |     constructor(config: StageConfig);
    23 |     _validateAdd(child: any): void;
    24 |     _checkVisibility(): void;
```

Here is repository created from `create-react-app` and added typescript. I just pasted example from README in `App.tsx` https://github.com/vojty/react-konva-typescript

I also made PR with validation for typescript typings https://github.com/konvajs/react-konva/pull/352 . Just run `yarn test:typescript`

I could use `skipLibCheck: true` or `strict: false` but that's not really the option.

**Comment by lavrton** [comment]
Yeah, we need to apply strict mode to the whole `Konva` codebase. And that is hard and not fast action.

**Comment by lavrton** [comment]
Just made a new release of `konva@3.2.5` and `react-konva@16.8.7-0`. It should work of with the strict mode. Please try it and let me know if it helps.

**Comment by vojty** [comment]
@lavrton not sure you noticed that ^^ :)

**Comment by lavrton** [comment]
`@types/react` already in `devDependencies` and I don't see the warnings you mentioned.

**Comment by vojty** [comment]
forgot to upgrade dependencies :man_facepalming: 
```
"konva": "^3.2.6",
"react-konva": "^16.8.7-2",
```
^^ works just fine. Great job, thank you
