### ISSUE TITLE
Animating clip or clipFunc

### ISSUE THREAD

**Issue by albinmartinsson91** [konvajs/react-konva#354]
I'm creating an animation that requires me to animate the values of a clip. I want a group to mask it's content and scale up to reveal them. 

I've found `.clip` to do the trick but I can't seem to figure out any way to animate it's values. Let's say for example that I'd want to move my clipping mask from `x:0` to `x:100`. 

Is there any way to animate these values?

**Comment by lavrton** [comment]
In that case, you can animate `clipX` value.

**Comment by albinmartinsson91** [comment]
Thank you! I'm looking to create a rounded mask. Is there any way to achieve this effect by rounding the group or updating the values inside a `clipFunc`?

```clipFunc(ctx => {
  ctx.arc(250, 120, 50, 0, Math.PI * 2, false)
})```
