### ISSUE TITLE
construct or call signatures

### ISSUE THREAD

**Issue by S4n60w3n** [konvajs/react-konva#357]
I am using typescript in my project and I am getting weird issue.
`JSX element type 'Rect' does not have any construct or call signatures.ts(2604)`

The same issues are present in all react-konva elements.

To make it work I need to retype them to any and that's unfortunate.

**Comment by lavrton** [comment]
Can you make a reproducible repo?

**Comment by S4n60w3n** [comment]
Should be basic ts project, I will do it.

**Comment by S4n60w3n** [comment]
Sorry, the issue was on my end. I had old react package `"react": "^16.4.1",`. Upgrading to the `"react": "^16.8.6",` fixed the issue.
