### ISSUE TITLE
package-lock.json is not present in source

### ISSUE THREAD

**Issue by sarat1669** [konvajs/react-konva#358]
Need package-lock.json for https://github.com/konvajs/react-konva/tree/v1.1.6

**Comment by lavrton** [comment]
Why do you need it?

**Comment by sarat1669** [comment]
@lavrton , I am trying to build it locally, but by default its installing react 16 instead of the react 15 which is required.

**Comment by kmannislands** [comment]
@lavrton Good idea to check in either `package-lock.json` or `yarn.lock` for this reason exactly. Certainly no point in using them and _not_ checking them in.
@sarat1669 about react versions, though, I am using with 16.8 and it seems fine for me

**Comment by sarat1669** [comment]
@kmannislands I am looking for a version which works with react 15.6. I am rendering the canvas inside an iframe, but the event listeners are being created on the original window. I need to monkey patch this to make it work for my requirements.

**Comment by kmannislands** [comment]
@sarat1669 in that case, I don't see how a lockfile would help you. The [`package.json` for this repo explicitly specifies react 16.8](https://github.com/konvajs/react-konva/blob/58e791703c73d48625bb04d45270eb446bb289c6/package.json#L24), so the lockfile would as well.

If I am understanding your use-case correctly, I don't think that you even need to build react-konva from source locally. Specifying your specific version of react as a ['resolution' in package.json should work]:
```js
{
// ...rest of package.json
  "resolutions": {
    "react": "~15.6.2"
  }
}
```

**Comment by sarat1669** [comment]
@kmannislands , I am looking for the lockfile of version v1.1.6, not the latest release and I need to build it not because of version mismatch, but because I want to change something in the code.

**Comment by lavrton** [comment]
Just manually install the required version of `React`. 

`react-konva@1.1.6` is very old. And I recommend you upgrade all dependencies if that is possible.
