### ISSUE TITLE
onTab event

### ISSUE THREAD

**Issue by S4n60w3n** [konvajs/react-konva#364]
Can you please verify that onTab event is listening correctly?

https://codesandbox.io/s/react-konva-consume-context-demo-tt3ng?fontsize=14

It`s not working for me and therefore I cannot use it on mobile phones, atleast not without workaround

**Comment by lavrton** [comment]
What is `onTab` event? Do you mean `onTap`?

**Comment by S4n60w3n** [comment]
Damt, i am so stupid :D Haven`t noticed the misspelling .... Thanks for quick response
