### ISSUE TITLE
useEffect Hook - uncaught callback scheduler error

### ISSUE THREAD

**Issue by Skaterjess2012** [konvajs/react-konva#365]
When using a useEffect hook, one of the dependencies of react-konva
(the scheduler) emits a strange error after being defined in a component:

scheduler.development.js:348 Uncaught TypeError: callback is not a function
    at flushFirstCallback (scheduler.development.js:348)
    at flushWork (scheduler.development.js:441)
    at MessagePort.channel.port1.onmessage (scheduler.development.js:188)
flushFirstCallback @ scheduler.development.js:348
flushWork @ scheduler.development.js:441
channel.port1.onmessage @ scheduler.development.js:188

this error repeats every time the canvas seems to update

**Comment by lavrton** [comment]
Can you make a demo? It works ok for me.

**Comment by Skaterjess2012** [comment]
Sorry; I just realized it was the issue with my yarn cache! for some reason it was causing this issue

**Comment by camroots** [comment]
@Skaterjess2012 I'm also facing this issue. Could you please tell me the steps you followed to resolve?

**Comment by lavrton** [comment]
@camroots try to reinstall all dependencies. Like
```bash
rm -rf ./node_modules
npm install
```

**Comment by Skaterjess2012** [comment]
this issue occurs when using react-hooks with react-konva in webpack; I'll put together a demo soon

**Comment by LinTmiN** [comment]
@Skaterjess2012 Are you using  `"react-konva": "16.8.7-2"`, Try using`"react-konva": "16.8.6"`  and re-running your package manager.The `"react-konva": "16.8.7-2"` use the wrong `scheduler `version.

**Comment by lavrton** [comment]
Yeah, `16.8.7-2` is using the new `scheduler`. And I saw this error once. But right now I can't reproduce it in tests. You may try to downgrade to `react-konva@16.8.6`.

**Comment by lavrton** [comment]
I found how to reproduce it! Just published new `react-konva@16.8.7-2` with the old `scheduler` version. And the issue should be fixed now.

**Comment by Skaterjess2012** [comment]
Thanks, guys! I worked like a charm
