### ISSUE TITLE
ie11 error

### ISSUE THREAD

**Issue by r1005410078** [konvajs/react-konva#367]
in IE11 exist error:
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

**Comment by lavrton** [comment]
Can you make a demo? Did you check this https://reactjs.org/docs/javascript-environment-requirements.html?

**Comment by lavrton** [comment]
Closing... Add more info if you still have issues.
