### ISSUE TITLE
Rotation of multiple stickers

### ISSUE THREAD

**Issue by developdeez** [konvajs/react-konva#371]
I've been trying to figure out how to use konva to put sitckers on an image and have them stick properly through rotation, scale, and moving.
I've got the last two done but rotation is throwing me in circles ;)

I clcik my rotation button then it rotates the main image and the sticker....am I missing several things?

So far I'm doing this:
```
  rotate = () => {
    if (this.mounted) {
      this.setState(
        {
          rotation: this.state.rotation + 90,
          konvaImageList: this.state.konvaImageList.map(konvaImage => {
            return {
              ...konvaImage,
              rotation: konvaImage.rotation + 90,
              x: konvaImage.x,
              y: konvaImage.y
            };
          })
        },
        () => console.log(this.state.konvaImageList, "konvaImageList")
      );
    }
  };
```

Thanks

**Comment by lavrton** [comment]
So what is your question?

**Comment by developdeez** [comment]
What is the key to rotating stickers on an image?
Is it the group feature? Or maybe a calculation based on base image?

**Comment by developdeez** [comment]
Here's the initial pic with a konva image (as a sticker) on top of another konva image
![image](https://user-images.githubusercontent.com/13059525/59154523-c9c58200-8a28-11e9-8f3b-429f2704b3f3.png)

Here's after  90 degree rotate:
![image](https://user-images.githubusercontent.com/13059525/59154526-db0e8e80-8a28-11e9-822a-84d72fcfc5fb.png)

Notice the change.

**Comment by developdeez** [comment]
It's rotating in it's own square I'd say. Just courious how to associate it with the base pic

**Comment by lavrton** [comment]
I think the simplest way is to move all of them into the group, and then just rotate the group.

**Comment by developdeez** [comment]
@lavrton Thanks for the response.

I've tried using Group but the trouble is the dragging of the main image within the group.
It seems to rotate Group has to have it's x,y set accoding to where the image will show. But when you drag this image, the Group has one idea of x,y while the image itself has another.

Basically what I want to do is rotate, drag the image and rotate it again.
