### ISSUE TITLE
Getting image x,y from Group

### ISSUE THREAD

**Issue by developdeez** [konvajs/react-konva#372]
I'm trying to save a copy of the image that the user edits.

I started using groups to better handle scaling and rotation but with that came a new issue.

Before I would get the values of the base image wherever it was on the canvas. Now that Im using group, that dosnt seem so straight forward. I've tried using "group".target.children[0].attrs... but ti doesnt seem to give good x,y data; also it causes errors if I drag images within the group (since the children dont have children.

How do I properly retrieve the x,y of in image in a Group?

Here's my current code to save for reference:

```
  handleExportClick = () => {
    if (this.mounted && !this.state.uploading && this.SourceImageRef) {
      this.setState({ hideTransformer: true, uploading: true }, () => {
        const rotation = this.state.rotation % 360;
        const width =
          rotation == 0 || rotation == 180
            ? this.state.imageWidth * this.state.scale
            : this.state.imageHeight * this.state.scale;
        const height =
          rotation == 0 || rotation == 180
            ? this.state.imageHeight * this.state.scale
            : this.state.imageWidth * this.state.scale;
        //TODO: get image height from group
        const x = this.state.x_pos - width / 2;
        const y = this.state.y_pos - height / 2;
        const dataURL = this.stageRef.getStage().toDataURL({
          mimeType: "image/jpeg",
          x,
          y,
          width,
          height,
          quality: 1,
          pixelRatio: this.pixelRatio
        });
        const blobData = this.dataURItoBlob(dataURL);
        const file = {
          filename: this.props.imageObject.name,
          filetype: "image/jpeg",
          filebody: blobData
        };

        this.handleUpload(file);
      });
    }
  };
```

**Comment by lavrton** [comment]
Where does it give you error here?

**Comment by developdeez** [comment]
Doesn't give an error. I thought I edited the comment.

My main problem is getting x,y of main image.

**Comment by lavrton** [comment]
You need to get position relative to what?

Local position: `image.position()`

Absolute position: `image.getAbsolutePosition()`.

**Comment by developdeez** [comment]
Position relative to Stage I guess. In the end I want to sleected the image within the Group. So starting at top left x,y and getting everything within the height and width of the image.

 

Thanks I’ll try the 2 methods below.

**Comment by developdeez** [comment]
Put a ref on the main image within the group.
Tried accessing in a few ways but it seems those functions dont exist for the <Image> components
```

 this.SourceImageRef.image.getAbsolutePosition(),
                      this.SourceImageRef.image.position()
```

**Comment by developdeez** [comment]
For clarification:
![image](https://user-images.githubusercontent.com/13059525/59233618-0b2b6e00-8b9e-11e9-8894-0a8a53c473cf.png)

**Comment by developdeez** [comment]
figured it out with math again :)
