### ISSUE TITLE
Label Tag not working

### ISSUE THREAD

**Issue by Epictek** [konvajs/react-konva#374]
I'm getting TypeError: parentInstance.add is not a function in my project, tried it in a codesanbox and it does the same

https://codesandbox.io/s/naughty-kilby-pgjsz

**Comment by lavrton** [comment]
It's API is a bit different. 

```javascript
<Label x={50} y={50}>
  <Tag pointerWidth={10} stroke="black" />
  <Text y={50} x={5} fontSize={18} text="test" fill="red" />
</Label>
```

`<Text />` should be a child of `<Label />'.

https://codesandbox.io/s/distracted-sun-mhym8
