### ISSUE TITLE
Apply global image filter

### ISSUE THREAD

**Issue by mariotacke** [konvajs/react-konva#375]
How would one go about adding a global `Blur` filter (or any other filter) to the entire scene/stage/layer? I've tried adding an overlay `Rect` with a `Blur` filter but it will not a apply to the content underneath it.

I'm using `konva-react`:

```
<Stage width={width} height={height}>
   <Layer>
     <Image x={width / 2} y={height / 2} />
     <Image x={width / 2} y={height / 2} />
     <Overlay x={0} y={0} width={width} height={height} />
  </Layer>
</Stage>
```

I've tried several things, including trying to copy the source canvas image context, generating a picture and adding it to the canvas with a `Blur` filter. 

Any idea how to go about this?

**Comment by lavrton** [comment]
Applying filter doesn't effect underlying shapes. If you need to apply blur for the whole layer you have to cache it and use `Blur` filters for it.

But also there is a hacky workaround. You can apply CSS filter to the canvas element of the layer. It will work much faster and you don't need to bother about caching.

```javascript
const canvas = layer.getCanvas()._canvas;

canvas.style.filter = 'blur(4px);'
```

The downside of that method is that it will be not visible if you will try to save stage/layer as an image (in that case you have to deal with caching).
