### ISSUE TITLE
react-kovan export images

### ISSUE THREAD

**Issue by tomnyson** [konvajs/react-konva#377]
I have a problem with react-kovan.
I have create Stage kovan with ref in react
<Stage
        width={200}
        height={300}
        ref={this.canvasRef}
      >
now I want to export this canvas created with kovan to img format base64 how can i do it

**Comment by lavrton** [comment]
What did you try?

**Comment by tomnyson** [comment]
Hello sir.
I tried to use this.canvasRef.current.toDataURL()
but error totally

**Comment by lavrton** [comment]
What error? The code looks ok for me.

**Comment by tomnyson** [comment]
http://prntscr.com/o4o6zk

**Comment by tomnyson** [comment]
`<img src='http://prntscr.com/o4o6zk'/>`

**Comment by tomnyson** [comment]
I can get list ref from react ref of Stage 
![image](https://user-images.githubusercontent.com/10257765/59897443-e7c2b780-9416-11e9-9770-6cc9e8f5a2d0.png)
which is attribute I can  export image to base 64

**Comment by lavrton** [comment]
Just try to google that error. Disclaimer: you have CORS issues with your images. Probably you are using an image from a different domain.

**Comment by lavrton** [comment]
https://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported
