### ISSUE TITLE
Circle class can't update when my position data x or y changed

### ISSUE THREAD

**Issue by nianiaJR** [konvajs/react-konva#378]
Hi, I've a Component which render about a Circle class like this:
```
     <Circle x={this.state.x} y={this.state.y} />
    <Line points={[....]} />
```
I when I change the (x,y) state, the Circle don't render expected. I know this attribute are primitive value. So how can I make this render update really?  BTW, the line can update correctly because points attribute always get a new array value.

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by Vicfeel** [comment]
try this  https://github.com/konvajs/react-konva/#strict-mode.

**Comment by nianiaJR** [comment]
I've find the solution. I just mistake the use of `x, y` with the `position` api. Thanks.
