### ISSUE TITLE
How to get position, rotation, scale elements of transformed group?

### ISSUE THREAD

**Issue by sadwizard** [konvajs/react-konva#380]
I am transforming group of elements and after transforming want to get (position | rotate | scale) each of element of group in order to save them. Is there any easy way to do this on konva ?

**Comment by sadwizard** [comment]
i can get position using getClientRect, but how about rotation and scale?

**Comment by lavrton** [comment]
You can take the absolute transformation matrix from the node and then compute all properties
```
const transform = node.getAbsoluteTransform();
const matrix = transform.getMatrix();
const x = matrix[4];
const y = matrix[5];
```

You can read here more for understanding the matrix: https://stackoverflow.com/questions/4361242/extract-rotation-scale-values-from-2d-transformation-matrix

Or you can just calculate all values manually by checking all the parents.

**Comment by sadwizard** [comment]
Thnx it's worked
