### ISSUE TITLE
Filter on whole <Layer/> while keeping shapes draggable

### ISSUE THREAD

**Issue by MarkusWendorf** [konvajs/react-konva#381]
Until now I used a css filter on top of the canvas element to apply filter effects to the whole stage / layer. However, as pointed out in [#375 ](https://github.com/konvajs/react-konva/issues/375), it isn't possible to save the resulting image. 

I think it would be possible to use [the new canvas filter property](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter), but sadly I'm stuck with a Webkit Webview on iOS that doesn't support this property.

I tried to modify the filter example to apply it to the Layer component, but I can't figure out how to make it work smoothly with draggable shapes: [Sandbox](https://codesandbox.io/s/react-konva-filters-demo-3bl6o). 

Is there a (good) solution for this problem?

Edit: something along the lines of onDragMove={() => this.layer.cache()} works if applied on every draggable element. But I'm still curious what else could be done.

**Comment by lavrton** [comment]
To make filters work we have to convert a node into an image. That is why we need to use `node.cache()`. The cached object became "static" as an image so it has not animations now draggable nodes. As workaround, we can use `onDragMove={() => this.layer.cache()} ` to recache node on every move so it will be "dynamic". But that operation can be slow on a large canvas.

Another way can be caching each child node individually and apply filters to them (without caching the layer).

Or we can try to use CSS filters in realtime, and then use caching + filters when you want to export canvas into image (or even try to use html2canvas library).

**Comment by MarkusWendorf** [comment]
Thank you for the explanation. But I'm having problems with Safari / Webkit (both Desktop and iOS).
I run out of memory if I interact with the canvas for some time (easily reproducable on "low" memory devices, e.g. iPad). Do I need to free memory manually and if so, how? Here's a sandbox: [Testcase for Safari](https://codesandbox.io/s/react-konva-memory-problem-recache-pbtq3).

**Comment by lavrton** [comment]
As workaround, you can try to "remove" canvas elements manually. See here: https://github.com/konvajs/konva/issues/653

**Comment by MarkusWendorf** [comment]
Closing this issue, my initial problem was solved but the memory problem remains.
