### ISSUE TITLE
Konva Filter on Images dont apply

### ISSUE THREAD

**Issue by ASVBPREAUBV** [konvajs/react-konva#383]
Thanks for the great libary. i use i frequent and really like it.
I tried to apply some simple filters on images in react.
I have a demo here : https://codesandbox.io/embed/react-konva-image-loading-pgy76
Its basicly a mix of the two demos in on the website.
Could not figure it out. is it the caching?
This is the interesting part:

` 
<Image
        x={this.props.x}
        y={this.props.y}
        image={this.state.image}
        filters={[Konva.Filters.Noise]}
        noise={1}
        ref={node => {
          this.imageNode = node;
        }}
      />
`

**Comment by lavrton** [comment]
Check the console. It has all the information.

**Comment by ASVBPREAUBV** [comment]
Oh man. Sorry. Thanks for the quick help

**Comment by lavrton** [comment]
We can't apply filters on CORS images.
