### ISSUE TITLE
React Konva nested functional component has no parent object?

### ISSUE THREAD

**Issue by ssolari** [konvajs/react-konva#385]
I expected to be able to build functional Konva components inside other functional Konva components.   The drawing of components works fine, but events on the nested functional components seem to lose their parents. 

In the following code the idea is to have a line track the angle of a click around a circle with multiple circles.    Clicking on the inner Circle inside Layer works fine.   However clicking on the NestedCircle (which is a wrapper around Circle) produces an error when capturing the touch event because ```var stage = e.target.getStage();``` produces an undefined stage even though e.target is a Circle.

Ultimately I'd like to create multiple components with a map function through some parameterization, but I don't understand why (and how to fix) the issue here. 

Example of issue:

```javascript
export function CircleTouch() {

    const xOrigin = 0.5 * window.innerWidth;
    const yOrigin = 0.5 * window.innerHeight;
    const outRad = 150;
    const inRad = 100;

    const [pointerRad, setPointerRad] = useState(0);
    const [isDown, setIsDown] = useState(false);

    function circleDown(e) {
        setIsDown(true);
        updateRad(e)
    }

    function circleUp(e) {
        setIsDown(false);
    }

    function circleMove(e) {
        if (isDown) {
            updateRad(e)
        }
    }

    function updateRad(e) {
        var stage = e.target.getStage();
        const pointerPos = stage.getPointerPosition();
        const xpos = pointerPos.x - xOrigin;
        const ypos = yOrigin - pointerPos.y;
        const rad = Math.atan2(ypos, xpos);
        setPointerRad(rad);
    }

    function NestedCircle (props) {
        return(
            <Circle
                x={xOrigin}
                y={yOrigin}
                radius={props.radius}
                fill="white" stroke="red" strokeWidth={1}
                onMouseDown={circleDown}
                onMouseMove={circleMove}
            />
        )
    }

    function getNewLine() {
        const x1 = xOrigin + inRad*Math.cos(pointerRad);
        const y1 = yOrigin - inRad*Math.sin(pointerRad);
        const x2 = xOrigin + outRad*Math.cos(pointerRad);
        const y2 = yOrigin - outRad*Math.sin(pointerRad);
        return [x1, y1, x2, y2]
    }

    return (
        <Stage width={window.innerWidth} height={window.innerHeight} onMouseUp={circleUp}>
            <Layer>
                <NestedCircle radius={outRad}/>
                <Circle
                    x={xOrigin}
                    y={yOrigin}
                    radius={inRad}
                    fill="white" stroke="grey" strokeWidth={1}
                    onMouseDown={circleDown}
                    onMouseMove={circleMove}
                />
                <Line stroke='purple' points={getNewLine()}/>
            </Layer>
        </Stage>
    )
}
```

**Comment by ssolari** [comment]
I should say that I have noticed that pushing the NestedCircle as its own first class functional component works, for example putting it outside the TouchCircle component 

```javascript
function NestedCircle2 (props) {
    return(
        <Circle
            x={props.xO}
            y={props.yO}
            radius={props.radius}
            fill="white" stroke="red" strokeWidth={1}
            onMouseDown={props.circleDown}
            onMouseMove={props.circleMove}
        />
    )
}

```
and using it instead as
```javascript
<NestedCircle2 xO={xOrigin} yO={yOrigin} circleDown={circleDown} circleMove={circleMove} radius={outRad}/>
```

So the issue really is why can't it be inside the functional component?   It would be nice to use the reach hooks as state inside the nested component.

**Comment by lavrton** [comment]
I don't think it is a good idea to define functional components inside other functional components.

I think it produces the bug because:
1. when you click on big circle it calls `circleDown`.
2. that updates the state with `setIsDown()`
3. updating the state will trigger rerender
4. As a new function component is used it will create NEW instance of circle shape, so the old instance is removed (so `getStage()` returns undefined).

Just use your updated version.
