### ISSUE TITLE
Non Negative Rect dimensions

### ISSUE THREAD

**Issue by jjarrett21** [konvajs/react-konva#386]
I'm using the transformer, and noticing my box dimensions go negative if I cross the axis and I want the position to stay the same but the box to always have positive dimensions and can't seem to work it out. I've attached a code snippet can't find anything in the docs about this. 
Math.abs() does weird things because of the scale. 

`const handleTransformEnd = (e: Konva.KonvaEventObject<Event>) => {
    const node = rectRef.current;

    // get the actual scale at this moment in time.
    const scaleX = node.scaleX();
    const scaleY = node.scaleY();

    // then reset it back
    node.scaleX(1);
    node.scaleY(1);
    onChange({
      ...shapeProps,
      x: Math.round(node.x()),
      y: Math.round(node.y()),
      width: Math.round(node.width() * scaleX),
      height: Math.round(node.height() * scaleY)
    });
    e.cancelBubble = true;
  };`

**Comment by lavrton** [comment]
Then just use a scale with a negative value. I can't think how the shape can keep the position and positive width/height being reverted at the same time.

**Comment by jjarrett21** [comment]
I don't see why the box dimensions would be negative, width and height aren't really based off of position, I tried some of this logic:

`    onChange({
      ...shapeProps,
      x: Math.round(node.x()),
      y: Math.round(node.y()),
      width:
        Math.round(node.width()) < 0
          ? Math.round(node.width() * -scaleX)
          : Math.round(node.width() * scaleX),
      height:
        Math.round(node.height()) < 0
          ? Math.round(node.height() * -scaleY)
          : Math.round(node.height() * scaleY)
    });`

**Comment by lavrton** [comment]
Sorry, I don't get what is your issue. Can you make a demo and show what behavior is not expected fro you?

**Comment by jjarrett21** [comment]
I can later today, but lets say you grab a box whose HxW if I drag one edge of the width from left to right and essentially inver it it tells me my box dimensions are negative.

**Comment by lavrton** [comment]
Right, because the `Transformer` is changing the scale on transform. If you change size over edge it will invert scale, so it produces negative value.
