### ISSUE TITLE
Image.fromURL is not a function

### ISSUE THREAD

**Issue by casamia918** [konvajs/react-konva#387]
Hi. I'm trying to implement image drag and drop functionality (drag from outer react dom), with following below tutorial.
https://konvajs.org/docs/sandbox/Drop_DOM_Element.html

But when I call Image.fromURL, it throws error that says Image.fromURL is not a function.

Why can't I use it? I can found that typescript type definition file has definition for "static fromURL" function. (konva/lib/types/shapes/Image.d.ts)

**Comment by lavrton** [comment]
I guess you need `Konva.Image.fromURL`
