### ISSUE TITLE
Is cache work fine?

### ISSUE THREAD

**Issue by Zabedovskiy** [konvajs/react-konva#388]
Hi! Very strange cache, @lavrton. When I changed count of texts to 1000, I saw 15 fps at Stats. Although I checked use cache, I saw the same 15 fps at Stats. Are you sure that cache work fine in react-konva realization? It's really important question for me, because I have large map 482250x120250 and I have about 4000 objects on map, when I try dragging or scale it I have about 10-20 fps. It's realy few. In the future at this map will be about 30000 object and I scared about performance that I will have. Can you recomend best way for it, or may be i must change 'react-konva' to simple konva library, because on this example with cache all works fine with count 20000k of objects

https://jsfiddle.net/513c8s5d/2/

ps it's copy of my question in https://github.com/konvajs/react-konva/issues/20#issuecomment-514913868 , you can delete it

**Comment by lavrton** [comment]
Can you make a `react-konva` version of your issue? It should work just fine. Probably you have performance issues because of React reconciliation process. It really depends on your components.
