### ISSUE TITLE
performance isuue react-konva vs vanilajs with requestAnimationFrame

### ISSUE THREAD

**Issue by vospascal** [konvajs/react-konva#396]
Could someone help me?
i got this example in vanillajs running on chome developer x6 slow down 57-60 fps
https://codesandbox.io/s/objective-frog-fe0zq code
https://fe0zq.csb.app/ demo

i got this example in react-konva running on chome developer x6 slow down 1-4 fps
https://codesandbox.io/s/react-konva-image-loading-7us54 code
https://7us54.csb.app/  demo

think the diverence is huge could be because react and konva is not running proper requestAnimationFrame any tips to make it run smoothly ? would realy like to use react and konva 

thnx in advance

**Comment by lavrton** [comment]
As I can see from Chrome Dev tools, performances issues go from the React. You can try to use it in production mode, as it should work faster.

Also as I can see you are changing the state of the app on every `touchmove` and `mousemove`. But events can be triggered very frequently. So I think it will make sense to throttle them (like with `requestAnimationFrame`).

**Comment by vospascal** [comment]
ill try the requestAnimationFrame throttling will report back ;-)

**Comment by vospascal** [comment]
@lavrton could you help me ? cant seem to figure it out

**Comment by lavrton** [comment]
Wait. Why do you add listeners in `render()`? `render()` function can be called many times per second. I don't think you want to subscribe to events so many times.

Here is my updated version: https://codesandbox.io/s/react-konva-paralax-demo-fv8yd
It works better for me. Also, the production version made with `npm run build` works even better.

React version will be always slower than the native version in your first demo.

**Comment by vospascal** [comment]
@lavrton add listeners in render ... right thnx.... how stupid over looked that completely ;-)
works great now konva is great to! 
Thnx for the help much appreciated!
