### ISSUE TITLE
How to set event onKeyUp, onKeyDown, on KeyPress for shape?

### ISSUE THREAD

**Issue by tanobi92** [konvajs/react-konva#397]
I Tried set event KeyDown for Rect, but it failed (set for Stage, Layer also failed).

Demo: https://jsbin.com/qiqavov/edit?js,console,output

Help me! please! Thanks :)

**Comment by lavrton** [comment]
There are not keyboard events in Konva. You can listen to them on wrapper div:

```
<div tabIndex={1} onKeyDown={this.handleTextareaKeyDown}>
 <Stage>
```

Related: https://konvajs.org/docs/events/Keyboard_Events.html#HTML5-Canvas-Keyboard-events-with-Konva

**Comment by tanobi92** [comment]
Hi @lavrton, I have meny shapes. I want to set color for shape selected?

**Comment by lavrton** [comment]
Then you need to have a concept of "selected shape" and save it somewhere in your store. In keyboard handler just update selected shape.

**Comment by tanobi92** [comment]
@lavrton, thank you very much! I done :D

**Comment by surajsharma** [comment]
i have `onKeyPress={handleKeyPress} ` where `handleKeyPress` is part of a functional component with hooks, trouble is, it never triggers, no matter which DOM element i pass it to, currently have it on my `<Stage/>` component. any ideas will be appreciated thanks.

**Comment by lavrton** [comment]
@surajsharma Konva nodes don't have keyboard events. Use events from the container as in my first comment above.

**Comment by surajsharma** [comment]
> @surajsharma Konva nodes don't have keyboard events. Use events from the container as in my first comment above.

The following doesn't seem to work either :

```
<CanvasContainer onKeyDown={handleKeyPress}>
            <CenteredContent onKeyDown={handleKeyPress}>
                {currentImage ? (
                    <>
                        <CanvasToolbar
                            drawMode={drawMode}
                            polyMode={polyMode}
                            setDrawMode={setDrawMode}
                            setPolyMode={setPolyMode}
                            drawVisible={drawVisible}
                            setDrawVisible={setDrawVisible}
                            grouped={grouped}
                            setGrouped={setGrouped}
                            scale={scale}
                            setScale={setScale}
                        />
                        <Stage
                            onMouseDown={handleMouseDown}
                            onMouseUp={handleMouseUp}
                            onMouseMove={handleMouseMove}
                            width={width}
                            height={height}
                            onClick={handleStageClick}
....
```
