### ISSUE TITLE
DragEnd event is called onClick

### ISSUE THREAD

**Issue by schester44** [konvajs/react-konva#401]
The onDragEnd callback fires when clicking on a shape.

Minimum reproduction:
https://codesandbox.io/s/konvajs-dragend-click-ex11i

**Comment by schester44** [comment]
this doesn't happen in older versions, v.1.7.2 to be specific.

https://codesandbox.io/s/react-konvajs-scale-center-ssl87

**Comment by lavrton** [comment]
That for the report. Fixed with the new version: https://codesandbox.io/s/konvajs-dragend-click-cgb1z

**Comment by lavrton** [comment]
New version of `konva`

**Comment by schester44** [comment]
ahh, sorry about that! thanks for the super quick response.
