### ISSUE TITLE
How can I create a new line inside a text element?

### ISSUE THREAD

**Issue by ribas14** [konvajs/react-konva#403]
In the documentation example (https://konvajs.org/docs/shapes/Text.html) it shows that I can use \n to create a new line, but it doesn't work for some reason.

```
      var complexText = new Konva.Text({
        x: 20,
        y: 60,
        text:
          "COMPLEX TEXT\n\nAll the world's a stage, and all the men and women merely players. They have their exits and their entrances.",
        fontSize: 18,
        fontFamily: 'Calibri',
        fill: '#555',
        width: 300,
        padding: 20,
        align: 'center'
      });
```

**Comment by lavrton** [comment]
Can you make a demo where a new line doesn't work for you?

**Comment by ribas14** [comment]
hey @lavrton, here it is

https://codesandbox.io/embed/react-konva-basic-demo-e4id5

**Comment by lavrton** [comment]
And what is not working here? The demo looks ok for me.

**Comment by fel-ri** [comment]
same problem, when I try to create a new line it doesn't work, like in this example:

```
        text:
          "COMPLEX TEXT\n\nAll the world's a stage, and all the men and women merely players. They have their exits and their entrances.",
```
\n should create a new line but it just appears as text

**Comment by lavrton** [comment]
Works just fine: https://codesandbox.io/s/react-konva-multiline-text-repi0

**Comment by ribas14** [comment]
I need to remove the listener of the enter key to create a new line, thanks.

**Comment by ankursehdev** [comment]
@ribas14 - how did you remove the listener on enter key? I want to edit text in multiline.
