### ISSUE TITLE
Is it possible to pass down attributes to the <canvas> via the Layer component?

### ISSUE THREAD

**Issue by marcofugaro** [konvajs/react-konva#404]
I want to pass down a `style` attribute to the `<canvas>` element, how do I do it?

Here is what I am doing:

```js
<Layer style={{ opacity: 0.3 }}>
  // ...
```

Hovever it just gets ignored

**Comment by lavrton** [comment]
There is no method for that right now. And it many cases it is not recommended. If you REALLY want it you can do this:

```javascript
const Regions = ({ regions }) => {
  const layerRef = React.useRef(null);

  React.useEffect(() => {
    // find canvas element
    // warn: to use private API of Konva
    const canvas = layerRef.current.getCanvas()._canvas;
    // set opacity manually:
    canvas.style.opacity = 0.8;
  });

  return (
    <Layer ref={layerRef}>
      {regions.map(region => {
        return (
          <Line
            points={region.points}
            fill={region.color}
            closed
          />
        );
      })}
    </Layer>
  );
};
```

**Comment by marcofugaro** [comment]
Thank you! More contextually I need to apply the opacity to the `<canvas>` via CSS because I have a shape with opacity + borders, and I can't set `perfectDrawEnabled={false}` because I need the borders.

I was having some performance issues and thankfully I found this https://konvajs.org/docs/performance/Disable_Perfect_Draw.html

**Comment by Kontinius** [comment]
Related to pass ref property to Konva components, how can I do to aply an animation to <Rect> component from function component ( from useEffect ) ? ie, how to apply this same animation , but from useEffect?

`    componentDidMount() {
        
        const {design} = this.props;
        if(design.blink){
            var period = 150;        
            var anim = new Konva.Animation(frame => {
                this.rect.opacity((Math.sin(frame.time / period) + 1.5) / 2);
            }, this.rect.getLayer());
        
            anim.start();
        }
    }

<Rect ref={node => {
              this.rect = node;
 }} 
`
Thanks in advance!
