### ISSUE TITLE
Is there a way to keep the image aspect ratio on transform?

### ISSUE THREAD

**Issue by ribas14** [konvajs/react-konva#407]
I'm adding images and everything is working, but I don't want to let users to stretch images, is there a way to lock the aspect ratio? 

I found this option on the documentation but I don't think that this applies to Images.

https://konvajs.org/api/Konva.Transformer.html#keepRatio

**Comment by lavrton** [comment]
It is enabled by default. You may want to disable some anchors:

```javascript
  const tr = new Konva.Transformer({
    node: img,
    enabledAnchors: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
  });
  layer.add(tr);
```

https://jsbin.com/voqeqixusu/1/edit?html,js,output

**Comment by ribas14** [comment]
Thanks, do you know how to do it in something like <Transformer ref={trRef} />?

**Comment by lavrton** [comment]
`<Transformer ref={trRef} enabledAnchors={['top-left', 'top-right', 'bottom-left', 'bottom-right']} />`

**Comment by ribas14** [comment]
Thats it, thank you.
