### ISSUE TITLE
Question: onDragEnd group children coordinates

### ISSUE THREAD

**Issue by mmarkelov** [konvajs/react-konva#413]
Thank you for perfect library. I have some troubles with group with **Rect** children in it. I want to update coordinates of rects in onDragEnd group function:
```javascript
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { Stage, Layer, Group, Rect } from "react-konva";

import "./styles.css";

const RECTS = [
  { x: 190, y: 220 },
  { x: 200, y: 130 },
  { x: 260, y: 130 },
  { x: 260, y: 220 }
];

const DOT_LENGTH = 15;

function App() {
  const [rects, setRects] = useState(RECTS);
  const [group, setGroup] = useState({ x: 0, y: 0 });

  const onDragEnd = e => {
    const group = e.target;

    const newRects = [...rects].map((item, index) => {
      const rect = group.findOne(node => {
        return node.className === "Rect" && node.name() === `${index}`;
      });
      const { x, y } = rect.getAbsolutePosition();
      // let x = rect.x(); let y = rect.y();
      // console.log(rect.getAbsolutePosition())

      return { x, y };
    });

    setRects(newRects);
    setGroup({ x: group.x(), y: group.y() });
  };

  return (
    <div className="App">
      <Stage width={1000} height={1000}>
        <Layer>
          <Group x={group.x} y={group.y} onDragEnd={onDragEnd} draggable>
            {rects.map((item, index) => (
              <Rect
                offsetX={DOT_LENGTH / 2}
                offsetY={DOT_LENGTH / 2}
                x={item.x}
                y={item.y}
                key={index}
                name={`${index}`}
                stroke="#000"
                fill="#000"
                strokeWidth={0}
                width={DOT_LENGTH}
                height={DOT_LENGTH}
              />
            ))}
          </Group>
        </Layer>
      </Stage>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

[![Edit charming-morning-pcsvb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-morning-pcsvb?fontsize=14)

But I see some jumping after it. Where is a problem?

**Comment by mmarkelov** [comment]
I suppose that I should dynamically change only **Group** coordinates?

**Comment by lavrton** [comment]
@mmarkelov right. You need to update just group coordinates. Otherwise, the change will sum up, so you see the jump.

**Comment by mmarkelov** [comment]
@lavrton thanks a lot!

**Comment by Batuhan-Akkaya** [comment]
@lavrton Is there any way to change the position of children of the group after drag event? Because my app delete group frame while deselect items. Also I need to update redux store with children positions of the group. I do not use group in store. Group shown in only ui.

**Comment by lavrton** [comment]
Sure. It really depends how you store you data and how you structure your components.

You can use `node.getAbsolutePosition()` to know where a node is after parent drag. Or just calculate it manually.

**Comment by l1zard** [comment]
@lavrton hey, I try to use `node.getAbsolutePosition()` of children i get valid position of elements, update position in my store (still valid) but after re-render the points are on different location, maybe someting wrong with `Group`?

**Comment by lavrton** [comment]
@l1zard can you make a demo?

**Comment by l1zard** [comment]
@lavrton  https://codesandbox.io/s/react-konva-position-group-cgxqk

**Comment by lavrton** [comment]
@l1zard 

You sum up positions of circles.

Group has its own {x,y}. Dragging is changing {x, y} of Group. The simplest solution is to just reset group position to {0, 0} when you update the state (like on `dragend` event).

**Comment by l1zard** [comment]
@lavrton thanks, reset works well. But if I use tranformer with a group I have same issue but at this time reset doesnt work. Can make demo again on that example

**Comment by king742171** [comment]
Hi, I met same problem, the group position will sum up.
I use Vue to make my project.
here the code:(probably)
`<v-group v-for="item in squareList"
                   :key="item.id"
                   :config="{
                           id: item.id,
                           draggable: true,
                    }"
                    @click="tableSetShow">
           <v-rect :config="{
                                id: item.id,
                                x: item.x,
                                y: item.y,
                                width: item.width,
                                height: item.height,
                                fill: tableColor,
                                opacity: 1,
                                shadowColor: 'black',
                                shadowBlur: 10,
                                shadowOpacity: 0.5,
                         }"
             />
  </v-group>

<script>

export default {
       
       data() {
               return {
                        id: 0,
                        squareList: [],
               }
        },
       created() {
                 let self = this;
                 self.id++
                  self.squareList.push({
                            id: self.id.toString(),
                            x: 10,
                            y: 10,
                            width: 100,
                            height: 100,
                   });
       }
}


</script>`

I want to try reset the group {0,0},
but the group is a list, I cat use "this.$refs.group.getNode()......" to reset anything
It will console "this.$refs.group.getNode() is not a function".

p.s. : 
In my project, I have some shape is not create by list.
So, I very sure "this.$refs.shape.getNode()....", this function can run.

**Comment by lavrton** [comment]
You can just use `e.target` inside `dragend` to get access to Konva nodes.
