### ISSUE TITLE
Pass ref property to Konva components from useEffect?

### ISSUE THREAD

**Issue by Kontinius** [konvajs/react-konva#417]
Related to pass ref property to Konva components, how can I do to apply an animation to <Rect> component from function component ( from useEffect ) ? ie, how to apply this same animation , but from useEffect?

`
class BoardBox extends Component{
    
    componentDidMount() {
        
        const {design} = this.props;
        if(design.blink){
            var period = 150;        
            var anim = new Konva.Animation(frame => {
                this.rect.opacity((Math.sin(frame.time / period) + 1.5) / 2);
            }, this.rect.getLayer());
        
            anim.start();
        }
    }
}
`

And then apply ref to Rect component

`<Rect 
    ref={node => {
        this.rect = node;
    }}  
/>`

Thanks in advance!

_Originally posted by @Kontinius in https://github.com/konvajs/react-konva/issues/404#issuecomment-541263668_

**Comment by lavrton** [comment]
Sorry, I don't get it. What do you want to do?

**Comment by Kontinius** [comment]
Hello Anton,

I'm trying to apply the same effect thet you did in one of your code
examples ( https://codesandbox.io/s/1oml6z6524 ). The question is how can
it be done from useEffect() instead of  componentDidmount.

In your example yo write this code:

class App extends Component {
componentDidMount() {
var period = 500;

var anim = new Konva.Animation(frame => {
this.rect.opacity((Math.sin(frame.time / period) + 1) / 2);
}, this.rect.getLayer());

anim.start();
}

and then you set the *ref* attribute to:
ref={node => {
this.rect = node;
}}

To do the same with useEffect, I have written next code:

const rectRef = React.useRef();


    React.useEffect( () => {

        if(design.blink){

            const period = 150;
            const anim = new Konva.Animation(frame => {
                rectRef.current.opacity((Math.sin(frame.time / period) + 1.5
) / 2);
            }, rectRef.current.getLayer());

            anim.start();
        }
    },[design]);

and then set the ref attribute to:

ref={rectRef}

But my code is not working and the animation is not running

Could you please tell me if I'm doing something wrong?

Thanks!!!

Josep Fusté | Barcelona | *t* +34 93 332 10 14 *m* +34 65 303 50 10 |
*LinkedIn* <http://www.linkedin.com/in/josepfuste>


Missatge de Anton Lavrenov <notifications@github.com> del dia ds., 12
d’oct. 2019 a les 21:02:

**Comment by lavrton** [comment]
It can be something like this:

```javascript
const App = () => {
  const rectRef = React.useRef();
  const [blink, setBlink] = React.useState(false);

  React.useEffect(() => {
    if (!blink) {
      return;
    }
    var period = 300;

    var anim = new Konva.Animation(frame => {
      rectRef.current.opacity((Math.sin(frame.time / period) + 1) / 2);
    }, rectRef.current.getLayer());

    anim.start();
    return () => {
      anim.stop();
    };
  }, [blink]);
  return (
    <div>
      <input
        type="checkbox"
        checked={blink}
        onChange={e => {
          setBlink(e.target.checked);
        }}
      />{" "}
      Blinking?
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <Rect
            x={20}
            y={20}
            width={50}
            height={50}
            fill="green"
            shadowBlur={5}
            ref={rectRef}
          />
        </Layer>
      </Stage>
    </div>
  );
};
```

https://codesandbox.io/s/react-konva-animation-demo-with-hooks-w9ns7

**Comment by Kontinius** [comment]
Hello Anton!

The code works perfectly! Thank you so much for your help :)

Best regards,

Josep Fusté | Barcelona | *t* +34 93 332 10 14 *m* +34 65 303 50 10 |
*LinkedIn* <http://www.linkedin.com/in/josepfuste>


Missatge de Anton Lavrenov <notifications@github.com> del dia dl., 14
d’oct. 2019 a les 19:17:
