### ISSUE TITLE
How can I use opencvjs and konva together in React?

### ISSUE THREAD

**Issue by zmqp111** [konvajs/react-konva#418]
Hi, Guys.

I'm working on a small React project.

In my project, I want to use opencvjs and Konva.

For example, is there a way to images process with opencvjs and output them to the React page via Konva?

Do you have an idea?

Thanks

**Comment by lavrton** [comment]
If you have an image (or a canvas) element generated with opencvjs, you can just use it for `Konva.Image` node.
