### ISSUE TITLE
How to test components containing react-konva components using react-testing-library?

### ISSUE THREAD

**Issue by anku255** [konvajs/react-konva#419]
Hi! First of all, thank you for creating this awesome library. It is really nice and useful.

Please look at this [codesandbox](https://codesandbox.io/s/black-paper-op4rw). I want to test the following things in the `Editor` component - 

1. Test if Stage and Layer renders.
2. Simulate mouse events on the Stage and test if I am able to draw/drag rectangles or not.

I have looked at [test/runner.js](https://github.com/konvajs/konva/blob/master/test/runner.js) and have an idea about simulating the mouse events but the first problem is getting the reference to Stage and Layer nodes.

I tried using `getByTestId` function in `react-testing-library` but `data-testid` doesn't get passed to the dom nodes from both the `Stage` and `Layer` components;

Can anyone please help me with testing these components? How should I approach this?

**Comment by lavrton** [comment]
I don't think we can test it with `react-testing-library` right now.

`react-testing-library` works in nodejs env. But `react-konva` renders to just simple `div` when it detects nodejs.

**Comment by anku255** [comment]
@lavrton Thank you for your response. I am open to using any library that can be used to test it. Can you point me to a tutorial for setting the required environment for testing konva.js?

**Comment by lavrton** [comment]
I am testing `react-konva` with the `enzyme`. You can take a look here https://github.com/konvajs/react-konva/blob/master/tests/index-test.js

**Comment by anku255** [comment]
Thanks @lavrton.

**Comment by HyoilKim** [comment]
Hi @lavrton 

> I don't think we can test it with react-testing-library right now.

Is it valid now? Couldn't it test with react-testing-library?

**Comment by lavrton** [comment]
I didn't try.

**Comment by HyoilKim** [comment]
Thank you for the reply.

How can I test Konva components(Stage, Layer...) with react-testing-library? Is there any example?

**Comment by rnike** [comment]
I don't know if it is possible to add `'data-testid': props['data-testid']` for the createElement parameter in `ReactConvaCore`, for example:

`src/ReactConvaCore.ts`
```diff
  return React.createElement('div', {
    ref: container,
    accessKey: props.accessKey,
    className: props.className,
    role: props.role,
    style: props.style,
    tabIndex: props.tabIndex,
    title: props.title,
+   'data-testid': props['data-testid'],
  });
```
or just allow all div props for the Stage component by doing this

`src/ReactConvaCore.ts`

```diff
  return React.createElement('div', {
    ref: container,
-    accessKey: props.accessKey,
-    className: props.className,
-    role: props.role,
-    style: props.style,
-    tabIndex: props.tabIndex,
-    title: props.title,
+   ...props,
  });
```

**Comment by richardnabu** [comment]
Are there any updates on this question ? I'd be happy to help work on the problem but I would need to be put on the right track...
[](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl)
