### ISSUE TITLE
Image element with no image tag and strokeEnabled crash

### ISSUE THREAD

**Issue by DanCaton** [konvajs/react-konva#420]
I am setting it from this.state.image, where this.state.image is populated after an image.onload. It's initial value is `null`.

`<Image id=1 height={40} width={40} image={this.state.image} strokeEnabled={true} stroke="red />`

Compiling and running this code results in the following error

Context.js:244 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

Workaround by setting `strokeEnabled={this.state.image !== null}

**Comment by lavrton** [comment]
Can you make a demo? I tried this works just fine: https://codesandbox.io/s/react-konva-image-with-stroke-demo-7kin2

Are you sure you are not setting passing not loaded image into `Konva.Image`?

**Comment by DanCaton** [comment]
Hi Lavrton,

I've tried to recreate the issue in a sandbox demo but cannot seem to replicate - I noticed that in package.json, react-konva is listed as 16.10.1, but in my local dev app an update only takes me to 16.9.1.

The only time I am setting the image in state is in the contrsutor (to null), and then using
image.onload.

**Comment by lavrton** [comment]
Hard do say. The issue should be somewhere else. `strokeEnabled` should not be related here. It doesn't affect any drawing.

**Comment by lavrton** [comment]
Do you use canvas for the image? That is what I see in your error.

**Comment by DanCaton** [comment]
I've managed to replicate - It's a very niche situation where multiple props are combined.

I am setting my stage height and width to 0 initially and then using componentDidMount to resize based on the width of the parent component (calculated using a ref that is passed into the stage component), to change the stage size based on a changing window size.

To replicate,
- The stage must have a height and width of 0
- The Image must have strokeEnabled={true}, image={null} with shadowBlur and stroke set to valid values

You can easily work around this by either setting the initial stage height/width to be non-zero, or when the image is null, set shadowBlur or strokeEnabled to 0/false.

See code below

`import React, { Component } from "react";
import { render } from "react-dom";
import { Stage, Layer, Image } from "react-konva";

// custom component that will handle loading image from url
// you may add more logic here to handle "loading" state
// or if loading is failed
// VERY IMPORTANT NOTES:
// at first we will set image state to null
// and then we will set it to native image instance when it is loaded
class URLImage extends React.Component {
  state = {
    image: null
  };
  componentDidMount() {
    this.loadImage();
  }
  componentDidUpdate(oldProps) {
    if (oldProps.src !== this.props.src) {
      this.loadImage();
    }
  }
  componentWillUnmount() {
    this.image.removeEventListener("load", this.handleLoad);
  }
  loadImage() {
    // save to "this" to remove "load" handler on unmount
    this.image = new window.Image();
    this.image.src = this.props.src;
    this.image.addEventListener("load", this.handleLoad);
  }
  handleLoad = () => {
    // after setState react-konva will update canvas and redraw the layer
    // because "image" property is changed
    this.setState({
      image: this.image
    });
    // if you keep same image object during source updates
    // you will have to update layer manually:
    // this.imageNode.getLayer().batchDraw();
  };
  render() {
    return (
      <Image
        x={this.props.x}
        y={this.props.y}
        image={this.state.image}
        ref={node => {
          this.imageNode = node;
        }}
        strokeEnabled={true}
        shadowBlur={6}
        stroke="red"
      />
    );
  }
}

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      height: 0,
      width: 0
    };
    this.updateDimensions = this.updateDimensions.bind(this);
  }
  componentDidMount() {
    this.updateDimensions();
    window.addEventListener("resize", this.updateDimensions);
  }

  componentWillUnmount() {
    window.removeEventListener("resize", this.updateDimensions);
  }

  updateDimensions() {
    this.setState({
      height: window.innerHeight,
      width: window.innerWidth
    });
  }

  render() {
    return (
      <Stage width={this.state.width} height={this.state.height}>
        <Layer>
          <URLImage src="https://konvajs.org/assets/yoda.jpg" x={50} />
        </Layer>
      </Stage>
    );
  }
}

render(<App />, document.getElementById("root"));
`

**Comment by lavrton** [comment]
I see the issue. `Konva` is trying to use a special buffer canvas for better drawing. But the stage size is 0 so it produces the error.

I am not sure we need to fix that from `Konva` side. Just use some positive value for the initial size.

```javascript
this.state = {
      height: 5,
      width: 5
    };
```
