### ISSUE TITLE
React hooks incorrect scope in nested components

### ISSUE THREAD

**Issue by Tybot204** [konvajs/react-konva#423]
React Konva: `16.10.1-0`
React: `16.10.2`

When using hooks inside nested Konva components, the hooks appear to lose the correct scope or context.

For a specific example, I am using some hooks from [Material UI](https://material-ui.com).
```js
const MyComponent = () => {
  const theme = useTheme();

  // Prints the correct theme object I have configured in my app
  console.log(theme);

  return (
    <Stage>
      <Layer>
        <NestedComponent />
      </Layer>
    </Stage>
  );
};

const NestedComponent = () => {
  const theme = useTheme();

  // Prints the default theme, ignoring the config I have in the rest of the app
  console.log(theme)

  return <Text text="My Text" x={0} y={0} />;
};
```

This is not exclusive to Material UI hooks. I run into a similar error when using other libraries. It may be related to [this issue](https://github.com/konvajs/react-konva/issues/317).

**Comment by lavrton** [comment]
`react-konva` is losing the context information from the tree above. At the current moment, I don't know any ways to automatically pass contexts into nested components. You have to "bridge" them manually.

For more info and a demo see here: https://github.com/konvajs/react-konva/issues/188
