### ISSUE TITLE
onMouseOver() event triggered multiple times

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#426]
I add the mouseover handler to Stage, but found the handler called multiple times even when the mouse pointer is only moving inside the canvas. It's not like the example: https://konvajs.org/docs/events/Image_Events.html . Any clue?

```js
onMouseOver(e) {
    if (e.target.attrs.x === undefined) {
      return;
    }

    let p = this.getPointFromEvent(e);
    console.log(p.x);
    // alert(p.x);

    if (p.x < 0 || p.x > gridX - 1 || p.y < 0 || p.y > gridY - 1) {
      return;
    }

    this.setState({
      hoverPiece: {x: p.x, y: p.y}
    });
  }

render() {
    return (
      <div>
        <Col span={8}>
          <Stage width={500} height={300} onClick={this.onClick.bind(this)} onMouseOver={this.onMouseOver.bind(this)} onMouseOut={this.onMouseOut.bind(this)}>
            <Layer>
              {
                this.renderGrid()
              }
              {/*<Text text="Some text on canvas" fontSize={15} />*/}
              {/*<Rect*/}
              {/*  x={20}*/}
              {/*  y={50}*/}
              {/*  width={100}*/}
              {/*  height={100}*/}
              {/*  stroke={"black"}*/}
              {/*  strokeWidth={4}*/}
              {/*  // fill="red"*/}
              {/*  // shadowBlur={10}*/}
              {/*/>*/}

              {
                this.renderPieces()
              }
              {/*<LionImage />*/}

              <Line
                points={this.getPoints()}
                stroke="black"
                strokeWidth={10}
              />
              {
                this.renderHighlight()
              }
            </Layer>
          </Stage>
        </Col>
      
      </div>

    );
  }
```

**Comment by lavrton** [comment]
`mouseover` in Konva works very similar to DOM events. It fires every time the pointer is over any child.

**Comment by hsluoyz** [comment]
Hi @lavrton , even if I only add the event handler to a circle (which has no child), the events are triggered multiple times when inside the circle:

```js
  renderPieces() {
    let res = [];

    for (let x = 0; x < gridX; x ++) {
      for (let y = 0; y < gridY; y ++) {
        const piece = this.state.pieces[x][y];
        if (piece.type === 'start') {
          // add handler here
          res.push(<Circle x={x * 50 + 25} y={y * 50 + 25} radius={25} fill="green" onMouseOver={this.onMouseOver.bind(this)} onMouseOut={this.onMouseOut.bind(this)} />)
        } else if (piece.type === 'end') {
          res.push(<Circle x={x * 50 + 25} y={y * 50 + 25} radius={25} fill="blue" />)
        } else if (piece.type === 'wall') {
          if (piece.visited) {
            res.push(<Rect key={100 + x * gridY + y} x={x * 50} y={y * 50} width={50} height={50} fill="yellow" stroke={"black"} strokeWidth={1} />)
          } else {
            res.push(<Rect key={100 + x * gridY + y} x={x * 50} y={y * 50} width={50} height={50} fill="red" stroke={"black"} strokeWidth={1} />)
          }
        }
      }
    }

    return res;
  }
```

**Comment by lavrton** [comment]
Can you make a demo?

I tried this one: https://jsbin.com/kosijepena/edit?js,console,output
I see only one trigger.

**Comment by hsluoyz** [comment]
```js
  renderHighlight() {
    if (this.state.hoverPiece.x !== -1) {
      let x = this.state.hoverPiece.x;
      let y = this.state.hoverPiece.y;
      return <Rect key={100 + x * gridY + y} x={x * 50} y={y * 50} width={50} height={50} fill="gray" opacity={0.5} stroke={"black"} strokeWidth={1} />
    } else {
      return null
    }
  }
```

I know why it's not working. What I want to do is to highlight the shape. So I put a half-transparent gray box on top of the shape being highlighted (green circle). But then circle lost mouse, so mouseout. Then mouseover again, causing the flipping.

![image](https://user-images.githubusercontent.com/3787410/69589998-001fa980-1029-11ea-9e39-8d61174ada12.png)


![image](https://user-images.githubusercontent.com/3787410/69589992-fa29c880-1028-11ea-8076-301819d40c83.png)

So what's the recommended way to implement a mouse-hover highlight for a shape? I know I can change the image or color manually. But it requires lots of work. I want the color to be automatically "deeper" a bit, just like the GitHub buttons in this page:

![image](https://user-images.githubusercontent.com/3787410/69590232-c56a4100-1029-11ea-8b03-ddd8c39a9145.png)

Can you help me?

**Comment by lavrton** [comment]
You can set `listening={false}` to background rectangle. So it doesn't affect hit regions and events.

**Comment by sajanthomas01** [comment]
Hi Guys, can you help me with this [https://codesandbox.io/s/bold-ellis-4dmnt?file=/src/App.js](https://codesandbox.io/s/bold-ellis-4dmnt?file=/src/App.js). in the example what I'm trying to achieve is show a tooltip when I hover over a shape, these shapes are generated from data I receive and the tooltip needs to be shown on top of the shape when I hover.I'm using the OnMOuseOver event on shapes, but even when I hover over the same shape onMouseOver is getting invoked continuously, can you help me out with how to disable the continuous on mouseover triggers when I hover over the same shape.

**Comment by lavrton** [comment]
This is how `mouseover` event works. I think you want `mouseenter` instead.
