### ISSUE TITLE
Group toDataUrl brings back nothing

### ISSUE THREAD

**Issue by developdeez** [konvajs/react-konva#427]
Im not sure why this happens but when I use it in my app for the first time after clearing cache it brings back nothing.

Anything I can do?
```
  const dataURL = await this.groupRef.toDataURL({
          mimeType: "image/jpeg",
          x,
          y,
          width: scaledImgWidth,
          height: scaledImgHeight,
          quality: 1,
          pixelRatio: this.pixelRatio
        });

        if (!dataURL) {
          this.props.ErrorHandler.catchErrors({
            error: "ERROR: dataObjURL empty:",
            dataURL,
            group: this.groupRef
          });
        }

        const blobData = await this.dataURItoBlob(dataURL);
        const file = {
          filename: this.props.imageObject.name,
          filetype: "image/jpeg",
          filebody: blobData
        };
//FILE EMPTY HERE
        await this.handleUpload(file);
```

Compoent:
```
    <Group
                  rotation={this.state.rotation}
                  x={x_pos}
                  y={y_pos}
                  draggable
                  scaleX={this.state.scale}
                  scaleY={this.state.scale}
                  ref={node => {
                    this.groupRef = node;
                  }}
 ....

```

**Comment by lavrton** [comment]
What do you mean by "brings back nothing"? Do you have empty `dataURL`? What nodes do you have inside the group?

**Comment by developdeez** [comment]
Actually I think it may be the dataURItoBlob

I caught the empty file object after seeing this alert (would this cause that?):


ReactKonva: You have a Konva node with draggable = true and position defined but no onDragMove or onDragEnd events are handled. Position of a node will be changed during drag&drop, so you should update state of the react app as well. Consider to add onDragMove or onDragEnd events. For more info see: https://github.com/konvajs/react-konva/issues/256
--
logger | console
extra | {"arguments":["ReactKonva: You have a Konva node with draggable = true and position defined but no onDragMove or onDragEnd events are handled.\nPosition of a node will be changed during drag&drop, so you should update state of the react app as well.\nConsider to add onDragMove or onDragEnd events.\nFor more info see: https://github.com/konvajs/react-konva/issues/256\n"]}

**Comment by developdeez** [comment]
It's weird because it only happens when access the page after clearing cache and opening a new window.

**Comment by lavrton** [comment]
That warning is not related here. Just check what do you have in `dataURL`. If it is a correct image (you can copy it and open in a new tab) then the error is somewhere else.

**Comment by developdeez** [comment]
Is there anything that can be done to prevent the dataURL from group ref wont come back empty or tainted?
Could it be how I'm processing the URL that makes the body come back empty?
Here's how Im doing it:
```
  dataURItoBlob = dataURI => {
    var binary = atob(dataURI.split(",")[1]);
    var array = [];
    for (var i = 0; i < binary.length; i++) {
      array.push(binary.charCodeAt(i));
    }
    return new Blob([new Uint8Array(array)], { type: "image/jpeg" });
  };
```

Wish I could find more details but this "empty" file body issue happens so randomly. But it's keeping users from uploading images so I may have to change the package worst case.

**Comment by lavrton** [comment]
I think before debugging the file, you should debug the `dataURI`. Make it has what you need.

You may have tainted issues of you have images inside the group from a different domain.
