### ISSUE TITLE
Center a text horizontally in React

### ISSUE THREAD

**Issue by Esporia** [konvajs/react-konva#428]
Hello, 
I wonder how to center a Text with Konva in React .

`              <Text
                        text="Test"
                        x={20}
                        y={100}
                        fontSize={15}
                        align='center'
                        verticalAlign="middle"
                        // horizontalAlign="middle"
                    />`

**Comment by lavrton** [comment]
The text will be centered only in specified `width` (or `height` for `verticalAlign`).

`<Text text="Test" x={20} y={100} fontSize={15} align='center'  width={300} />`
