### ISSUE TITLE
Support droppable or how to use Konva together with React DnD/react-beautiful-dnd ?

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#429]
Konva provides some sort of dragging & drop (DnD) support. But's it's not that powerful compared to more professional DnD libraries like [React DnD](https://react-dnd.github.io/react-dnd/)/[react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd).

For example, I want to drag the right-side yellow boxes (draggable) into the green boxes (droppable) in the tree. But Konva has no concept about droppable. So I have to write a lot of code to handle the collision detection, image update, dropping animation, etc.

![image](https://user-images.githubusercontent.com/3787410/71264393-fc104e80-237e-11ea-8e45-79dd5ed093b1.png)

Why I can't use React DnD/react-beautiful-dnd directly to fulfill my need is because the binary tree (in the picture) is hard to draw without Konva.

1. Can we support droppable as well as draggable in Konva?
2. If 1. is impossible, how to use react-konva with React DnD/react-beautiful-dnd? I tried to put react-beautiful-dnd's Droppable component into Konva's Stage, it reports error: 
`
Could not find "store" in the context of "Connect(Droppable)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Droppable) in connect options.
`

3. If 2. is also impossible, how to use React DnD/react-beautiful-dnd as another layer on top of Konva's canvas? So Konva is just used as a static background?

4. Any other ways?

An example for DnD: https://react-beautiful-dnd.netlify.com/?path=/story/board--simple

**Comment by lavrton** [comment]
1. Very related demo: https://konvajs.org/docs/drag_and_drop/Drop_Events.html

2. I am not sure any DnD react library will work. I don't know how they are implemented. But I guess they rely on DOM and its events. Konva nodes are not DOM nodes. So I don't think such libs will work with `react-konva`. 

3. Sorry, I don't get this point.

**Comment by hsluoyz** [comment]
Finally, I went with 1 (self-drawing). Thanks!
