### ISSUE TITLE
Typescript/Webpack issues 

### ISSUE THREAD

**Issue by svew** [konvajs/react-konva#431]
I'm trying to set up a system using React, Typescript, and React-Konva. I've followed [this](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html) tutorial to a tee to set up my project, then tried to add in the code from [this](https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/basic_demo?from-embed) react-konva sample code. When I try to run my webpack command, I get this error from react-konva.

> D:\Development\Examples\typescript-react-konva>npx webpack
> Hash: b88b940494bcecb1b240
> Version: webpack 4.41.5
> Time: 6745ms
> Built at: 12/28/2019 12:58:23 PM
>  2 assets
> Entrypoint main = main.js main.js.map       
> [1] ./src/index.tsx 2.29 KiB {0} [built]    
> [2] external "React" 42 bytes {0} [built]   
> [3] external "ReactDOM" 42 bytes {0} [built]
>     + 2 hidden modules
> 
> ERROR in ./node_modules/react-konva/lib/ReactKonva.js
> Module not found: Error: Can't resolve './ReactKonvaCore' in 'D:\Development\Examples\typescript-react-konva\node_modules\react-konva\lib'
>  @ ./node_modules/react-konva/lib/ReactKonva.js 12:21-48
>  @ ./src/index.tsx
> 
> ERROR in ./node_modules/konva/lib/index.js
> Module not found: Error: Can't resolve './_FullInternals' in 'D:\Development\Examples\typescript-react-konva\node_modules\konva\lib'
>  @ ./node_modules/konva/lib/index.js 1:12-39
>  @ ./src/index.tsx

**Comment by lavrton** [comment]
Check files in `node_modules/konva/lib`. If they are there, it means something wrong with your setup and not `react-konva`.

**Comment by lavrton** [comment]
Closing as not enough info.
