### ISSUE TITLE
Is there any simple and straightforward way to update an image?

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#432]
I have read:

https://konvajs.org/docs/react/Images.html
https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/images?from-embed
https://stackoverflow.com/questions/49736475/react-konva-how-to-change-image-after-uploading

But the solutions are never beautiful. Can we just provide a component like the following `MyImage` and hide all details, and its image will auto update with `src`?

`this.state.url` is an Internet URL, so no local image loading.

```js
render() {
    return (
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <MyImage src={this.state.url} x={150} />
        </Layer>
      </Stage>
    );
  }
```

**Comment by lavrton** [comment]
```javascript
// the first very simple and recommended way:
const MyImage = ({ url, ...props}) => {
  const [image] = useImage(url);
  return <Image image={image} {...props} />;
};
```

**Comment by hsluoyz** [comment]
Thanks! It works!
