### ISSUE TITLE
How to set a `onClick()` handler when no shape is clicked on?

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#433]
When a user clicks on empty space inside layer/stage (no shape is clicked), I want to do something. How to do it? Thanks.

I tried to add a handler to stage, but when I click on a shape, two events are received: stage's onClick() and shape's onClick(). What I want is:

1. Click a shape --> shape's onClick()
2. Click on empty space --> stage's onClick()

**Comment by lavrton** [comment]
You can use `event.target` to detect the clicked object. If you click on empty space `event.target` will be equal to stage. So when you listen to stage click you can do this:

```
onClick={(e) => {
   const emptySpace = e.target === e.target.getStage();
   if (!emptySpace) {
     return;
   }
   // do you work
}}
