### ISSUE TITLE
How to implement a background rect for text?

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#434]
I want to draw something like this:

![image](https://user-images.githubusercontent.com/3787410/71870633-a6df8580-3151-11ea-9afe-62a306e66c37.png)

The hard part is that when the text is long, the background rect should also have larger width. How to do it with react-konva? Thanks.

**Comment by lavrton** [comment]
Two ways:

1. Use https://konvajs.org/docs/shapes/Label.html. It will adopt Tag size automatically.

2. use React's `ref` to access text node directly and read its size. Something like this:

```js
const Shape = () => {
   const [width, setWidth] = React.useState(0);
   const textRef = React.useRef();
   React.useEffect(() => {
      if (width !== textRef.currect.width()) {
        setWidth(textRef.currect.width());
      }
   });
   return <Group><Text ref={textRef} /> <Rect width={width} /></Group>
}
```

**Comment by isopterix** [comment]
I think a more performant way would be this:

```js
const Shape = () => {
   const rectRef = React.useRef();
   const textRef = React.useRef();
   React.useEffect(() => {
      rectRef.current.width(textRef.current.width());
      rectRef.current.getLayer().batchDraw();
   });
   return <Group><Text ref={textRef} /> <Rect ref={rectRef} width={width} /></Group>
}
```
