### ISSUE TITLE
Support React 16.12.0

### ISSUE THREAD

**Issue by ArgonAlex** [konvajs/react-konva#435]
Are there plans to support the latest versions of React?

**Comment by telmo08** [comment]
I'm using react 16.12.0, didn't have any issue yet.

**Comment by lavrton** [comment]
I tried to use the last version. It was working ok for me. But anyway, I updated all internal dependencies and published `react-konva@16.12.0-0`.

**Comment by ArgonAlex** [comment]
Thanks! The main issue I had was that duplicate copies of the `scheduler` package were being included in our bundles because of the incompatible ranges. We use duplicate-package-checker-webpack-plugin to detect this.

**Comment by lavrton** [comment]
Yeah, that is a valid case. Is it ok now?

**Comment by ArgonAlex** [comment]
Yup it's ok now.
