### ISSUE TITLE
Issue with shadow feature

### ISSUE THREAD

**Issue by srijakumar** [konvajs/react-konva#436]
Hi!

I am trying to add shadows to an image that wont disappear after the image has been dragged to a new location or transformed to a new size. However, I am encountering issues.

1.  I have tried to create  example here -- https://codepen.io/Srij/pen/mdybZyz?editors=0010

With this code, I would expect all the images to have the shadow property before and after the transformation. However, only one image has the shadow property and the rest dont have the shadow

2. The second example below loses the shadow once the image is moved 
  render(){
    const { image, size, x, y } = this.state
    const { isSelected, onSelect } = this.props

    return(
      <React.Fragment>
        <Image
          x = {x}
          y = {y}
          scaleX = {size}
          scaleY = {size}
          image = {image}
          draggable = {true}
          shadowColor ='black'
          shadowBlur={10}
          shadowOpacity={0.9}
          onClick = {onSelect}
          ref={(ref) => this.imageRef = ref}
        />
        {isSelected && (
          <Transformer
            ref={(ref) => this.trRef = ref}
            anchorCornerRadius={5}
            borderEnabled={false}
          />
        )}
      </React.Fragment>
    )
  }

Thank you!

**Comment by lavrton** [comment]
As I can see it is a Chrome bug. Firefox and Safari work ok for me.

Until the bug is fixed, as a workaround you can just set transparent stroke: `stroke: 'rgba(0,0,0,0)'`

**Comment by LaureanoBlonsky** [comment]
Hi, I having the same issue, how can we enforce it to work nice in every browser? It affects desktop Chrome and Mobile Chrome.

The shadow also disappear if you refresh the page with F5. With Ctrl+F5 works great, so it seems to be a cache issue. 

I tested a lot of things without luck. the clearCache method doesnt seems to work.

Any ideas??

**Comment by lavrton** [comment]
That looks like a weird browser behavior. I am not sure we should do anything here from `Konva` or `react-konva` side.
