### ISSUE TITLE
FillText not found

### ISSUE THREAD

**Issue by Pedroxam** [konvajs/react-konva#438]
Hi,
I don't find any method to add text, (fillText) ...

Eg:

       var c = document.getElementById("graph");

        var ctx = c.getContext("2d");

        ctx.fillText("TEXT",65,55); // THIS

**Comment by lavrton** [comment]
```js
import { Stage, Layer, Text } from 'react-konva';


const Canvas = () => {
   return (
    <Stage width={100} height={100}>
      <Layer>
        <Text text="hello" />
      </Layer>
    </Stage>
  );
}
```

**Comment by Pedroxam** [comment]
@lavrton, vey thanks
