### ISSUE TITLE
Draw svg on canvas - SVG comes as simple string

### ISSUE THREAD

**Issue by Belisarith** [konvajs/react-konva#441]
I've got the following problem:
I store svg-Elements as string in a database and I want to use them in react-konva. I've read the following documentation for the konvajs core library: 
[Draw svg in konva](https://konvajs.org/docs/sandbox/SVG_On_Canvas.html)
However, I do not get how to replicate this in the react environment. The thing is also complicated due to the fact, that I am getting the svg directly as a string and not from a url. 
Therefore, in essence I have something like this information, although it is pulled from the database and the shapes may be much more complicated:
`const svgPath = '<path fill=\"none\" stroke=\"red\" stroke-width=\"4\" d=\"M0 0 L10 10"></Path>'`

As a  follow up question, if i suceed in drawing this svg somehow with the proposed workarround of putting it in an image and drawing this image to the canvas, can I still update attributes like stroke color or is this ability then lost?

**Comment by lavrton** [comment]
As in the demo, you can use `canvg` to convert SVG string into the canvas element and use it for `Image` component.
You can manipulate that SVG string directly to change styles.  Then just update the canvas with `canvg` again.

You may also try convert svg string into base64 url and use it as image source.
```javascript
const url = 'data:image/svg+xml;base64,' + window.btoa(svgString);
```

**Comment by MayankMaurya7** [comment]
I want to draw an icon using fontAwsome library inside a layer , how can I do that?
