### ISSUE TITLE
How to add an iframe as the background of a Konva canvas?

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#442]
I'm working on a website monitoring tool. Konva is used to show the visualization of the user behaviors (like mouse movement) on a website. So I need to use the website (in iframe) as the background and draw mouse pointers, traces with Konva shapes.

My question is: How to add an iframe as the background of a Konva canvas?

**Comment by lavrton** [comment]
1. Create an `iframe`
2. Create `<Stage />` on top of the `iframe` with an absolute position by CSS.
