### ISSUE TITLE
Performance: Slow Rerenders, if Image has Filters

### ISSUE THREAD

**Issue by johannwagner** [konvajs/react-konva#444]
Hey,

first of all: Thanks for your amazing work.

I am currently try to apply filters to a user uploaded image, which I handle as HTMLImageElement internally.

If I try to apply filter to an image, I ran into some performance problems. My draw needs almost 3s and it seems, that the Stage size is not relevant. Also, if I remove image filters, everything works fine.

I also appended a screenshot and the profiler files.

![Screenshot from 2020-02-18 19-04-43](https://user-images.githubusercontent.com/12380026/74764432-fb623e80-5281-11ea-8491-5c608e980e2c.png)

[filtercache.txt](https://github.com/konvajs/react-konva/files/4220883/filtercache.txt)

This is one of the elements, which I am using. Other ones are quite similar. KImage is Image from Konva.

```tsx
import { Brighten } from 'konva/lib/filters/Brighten';
import { HSL } from 'konva/lib/filters/HSL';
import { Contrast } from 'konva/lib/filters/Contrast';

const imageFilters = [
    Brighten,
    Contrast,
    HSL,
];
```
```jsx
<Stage
    ref={stageRef}
    className={className}
    width={containerDimensions.width}
    height={containerDimensions.height}
    x={containerDimensions.width * 0.5}
    y={containerDimensions.height * 0.5}
    offsetX={containerDimensions.width * 0.5}
    offsetY={containerDimensions.height * 0.5}
    opacity={0.2}
    scaleX={containerScale}
    scaleY={containerScale}
    rotation={transform.angle}
>
    <FastLayer>
        <KImage
            ref={ref => {
                ref?.cache();
                ref?.getLayer()?.batchDraw();
            }}
            x={backgroundImg.width * transform.scale / 2 - (backgroundImg.width * transform.scale - containerDimensions.width) / 2 + transform.x}
            y={backgroundImg.height * transform.scale / 2 - (backgroundImg.height * transform.scale - containerDimensions.height) / 2 + transform.y}
            offsetX={backgroundImg.width / 2 }
            offsetY={backgroundImg.height / 2 }
            scaleX={transform.scale}
            scaleY={transform.scale}
            image={backgroundImg}
            filters={imageFilters}
            brightness={getBrightnessFromPercentage(effects.brightness)}
            contrast={getContrastFromPercentage(effects.contrast)}
            saturation={getSaturationFromPercentage(effects.saturation)}
        />
    </FastLayer>
</Stage>
```

Can you give me a hint what to try next? 

Best, 
   Johann

**Comment by lavrton** [comment]
1. check the size of the image. The caching of large images is slow. You may try to use `node.cache({pixelRatio: 0.5})` to reduce the size and quality of the cached image.
2. Do not do this:
```javascript
ref={ref => {
  ref?.cache();
  ref?.getLayer()?.batchDraw();
}}
```

`ref` is called on every render of the component. It means you will recache the image every render.
Probably you need to cache the image ONLY when any properties of the images are changed.

**Comment by johannwagner** [comment]
Thanks in Advance, I will try this and close the issue, if this fixes my concerns.
Is there a way to apply filters without caching?

**Comment by lavrton** [comment]
No. That is the main point. Applying filters is a very expensive action. So a node must be cached to render it once, and then draw fast with cached version.

**Comment by johannwagner** [comment]
Okay, than my use case may be an edge case. Almost every redraw is a change of a filter value.

Do I need to recache images after moving on the Layer/Stage?

**Comment by lavrton** [comment]
@johannwagner You don't need to recache node if you move them into another container.

**Comment by lavrton** [comment]
Also in some cases you may try to use CSS filters (the usually faster). Take a look here for a related demo: https://lavrton.com/case-study-image-labeling-for-machine-learning/

**Comment by johannwagner** [comment]
Ah, maybe I asked the wrong question:

My Image has quite a lot of properties, as mentioned above. Do I have to recache the issue on the change of any property or just on specific ones?

**Comment by lavrton** [comment]
You don't need to recache if you change:
1. transform (such as position, rotation or scale)
2. or filter properties (such as `brightness`).

You will have to recache on other changes that affect the image itself (like stroke, or shadow).

**Comment by johannwagner** [comment]
Thanks a lot for your help!
