### ISSUE TITLE
Konva is hijacking React context and not allowing other context providers

### ISSUE THREAD

**Issue by chrisjpatty** [konvajs/react-konva#446]
When using Context in React, Konva apparently hijacks the context tree in a way that prevents an providers wrapping the stage from ever updating from their default values. In this [Code Sandbox example](https://codesandbox.io/s/konva-context-bug-9jusp) you can see that according to the rules of context, the rectangle should render as red, even though the default value of the context is blue. Because the default is never overwritten, the rectangle renders as blue, even though a value of "red" is being passed to the context provider.

**Comment by ejarzo** [comment]
You will likely need to 'bridge' the context through the Konva Stage - more discussion and example here: https://github.com/konvajs/react-konva/issues/188#issuecomment-478302062

**Comment by chrisjpatty** [comment]
That makes sense thanks. can I suggest that this be documented? Konva doesn't throw any warnings when it overrides the normal context functionality, and it may make for some frustrating debugging situations. I'd be happy to put in a pull request for that.

**Comment by lavrton** [comment]
Sure. It will be very good to have documentation in the README.

**Comment by Cosmet** [comment]
I'm getting the same issue with Redux Providers. Have to place a provider as a child of stage for its children to have have access.

**Comment by ejarzo** [comment]
I have create a PR for adding info to the README: https://github.com/konvajs/react-konva/pull/450 - let me know if I missed anything

**Comment by lavrton** [comment]
Update on this issue. From `react-konva@18.2.2`, context bridge should work by default. It will be really cool if someone can try it and provide feedback.
