### ISSUE TITLE
FPS is too low

### ISSUE THREAD

**Issue by Stupidism** [konvajs/react-konva#447]
I got this performance issue [why-i-get-30-fps-in-chrome-dev-tool-performance-panel-but-js-and-react-both-say](https://stackoverflow.com/questions/60467411/why-i-get-30-fps-in-chrome-dev-tool-performance-panel-but-js-and-react-both-say).

I guess it's caused by `react-konva`. Can you guys help me take a look?

Maybe it's not a good choice to use `react-konva` to develop games at all.

**Comment by Stupidism** [comment]
I located the problem, it's caused by the [batchDraw](https://github.com/konvajs/react-konva/blob/9b3b2f4ecb446fe21f6370c4d33be854b5bd1d74/src/makeUpdates.js#L109):

After change this line, I can get 60fps movement now.
```
-  drawingNode && drawingNode.batchDraw();
+  drawingNode && drawingNode.draw();
```

**Comment by lavrton** [comment]
That may work. But be very careful when you have many components on the canvas.

`drawingNode.draw()` will redraw everything on canvas from scratch. If you have many components, it will redraw many times.

**Comment by Stupidism** [comment]
@lavrton Yes, you're right! High-frequency `draw()`s are definitely not what I want.
So I wrote a better `batchDraw` to fix this problem with tests.
