### ISSUE TITLE
Is there an advanced painter/sketch tool based on React-Konva like this one?

### ISSUE THREAD

**Issue by hsluoyz** [konvajs/react-konva#449]
I want a painter/sketch tool with toolbox like pen, rectangle, circle, can change color, background, add image, etc. We can also select a rectangle and resize or move or spin it. Like this one: http://tbolis.github.io/showcase/react-sketch/ or this: http://fabricjs.com/freedrawing

![image](https://user-images.githubusercontent.com/3787410/76136308-07644380-606b-11ea-95bf-11a4d6e40a22.png)

I know Konva has a free-drawing demo here: https://konvajs.org/docs/sandbox/Free_Drawing.html But it's too simple. It has only a brush tool. And it seems not compatible with React very well.

Can we have such a tool? Thanks.

**Comment by lavrton** [comment]
I don't know any. If you need one - you have to create it. I think Konva has all the required tools for that.

**Comment by hsluoyz** [comment]
Thanks!
