### ISSUE TITLE
hitStrokeWidth not working

### ISSUE THREAD

**Issue by maurobender** [konvajs/react-konva#451]
I'm trying to use `hitStrokeWidth` property to increase the hover surface for a thin shape with `react-konva` but even though I'm setting the property to a value of `20` like the example [here](https://konvajs.org/docs/events/Custom_Hit_Region.html) but it doesn't seem to work.

The code:

```js
const App = () => {
	const layerRef = useRef(null);
	const [opacity, setOpacity] = useState(0.5);

	const toggleLayerHitCanvas = useCallback(
		() => {
			if (!layerRef || !layerRef.current) { return; }
			layerRef.current.toggleHitCanvas();
		},
		[]
	);

	return (
		<div className="App" style={{ width: 1000, height: 600 }}>
			<button onClick={toggleLayerHitCanvas}>Toggle</button>
			<Stage
				style={{ backgroundColor: 'blue' }}
				width={1000}
				height={600}
			>
				<Layer ref={layerRef}>
					<Line
						points={[100, 200, 300, 400]}
						opacity={opacity}
						stroke={'red'}
						strokeWidth={4}
						hitStrokeWidth={20}
						strokeHitEnabled
						onMouseOver={() => setOpacity(1)}
						onMouseLeave={() => setOpacity(0.5)}
					/>
				</Layer>
			</Stage>
		</div>
	);
}
```
Drawed figure:
<img width="1002" alt="Captura de Pantalla 2020-03-23 a la(s) 19 22 50" src="https://user-images.githubusercontent.com/450467/77349730-be371380-6d3b-11ea-95ba-887e1da3a53f.png">

Hit canvas:
<img width="997" alt="Captura de Pantalla 2020-03-23 a la(s) 19 22 59" src="https://user-images.githubusercontent.com/450467/77349742-c55e2180-6d3b-11ea-8a84-a59e976744cd.png">

As you can see in the example the hitCanvas shows the same stroke as the normal canvas.

I'm using:
- react: v16.13.1
- react-konva: v16.12.0
- konva: v4.2.0

**Comment by lavrton** [comment]
That is an unexpected behavior of `strokeHitEnabled`. Just remove that property and it will work.

I am going to deprecate that property.
