### ISSUE TITLE
How to use React Konva for making a heading element drag and drop.

### ISSUE THREAD

**Issue by cmcodes1** [konvajs/react-konva#452]
Hey there!
Lately I had been searching a lot for a library which provides drag-and-drop facility with ease. Out of all the searches, I found yours to be the most easy and simple to implement, but it works with graphic elements only (not text). I tried using <Text /> component but got an error and a warning which are as follows:

```
Error
The above error occurred in the <Stage> component: in Stage (created by ForwardRef) in Txt (created by MemeGenerator) in div (created by MemeGenerator) in div (created by MemeGenerator) in MemeGenerator (created by App) in div (created by App) in App Consider adding an error boundary to your tree to customize error handling behavior.

Warning
Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. in MemeGenerator (created by App) in div (created by App) in App.
```

Please suggest a way (code demo) so that I can integrate it with my existing heading element to make it dnd. Thanks!

**Comment by lavrton** [comment]
What elements do you want to drag&drop? DOM elements? Canvas elements of Konva?

**Comment by cmcodes1** [comment]
DOM Element (Heading Element).
I was looking for a way to use React Konva to dnd a heading element.
Can you please share the code for the same, if possible.

**Comment by lavrton** [comment]
I don't think `react-konva` will help there. It is not designed for drag&drop of every component. Just for canvas drawings.

I think you have to use another library for that. Actually there are many draw&drop components for react.
