### ISSUE TITLE
Bump peerDependencies for react 16.13.x

### ISSUE THREAD

**Issue by 0xdevalias** [konvajs/react-konva#453]
React is up to `v16.3.1`, but this libraries `peerDependencies` pin to `16.12.x`

- https://github.com/facebook/react/releases/tag/v16.13.1
- https://github.com/konvajs/react-konva/blob/master/package.json#L24-L25

**Comment by lavrton** [comment]
updated

**Comment by 0xdevalias** [comment]
Thankyou :)

I’m curious, is there a need to pin it like this, as opposed to say just the 16.x? Would reduce the friction/need to update it between smaller React releases.

**Comment by lavrton** [comment]
For now, I want to keep strict rules, because previously we had a lot of versions mismatch errors.

**Comment by 0xdevalias** [comment]
That makes sense :)
