### ISSUE TITLE
Bump peerDependencies for konva 4.2.2

### ISSUE THREAD

**Issue by 0xdevalias** [konvajs/react-konva#454]
Konva is up to `4.2.2` but this libraries `peerDependencies` pin to `^3.2.5 || ^4.0.3`

- https://github.com/konvajs/konva/blob/master/CHANGELOG.md#422---2020-03-26
- https://github.com/konvajs/react-konva/blob/master/package.json#L23

**Comment by lavrton** [comment]
`4.2.2` is in range of `^3.2.5 || ^4.0.3`
