### ISSUE TITLE
Reduce bundle size: react-reconciler / scheduler

### ISSUE THREAD

**Issue by 0xdevalias** [konvajs/react-konva#455]
Currently there is a hard dependency on `react-reconciler`:

- https://github.com/konvajs/react-konva/blob/master/package.json#L20

According to bundlephobia, this is contributing `76.6%` of `react-konva`'s bundle size:

- https://bundlephobia.com/result?p=react-konva@16.13.0-0

Less of an issue, but similarly, the `scheduler` dependency is adding `5.1%` to the size.

It would be nice if we could avoid this somehow.

As it currently is, I expect these extra imports add more bundle size than following these recommendations will save:

- https://github.com/konvajs/react-konva#minimal-bundle

**Comment by lavrton** [comment]
I don't think there is a way to avoid `react-reconciler`. That is the core part of the library.  `scheduler` is used in `react-dom`. So it doesn't matter if we remove it.
