### ISSUE TITLE
React Concurrent mode

### ISSUE THREAD

**Issue by Domino987** [konvajs/react-konva#456]
Hello, 
Great library, thank you for that.
I was testing it with the soon to be released react concurrent mode (still experimental) and it does not work for konva currently.

The following error is thrown:
`Cannot read property 'alternate' of undefined`

[Sandbox](https://codesandbox.io/s/great-jones-e6xdd?file=/src/index.js)

Is there a way to get it to work?

**Comment by lavrton** [comment]
No idea. I will take a look into it only when it will be released.

**Comment by aleksandr-leontev** [comment]
@Domino987 I had the same issue.
The problem for me was that I had React V 16 and used React-Konva V17
So I advise you to check to React, ReactDom, and React Konva Versions. It should be the same at lest in major part of version

CC @lavrton 
PS: @lavrton thanks for this wrapper for konva.

**Comment by lavrton** [comment]
I am closing the issue. The last `react-konva@17.0.2-0` version works ok for me for `react@16`,  `react@17` and `react@experimantal`.
