### ISSUE TITLE
Apply one transform for multiple shapes demo

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#458]
I'm using react konva for creating multiple rectangle shapes and passing it to transformer but my issue is, how can I apply only one transform for multiple shapes...

**Comment by lavrton** [comment]
Almost the same way as you attach one shape. Just attach many of them (use `konva@5.x.x`).

What did you try?

**Comment by mdmusaib** [comment]
Thanks for helping 😊
