### ISSUE TITLE
React Konva shape referencing another shape.

### ISSUE THREAD

**Issue by nommuna** [konvajs/react-konva#459]
Hello, I am working with React-Konva in my app and I am experiencing a weird issue where if I am drawing multiple custom shapes. The shape will reference the first shape that is drawn. 
For example: 
 - Draw an array of 2 shapes and add click listeners to them
 - When I click on the second shape, the information I get back is from the first shape

It's like each shape in the array is just a reference to the first one. Tried messing with cloning the shape but that didn't work. 

Any ideas?

**Comment by lavrton** [comment]
It sounds like a classical javascript closure issue.

Can you make a demo?

**Comment by nommuna** [comment]
Thanks for the insight. You are right. After your comment I went back and saw it was indeed a closure issue. Thanks for the help!
