### ISSUE TITLE
Calculate stage width and height dynamically

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#460]
how can I calculate my stage width and height dynamically, if I resize my windows the stage is not loading completely....

**Comment by lavrton** [comment]
What did you try?

Similar to this demo: https://konvajs.org/docs/sandbox/Responsive_Canvas.html#page-title

You just need to read container size (using `ref`) and set the size according to it.

**Comment by mdmusaib** [comment]
That's working fine, thanks for the quickly response....

**Comment by mdmusaib** [comment]
Thanks for the quickly response
