### ISSUE TITLE
how to apply transform for multiple shapes without using group

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#461]
Hi, I'm generating rectangle dynamically for that how can I transform using transformer, 
In rectangle I have given the ref dynamically and that I assigned to the transform dynamically it is working fine, but I don't konw the calculation of resize of multiple rect....

**Comment by lavrton** [comment]
> I don't konw the calculation of resize of multiple rect.

Why do you mean here?


Basically you just need to use a ref and get all rectangles to transform.

```js
// use layer or stage ref to find all rectangles to transform
const shapes = stageRef.current.find('.rectangle-name').toArray();
transformerRef.current.nodes(shapes);
stageRef.current.draw();
```

**Comment by mdmusaib** [comment]
Hi, what you told is exactly correct, but in my scenario it will not going to work, let me explain u clearly, I'm creating a rectangle dynamically only for the view purpose to show the x,y,endx,endy dot for the selected shapes then for this situation I don't have the ref of rectangle exactly, I have the ref of only the view rectangle......

**Comment by mdmusaib** [comment]
Also I'm using class component here, so how to useRef will work

**Comment by lavrton** [comment]
Sorry, I can't provide calculations on how to apply changes back to original shapes. It is not trivial. You can read the Transformer code to understand it.

Or just apply the transformer directly into shapes, without create new dynamic rectangle.
