### ISSUE TITLE
ZoomIn, ZoomOut shape quality is effecting

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#464]
Hi, I have zoomIn, ZoomOut, normal option in my app, if I do zoomIn , ZoomOut the shape clearity is effecting, particularly if I do zoomIn the shape is getting blur at some point, how to fix this issue.....
Looking for ur help...

**Comment by lavrton** [comment]
What shape? Do you use caching?

**Comment by mdmusaib** [comment]
Normally I have a zoomIn, ZoomOut button I haven't used caching, but scenario if I click that the react stage is zooming but the shape is getting blur after somepoint how to make the shape visible clearly after the zoomIn also....

**Comment by lavrton** [comment]
I need a demo.
How did you implement zoom in/out? With `scaleX` and `scaleY`?

Scaling should NOT blur vector shapes. Images can be blurred.

**Comment by mdmusaib** [comment]
I haven't used scaling, if user clicked on zoomin button means I'm just adding the css property to the react stage...

transform: scale(1.15);
transform-origin: 0% 0%;

if I do like this means the shape rectangle, circle, sqaure getting blur.....

**Comment by lavrton** [comment]
I see. That is why you have a blur. `Konva` can do nothing here. To keep images sharp, don't use CSS to scale the canvas and use `scaleX()` and `scaleY()` methods instead.
