### ISSUE TITLE
How to specify more complex clipFunc?

### ISSUE THREAD

**Issue by Sniffing** [konvajs/react-konva#466]
Say I have a line

```
<Line
  points={[10,50, 70,75, 130,50, 70,25]}
  tension={0.35}
  closed
  stroke="black"
  />
```

and I want to add a clipping function to obscure everything outside
```
<Group
  clipFunc={this.clipFn}>
...
  lineAbove
</Group>
```

```
private clipFn = (ctx: Context) => {
    ctx.beginPath();
    ctx.lineTo(10,50);
    ctx.lineTo(70,75);                           
    // ctx.bezierCurveTo(70,75);
    ctx.lineTo(130,50);
    ctx.lineTo(70,25);
    ctx.moveTo(10, 50);
    ctx.closePath();
  }
```

It would be nice to be able to supply the same kind of <Line> and props to the function or translate the `tension={0.35}` into the necessary points maybe through some helper. Is there an existing way outside of digging into source code and calculating raw control points myself?
For example

```
private clipFn = (ctx: Context) => {
    const points = Utils.calculateLinePoints([10,50, 70,75, 130,50, 70,25], 0.35);
    ctx.beginPath();
    for(let i=0; i<points.length; i++) {
    ctx.bezierCurveTo(points[0],points[1].....);
    }
    ctx.closePath();
  }
```

**Comment by lavrton** [comment]
I never tried it, but with pure `Konva` I was able to do this:

```js
var clipShape = new Konva.Line({
  points: [0, 0, 50, 0, 50, 50, 0, 50],
  tension: 1
})
const layer = new Konva.Layer({
  clipFunc: (ctx) => {
    clipShape.drawScene(ctx.canvas);
  }
});
```

https://jsbin.com/jimoyagoxa/2/edit?html,js,output

I think you can try to do the same with `react-konva`. Just create `clipShape` manually with Konva API (not jsx).

Otherwise, I think you have to dive-in into the code or find your own implementation.

**Comment by Sniffing** [comment]
This is perfect, actually, since I'm also in typescript I solved it with the following, would be great to have the documentation for this added:
```
const line: Konva.Line= new Konva.Line({
    points: [10,50, 70,75, 130,50, 70,25],
    tension: 0.35,
    closed: true,
  })

  private clipFn = (ctx: Context) => {
    line.drawScene(ctx.canvas, undefined, true, undefined);
  }
```

**Comment by lavrton** [comment]
I am not sure we will officially support such behavior. For now, it works. Probably it will work forever.
