### ISSUE TITLE
Konva 5

### ISSUE THREAD

**Issue by Reggino** [konvajs/react-konva#467]
Is konva 5.x officially supported? Installing it shows a warning:

```
warning " > react-konva@16.13.0-0" has incorrect peer dependency "konva@^3.2.5 || ^4.0.3".

```

But the examples seem to work fine?

**Comment by lavrton** [comment]
Yes, we will add it to dependency soon. For now, you can just ignore the warning.

**Comment by lavrton** [comment]
Updated deps.
