### ISSUE TITLE
canvas drwaing becomes slow while I am scaling and increasing height and width of the stage

### ISSUE THREAD

**Issue by umeshdobai** [konvajs/react-konva#468]
this.state{
            stageWidthForZoomIn: Number(window.innerWidth),
            stageHeightForZoomIn: Number(window.innerHeight),
        }
        
        const stage = this.stageRef.getStage();//getting stage ref
        let stageX = stage.scale().x;// getting scale
        let stageY = stage.scale().y;
        if (stageX <= 4 && stageY <= 4) {
          let height = stage.attrs.height;//getting height
          let width = stage.attrs.width;
          height = height + 200;//here I am adding 200px into the stage height every time
          width = width + 200;
          this.setState({
            stageHeightForZoomIn: height,
            stageWidthForZoomIn: width,
          });
          stage.scale({ x: stageX + 0.25, y: stageY + 0.25 });//Here I am scaling stage scale every time 
        }

        <Stage
          className="stageClass"
          ref={ref => {
            this.stageRef = ref;
          }}
          width={this.state.stageWidthForZoomIn}
          height={this.state.stageHeightForZoomIn}
        />

The above code is going to be execute mutiple times(till the stage scale becomes 4)
After scaling and increasing height and width then, canvas drawing is becoming slow(some delaying is there)
when I am scaling stage there is no problem for drawing any shape only i am facing this problem while increasing height and width of the stage.

**Comment by lavrton** [comment]
Try to make a performance audit of the app. What is slow? React? Konva? Canvas drawing?

Try to make a small demo.

**Comment by umeshdobai** [comment]
should I get any performance issue(in canvas) if I increased stage height and width upto some extent.

**Comment by lavrton** [comment]
You may. The bigger is a stage, the slower is drawing. So it is better to keep it as small as possible.

**Comment by umeshdobai** [comment]
ok
