### ISSUE TITLE
line stroke problem

### ISSUE THREAD

**Issue by umeshdobai** [konvajs/react-konva#469]
drawGrid = () => {
    let points = this.state.points;
    let padding = 10;
    let width = window.innerWidth;
    let height = window.innerHeight;

    for (let j = 0; j <= height / padding; j++) {
      points.push([0, Math.round(j * padding), width, Math.round(j * padding)]);
    }

    for (let i = 0; i <= width / padding; i++) {
      points.push([Math.round(i * padding), 0, Math.round(i * padding), height]);
    }

    this.setState({
      points,
    });
  };

  render() {
    console.log('scx');
    return (
      <>
        {this.state.points.map(data => {
          return (
            <Line
              perfectDrawEnabled={false}
              points={data}
              stroke={'#181a1b'}
              strokeWidth={(data[0] !== 0 && data[0] % 90 === 0) || (data[1] !== 0 && data[1] % 90 === 0) ? 0.45 : 0.2}
              strokeScaleEnabled={false}
            />
          );
        })}
      </>
    );
  }

The above code is grid in canvas 
After scaling the stage then some line stroke is changing.
(you can see the below attached file)

![Screenshot (10)](https://user-images.githubusercontent.com/28566994/81797428-698a6a80-952c-11ea-9537-1c92eb7ee94f.png)(this is the before scaling of stage)

![Screenshot (11)](https://user-images.githubusercontent.com/28566994/81797520-8888fc80-952c-11ea-8d18-5410f877bc7f.png)(this is the afterscaling of stage)

**Comment by lavrton** [comment]
Can you make a demo?

That is probably just a browser's behavior of antialiasing.
