### ISSUE TITLE
onMouseDown prevents shapes from being dragged

### ISSUE THREAD

**Issue by iTakeshi** [konvajs/react-konva#471]
### description
When `onMouseDown` prop is set for a shape, the shape cannot be dragged only for the first drag attempt after the page loaded. `onMouseUp` behavior is not executed for this time as well.
Dragging and `onMouseUp` recover their correct behaviors on the second and subsequent drag attempts.

### Reproducibility
[demo](https://codesandbox.io/s/react-konva-dragging-issue-5e303)
Reload the sandbox first, because the buggy behavior is only observed for the first time just after the page loaded/refreshed.
1. Place the mouse cursor on the black rectangle.
2. Press down the left mouse button.
3. Drag the cursor out of the rectangle, while pressing the mouse button.
4. Release the mouse button.

### Expected behavior
After step 2, the rectangle becomes red.
During step 3, the rectangle moves.
After step 4, the rectangle becomes black.

### Actual behavior
After step 2, the rectangle becomes red. [OK]
During step 3, the rectangle stays the original position. [FAIL]
After step 4, the rectangle remains red. [FAIL]

**Comment by lavrton** [comment]
That is an interesting issue.

**Comment by lavrton** [comment]
Fixed with `react-konva@16.13.0-3`. Thanks for the report.

Demo: https://codesandbox.io/s/react-konva-dragging-issue-k1rn3?file=/src/index.js

**Comment by iTakeshi** [comment]
Thanks for the quick fix!
