### ISSUE TITLE
Manipulate an arrow like MS Powerpoint's one

### ISSUE THREAD

**Issue by kosuke-kitahara** [konvajs/react-konva#473]
Hello. I'm struggling to create an arrow like MS PowerPoint's one. 

Requirements below.

- drag a start point while fixing an end point and vice versa
- drag a stroke with sticky start and end points (both two tracking a stroke)

Regarding the first requirement, I can refer to this [sandbox](https://codesandbox.io/s/react-konva-weighted-arrow-wsrbd?file=/src/index.js:530-535), but I have no idea to implement the second. 

Thanks in advance.

**Comment by lavrton** [comment]
I am not sure I understand it. Drag the whole arrow?

**Comment by kosuke-kitahara** [comment]
Thank you for your reply. 

> Drag the whole arrow?
yes. In your [demo](https://codesandbox.io/s/react-konva-weighted-arrow-wsrbd?file=/src/index.js:530-535), an arrow is not clickable. is that correct?

I want to drag it with circles like below.
![Untitled](https://user-images.githubusercontent.com/42398050/82398668-62181380-9a8e-11ea-9751-3682eac6ccd5.gif)

**Comment by lavrton** [comment]
You can make an arrow (or group) draggable. Then update nodes position inside `dragmove` or `dragend` event

**Comment by kosuke-kitahara** [comment]
thanks. I've make a group (two nodes and an arrow) draggable. However, I can't update the positions of two nodes when dragging an arrow. I want to set `x` and `y` axis of two nodes as State.

**Comment by lavrton** [comment]
Just remember that `<Group />` has its own `{x, y}`. So when a group is dragged, its position is changed.

There are many ways to resolve the issue.
For example, you can listen to `dragend` event and in the event, you need to update state positions by moving then with group `{x,y}` values. Then just reset group position back into `{0, 0}` manually (so the difference don't sum up twice).
