### ISSUE TITLE
Webworker support

### ISSUE THREAD

**Issue by rmdort** [konvajs/react-konva#474]
Hi, Is there anyway to add webworker support to react-konva ?

**Comment by lavrton** [comment]
How do you see it? What is your use case?

**Comment by rmdort** [comment]
I want to improve rendering performance of this grid - https://github.com/rmdort/konva-grid . 

My use-case is to have an excel like grid, with streaming data. ie 40-50 cell updates per second. So having a worker thread do the rendering would be useful.

Other workaround is to do update the grid imperatively

````
stage.find('.cell').filter(cell => shouldUpdate ?).draw()
````

**Comment by lavrton** [comment]
I don't see any good way to make it from `react-konva`. So I am going to close the issue for now.

**BTW, your project is really awesome.**

**Comment by rmdort** [comment]
Thank you :)

Yep. Offscreen canvas can be really tricky. And maintaining the state of the nodes across render/commit phases in an async way will not be that straightforward.

**Comment by EdouardLauret** [comment]
Hi there, I'm making a web audio sequencer and I have the same problem for my grid rendering. I can have lot of audio tracks and many audio regions into them ... @rmdort, have you found a workaround to this (other than vanilla canvas+offscreen) ? Rect Konva is very convenient to use but really slow when you have a lot of components to display and lots of reactive changes (for me it is related to my player head and vu meters in some RAF stuffs that change in real time every frame...)

**Comment by rmdort** [comment]
IMO, i doubt web worker rendering is ever going to land in `react-konva`.  

But i dont think `react-konva` is slow. I am using it to create grids, around 1 million rows x 1 million columns. I find it really fast, comparable to native canvas, with marginal difference. 

Some things i have done to improve perf

1. Drawing only what you see on the screen. Hiding components that are not visible
2. Set `listening=false` on component that dont need any user interaction
3. Set `listening=false` when user is scrolling. This is to prevent `layer.drawHit()` from being called
4. Use multiple layers ( i have 2 layers)
5. React memo - This is working really well from me . Only modified shapes are rendered
6. For State management `zustand` is good, giving u component level performance tuning. Each component can subscribe to a slice of state. With `memo` and `zustand`, you can prevent unnecessary child component re-rendering

Some tips are documented here https://konvajs.org/docs/performance/All_Performance_Tips.html

**Comment by lavrton** [comment]
@EdouardLauret first you need to find where the slowness comes from. From React (it is slow in many cases), from Konva rendering?

Using a Webworker is not a magic way to solve the performance. It can make the UI more responsive, but rendering itself may be still slow.

For now, I have no idea how we can synchronize react in the main thread with nodes three in the web worker. As I know, there are some attempts to run full react in the Webwork, but it is too complex.

**Comment by EdouardLauret** [comment]
Sorry, i misspoke, the canvas renderer is blocked on the main thread because of the huge computation in the app : the scroll that rerenders all the scene, the multiple waveforms that are recomputed every time for visual feedbacks, redux which computes many selectors, some animations triggered by RAFs etc.... I thought relocating the context computation into an offscreen canvas would prevent blocking the main thread and unfreeze the main thread every time an event is fired.
The best I could think of is to relocate my state manager in a web worker and all the huge computation in webassembly, and use an offscreen canvas to render from another thread. But this would be in an ideal and deadlineless dev project ...
