### ISSUE TITLE
Konva dragend not fired when viewport is left

### ISSUE THREAD

**Issue by spancioc** [konvajs/react-konva#475]
Hi guys!

I noticed an issue when a layer is dragged out of the viewport. The layer remains in dragmove state even I release the click button and goes on until I do a click anywhere in the page. Do you have a workaround for that?

Thank you!

**Comment by lavrton** [comment]
Can you make a demo? I can't reproduce.

**Comment by spancioc** [comment]
Sure. Here: https://codesandbox.io/s/llxq3yv829?file=/index.js please drag the red rectangle out of viewport and release the mouse button - the rect will be sticky to cursor.

**Comment by lavrton** [comment]
Closing as now enough information.
