### ISSUE TITLE
Demo not working on Firefox Developer Edition

### ISSUE THREAD

**Issue by ejarzo** [konvajs/react-konva#477]
So this is a pretty specific issue but I noticed that shape handlers are not working properly in Firefox Developer Edition (V 77.0b9). Clicking and hovering in this demo do not have any effect: https://codesandbox.io/s/react-konva-basic-demo-vifyy

I tried in regular Firefox 77 as well as Firefox Nightly 78.0a1 and it works fine in both so this likely isn't an issue with React Konva itself but I thought I'd bring it up.

**Comment by lavrton** [comment]
Yes. Thanks for the report, we are tracking that issue there: https://github.com/konvajs/konva/issues/912
