### ISSUE TITLE
Offscreen canvas with React Konva ?

### ISSUE THREAD

**Issue by EdouardLauret** [konvajs/react-konva#479]
Hi, I saw this post on the website concerning the use of offscreen canvas with Konva : [Offscreen Canvas with Konva](https://konvajs.org/docs/sandbox/Web_Worker.html )
Is there a way to use it with React Konva ?

Thanks in advance, Regards.

**Comment by lavrton** [comment]
I am going to close the issue for now. I don't see any good ways to use offscreen canvas with `react-konva`.
