### ISSUE TITLE
Looks like is not working on Chrome and Chromium for Ubuntu

### ISSUE THREAD

**Issue by jarenal** [konvajs/react-konva#480]
Looks like is not working on Chrome and Chromium for Ubuntu.

When I try some demos nothing is rendered in the canvas, everything is white.

I'm using Chrome and Chromium under Ubuntu 18.04.

With Firefox is working fine.

**Comment by jarenal** [comment]
any news or feedback?

**Comment by lavrton** [comment]
I don't have Ubuntu installed right now to test it. I will be happy if someone can check it and check the errors.

**Comment by lavrton** [comment]
I don't have any additional info about that issue. I am going to close it for now.

**Comment by ShivanshSharma1** [comment]
It works on Chrome for Ubuntu.What version of Chrome and Ubuntu you are using and is it giving any type of error.
