### ISSUE TITLE
drag and drop of shape enable dynamic scrollbar based on the mouse position

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#481]
Hi, I have created a react stage of width is window.innerwidth, heigh:window.innerheight, my issue is, if I move a shape beyond the boundaries means the scrollbar should come for the canvas, user can be able to see the dynamic scrollbar based on the mouse position

**Comment by lavrton** [comment]
What did you try? Basically you have two options:
1. Just increase stage size
2. Or emulate scrollbars with `Konva` shapes.

Something similar to https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#page-title

**Comment by mdmusaib** [comment]
thanks for your quick response really appreciate your efforts, my scenario is initially I don't have any scrollbar for stage, stage will be of window.innerwidth,window.innerheight, what I want is if I draw a rectangle and move it to end means automatically the vertical and horizontal scrolling should come, is it possible to implement,

**Comment by lavrton** [comment]
It is possible.

**Comment by mdmusaib** [comment]
I think it is possible, because if I get the x and y of particular dragging shape means I can enable the scrollbar using css property, like if I touch the center point of drawing area that time I can enable scrollbar, can you just tell me how to achieve this scenario...

**Comment by mdmusaib** [comment]
Can you give me some examples or demo in that

**Comment by lavrton** [comment]
So first you need to decide what type of scrollbars do you want. The demo I posted showed it: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#page-title

1. Native scrollbars - just increase stage size when hit the edge
2. Virtual scrollbars (eg generated by konva rectangles).

**Comment by mdmusaib** [comment]
Close the issue

**Comment by ganeshpatwaypi** [comment]
@lavrton  i tried some thing like this https://jsbin.com/rukimeyoto/edit?html,output

**Comment by ganeshpatwaypi** [comment]
@mdmusaib  can you share if you have the same
