### ISSUE TITLE
Trigger a event if my mouse position only at the center of stage

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#482]
Hi, how to trigger an event, only if I move my mouse at the center of stage, like I draw some rectangle and I try to move means once I reach to center position of stage means I want to trigger an event, how to do this...

**Comment by ejarzo** [comment]
Do you mean triggering an event when you are dragging something? You could use the `onDragMove` handler and check the event's `target.attrs` to find the `x` and `y` position of the shape. [demo](https://codesandbox.io/s/react-konva-basic-demo-9kges?file=/index.js)

**Comment by lavrton** [comment]
@ejarzo  Good answer.

@mdmusaib I hope it helps. Just check the position of a node inside `dragmove` event.

BTW. it is better to use `e.target.x()` and `e.target.y()` instead of `e.target.attrs.x`.  `attrs` attribute is not recommended to use.
