### ISSUE TITLE
Stage event listener delegation (with Redux)

### ISSUE THREAD

**Issue by l1zard** [konvajs/react-konva#483]
Hey, I have a problem and I don't know how to handle it.

My scenario:
I have tool palate with lots of tools. Every tool have different function with different listeners. (components)
Tool is drawing rectangles so on my main component i have listeners **onMouseDown, onMouseMove** etc. every change of listener I store in my reducer (so I have actuall position of mouse moving). and this data I used in different component that shows the drawing preview. Everything works well but If i have many objects on Stage its quite more laggy with more objects. 

_So my question is how can I access to event listener (Stage - onMouseMove event for example) from different components without storing event in state or redux_

**Comment by lavrton** [comment]
Yeah, storing mouse position inside the store is very slow (especially with redux).

You can do this:

```js
const Widget = () => {
  const rectRef = React.useRef();

  React.useEffect(() => {
    const onMouseMove = () => {
       // listener here
    }
    const stage = rectRef.current.getStage();
    stage.on('mousemove', onMouseMove);
    return () => {
        stage.off('mousemove', onMouseMove);
    }
  }, []);

  return <Rect {...someProps} ref={rectRef} />;
};

**Comment by l1zard** [comment]
> Yeah, storing mouse position inside the store is very slow (especially with redux).
> 
> You can do this:
> 
> ```js
> const Widget = () => {
>   const rectRef = React.useRef();
> 
>   React.useEffect(() => {
>     const onMouseMove = () => {
>        // listener here
>     }
>     const stage = rectRef.current.getStage();
>     stage.on('mousemove', onMouseMove);
>     return () => {
>         stage.off('mousemove', onMouseMove);
>     }
>   }, []);
> 
>   return <Rect {...someProps} ref={rectRef} />;
> };
> ```

Thanks for answer, can be somehow used without _React.useEffect_?

**Comment by l1zard** [comment]
moving the drawing preview to different layer fix the issue.

**Comment by chopfitzroy** [comment]
> moving the drawing preview to different layer fix the issue.

Could you expand on this? Do you mean adding the drawing preview to a different `Stage` or a different `Layer`?
