### ISSUE TITLE
Provide a way to style the canvas

### ISSUE THREAD

**Issue by danielo515** [konvajs/react-konva#484]
Hello and thanks for this cool wrapper.
I noticed that you are injecting some inline styles to the canvas. This makes almost impossible to style it using CSS. Not sure if this is knova specific or if it is react-konva (I think it's konva specific).
Could you take a property like className and pass it down to the generated canvas? That way it will be much easier to target with CSS.
Regards

**Comment by lavrton** [comment]
Why do you need it? What styles do you want?

You have stage container to control. Can you just apply styles to it? Or do something like that:

```css
.stage-container canvas {
  background: none;
}
```

**Comment by danielo515** [comment]
> Why do you need it? What styles do you want?
I think it is quite common to want to style underlying components. For example I wanted to add some borders, but RN it is impossible because canvas has some inlined srtyles.
It's not a deal breaker for me now, but I'll try what you are suggesting (albeit I'm pretty sure I will not be able to change the inlined ones)

**Comment by lavrton** [comment]
So as I mentioned you can just apply styles for a stage container. The border will work just fine here.

If you REALLY need it you can access `Konva.Layer` with a `ref` and use this:

```js
const layer = layerRef.current;
const nativeCanvas = layer.getCanvas()._canvas;
nativeCanvas.style.border = '1px solid black`;
```
