### ISSUE TITLE
On tap may be triggered twice on mobile devices

### ISSUE THREAD

**Issue by danielo515** [konvajs/react-konva#485]
Hello,
I have noticed something weird on mobile (and only on mobile) where I think the onTap callback may be called twice.
It only happens on the following scenario:

- You tap on an empty canvas
- You have both onClik and onTap callbacks setup

The empty canvas part is key. If I load an image on the canvas and I tap on top of the image, then it is only triggered once.
This is how I have it set-up:

```
  const addPoint = e => {
    const pos = e.currentTarget.getPointerPosition();
    setPoints(state => [...state, { x: pos.x, y: pos.y }]);
  };

    <Stage
        draggable
        width={window.innerWidth - 10}
        height={window.innerHeight - 16}
        onClick={addPoint}
        onTap={addPoint}
      >
        <Layer ref={layerRef}>
          {imageInfo.loaded && <Image image={image} />}
          {points.map(p => (
            <Circle
              key={pointId(p)}
              x={p.x}
              y={p.y}
              fill={color}
              radius={size}
            />
          ))}
        </Layer>
      </Stage>
```

Let me know if you need more details and I will provide you a CodeSandbox link

**Comment by lavrton** [comment]
Should be fixed with `konva@7.0.2`.

**Comment by danielo515** [comment]
Fantastic! Is it published already? Should also update react-konva?

**Comment by danielo515** [comment]
Just upgraded and it works perfectly. Thanks!
