### ISSUE TITLE
Declarative drag & drop using drag layer and Layer.getIntersection()

### ISSUE THREAD

**Issue by myq** [konvajs/react-konva#486]
In Konva (without React), when dropping a shape onto another shape, we can detect the shape that was dropped on by doing the following:

onDragStart: move target shape to a dedicated "drag layer" (`e.target.moveTo(dragLayer)`)
onDragEnd: use `layer.getIntersection(stage.getPointerPosition(), selector)` to get the target shape, then move the target back to its original parent (`e.target.moveTo(parentNode)`)

In react-konva, is there a declarative way to accomplish this?

Note: I viewed your example code [here](https://codesandbox.io/s/xv8kmkjkwp), but I find this confusing because you created a `<Layer name="dragging-layer" />` but never used it.

**Comment by myq** [comment]
Using `moveTo` does not work properly with React (especially with `useStrictMode` enabled, which my app requires), but `getIntersection` does not work properly if the shape being dragged is in the same layer as everything else - in that case, `getIntersection(pos)` will always return the shape being dragged rather than the shape beneath it.

**Comment by ejarzo** [comment]
I haven't tested this but is it possible to render the shape conditionally in one of the two layers using the same key? That way you wouldn't need `moveTo()` eg:
```js
<Layer name="dragging">
  {isDragging && <Shape key="my-shape" />
</Layer>
<Layer>
  {!isDragging && <Shape key="my-shape" />
<Layer>
```

**Comment by lavrton** [comment]
@ejarzo such solution with `key` will not work, because components are placed inside different parent Layers.

Pure declarative way will be:

```js
import React from "react";
import { render } from "react-dom";
import { Stage, Layer, Circle } from "react-konva";

const DEFAULT_STATE = [
  { id: "1", x: 60, y: 60, isDragging: false },
  { id: "2", x: 250, y: 250, isDragging: false }
];

const Target = ({ target, onDragStart, onDragEnd }) => {
  const ref = React.useRef(null);

  React.useEffect(() => {
    if (target.isDragging) {
      ref.current.startDrag();
    }
  }, [target.isDragging]);

  const handleDragMove = e => {
    const stage = e.target.getStage();
    const layer = stage.findOne(".main-layer");
    const hoverTarget = layer.getIntersection(e.target.position());
    console.log("hover", hoverTarget?.id());
  };

  return (
    <Circle
      draggable
      ref={ref}
      id={target.id}
      x={target.x}
      y={target.y}
      fill="red"
      radius={50}
      onDragStart={onDragStart}
      onDragEnd={onDragEnd}
      onDragMove={handleDragMove}
    />
  );
};

const App = () => {
  const [targets, setTargets] = React.useState(DEFAULT_STATE);

  const handleDragStart = e => {
    setTargets(
      targets.map(t => {
        if (t.id === e.target.id()) {
          return {
            ...t,
            isDragging: true
          };
        } else {
          return t;
        }
      })
    );
  };

  const handleDragEnd = e => {
    setTargets(
      targets.map(t => {
        if (t.id === e.target.id()) {
          return {
            ...t,
            isDragging: false,
            x: e.target.x(),
            y: e.target.x()
          };
        } else {
          return t;
        }
      })
    );
  };

  return (
    <Stage width={window.innerWidth} height={window.innerHeight}>
      <Layer name="main-layer">
        {targets
          .filter(t => !t.isDragging)
          .map(t => (
            <Target key={t.id} target={t} onDragStart={handleDragStart} />
          ))}
      </Layer>
      <Layer>
        {targets
          .filter(t => t.isDragging)
          .map(t => (
            <Target key={t.id} target={t} onDragEnd={handleDragEnd} />
          ))}
      </Layer>
    </Stage>
  );
};

render(<App />, document.getElementById("root"));
```

Demo: https://codesandbox.io/s/react-konva-drag-on-another-layer-g1893?file=/src/index.js:0-2163

The trick is to manually start drag when component is mounted:

```js
  React.useEffect(() => {
    if (target.isDragging) {
      ref.current.startDrag();
    }
  }, [target.isDragging]);
```

Moving component into top layer will do unmount/mount. So we drag action will be canceled. So we have to start it again. Just need to be careful here, because `dragstart` and `dragend` may be called twice.
