### ISSUE TITLE
Multi select Rect and Drag drop dragBoundFunc is not working

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#487]
Hi, here is my rectangle
<Rect>
 dragBoundFunc={pos => {
          let newX = pos.x < dragBoundaryLimit ? dragBoundaryLimit : pos.x;
          let newY = pos.y < dragBoundaryLimit ? dragBoundaryLimit : pos.y;
          return {
            x: newX,
            y: newY,
          };
        }}
</Rect>
for single rectangle if I select and drag out of boundary means it is restricting me this is fine for single select and drag.
but if I select multiple rectangle then try to drag out of boundary that time it should restrict, but it allowing to go out of boundary for all the shapes....

**Comment by lavrton** [comment]
We don't have any general logic to control bound boxes of several nodes at the same time. You have to control the boundary limit on every node individually. So you may need to recalculate it for whole set of selected nodes.

**Comment by mdmusaib** [comment]
I don't know how to achieve that, can you just give some idea on that in react konva

**Comment by lavrton** [comment]
Can you make a demo of what you are trying?

**Comment by mdmusaib** [comment]
Thanks for the quick response.👍

**Comment by mdmusaib** [comment]
In render method I'm just calling the Rectangle components, in seperate rectangle file I'm getting props and there I'm setting the dragBoundFunc

**Comment by mdmusaib** [comment]
> So you may need to recalculate it for whole set of selected nodes.

How to do this?

**Comment by lavrton** [comment]
There are many ways. For example with `rect.getClientRect()` of each rectangle.

**Comment by mvsweb** [comment]
can you please show me a small example demo, It will be very helpful for me.....

**Comment by lavrton** [comment]
What did you try?
