### ISSUE TITLE
onDragEnd fires on Rect click

### ISSUE THREAD

**Issue by inovramadani** [konvajs/react-konva#488]
Tried on v16.13.0-3, if we just click (without dragging at all) on Rect, the dragEnd event fires, which should not be. This behavior brings bugs to my application somehow. Please kindly fix, many thanks.

**Comment by lavrton** [comment]
What `konva` version are you using? Can you try the last one? If it doesn't work as expected, please make a demo.

**Comment by inovramadani** [comment]
I used konva 6.0.0.  
I tried using latest konva 7.0.2 on my application, the bug also occurs.  
  
Somehow I can't replicate it in demo, since the application is way too complex already. I created the demo here: https://codesandbox.io/s/eager-leftpad-dpoy6, but everything seems to be fine.  
  
I tried to use debugger to find out what causes it, but strangely if I use debugger the bug will not appear. Even if I directly press F8 (resume script) right after debugger stop the code on the onClick event. Without debugger I can get the bug consistently.  

The other thing that I recognize also on actual dragEvent it fires 2 times. As if the fake dragEvent always follows the other event.  
Any clue what might be the cause?

**Comment by lavrton** [comment]
Hard to say. Try to put `console.error('fire event');` instead of debugger. So you may try to follow full stack trace.

**Comment by inovramadani** [comment]
This is the trace I got when I put above code on dragEnd event:  
![full stack trace konva dragend bug](https://user-images.githubusercontent.com/27492820/87078448-d715f700-c24e-11ea-94c2-60003e165412.png)

video recording: https://streamable.com/fpoogm
Seems like normal to me. My application code is up to selectScreen redux action and then finally it automatically triggers the dragEnd event after passing react-conciler, react-konva, and then konva lib codes.

**Comment by lavrton** [comment]
Do you change `draggable` property on click somehow? Do you use custom `dragDistance`?

**Comment by inovramadani** [comment]
The draggable for Rect is derived from the user access. I just found out that it changes from true to false and back to true again after click. I don't use dragDistance.

**Comment by lavrton** [comment]
Then you need to check why you change it to true/false. Probably update your demo above with the same logic to show the bug.

**Comment by inovramadani** [comment]
yes, when I commented out the draggable props on Rect, the bug disappears. So confirmed that is the cause. I will try to shrink the bug on the updated demo link.

**Comment by inovramadani** [comment]
I have updated the demo: https://codesandbox.io/s/eager-leftpad-dpoy6
But differently on the demo only triggers the stage dragEnd. While on my app, it triggers Rect and Stage dragEnd.

**Comment by lavrton** [comment]
Ok. Just released `konva@7.0.3` with a fix for such an edge case. The demo works fine for me with the new version.
