### ISSUE TITLE
bug on perpendicular arrow custom shape, hover event triggers wrongly

### ISSUE THREAD

**Issue by inovramadani** [konvajs/react-konva#489]
Please see the bug demo on this video: https://streamable.com/93y0ap
It triggers on the blank part of the canvas inside the perpendicular arrow

**Comment by lavrton** [comment]
Please make a demo. Also, you may try to check the hit graph of the layer with `layer.toggleHitCanvas()`

**Comment by inovramadani** [comment]
Here is the demo: https://codesandbox.io/s/magical-flower-p97ip
I am not sure how to get the layer instance as I only render it as React component and how to use toggleHitCanvas?

**Comment by lavrton** [comment]
Konva is trying to automatically fill the shape. On scene (visible canvas on the page) is not visible, but on hit canvas it is visible.

To access layer directly you can do this:

```js
  const layerRef = React.useRef();

  React.useEffect(() => {
    layerRef.current.toggleHitCanvas();
  }, []);

 <Layer ref={layerRef}>
```

Here is the demo: https://codesandbox.io/s/react-konva-toggle-hit-graph-4hhsb

To fix the issue you can just add `fillEnabled={false}` to the shape.
