### ISSUE TITLE
transformer rotation problem

### ISSUE THREAD

**Issue by l1zard** [konvajs/react-konva#490]
Hey,
I have problem with transformer rotation position when I select already moved and rotated elements.
Scenario:
I have circles and they are selectable as rows 1..n (circles are stored in redux).
When I selected for example 2 circles, I remove them from current array in redux and move them to new array in redux (also new layer in stage). Circles are in `Konva Group` Drag them a rotate them on Stage.
After deselect I move them back into previous store (update position - x|y, rotation etc.) and empty the current redux store (rerender the stage). Every think is OK, but when i select them again and try to set current rotation they jump. If I do not set rotation of group, there is no jump but `Konva Transformer` is reseted to default

**Comment by lavrton** [comment]
Do you really need to create a group for transforming?

Can you make a demo?

**Comment by l1zard** [comment]
@lavrton so how to drag multiple elements (circles) at once? I found only group for that.

**Comment by lavrton** [comment]
If you are using `Konva.Transformer` for several nodes, you can transform/drag them at once. Available from `konva@6`.

**Comment by l1zard** [comment]
but for example i selected 500 circles in one select render them from array so If i put them into group its much easier then create ref for every single circle and put them into transformer, I just put group into transformer node, but dragging a group with lots of elements is quite laggy (tested only in dev mode with dev tools off) is this normal?

**Comment by lavrton** [comment]
Then you may use a group if it feels better to you. For performance fixes, there are many ways. I guess the cache will boost the perf a lot.


It may be not trivial to reuse "old transformer position" for another selection. Why do you need to keep an old rotation on another select? Can you make a simple demo?
