### ISSUE TITLE
Performance Issue for more shapes

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#491]
created  app like paint using react konva.
If I created more than 500 shape means applications is too slow,everything is lagging like drag and drop, transform, also while creating shapes.

If number of shape is getting increased,  performance of app is getting decreased...

Tell me some solution to improve performance.

**Comment by lavrton** [comment]
First, you need to find where the slowness comes from.  Is it from React or Konva rendering?

For rendering performance tips take a look here: https://konvajs.org/docs/performance/All_Performance_Tips.html#page-title

For React you may try to find some other solutions online.
