### ISSUE TITLE
strokewidth is applying as curved shape for Rectangle only in firefox browser

### ISSUE THREAD

**Issue by mvsweb** [konvajs/react-konva#493]
Hi, 
strokewidth is applying differently like if I try to apply strokewidth as 50 in firefox it is showing as a curved shapes.
after applying strokewidth if click on canvas area  it is showing rounded dots, only in firefox the strokewidth causing problems

let me know the solutions.

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by mvsweb** [comment]
Here is the demo, but I checked in firefox it is working fine, but in my realtime project while increasing the strokewidth it is not applying properly
https://stackblitz.com/edit/react-h1ntup

**Comment by mvsweb** [comment]
some how I got the issue, actually the problem is in firefox in handleMouseMove I'm updating the cornerRadius for the rectangle, 
that's why it is showing little curved shape, 
how to apply cornerradius properly even it should apply in handleMouseMove also, and even if I try to draw from right to left or left to right any position, cornerRadius should apply properly.
 can you tell me the solution for applying cornerRadius for rectangle in all this suituation.....

**Comment by lavrton** [comment]
Sorry, I don't understand your question. 

> can you tell me the solution for applying cornerRadius for rectangle in all this suituation

What situation? Just use `cornerRadius` property.

**Comment by mvsweb** [comment]
while drawing in reverse order that cornerRadius property is not working (drawing rectangle from right to left)

**Comment by lavrton** [comment]
Do you mean on negative width/heigh? If so - just don't use them.

**Comment by mdmusaib** [comment]
Thanks for response, it helps to solve....
