### ISSUE TITLE
Line position malfunctioning

### ISSUE THREAD

**Issue by idfunctor** [konvajs/react-konva#494]
Hey! Great library; love it and really wanna express my thankfulness to your work.
I am making something like your recent example of AI annotation using Konva; except using Rect and Line for rectangle & polygon annotations. My shapes (Rect, Line) are rendered inside of a Group; which is inside an image layer.
When I use Rect, the .position() method returns position respective to group. And for the same code; if i use .position() for Line; it returns x and y values relative to its initial position. i.e. starts going in the negative when i move it towards top or left...

Is there any reason for this to happen or is this a bug?

Image shows how the Polygon is pretty much near center of the image; yet the console shows x & y values in the negative.
Same thing for Rect shows expected values relative to the background image.

![image](https://user-images.githubusercontent.com/13308108/87586786-b4785800-c6fe-11ea-96ab-8a444e05c3b6.png)

**Comment by lavrton** [comment]
Default line position is {0, 0}. If you are moving line into top-left direction, then the position goes into negative value.

**Comment by lavrton** [comment]
By "position" I mean `x` and `y` attributes.

**Comment by idfunctor** [comment]
@lavrton thanks for that clarification; it's not consistent with that of Rect so I got confused.

**Comment by idfunctor** [comment]
Also I'm new to all this so forgive me if that's a bad question, but is there a reason for the line position to behave differently than a Rect? Just asking for my understanding.

**Comment by idfunctor** [comment]
I found the my use case can be worked out by using getClientRect btw, so I'm glad that the Line API doesn't leave it to me to have to calculate absolute 0! phew!

**Comment by lavrton** [comment]
> but is there a reason for the line position to behave differently than a Rect?

It is not different. It works consistently. Dragging is changing `{x, y}` attributes. Just don't confuse `points` attributes of the line and its position.

**Comment by idfunctor** [comment]
In my case, if i do `e.currentTarget.position()` for Rect it gives me x, y relative to parent. the same doesn't happen with line...line.position() always starts with 0, 0 no matter where the line is.
My confusion is why while dragging; does the Rect not always start with 0,0 if the line does....maybe I can create a Codesandbox to show what I mean.

**Comment by lavrton** [comment]
`e.currentTarget.position()` just returns `x` and `y` attributes. I guess for rect you set them for some value. For line, you probably didn't. So it is {0,0} by default.

**Comment by idfunctor** [comment]
Ahhhh that clears everything; thanks!!!

**Comment by idfunctor** [comment]
@lavrton sorry to annoy you but is there a way to convert position values of Line to absolute position values?
