### ISSUE TITLE
drawing shape beyond the canvas.

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#496]
If I draw shapes beyond the canvas area means it is not allowing to draw, but in case of drag it is allwoing to drag beyond the canvas area, simply I need to draw out of canvas but the shape should not visible to user when I come back to canvas it should continue the shape, how to do this with react konva...

**Comment by lavrton** [comment]
You can just create it outside of visible view and then change position manually while listening `mousemove` event of `window`.

Or you can call `node.startDrag()` for a created component at any point of time.

```
const Widget = () => {
  const ref = React.useRef();
  React.useEffect(() => {
     // at some point of time
     ref.current.startDrag();
  }, [])
  return <Rect ref={ref} />
}
```
