### ISSUE TITLE
Blurrness is coming in the rectangle without adding blurrness property

### ISSUE THREAD

**Issue by umeshdobai** [konvajs/react-konva#497]
We are giving strokeWidth 1 for rectangle without adding any blurrness property.
Some of the rectangle are fine and some are showing blurred. Although we have same strokeWidth for all rectangles.

Find the below image
![Screenshot (27)](https://user-images.githubusercontent.com/28566994/87950314-c3775580-cac4-11ea-99c3-a48ddafb9168.png)

**Comment by umeshdobai** [comment]
non HDP screen means

**Comment by lavrton** [comment]
Screens where `window.devicePixelRatio = 1`. https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
