### ISSUE TITLE
Shape not visible after zoomIn

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#499]
I have a stage width and height around 1000,600 respectively, also I have zoomin, ZoomOut button, while clicking on zoomIn I'm increasing 0.1 scalex upto 3, scaley.

If I try to draw a shape in position at x:900, y:400 in normal scale 1, after that clicking on zoomIn button continuously it will increasing scalex,scaley upto some limit say 3,but the problem is I'm not able to see the shape whichever I have drawn at given position while zoomIn, shape is going beyond the canvas, if I click normal that time only the shape is showing..

Whereas if I draw a shape at beginning or center of canvas then even after zoomIn also the shape is visible Zoomin working fine, but if I draw at ending corner of canvas that time if I zoomIn the shape is not visible it's going beyond the canvas

Help me to fix this problem....

**Comment by lavrton** [comment]
Can you make a demo? I don't understand the issue.

If you zoom in a stage, then all shapes will be moved on the screen. And they may go out of the visible viewport. From the description that looks expected to me.
