### ISSUE TITLE
Rotation Snap Tolerance

### ISSUE THREAD

**Issue by rmnbod** [konvajs/react-konva#500]
konva 7.0.4
react-konva 16.13.0-5

rotationSnaps with range 0 - 90 has no effect, as the computed values are negative.
This issue is similar to https://github.com/konvajs/konva/issues/888

**Comment by lavrton** [comment]
Can you make a demo? I just made this: https://jsbin.com/vipoxegeki/edit?html,js,output, it works ok for me.

**Comment by lavrton** [comment]
Closing as no info...
