### ISSUE TITLE
Show transformer border out off stage

### ISSUE THREAD

**Issue by Batuhan-Akkaya** [konvajs/react-konva#501]
Hello, is it possible to show the transformer border out of stage? example:

<img width="337" alt="Screen Shot 2020-08-01 at 11 33 50" src="https://user-images.githubusercontent.com/22476697/89097800-f685e700-d3ea-11ea-9a99-4ff387b8c375.png">

**Comment by lavrton** [comment]
No. `Konva` can't draw outside of the canvas. But you can make a canvas bigger and use `clip` to cut shapes area. But keep the transformer inside a parent without clip. I made that on https://polotno.dev/ project.

**Comment by Batuhan-Akkaya** [comment]
@lavrton  Thank you for your response. I am going to try `clip`. Also can you share how did you do these rule lines and select items with mouse area in "Polotno"? 
Thanks

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Objects_Snapping.html#page-title
https://konvajs.org/docs/select_and_transform/Basic_demo.html#page-title

**Comment by Batuhan-Akkaya** [comment]
Okay, what about this (mouse creates blue area to select items)
<img width="493" alt="Screen Shot 2020-08-01 at 16 06 56" src="https://user-images.githubusercontent.com/22476697/89102371-2e078a00-d411-11ea-9e5e-7bba28632bee.png">
:

**Comment by lavrton** [comment]
Just take a look into the second link again.

**Comment by Batuhan-Akkaya** [comment]
@lavrton I tried the method you said but it gives the following warning. Can you help me please?
**Konva warning: Transformer and attached node have different parents. Konva does not support such case right now. Please move Transformer to the parent of attaching node.**
My code hierarchy:
```
<Layer>
          <Group clip={clip}>
                <Shape />
          </Group>
          <Transformer/>
</Layer>
```

**Comment by lavrton** [comment]
@Batuhan-Akkaya it looks like you are using an old version of Konva. The new version should not have that warning

**Comment by Batuhan-Akkaya** [comment]
Yes thank you.
I also have one more question: I have a code to download canvas as a image but now there is unnecessary spaces after add additional group.
```
onClick={() => {
          if (props.stageRef) {
            props.setSelectedComponent([]);
            const dataURL = props.stageRef.toDataURL({pixelRatio: ratio});
            const link = document.createElement("a");
            link.download = "";
            link.href = dataURL;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
          }
```
code structure:
```
<Stage width={canvasWidth + 400} height={canvasHeight + 400}>
            <Layer>
              <Rect width={canvasWidth} height={canvasHeight} fill={settings.cBgColor} ref={containerRectRef} x={200} y={200} />
              <Group clip={{x: 200, y: 200, width: canvasWidth, height: canvasHeight,}}>
                <Shape/>
              </Group>
            </Layer>
          </Stage>
```
Canvas:
<img width="485" alt="Screen Shot 2020-09-17 at 05 43 28" src="https://user-images.githubusercontent.com/22476697/93413953-0711f400-f8a9-11ea-834a-561ebc39da87.png">
Note: Overflow: hidden works on canvas but not png.

**Comment by ntlongctt** [comment]
@lavrton I have followed you idea but I cannot interact with the object outside of the clip region, how I can deal with this issue, thanks

**Comment by lavrton** [comment]
This is intentional of clipping. If you want to interact with an object, outside the clipping area, then you have to find another way to cut the content. You can take a look into `globalCompositeOperation` option to cut content or simply draw a background/border on top around your content.
