### ISSUE TITLE
Image keeps snapping to a random position after being moved.

### ISSUE THREAD

**Issue by ivanleomk** [konvajs/react-konva#502]
![2020-08-04 00 29 49](https://user-images.githubusercontent.com/45760326/89205109-c35d7680-d5e9-11ea-8b02-3cc56e3276bd.gif)

Hi guys,

I'm not sure what's happenning with my particular React-Konva app. I've set an event handler on my image such that it updates the global state with the new x and y co-ordinates of the image onDragEnd.

```
onDragEnd={e => {
          console.log(e.target)
          onChange({
            ...shapeProps,
            height: e.target.height(),
            width: e.target.width(),
            x: e.target.x() - e.target.getStage().x(),
            y: e.target.y() - e.target.getStage().y()
          })
        }}
```

I then pass it into a global reducer which then destructures out the new x , y , width and height property and updates before rendering the image with its new x and y co-ordinates using

```
<Image
x={x}
y={y}
width={width}
height={height}
/>
```

Any idea what might have caused this bug? I've been trying to debug for a week but to no avail. I've tried taking into account the offset of the stage but that doesn't seem to make a difference since I keep getting a value of 0 for the offset x and y

**Comment by lavrton** [comment]
What is draggable here? An image? Do you pass resulted {x, y} into the same component that has `onDragEnd` handler?

**Comment by ivanleomk** [comment]
Yes it's an image which is draggable and I pass the resulted {x,y} into the same component.

```
<Image
        onClick={onSelect}
        image={image}
        ref={shapeRef}
        x={x}
        y={x}
        draggable
        onDragStart={
          e => console.log(e.target.x(), e.target.y())
        }
        onDragEnd={e => {
          console.log(e.target)
          onChange({
            ...shapeProps,
            height: e.target.height(),
            width: e.target.width(),
            x: e.target.x() - e.target.getStage().x(),
            y: e.target.y() - e.target.getStage().y()
          })
        }}
        onTransformEnd={e => {
          const node = shapeRef.current
          const scaleX = node.scaleX()
          const scaleY = node.scaleY()
          onChange({
            ...shapeProps,
            x: node.x(),
            y: node.y(),
            width: node.width() * scaleX,
            height: node.height() * scaleY
          })
        }}
      />
```

The onChange function I'm using

```
onChange={newAttrs => {
              console.log(newAttrs)
              const { x, y, width, height } = newAttrs
              
              dispatch({
                type: UPDATE_IMAGE,
                payload: {
                  x,
                  y,
                  width,
                  height,
                  id: item.id
                }
              })
            }}
```

**Comment by lavrton** [comment]
Hmm. Why do you apply stage position in dragend?
Why do you use `e.target.y() - e.target.getStage().y()` instead of just `e.target.y()`?

**Comment by ivanleomk** [comment]
I originally thought that the problem might lie with the fact that the final x and y co-ordinate didn't take into account the stage offset. Hence I thought of subtracting the stage offset from the x and y co-ordinates.

The way I initially thought to implement it was

1. User creates draggable image by clicking on image button
2. Image is initialised with x, y ,height,width and src attributes.
3. When user finishes dragging images, the x and y co-ordinates of image are updated through a redux dispatch. I believe this is what's causing the final flicker back. The x and y co-ordinates are from e.target.x() and e.target.y() .

I've tried implementing a temporary workaround

```
onDragMove={e =>
          onChange({
            ...shapeProps,
            height: e.target.height(),
            width: e.target.width(),
            x: e.target.y(),
            y: e.target.x()
          })
        
        }
```

This eventually moves the image to the desired X co-ordinate by making it flicker here and there but it gets the image to the desired location sometimes. 


Here is the canvas object I'm currently using that the image object exists on top of : https://gist.github.com/ivanleomk/aecede8c7e40eaa42741a66f01a2f0a9
Here is the Image Object that is being rendered: https://gist.github.com/ivanleomk/a0f45a6579ffe6e9309156c785ca16c4

**Comment by lavrton** [comment]
Can you make a small demo? I don't see any issues in the code.

**Comment by ivanleomk** [comment]
Sure not a problem! I'll get on it now. I've been trying to get it working on jsfiddle but I can't seem to import in react konva into jsfiddle. Will try a bunch of different ones till I get it to work!

**Comment by lavrton** [comment]
For `react-konva` is is better to use codesandbox for demos. Like start from this template: https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/shapes?from-embed

**Comment by lavrton** [comment]
I am going to close the issue for now. If you still have that bug, please provide a small demo.
