### ISSUE TITLE
without using any blurness property, showing blurness for rectangle in two side.

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#503]
if I draw a rectangle with a stroke size  of 1, left and right side line is fine, but top and bottom line is blurred, sometimes it's getting swapped with the sides. 
we tried applying pixelRatio above 1.5  to layer, but there is no difference, I want to be view same as in both HD screen, and non hdp screen.
here is the shape of blurred image.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/19144712/89523177-14df4e80-d800-11ea-81fb-ca5e2a7bc62e.png)

**Comment by lavrton** [comment]
That is how canvas/stroke drawing works. You may need to move your drawing by `0.5px`.

For more info take a look here: https://stackoverflow.com/questions/8696631/canvas-drawings-like-lines-are-blurry

**Comment by mdmusaib** [comment]
We are using react konva Rect component only, how to do this with react konva, how to move 0.5px using this react konva Rect component.
https://konvajs.org/docs/react/Shapes.html

**Comment by lavrton** [comment]
Just try to move any component by `0.5`

```js
<Stage x={0.5} y={0.5} />
// or
<Layer x={0.5} y={0.5} />
// or
<Rect x={props.x + 0.5} y={props.y + 0.5} />
```

**Comment by mdmusaib** [comment]
I added 0.5 in stage and rect, even after added it is showing same issue only..
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/19144712/89633342-5421a400-d8c1-11ea-8a9f-9bd1c6790b96.png)

**Comment by lavrton** [comment]
As I can see in the picture, the left and top edges are ok. You may try to do something similar for width/height to adjust the bottom and right edges.

**Comment by mdmusaib** [comment]
I checked adding 0.5 to width & height also, but it's not working, can you give any other solutions..

**Comment by lavrton** [comment]
I am not sure I can do much here from the Konva side. You just have to learn how pixes antialyzing works on native canvas. I guess with a native canvas you will have the same result. If not - please provide a demo.

**Comment by mdmusaib** [comment]
As you told add 0.5, to x and y respectively, it is working fine now, the shapes clarity is little bit ok, but the problem is after adding 0.5 to each x,y , I'm facing some other issue, like in dragBoundFunc 
const dragBoundaryLimitX=2;
 dragBoundFunc={pos => {

          return {
            x: pos.x < dragBoundaryLimitX
              ? dragBoundaryLimitX
              : pos.x,
            y: pos.y < dragBoundaryLimitY
              ? dragBoundaryLimitY
              : pos.y,
          };
        }}
if the shape drag beyond the limit, it is stopping the drag, but my issue is shape is flickering because we added 0.5 right. so that only the shape is keep on moving once it reach to dragBoundlimit.
 

how to solve this problem, help me to fix the issue.

**Comment by lavrton** [comment]
You don't need to add 0.5 to each x,y. Just set it once on a stage or layer.

**Comment by mdmusaib** [comment]
I tried added in stage as well as layer, but it is not working, only if I add to Rectangle shape then only it is showing sharp edges clearly visible in any screen resolution, how to fix this , with adding in shape

**Comment by lavrton** [comment]
> I tried added in stage as well as layer

Of course, it will not work if you add to BOTH of them. The main hack about `0.5` is to move all drawings a bit. So you just need to define it once.
