### ISSUE TITLE
without using scaleX,scaleY value how to find the updated points on transform

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#505]
We are using react custom shape, const points=[{x:34,y:23},{x:74,y:53},{x:84,y:73},{x:94,y:43}], using this sceneFunc 
 sceneFunc={(context, shape) => {
            context.beginPath();
            props.points.map((data, i) => context.lineTo(data?.x , data?.y ));
            props.isClosed &&
              props.points &&
              context.lineTo(props.points[0].x , props.points[0].y);
            context.fillStrokeShape(shape);
          }}
for this points array, on transform end how to get the new updated points array without using scaleX,scaleY

**Comment by lavrton** [comment]
> without using scaleX,scaleY

Why without using them?


you can use `shape.getTransform().point(onePointFromArray)` to get a result position of one point.

**Comment by mdmusaib** [comment]
where we need to call this shape.getTransform(onePointFromArray ).point() and what is that onePointFromArray means?
we need to added this line in sceneFunc or some where else can you tell that...

**Comment by lavrton** [comment]
> where we need to call this shape.getTransform(onePointFromArray ).point()

I don't where you need it. Probably in `transformend` event as you mentioned in the first comment. 

>  what is that onePointFromArray means?

It is a variable with `{x, y}` properties (see docs). If you want to know the position of update points, then you need to iterate over each point in `points` array and calculate transformed position.

**Comment by mdmusaib** [comment]
we are using this code for drawing polygon ,on transformend we are calling shape.getTransform().point({ x: data?.x - startX, y: data?.y - startY }) inside sceneFunc, I don't know where to call, and how to get the updated points on transformEnd.
`<Group
        ref={shapeRef}
        draggable={props.draggable}
        x={props.x || startX}
        y={props.y || startY}
        height={props.endY - props.y}
        width={props.endX - props.x}
        onTransform={e => console.log('transfromStart', e)}
        onTransformStart={() => handleTransformStart()}
        onTransformEnd={e => handleTransform(e)}
        onDragStart={e => handleDragStart(e)}
        onDragMove={e => props.handleUpdatedDrag(e.target.attrs, props.index, 'drag', true)}
        onDragEnd={e => props.handleUpdatedDrag(e.target.attrs, props.index, 'drop', false)}
        scaleX={props.scaleX}
        scaleY={props.scaleY}
        _useStrictMode={enableStrict && strict}
       
      >
        <Rect
          x={0}
          y={0}
          height={endY - startY}
          width={endX - startX}
          strokeWidth={props.strokeWidth}
          stroke={'transparent'}
        />
        <Shape
          sceneFunc={(context, shape) => {
            context.beginPath();
            props.points.map((data, i) => {
            context.lineTo(data?.x - startX, data?.y - startY);
            shape.getTransform().point({ x:data?.x - startX, y:data?.y - startY });
            });
            props.isClosed && context.closePath();
            // context._applyLineCap('miter');
            context.fillStrokeShape(shape);
          }}
          stroke={props.stroke || 'black'}

          strokeScaleEnabled={false}
          strokeWidth={props.strokeWidth * props.zoomScaleX || 1 * props.zoomScaleX}
          id={props.id}
        />
      </Group>
      {props.isClosed && props.isSelected && (
        <Transformer
          ignoreStroke={true}
          rotateEnabled={false}
          anchorSize={5 * props.zoomScaleX}
          anchorStroke={'black'}
          anchorFill={'black'}
          
          borderStroke={'transparent'}
          ref={trRef}
          boundBoxFunc={(oldBox, newBox) => {
            if (newBox.x > 0 && newBox.y > 0) {
              if (newBox.width < 5 || newBox.height < 5) {
                return oldBox;
              }
              return newBox;
            }
            return oldBox;
          }}
        />
      )}`

**Comment by mdmusaib** [comment]
I made a small demo of shape, https://jebeq.csb.app/
can you tell me how to get the updated points onTransformEnd from the above demo.

**Comment by lavrton** [comment]
You have "transformend" event (on both transformer and attached node - the group in your case). Inside that event you can do this:

```js
const handleTransformEnd = (e) => {
   const shape = pointsRef.current;
   const points = shape.getAttr('points');
   const transform = shape.getAbsoluteTransform();
   const absolutePoints = points.map(p => transform.point(p);
   // then do something with absolute points coordinates
   // like save into state
   // or adjust it by group {x, y} and then save
}
```

**Comment by mdmusaib** [comment]
whatever your given the solution, I tried but   const points = shape.getAttr('points'); is given undefined, we also tried given our default points array , but after transformEnd it's given wroung values, can you make a small demo using our code..

**Comment by lavrton** [comment]
>  I tried but const points = shape.getAttr('points'); is given undefined

Right, looks like you are not saving them in Shape attributes, that just use from props.

> but after transformEnd it's given wroung values

What do you mean by wrong values?
