### ISSUE TITLE
horizontal and vertical scrollbar for stage 

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#511]
Hi,
How to give a scrollbar for stage, initially the stage should have some width and height upon clicking on zoomin, ZoomOut I want to show the scrollbar respectively, 
Can you please make a small demo on that, really looking out for a solution.
Thanks....

**Comment by lavrton** [comment]
There are many samples here: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#page-title

**Comment by lavrton** [comment]
I just need to convert any of that demos to react.

**Comment by mdmusaib** [comment]
Yeah I already check this demos, my doubt is without any shapes empty canvas, I just wanted todo, if I click the zoomin, ZoomOut, the canvas area should automatically increase and decrease, this is what I'm looking for

**Comment by lavrton** [comment]
What did you try?

From the demos, you just need to recalculate the total "virtual" width/height of the viewport.

**Comment by Andrew-Pynch** [comment]
> ar for stage, initially the stage should have some width and height upon clicking on zoomin, ZoomOut I want to show the scrollbar resp

Where you able to convert this into React?

**Comment by nnha19** [comment]
@mdmusaib Did you manage to get it done?? I need to do the exact same thing. If you accomplished this, could you share your solution?
