### ISSUE TITLE
Scrollbar issue in react konva

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#512]
Hi, I have given overflow:scroll for the stage , and added width, height, but when click on zoomIn the stage width is increasing but the scrollbar is not increasing...

Here I'm attaching small demo link

https://stackblitz.com/edit/react-hbnsxe?file=src%2FApp.js

I checked your demos from here https://konvajs.org/docs/sandbox/Canvas_Scrolling.html
this 3rd examples can you do a demo on react app 
3.Emulate scrollbars in react APP

**Comment by lavrton** [comment]
I don't recommend injecting CSS styles into Konva internals with `.konvajs-content`.


If you want to emulate scrollbars, then you have to draw them manually. With rectangles or other shapes.

**Comment by mdmusaib** [comment]
Okay, I'm giving parent div width and height to stage, but I'm setting that in componentDidMount() is it the right way to set there? Or any other possible ways? I'm just setting the parent container width and height and I'm not scalling anything, but if the parent div overflow scrolling should come but it is not coming

**Comment by lavrton** [comment]
> Okay, I'm giving parent div width and height to stage

What does it mean? size of parent equal to stage?

> but I'm setting that in componentDidMount()

Why? Why not just render?

> but if the parent div overflow scrolling should come but it is not coming

Make a demo, I don't see that in your first demo. Set `scroll: auto` to the parent.

**Comment by mdmusaib** [comment]
thanks for the quick reply this issue is fixed now....
