### ISSUE TITLE
Available by CDN

### ISSUE THREAD

**Issue by ChristopherHButler** [konvajs/react-konva#513]
Sorry, not so much an issue, I was just wondering if react-konva is available from a cdn like cdnjs?

**Comment by lavrton** [comment]
Hmm. I don't think so.

You can use upkg for CDN access: https://unpkg.com/react-konva@16.13.0-6/lib/ReactKonva.js

But `react-konva` made in commonjs style. So I guess it will not work in the browser directly. And I don't know what is the use case to use CDN for `react-konva`. The majority of `react-konva` users (or all users) are using bundlers such as webpack.

**Comment by ChristopherHButler** [comment]
Fair enough. I made an online code editor that does not use a bundler so that is my use case.
