### ISSUE TITLE
By increasing stage width and height, shape position is getting changed

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#515]
Hi, I'm doing zoomIN, zoomOut, when I'm clicking the zoomIN button, I'm doing some calculations like i'm increasing the stage width and height by 100 and increasing the stage scaleX,scaleY with 0.1, but the problem is my shape is not staying in the stage it is going beyond the stage width and height and I'm not able to see my shape around in stage, when doing zoomOut that time all the shape getting appears, I don't know what's the issue here, can you check and revert back to me, 

My expectation is when zoomIN the stage width and height plus scaling should work properly even thought I have multiple shapes....

**Comment by lavrton** [comment]
Why do you increase size by `100`? Why not `200`?

**Comment by mdmusaib** [comment]
I'm just increasing by 100 only, if I do increase by 200 it would solve the problem?

**Comment by lavrton** [comment]
I guess that number should be relative to the size of your stage and scale factor.  You said that you don't see shapes after zoom because they are out of the viewport. That means you need to change width/height by a different number.
