### ISSUE TITLE
Intermittent lines missing

### ISSUE THREAD

**Issue by hmeerlo** [konvajs/react-konva#517]
I have a very strange issue. I have done quite some debugging already but can not pinpoint what goes wrong. I'm trying render a grid on an image by drawing all lines of the grid using the points property. This grid represent a projection of a calibration result on a camera: 

<img width="794" alt="Screenshot 2020-09-22 at 20 14 22" src="https://user-images.githubusercontent.com/448150/93928874-4b731900-fd1b-11ea-8f8c-5598a9538c88.png">

At the bottom of the image there is one line missing indicated by the handdrawn green line. I added logging to my code and know that it is line 107 that is missing. So I logged the line before (106) and 107 and I see no difference between the two.

```
import React, { Fragment, useMemo } from 'react';
import { Line } from 'react-konva';

interface Props {
  template: Array<Array<number>>;
  scale: number;
  projection: Array<Array<number>> | null;
}

const Projection: React.FunctionComponent<Props> = (props) => {
  const lines = useMemo(() => {
    const ret = [];
    if (props.projection && props.projection.length === props.template.length) {
      let i = 0;

      let width = 0;
      while (props.template[i][1] === 0) i++;
      width = i;
      const height = props.projection.length / width;

      for (i = 0; i < height; i++) {
        ret.push(props.projection.slice(i * width, (i + 1) * width).flatMap((p) => [...p]));
      }
      for (i = 0; i < width; i++) {
        const add = [];
        for (let j = 0; j < height; j++) {
          add.push(props.projection[i + j * width][0]);
          add.push(props.projection[i + j * width][1]);
        }
        ret.push(add);
      }
    }
    return ret;
  }, [props.projection, props.template]);
  return props.projection ? (
    <Fragment>
      {lines.map((l, i) => {
        const ret = (
          <Line key={i} points={l} stroke={i === 107 ? 'red' : 'blue'} strokeWidth={Math.ceil(1 / props.scale)} />
        );
        if (i === 107 || i === 106) {
          console.log(ret);
        }
        return ret;
      })}
    </Fragment>
  ) : (
    <Fragment />
  );
};

export default Projection;

```

The logged lines:
<img width="684" alt="Screenshot 2020-09-22 at 21 36 56" src="https://user-images.githubusercontent.com/448150/93929178-c4727080-fd1b-11ea-9cbb-185c6c70916d.png">

Any help would be appreciated!

**Comment by lavrton** [comment]
Hard to say. Try to stroke that line with a different color, Probably it is placed somewhere else.

**Comment by hmeerlo** [comment]
Yes I tried that already. I can actually see from the points of the line that it should have been visible because the coords are correct.

**Comment by lavrton** [comment]
Try to remove all lines and display only one that you think is correct. And debug them one by one.

IF you still have - please create a small demo.
