### ISSUE TITLE
Only style the rotater_anchor

### ISSUE THREAD

**Issue by Tarshh** [konvajs/react-konva#518]
Hello,

I'm trying to style the transformer object ONLY on the rotate anchor.
Is there a way to style specifically this point of the transformer? Image to show what anchor i mean.

![image](https://user-images.githubusercontent.com/47401362/94144497-7d968f00-fe71-11ea-987c-7a4da3845451.png)

Thank you.

**Comment by Tarshh** [comment]
`      const rotator = transformerRef.current.findOne('.rotater');
      Konva.Transformer.prototype.update.call(rotator);
      rotator.attrs.fill = "green";
      transformerRef.current.update()`

This is the closest i got to a solution but it gives me a runtime error in in konva node module 
![image](https://user-images.githubusercontent.com/47401362/94198078-fd931800-feb6-11ea-8504-98e736f6e2da.png)

Is this the correct way? Thank you

Using: 
React 16.13
Typescript 4.0.2

**Comment by lavrton** [comment]
Did you take a look here?

https://stackoverflow.com/questions/63455286/is-it-possible-to-use-an-icon-as-a-rotater-in-react-konva-transformer

It has a code sample with a demo.
