### ISSUE TITLE
shape polygon on close it getting tapped at closing point

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/react-konva#519]
`{"points":[{"x":152.8333282470703,"y":60.83332824707031},{"x":143.8333282470703,"y":418.8333282470703},{"x":682.8333282470703,"y":409.8333282470703},{"x":680.8333282470703,"y":68.83332824707031}],
"stroke":"#000000","strokeWidth":50,"shape":"Polygon","id":"Polygon_0",
"isClosed":true,"isSelected":true,"x":143.8333282470703,"y":60.83332824707031,"oldX":143.8333282470703,"oldY":60.83332824707031,"endX":682.8333282470703,"endY":418.8333282470703,"height":358,"width":539,"`

we are using konva shape and scenefunc and passing points as props for creating polygon on closing it is getting tapped like the below image. how to solve this issue, we want sharp corner at all sides....

<img width="535" alt="Screenshot 2020-09-25 165247" src="https://user-images.githubusercontent.com/19144712/94261901-3b904a80-ff50-11ea-8acf-dac3cd4cd884.png">

**Comment by lavrton** [comment]
Can you make a demo? Do you have it for every browser?

**Comment by lavrton** [comment]
Closing as no additional info.
