### ISSUE TITLE
Getting shapes attrs after transforming multiple

### ISSUE THREAD

**Issue by Artas47** [konvajs/react-konva#520]
Hi, referring to this demo https://codesandbox.io/s/multiple-selection-react-hooks-and-konva-forked-tgggi?file=/src/index.js .
I wonder if there is a way to get the attrs of all updated (transformed) shapes. At the first sight it might look that the all shapes are updated but when I started to debug with console.logs I see that only one shape gets attrs updated. I would like to store all updated  attrs in my redux store after transform. The final question is - how can I get attrs of all updated shapes after transform?

**Comment by lavrton** [comment]
So every shape has `transformend` event. You can read all attributes inside that event.
