### ISSUE TITLE
Intersection

### ISSUE THREAD

**Issue by Artas47** [konvajs/react-konva#521]
Hi, referring to this demo https://konvajs.org/docs/sandbox/Collision_Detection.html . How can I make this intersection check without this additional space (orange colored)?
![1](https://user-images.githubusercontent.com/33393790/94684831-e88c0e00-0328-11eb-8b65-3291aa84f306.png)

**Comment by lavrton** [comment]
`Konva` doesn't have such API. You have to use the power of math to calculate such intersections manually (or with some physics engine).

Take a look here: https://github.com/jriecken/sat-js
