### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by l1zard** [konvajs/react-konva#523]
Hey,
I draw a theatre hall with 1200+- seats (circles). Every seats is clickable (to reserve) and when I try to drag or zoom is super laggy. I looked into performance issues section but nothing works well for me. Stage size is about 2000x2000 max.

**Comment by lavrton** [comment]
Did you try caching? I am sure it should help there a lot.

**Comment by l1zard** [comment]
@lavrton yes its super fast then, but because of scale/zoom (primary for mobile devices) is fuzzy and not so nice. It is possible somehow after scale to re-cache again? I tried to clear cache and cache again but result is same.

**Comment by lavrton** [comment]
Yes. There result of simple recache will be the same. You may need to change the cache quality with the `pixelRatio` option.

**Comment by l1zard** [comment]
@lavrton Thanks, I will try :)

**Comment by l1zard** [comment]
@lavrton It works very well now. But I have issues with animation. If i cached the seat the animation on click will not work now.  Is there possible destroy the cache on click and run animation of a seat?

**Comment by lavrton** [comment]
Yes. `node.clearCache()`.
