### ISSUE TITLE
Performance Issue after increasing stage height and width

### ISSUE THREAD

**Issue by umeshdobai** [konvajs/react-konva#525]
Hi,
I am using scale to zoom the canvas area and increasing height and width of the stage by 130px.
After certain click on zoom in it is lagging.

 const stage = this.stageRef.getStage();
    const stageX = stage.scale().x;
    const stageY = stage.scale().y;
    const height = stage.attrs.height;
    const width = stage.attrs.width;
if (stageX <= 3.5 && stageX >= 1) {
          let heightZoomIN = height + 130;
          let widthZoomIn = width + 130;
          stage.height(heightZoomIN);
          stage.width(widthZoomIn);
          this.setState({
            zoomScaleX: stageX + 0.1,
            zoomScaleY: stageY + 0.1,
            drawingEditorWidth: widthZoomIn,
            drawingEditorHeight: heightZoomIN,
          });
          stage.scale({ x: stageX + 0.1, y: stageY + 0.1 });
        }

**Comment by lavrton** [comment]
To what stage size do you scale? In general, it is better to keep the stage size as small as possible. Usually, it should be larger than the screen size.

**Comment by umeshdobai** [comment]
width near to 4683px and height to 1300px

**Comment by umeshdobai** [comment]
Initially canvas is taking from window innerHeight and innerWidth.

**Comment by lavrton** [comment]
That is large. Just try to keep it smaller. If you need scrolling take a look here: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html

**Comment by umeshdobai** [comment]
ok thank you
