### ISSUE TITLE
Wrong client rectangle for handwriting fonts

### ISSUE THREAD

**Issue by longlong88** [konvajs/react-konva#526]
Hi,

When I'm getting client rect of `Text` with one of the handwriting fonts `Pacifico`/`Homemade Apple`/`Charm`/`Coming Soon`, it returns incorrect height of the area. On the screenshot you can see that black pieces of the letters are out of red `Rect`, which has the size returned from `getClientRect` method of text element.
![image](https://user-images.githubusercontent.com/28686881/98448065-210add00-215c-11eb-994c-6b17a01ef642.png)

I need exact size, because I convert text to the image by `toDataURL` method of `Layer`, which converts area specified by this size. But because of the issue I'm getting image with cropped bottom and top parts of the text. Something like this:
![image](https://user-images.githubusercontent.com/28686881/98448391-3da81480-215e-11eb-9a08-b4ab0c2e1147.png)

Here is the sample to reproduce the issue
https://codesandbox.io/s/react-konva-text-size-forked-se4g1

**Comment by lavrton** [comment]
In the current moment, Konva can't detect the sizes of such text. Some fonts are crazy and can go out of default bounding boxes.

As a simple workaround, you can just add an additional padding size to the `getClientRect()` result. It may be different for different fonts.

As a complex workaround you can:
1. draw text into external canvas
2. get `imageData` of the canvas
3. Manually check every pixel to check the bounding box of the text
4. from pixels information calculate the correct size

**Comment by zakariamofaddel** [comment]
Thanks for this @lavrton! Is there a more viable solution these days? The complex solution would get quite expensive to run every time a user changes text/font.

**Comment by lavrton** [comment]
I don't have any. Probably `context.measureText()` from native 2d API may help you.

**Comment by zakariamofaddel** [comment]
Is there any particular reason why konva has chosen to ignore the ascent and descent data coming from the _context.measureText_ method when calculating the actual height and width of the text node?

**Comment by lavrton** [comment]
It is just not using them. The height of the text is defined by the font size. I don't think ascent and descent are affecting width.
