### ISSUE TITLE
Cropping sometimes inexact on Images when scale is applied to Stage

### ISSUE THREAD

**Issue by clavery63** [konvajs/react-konva#528]
Hi,

I am trying to render cropped regions of a small (56px x 56px) image to use as a font. I am also using `scale` on my Stage since I want the overall pixel resolution to be clamped at 240x256. I've made this scale responsive by listening to `resize` events. What I'm finding is, when the scale is at certain values, I'm seeing sub-pixel-sized artifacts around some of the characters. Other times it looks perfectly smooth. I can see this change as I adjust the viewport size.

Is there something else I can be setting to make sure the cropping remains exact? Or is there a better way to do what I'm trying to do here (I looked into Sprite, but that seemed more meant for animations)?

See below for screenshots and some code. I had trouble getting with working in a jsbin, but can figure that out if it would be helpful.

#### Spritesheet:
![alpha](https://user-images.githubusercontent.com/4368490/98708303-03ea3000-234f-11eb-9ed7-893cb7086a3d.png)
#### (almost) correct cropping (first column of characters are slightly off)
<img width="570" alt="Screen Shot 2020-11-10 at 11 10 19 AM" src="https://user-images.githubusercontent.com/4368490/98708393-17959680-234f-11eb-9923-27d2b4373c71.png">

#### incorrect cropping
<img width="578" alt="Screen Shot 2020-11-10 at 11 10 08 AM" src="https://user-images.githubusercontent.com/4368490/98708730-7fe47800-234f-11eb-94e9-8edc63a226c9.png">

### Code
```javascript
/// App.js

import React, { useRef, useEffect, useState } from 'react';
import { ReactReduxContext, Provider } from 'react-redux';
import { Stage, Layer } from 'react-konva';
import TextOverlay from './sections/textOverlay/TextOverlay';

const pixelWidth = 256;
const pixelHeight = 240;
const horizStretch = 1.1;
const aspectRatio = (pixelHeight / (pixelWidth * horizStretch));
const paddingFactor = 0.9;

const calculateSize = stageRef => {
  const { innerHeight, innerWidth } = window;
  const fullWidth = Math.min(innerHeight / aspectRatio, innerWidth);
  const width = fullWidth * paddingFactor;
  const height = width * aspectRatio;
  const left = (window.innerWidth - width) / 2;
  const top = (window.innerHeight - height) / 2;
  stageRef.current.content.style.left = `${left}px`;
  stageRef.current.content.style.top = `${top}px`;

  return width;
};

const App = () => {
  const stageRef = useRef(null);
  const layerRef = useRef(null);
  const [width, setWidth] = useState(0);
  const scale = width / pixelWidth;

  useEffect(() => {
    setWidth(calculateSize(stageRef));
    const resize = () => setWidth(calculateSize(stageRef));
    window.addEventListener('resize', resize);
    return () => window.removeEventListener('resize', resize);
  }, [stageRef]);

  useEffect(() => {
    layerRef.current.imageSmoothingEnabled(false);
  }, [layerRef]);

  return (
    <ReactReduxContext.Consumer>
      {({ store }) => (
        <Stage
          width={width}
          height={width * aspectRatio}
          scaleX={scale * horizStretch}
          scaleY={scale}
          ref={stageRef}
        >
          <Provider store={store}>
            <Layer ref={layerRef}>
              <TextOverlay />
            </Layer>
          </Provider>
        </Stage>
      )}
    </ReactReduxContext.Consumer>
  );
};

export default App;
```

```javascript
// TextOverlay.js

import React, { useEffect, useState } from 'react';
import { Image } from 'react-konva';
import alphaSrc from '../../../images/alpha.png';

const testStrs = [
  'Lorem ipsum dolor sit  ',
  'amet, consectetur',
  'adipiscing elit, sed',
  'do eiusmod'
];
const sheetWidth = 8;
const spriteWidth = 7;
const spriteHeight = 7;

const TextOverlay = () => {
  const [alphabet, setAlphabet] = useState(null);

  const top = 100;
  const left = 50;
  const shift = ' '.charCodeAt(0);
  const strs = testStrs.map(str => {
    const upper = str.toUpperCase();
    return upper.split('').map(char => char.charCodeAt(0) - shift);
  });

  useEffect(() => {
    const alphaImg = new window.Image();
    alphaImg.src = alphaSrc;
    setAlphabet(alphaImg);
  }, []);

  return (
    <>
      {strs.map((line, lineNumber) => {
        return line.map((code, charNumber) => (
          <Image 
            key={lineNumber * 1000 + charNumber}
            x={left + charNumber * (spriteWidth + 1)}
            y={top + lineNumber * (spriteHeight + 1)}
            width={spriteWidth}
            height={spriteHeight}
            image={alphabet}
            crop={{ 
              x: (code % sheetWidth) * spriteWidth,
              y: Math.floor(code / sheetWidth) * spriteHeight,
              width: spriteWidth, 
              height: spriteHeight 
            }}
          />
        ));
      })}
    </>
  );
};

export default TextOverlay;
```

Any help is much appreciated!

**Comment by lavrton** [comment]
The approach looks good to me.

But I need a demo. It will be simpler to use https://codesandbox.io/ for the demo.

**Comment by clavery63** [comment]
Thanks for the tip! Here's a sandbox link:

https://codesandbox.io/embed/intelligent-mayer-07rkw

It should be responsive but I also added a button to jump to an example size that causes a subtle example of the issue, at least for me on Chrome and Safari.

To be fair, it's hard to repro on desktop and I'm being a little nitpicky. However, on mobile it's much more apparent, per the comparison below)

<img width="1065" alt="Screen Shot 2020-11-10 at 3 14 41 PM" src="https://user-images.githubusercontent.com/4368490/98729511-078ab080-2369-11eb-96e0-6b5d914d02fe.png">

**Comment by lavrton** [comment]
I see it. Looks like it is a WebKit bug (or just a specific behavior with its internal rounding). It was working ok for me in FF.

I don't think we can do anything here from the `Konva` side. As a solution I suggest:

1. Draw every character into a separate small external canvas. (So you have many canvases in the memory)
2. Instead of Image with a crop, just find the correct canvas for a symbol and use it for `<Image />`.

**Comment by clavery63** [comment]
OK, thanks. I'll give that a shot
