### ISSUE TITLE
space between components

### ISSUE THREAD

**Issue by toreal** [konvajs/react-konva#529]
When there are a space between the components, here will have the error.
Invariant Violation
Text components are not supported for now in ReactKonva. You text is: " "

for example:
```
<Stage >
<Layer>
<Text  text="weird" /> 
</Layer> </Stage>  
```

 I put a space between `</Layer> </Stage>` then the error will happen.

**Comment by lavrton** [comment]
This is how `jsx` works.  And `react-konva` can't render a space. Just don't put spaces between them.
