### ISSUE TITLE
Remove react-dom from peer dependencies

### ISSUE THREAD

**Issue by fbessou** [konvajs/react-konva#531]
Hi there :)
It seems that `react-dom` is not used inside 'react-konva'. Is there a reason to keep it as a peer dependency ?
I think we shouldn't have to depend on react-dom when writing a library which uses react and react-konva but doesn't render anything.
Currently, when installing dependencies of such a library we get the following warning:
```
warning " > react-konva@16.13.0-0" has unmet peer dependency "react-dom@16.13.x".
```

**Comment by lavrton** [comment]
`react-konva` is still using `react-dom`. Not directly, but the `Stage` component is a `react-dom` target.

What `react-dom` version do you have?

**Comment by fbessou** [comment]
I am authoring a react library and I currently don't add react-dom as a dependency in order to let the client application choose which rendering library it uses. I didn't want to force them to use `react-dom` (one could use preact for example).
Nevertheless, it seems that adding `react-dom` as peer dependency is quite common in libraries (react-bootstrap, react-modal and others do that too).
You can close this issue as it may not worth doing any change. :)
