### ISSUE TITLE
Resize text with tag

### ISSUE THREAD

**Issue by otaviosoares** [konvajs/react-konva#532]
I'm trying to resize a text and I expect the tag to follow. It works perfectly when resizing the x axis, but the y only works after the 2nd attempt, or after I resize the x again. Am I missing something?

![UmKVaXMHoJ](https://user-images.githubusercontent.com/180912/100144443-a32d1e00-2e4b-11eb-9560-7e349f540436.gif)

code: https://codesandbox.io/s/react-konva-text-transformation-jj975?file=/src/App.js

**Comment by lavrton** [comment]
Looks like `Label` is not synching height changes of a text. The current workaround is to resync manually:
```
  React.useLayoutEffect(() => {
    shapeRef.current._sync();
    if (isSelected) {
      trRef.current.nodes([shapeRef.current]);
      trRef.current.getLayer().batchDraw();
    }
    shapeRef.current.getLayer().draw();
  }, [isSelected, shapeProps]);
```

https://codesandbox.io/s/react-konva-text-transformation-forked-behnz?file=/src/App.js

**Comment by lavrton** [comment]
Fixed it from the konva side. The fix will be released later with the `konva` package.
