### ISSUE TITLE
show DOM elements on Konva

### ISSUE THREAD

**Issue by xhy279** [konvajs/react-konva#537]
I got a similar problem here. Need to show multiple popovers triggered by image click on top of react konva. Any advice? Appreciate!
I tried the solution provided here https://konvajs.org/docs/react/DOM_Portal.html

How do I not to use the absolute position there. Because for my scenario, i need to render multiple elements and position is dynamically rendered using  .map. 

My code looks something like this:
```code
<Portal>
    <Popover placement="topLeft" title={text} content={content} trigger="click">
          <Image
            image={image}
            x={x}
            y={y}
            key={item.id}
            width={100}
            height={100}
          />
     </Popover>
</Portal>
```
_Originally posted by @xhy279 in https://github.com/konvajs/react-konva/issues/430#issuecomment-742984880_

**Comment by lavrton** [comment]
What is the `<Popover />` element in your example? DOM element?

You can't mix DOM elements like `<Portal />` with konva nodes like `<Image />`.

And I don't see what is the issue with absolute position.

**Comment by xhy279** [comment]
> What is the `<Popover />` element in your example? DOM element?
> Here is the link for `<Popover/>` : https://ant.design/components/popover/#header

> You can't mix DOM elements like `<Portal />` with konva nodes like `<Image />`.
> 

> And I don't see what is the issue with absolute position.
> The problem here for my scenario is we are rendering multiple images which wrapped by konva <Image /> and their position are dynamically located  using a .map.

**Comment by lavrton** [comment]
> The problem here for my scenario is we are rendering multiple images which wrapped by konva  and their position are dynamically located using a .map.

So what is the problem? Can you make a demo?
