### ISSUE TITLE
Help in a query

### ISSUE THREAD

**Issue by Adarsh1999** [konvajs/react-konva#538]
Hi,
I am recently given a task **Remove white background from a product pic on Konvajs** by my company and I am very new to konva just know the basic working so I don't know where to start with.
Basically, I thought that this is a work of semantic segmentation in the backend but actually I have to do it in frontend.
So can anybody help me find the solution...?

**Comment by lavrton** [comment]
For those use cases, you can write a custom filter. For a demo take a look here: https://konvajs.org/docs/filters/Custom_Filter.html#page-title

You can detect white color in `imageData` and remove it (set the opacity to 0). It may be harder to detect if a white pixel is a background or a part of the product picture. But it is out of `konva` and `react-konva` scope.
