### ISSUE TITLE
Custom filter 

### ISSUE THREAD

**Issue by Adarsh1999** [konvajs/react-konva#539]
I was trying to follow your example (https://konvajs.org/docs/filters/Custom_Filter.html#page-title) but in react so when I was implementing here [codesandbox](https://codesandbox.io/s/wizardly-wildflower-98nku?file=/src/index.js) but thing didn't work like the transparency of the image didn't gone away as expected so what am I missing?

**Comment by lavrton** [comment]
In order to use filters, you have to cache image node. For demo see: https://konvajs.org/docs/react/Filters.html

Your example, but fixed: https://codesandbox.io/s/dazzling-https-9z9z7?file=/src/index.js

Also, I think your image in the example doesn't have transparent pixels.
