### ISSUE TITLE
Using useReducer in Context to fetch data in canvas is not working

### ISSUE THREAD

**Issue by teetl6** [konvajs/react-konva#540]
Hi

I'm trying to use context data (which is fetched using useReducer) in my canvas but nothing seems to be working.

I'm wrapping <Layer> component again in provider as pointed out in documentation but it doesn't seem to be working when data is in reducer in context.Some of my code.

This is outside of the component>
```jsx

const measurement = {
  measurement: null,
  loaded: false,
}

export const reducer = (state, action) => {
  switch (action.type) {
    case 'FETCH':
      console.log('fetch', state, action)
      return { ...state, measurement: action.payload, loaded: true }
    default:
      return state
  }
}

```

This is provider code>
```jsx
return (
    <MeasurementContext.Provider
      value={{
        state, 
        dispatch
      }}
    >
      {children}
    </MeasurementContext.Provider>
  )
```

And this is inside of the component I'm rendering (also parent component is wrapped inside Provider). All other components are getting data properly, before using reducer, data was also fetched properly but there's something wrong when using reducer:
```jsx
return(
      <div>
            <Stage draggable="true">
            <MeasurementProvider>
              <Layer>
                {
                  canvas.visible.logs && 
                  <Logs 
                    logs={measurement.state.measurement.attributes.logs} 
                  />
                }
              </Layer>
            </MeasurementProvider>
          </Stage>
      </div>
    )
```

Is there possibility that when fetching data through useReducer in Context, there should be something done differently?

**Comment by lavrton** [comment]
Can you make a small online demo, please?

**Comment by teetl6** [comment]
Well that's strange, when i rewrite code in sandbox, it works in my opinion. Probaly some dataflow is erroreus in my project.

Here is example how I used it, hopefully it helps someone else to use:
https://codesandbox.io/s/konva-react-reducer-pp3e6
