### ISSUE TITLE
Video in react-conva

### ISSUE THREAD

**Issue by Adarsh1999** [konvajs/react-konva#541]
Hi,
I am given a task : **show this video https://www.youtube.com/watch?v=l0eEqeizNCA and display Happy Birthday text at 10s and Cadbury logo (transparent) from 20s to 40s.**
So I found your example: https://codesandbox.io/s/react-konva-video-on-canvas-oygvf?file=/src/index.js
but I don't know how to add Happy birthday and cadbury logo at the that particular time duration.
Is it possible to do that in Konva?

**Comment by lavrton** [comment]
It may be hard to inject a youtube video directly into the canvas.

You can place a youtube video and canvas stage on top of it with absolute position.
Use some youtube player API (or probably direct DOM video API) to access the current time of the video. If a time passed some time limits - draw what you need on canvas.
