### ISSUE TITLE
Draggable Rect with Children

### ISSUE THREAD

**Issue by rahulrentash** [konvajs/react-konva#544]
Hi all,

To start, I LOVE react-konva. But, I'm really new and struggling to do something very basic. I posted a SO: https://stackoverflow.com/questions/65415385/konva-draggable-rect-with-children

Basically, I just want to add children to a draggable rect. I'm sure that there exists this functionality, but I can't find anything about it online. Thanks!

**Comment by lavrton** [comment]
Answered in SO.
