### ISSUE TITLE
dynamically obtain the relative canvas position

### ISSUE THREAD

**Issue by codcer** [konvajs/react-konva#547]
In React-konva, how to dynamically obtain the relative canvas position？

**Comment by lavrton** [comment]
What is "relative canvas position"? Why do you need it?

**Comment by codcer** [comment]
After zooming, the canvas will be shifted again

**Comment by codcer** [comment]
after the stage is zoomed, the position of the mouse in the stage;

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html
