### ISSUE TITLE
React konva dynamic call Layer.add report errors

### ISSUE THREAD

**Issue by codcer** [konvajs/react-konva#548]
![image](https://user-images.githubusercontent.com/7337505/103882342-9d974900-5116-11eb-8c62-8b2230c13bed.png)
![image](https://user-images.githubusercontent.com/7337505/103882701-2ada9d80-5117-11eb-9760-9736186f233e.png)

**Comment by lavrton** [comment]
Can you make an online demo?

**Comment by codcer** [comment]
The error is version3.2.5 question!
