### ISSUE TITLE
Base64 Video

### ISSUE THREAD

**Issue by dhwalin** [konvajs/react-konva#549]
How can I draw video with base64 string?

When I try to draw with <Image> I cannot see the video on canvas.

I have base64 string with “data:video/mp4,”

**Comment by lavrton** [comment]
How do you do it?

**Comment by lavrton** [comment]
I am not sure it is a good idea to store video in base64.

**Comment by dhwalin** [comment]
I am using Konva with ReactJS and ionic to develop the iOS App.  In iOS, every image layer need to be added from same URL otherwise it won't change canvas to DataURL.

So I marge images by converting them to base64 and it is running successfully.

Same thing I want to do it with video. So just a question that can I give value of src as base64 string of video in below code?

```
const videoElement = React.useMemo(() => {
    const element = document.createElement("video");
    element.src = src;
    return element;
  }, [src]);
```
As per your example: https://codesandbox.io/s/react-konva-video-on-canvas-oygvf?file=/src/index.js:383-534

**Comment by lavrton** [comment]
Did you try it?

**Comment by dhwalin** [comment]
I didn't try as per your example but with my code, it is not working.

I will comment tomorrow with your example code and will give you an update.

I thought if anyone has tried then I could feel confident.

I will comment soon.

**Comment by dhwalin** [comment]
I have tested.

```
const Video = ({ src }) => {
  const imageRef = React.useRef(null);
  const [size, setSize] = React.useState({ width: 50, height: 50 });

  // we need to use "useMemo" here, so we don't create new video elment on any render
  const videoElement = React.useMemo(() => {
    const element = document.createElement("video");
    element.src = src;
    return element;
  }, [src]);

  // when video is loaded, we should read it size
  React.useEffect(() => {
    const onload = function() {
      setSize({
        width: videoElement.videoWidth,
        height: videoElement.videoHeight
      });
    };
    videoElement.addEventListener("loadedmetadata", onload);
    return () => {
      videoElement.removeEventListener("loadedmetadata", onload);
    };
  }, [videoElement]);

  // use Konva.Animation to redraw a layer
  React.useEffect(() => {
    videoElement.play();
    const layer = imageRef.current.getLayer();

    const anim = new Konva.Animation(() => {}, layer);
    anim.start();

    return () => anim.stop();
  }, [videoElement]);

  return (
    <Image
      ref={imageRef}
      image={videoElement}
      x={20}
      y={20}
      stroke="red"
      width={size.width}
      height={size.height}
      draggable
    />
  );
};
```

I have defined this and try to draw video with react-konva:

```
const CreateVideo: React.FC = () => {

return(

<Stage width={imageWidth*scaleState} height={stageHeight*scaleState} scaleX={scaleState} scaleY={scaleState} ref={stageRef}>

          <Layer>
          <Video src={bgImgUrl} />
          </Layer>

</Stage>

)

}
```
Two things I have noticed:
1. Video start playing but not in canvas. It starts play on full screen with native video player.
2. Only one of random thumbnail of Video is getting drawn on Canvas.

**Comment by lavrton** [comment]
So as I understand in general it works.


> Then when I try to save that canvas by converting to dataURL, its saving as still image. Not video.

Canvas export can only save images. It is not supposed to save videos. If you need a video, you may try to generate it from several exported images.
