### ISSUE TITLE
Usage with ReactDOMServer.renderToStaticMarkup()

### ISSUE THREAD

**Issue by rasgo-cc** [konvajs/react-konva#550]
Hello,

I'm currently trying to get the HTML that react produces through `ReactDOMServer.renderToStaticMarkup` and for some reason I can't see the Konva/Stage on the output. The `<canvas>` is there but the `<div>` element surrounding my `<Stage>` is completely empty. There's no `<div class="konvajs-content>`

I'm assuming react is (statically) rendering the first thing it sees and that Konva somehow takes more time than that to render things on the canvas. Does this make any sense? Any idea why this is happening? 

To be a bit more precise, I'm doing something like this:
```jsx
    const html = ReactDOMServer.renderToStaticMarkup(
      React.cloneElement(
        <ComponentThatRendersKonva />
      )
    );
```

Edit: 
https://github.com/konvajs/react-konva/blob/master/src/ReactKonvaCore.js#L46

Maybe this explains it? Konva is rendered only after the react component is mounted, so too late for the `renderToStaticMarkup`?

**Comment by lavrton** [comment]
That is correct behavior.

`ReactDOMServer` is rendering HTML string. Canvas drawing can't be part of the HTML.

**Comment by armand1m** [comment]
Check https://github.com/konvajs/react-konva/issues/572 for a solution
