### ISSUE TITLE
Testing with mount() the drag&drop of Konvajs elements

### ISSUE THREAD

**Issue by steinhardt21** [konvajs/react-konva#551]
Hello Anton,

First of all compliments for the amazing library that you created!

I am using konvajs for a Reactjs project inside my company and I encountered some issues in testing the Konvajs elements.
So, I build this test: 
```
it('check the connectionsUpdate callback - called correctly 1 time', () => {
  const xCoordinateStart = 50
  const yCoordinateStart = 50
  const xCoordinateEnd = 55
  const yCoordinateEnd = 55 
 const App = () => {
    return (
      <Stage height={300} width={300}>
        <Layer>
            <ExternalComponent {...props} />
        </Layer>
      </Stage>
    )
  }
mount(<App />)
const stage = Konva.stages[Konva.stages.length - 1]
dragElement(stage, xCoordinateStart, yCoordinateStart, xCoordinateEnd, yCoordinateEnd)

expect(stage.findOne('Group').isDragging()).toBe(true)
  expect(props.connectionsUpdate).toHaveBeenCalledTimes(1)
})
```

As you can see I use mount() from 'enzyme' library as you use it here https://github.com/konvajs/react-konva/blob/master/tests/index-test.js.

However, when I run the test I continue to have this error that is generated by mount() in fact the same error appears in other test where I use mount() with Konvajs elements: 
` console.error
      Warning: It looks like you're using the wrong act() around your test interactions.
      Be sure to use the matching version of act() corresponding to your renderer:
      
      // for react-dom:
      import {act} from 'react-dom/test-utils';
      // ...
      act(() => ...);
      
      // for react-test-renderer:
      import TestRenderer from react-test-renderer';
      const {act} = TestRenderer;
      // ...
      act(() => ...);`

Can you please help me with this problem?

**Comment by steinhardt21** [comment]
Sorry for the formating of the code in the first part but github is giving me problems

**Comment by lavrton** [comment]
Can you make a small demo where I can reproduce the issue? Do tests work for you and you just have a warning?

**Comment by DarkBitz** [comment]
@steinhardt21 how do you solve this problem? I have the same warning with react testing library :(

**Comment by steinhardt21** [comment]
No, I forgot to update this thread
