### ISSUE TITLE
【Question】How to draw a mjpeg Image on a layer?

### ISSUE THREAD

**Issue by tomofu74** [konvajs/react-konva#552]
I tried to draw mjpeg with sample of simple way. 
https://konvajs.org/docs/react/Images.html

But it is a still image. I don't know how to draw mjpeg live movie. Would you show me a sample of draw mjpeg on a layer?

Then, I draw some lines on other layer. I want to overlap a lines layer on the mjpeg image layer.

**Comment by lavrton** [comment]
Did you look here: https://konvajs.org/docs/sandbox/Video_On_Canvas.html#page-title ?

**Comment by tomofu74** [comment]
Thank you, Iavrton, and sorry to late to reply.
I would try to treat a ip-camera's streaming mjpeg, that is a consecutive jpeg image. I had not look that sample. Then, I found your message "You may need to use some server side solutions to create such video. You can export each frame into image, and then combine these images into video file." in that sample.

 You say that I should redraw the canvas image with layer anim, isn't that?

Kind regards,

**Comment by lavrton** [comment]
> You say that I should redraw the canvas image with layer anim, isn't that?

Yes. Using `Konva.Animation` or other ways to constantly redraw a layer.

**Comment by tomofu74** [comment]
OK, I got it. I also could refer to your another sample.
https://stackoverflow.com/questions/59741398/play-video-on-canvas-in-react-konva

Next, I have to learn and master 'React.useRef (null)'. What exactly is this? Why I can not use 'videoElement' for <Image ref>?

Great thanks, lavrton!

```
const Video = ({ src, _x, _y, _width, _height }) => {
  const imageRef = React.useRef(null);
  const [size] = React.useState({ x: _x, y: _y, width: _width, height: _height, });

  // we need to use "useMemo" here, so we don't create new video elment on any render
  const videoElement = React.useMemo(() => {
    // mjpeg is drawn on a <img> element.
    const element = document.createElement("img");
    element.src = src;
    return element;
  }, [src]);

  // use Konva.Animation to redraw a layer
  React.useEffect(() => {
    const layer = imageRef.current.getLayer();

    const anim = new Konva.Animation(() => {}, layer);
    anim.start();

    return () => anim.stop();
  }, [videoElement]);

  return (
    <Image
      ref={imageRef}
      image={videoElement}
      x={size.x}
      y={size.y}
      width={size.width}
      height={size.height}
    />
  );
};
```
