### ISSUE TITLE
Browser support: Issues in Firefox

### ISSUE THREAD

**Issue by kondulak10** [konvajs/react-konva#553]
Are there any browser specific guidelines or reported performance issues?

Test page: https://mapheim.com/pure/custom/mafia-125299

Chrome, Safari, Edge: Perfect performance (Both on PC and mobile)
Firefox: Unusable (while zooming)

This visualization is only draggable Stage, Layers and Images with click / pinch / zoom handlers.

**Comment by lavrton** [comment]
Try to run the profiler and see what is slow. Will it be slow with lower `pixelRatio`?
I am not sure were can do much here from the framework side.

**Comment by kondulak10** [comment]
![Profiler](https://user-images.githubusercontent.com/2103269/107835045-6d3b6e00-6d98-11eb-9c2d-56f505301c5c.PNG)

The frames while zooming drop to 1fps, is there anything I can debug it more?
Pixelratio is default to 1

**Comment by lavrton** [comment]
Try the "call tree" view and see what exactly is slow.

**Comment by kondulak10** [comment]
![image](https://user-images.githubusercontent.com/2103269/107851559-36527000-6e0b-11eb-9684-071c44ed8099.png)
Thanks, Well I guess only thing I can try is to start removing features and find out which one is problematic

**Comment by lavrton** [comment]
AS I can see "Tools" are eating all the resources. I don't know what is that. Probably some firefox internals for `getImageData()` function. Need to find that.

**Comment by kondulak10** [comment]
I think I am not able to solve that, so will try pure canvas instead

**Comment by kondulak10** [comment]
The issue was fixed!
I have no idea why, but removing the <Image> Rendering in the same component as <Layer> and <Stage>, and using another Wrapper for <Image> rendering in its own component seems to solve it.
![image](https://user-images.githubusercontent.com/2103269/108604937-2f9a9e80-73b1-11eb-9985-119c33054b5a.png)

**Comment by lavrton** [comment]
I can tell you why. Never define components (such as `MapImage`) inside render function. It creates a new function so Reac thinks it is a very different component, so it is doing a lot of extra work.

**Comment by kondulak10** [comment]
I see, okey thank you, then it is solved.
