### ISSUE TITLE
Konva free drawing & adding shapes/images in the same time

### ISSUE THREAD

**Issue by amer-yousuf** [konvajs/react-konva#554]
Thanks for this cool library!

Please, is there any way to support both free drawing (by accessing the native 2d canvas context) and adding shapes/images, and keep the order/index of them reflect the adding/drawing time?

I'm using the manual method to access the native 2d canvas context, by creating a new canvas element manually and then use it for Knova.Image to access the context. This allows me to draw some advanced brushes (not only simple lines) like spray, long fur, ribbon... etc. (like the ones in the attached screenshot)

At the same time, I'm using the konva to add shapes/images to the layer.

The problem in this approach is that the free drawing is always on the bottom even if I draw it after adding some shapes, and the shapes are always on top even if they added before I draw something, because the image/layer that I'm using the context of it to do the free drawing is added while initializing the stage and layer (has a z-index smaller than the newly added shapes).

![image](https://user-images.githubusercontent.com/44733554/107127524-b3d82680-68c7-11eb-9fe4-cc6a4a202a16.png)

**Comment by lavrton** [comment]
There are several ways.

1. Use the vector approach from the free drawing. Instead of using `Konva.Line` you can create your own custom shape and access native 2d canvas API there. You only need to remember to write a custom hit function.

2. Use a separate canvas element (Konva.Image) for every drawing.  It may consume too much memory.

**Comment by amer-yousuf** [comment]
Thanks for your reply,

After posting this issue, I tried the second approach, by assigning one layer for drawing (always on top, with listening off), and another one for containing all the elements inside. After each drawing (on mouseup) I'm moving the drawn area to the second layer (as a Konva.Image) to arrange it with other elements (it will take the higher index), and then clean the drawing canvas to accept the new drawing.

This approach worked to achieve the requirement, but it consumes (as you said) too much memory!

Regarding the first approach:
- Do you mean to create a custom shape for each brush, or one custom shape just for accepting drawing?
- Are there any tutorials or links that help in creating custom shapes to draw while moving the mouse and have a custom hit function?

Thanks in advance.

**Comment by lavrton** [comment]
> Do you mean to create a custom shape for each brush, or one custom shape just for accepting drawing?

A new shape for each brush.

> Are there any tutorials or links that help in creating custom shapes to draw while moving the mouse and have a custom hit function?

No much.
Drawing: https://konvajs.org/docs/shapes/Custom.html#page-title
Hit: https://konvajs.org/docs/events/Custom_Hit_Region.html

On mousemove, you should add a new point into a custom attributes `points` of a custom shape. Then in sceneFunc you just drawing your custom brush from all points.

**Comment by amer-yousuf** [comment]
Ok thanks, I will give it a try with this approach.

**Comment by MentalGear** [comment]
> Ok thanks, I will give it a try with this approach.

Hey @ameryousuf I have the same issue. May I ask how it went with the direct 2 canvas drawing approach for brushes? Is there maybe even a demo of your approach available somewhere?
