### ISSUE TITLE
It doesn't work smoothly on mobile device.

### ISSUE THREAD

**Issue by ats1999** [konvajs/react-konva#555]
Open this link https://dsa.bdevg.com/animation/linear-search on a mobile device, and scroll the page. You can clearly see the delay in scrolling.

**Comment by lavrton** [comment]
By default, konva prevents default behavior (like scrolling) when you interact with shapes. If you want to enable it back do this:

```js
shape.preventDefault(true);
```

https://konvajs.org/api/Konva.Node.html#preventDefault

**Comment by ats1999** [comment]
I am using the `Stage, Layer, Rect and Text` component of `react-konva`. I don't see any way in docs to get access to shape and use `shape.preventDefault(true)`.

**Comment by lavrton** [comment]
`<Rect preventDefault />`
