### ISSUE TITLE
Adding Layer fire mouseLeave event

### ISSUE THREAD

**Issue by lalop** [konvajs/react-konva#556]
I created a sandbox to explain this issue https://codesandbox.io/s/crazy-kepler-2t38f?file=/src/index.js
I add a layer when the mouse enter on the stage but this fire a mouseleave event so this is looping how you can see

**Comment by lavrton** [comment]
That is interesting. And looks like a bug. As a workaround just use the same number of layers.

**Comment by lalop** [comment]
It's what I do actually in the project

**Comment by lavrton** [comment]
Fixed with `konva@7.2.4`. https://codesandbox.io/s/dreamy-sutherland-p096y?file=/package.json:183-188
