### ISSUE TITLE
while dragging a shape no mousemove event are fired

### ISSUE THREAD

**Issue by lalop** [konvajs/react-konva#557]
As you can see here https://codesandbox.io/s/misty-sound-4kpjb?file=/src/index.js I listen mouseMove on stage and log the pointer position but when I drag the rect no mouseMove event are fired

**Comment by lavrton** [comment]
It is a performance optimization and default behavior of Konva. If you want to disable that you can do this:

```js
import Konva from "konva";

Konva.hitOnDragEnabled = true;
```

https://codesandbox.io/s/mystifying-fire-i63w3?file=/src/index.js

**Comment by lalop** [comment]
ok, thank you
