### ISSUE TITLE
Error Image getting state value to rerender

### ISSUE THREAD

**Issue by juanda99** [konvajs/react-konva#558]
I have an image inside a grid. 
I would like the image to be draggable but just inside grid lines (fixed positions).
Image has [x,y] positions.  It works ok when I move the image to new [x,y] coordinates,  but if x or y does not change, for example moving the image vertically or horizontally, the image is not right positioned.

https://codesandbox.io/s/admiring-dew-hpojb?file=/src/App.js

**Comment by lavrton** [comment]
By default `react-konva` skips updating props, if they are not changed. With such snaps there is a high chance that `x` or `y` will not change on dragend.

There are two solutions:
1. Update the state of the app on `dragmove` event (without snapping). And then snap on dragend
2. Or use strict mode to force properties. https://github.com/konvajs/react-konva#strict-mode
