### ISSUE TITLE
Ellipse transformer event....??

### ISSUE THREAD

**Issue by daekyocnslab** [konvajs/react-konva#559]
If you change the size, it will be greatly enlarged or reduced.
Do you have anything to fix?

`
          import React from 'react';
          import { Ellipse, Circle, Transformer } from 'react-konva';
          import clamp from "clamp";
          
          const CircleComponent = ({  shapeProps, tool, isSelected, onSelect, onChange, toolboxUse }) => {
            const shapeRef = React.useRef();
            const trRef = React.useRef();
          
            React.useEffect(() => {
              if (tool == "cursor" && isSelected && toolboxUse) {
                trRef.current.nodes([shapeRef.current]);
                trRef.current.getLayer().batchDraw();
              }
            }, [isSelected]);
          
            return (
              <React.Fragment>
                <Ellipse
                  onClick={onSelect}
                  onTap={onSelect}
                  ref={shapeRef}
                  strokeScaleEnabled={false}
                  {...shapeProps}
                  draggable={tool == "cursor" && toolboxUse}
                  onDragEnd={(e) => {
                    onChange({
                      ...shapeProps,
                      x: e.target.x(),
                      y: e.target.y(),
                    });
                  }}
                  onTransformEnd={(e) => {
                    const node = shapeRef.current;
          
                    let radiusX = Math.floor(node.width() * node.scaleX() / 2);
                    let radiusY = Math.floor(node.height() * node.scaleY() / 2);
          
                    let param = {
                      fill: shapeProps.fill,
                      id: shapeProps.id,
                      key: shapeProps.key,
                      regId: shapeProps.regId,
                      scaleX: 1,
                      scaleY: 1,
                      stroke: shapeProps.stroke,
                      strokeWidth: shapeProps.strokeWidth,
                      tool: shapeProps.tool,
                      x: node.x(),
                      y: node.y(),
                      rotation : node.attrs.rotation,
                      radiusX : radiusX,
                      radiusY : radiusY,
                      width : node.width(),
                      height : node.height()
                    };
          
                    console.log(param);
                    onChange(param);
                  }}
                />
                {tool == "cursor" && isSelected && toolboxUse && (
                  <Transformer
                    ref={trRef}
                    centeredScaling={true}
                    boundBoxFunc={(oldBox, newBox) => {
                      console.log(oldBox);
                      console.log(newBox);
                      // if (newBox.width > 200) {
                      //   return oldBox;
                      // }
                      return newBox;
                    }}
                  />
                )}
              </React.Fragment>
            );
          };
          
          export default CircleComponent;

`

https://user-images.githubusercontent.com/36141397/108816214-1dab3c80-75f9-11eb-9715-af97bd01a8e2.mp4

**Comment by lavrton** [comment]
You have this effect because size change is applied twice: (1) transformer is changing scale attribute and (2) you apply scale changes back to radius attribute.

Even when you specify `scaleX: 1, scaleY: 1,` in your `params`, the actual value of scale will be not `1`, because by default `react-konva` updates only changed from render properties. `scaleX` and `scaleY` are not changed in render props (they were `1` and new value still `1`). But the node itself will have scale !== 1, because it is changed by Transformer. 

There are two solutions:

1. Manually force update scale of the node to 1: `node.scale({ x: 1, y: 1})` inside `onTransformEnd`.
2. Or use `strictMode` to force all properties from render to node even if they are not changed: https://github.com/konvajs/react-konva#strict-mode

**Comment by daekyocnslab** [comment]
@lavrton 
Thank you for answer.

I tried applying the solution
[1. Manually force update scale of the node to 1: node.scale({ x: 1, y: 1}) inside onTransformEnd.]
The same thing happens. Is there anything else I need to fix?
Or is there an example I can check?

Data flow chart
1. transform => params data init => onChange Evnet => api => mongodb insert
- save
2. front => api => mongodb select => front => react-konvajs init data
- load
3. example data
- params =>
fill: "rgba(0, 0, 0, 0)"
height: 204
id: "circle0"
key: "mingiki1"
radiusX: 187
radiusY: 101
regId: "mingiki"
rotation: 0
scaleX: 1
scaleY: 1
stroke: "#000"
strokeWidth: 4
tool: "circle"
width: 356
x: 620.5217011030594
y: 261.3250357500233

- boundBoxFunc newBox =>
height: 207.9999999999999
rotation: 0
width: 380
x: 431.5217011030595
y: 158.32503575002335



`
      import React from 'react';
      import { Ellipse, Circle, Transformer, useStrictMode } from 'react-konva';
      import clamp from "clamp";
      
      
      const CircleComponent = ({  shapeProps, tool, isSelected, onSelect, onChange, toolboxUse }) => {
        const shapeRef = React.useRef();
        const trRef = React.useRef();
       
      
        React.useEffect(() => {
          if (tool == "cursor" && isSelected && toolboxUse) {
            trRef.current.nodes([shapeRef.current]);
            trRef.current.getLayer().batchDraw();
          }
        }, [isSelected]);
      
        return (
          <React.Fragment>
            <Ellipse
              onClick={onSelect}
              onTap={onSelect}
              ref={shapeRef}
              strokeScaleEnabled={false}
              // _useStrictMode
              {...shapeProps}
              draggable={tool == "cursor" && toolboxUse}
              onDragEnd={(e) => {
                onChange({
                  ...shapeProps,
                  x: e.target.x(),
                  y: e.target.y(),
                });
              }}
              onTransformEnd={(e) => {
                const node = shapeRef.current;
      
                let radiusX = Math.floor(node.width() * node.scaleX() / 2);
                let radiusY = Math.floor(node.height() * node.scaleY() / 2);
      
                let param = {
                  fill: shapeProps.fill,
                  id: shapeProps.id,
                  key: shapeProps.key,
                  regId: shapeProps.regId,
                  stroke: shapeProps.stroke,
                  strokeWidth: shapeProps.strokeWidth,
                  tool: shapeProps.tool,
                  scaleX: 1,
                  scaleY: 1,
                  x: node.x(),
                  y: node.y(),
                  rotation : node.attrs.rotation,
                  radiusX : radiusX,
                  radiusY : radiusY,
                  width : node.width(),
                  height : node.height()
                };
      
                onChange(param);
      
                node.scale({ x: 1, y: 1});
              }}
            />
            {tool == "cursor" && isSelected && toolboxUse && (
              <Transformer
                ref={trRef}
                // centeredScaling={true}
                boundBoxFunc={(oldBox, newBox) => {
                  // if (newBox.width < 5 || newBox.height < 5) {
                  //   return oldBox;
                  // }
                  return newBox;
                }}
              />
            )}
          </React.Fragment>
        );
      };
      
      export default CircleComponent;



`


https://user-images.githubusercontent.com/36141397/108931655-54319780-768b-11eb-98dc-a45b19837284.mp4

**Comment by lavrton** [comment]
Can you please make a small codesandbox demo?

**Comment by daekyocnslab** [comment]
@lavrton 

Demo site here

https://codesandbox.io/s/elastic-edison-7ps4d?file=/src/component/CircleComponent.js

**Comment by lavrton** [comment]
I see the issue.

```js
width : node.width(),
height : node.height()
```

Do not specify width/height for an ellipse. It is a duplication from `radiusX` and `radiusY`. And looks like it produces conflict in attributes settings. 

Fixed version: https://codesandbox.io/s/sleepy-cloud-7h8lh?file=/src/component/CircleComponent.js

**Comment by daekyocnslab** [comment]
@lavrton 

Thank you you are a genius
