### ISSUE TITLE
[Question] Draw shapes in real time

### ISSUE THREAD

**Issue by roshansachan** [konvajs/react-konva#560]
Is there a way to draw shapes in real-time? Instead of dropping the rectangle with predefined width and height, can we draw a shape as the user drags the mouse on canvas?

https://user-images.githubusercontent.com/4952904/109599658-905c7080-7b41-11eb-9663-19d4b2054e97.mov

**Comment by lavrton** [comment]
Yes. It is easily possible. What did you try?

**Comment by roshansachan** [comment]
I got the idea of how to implement this from the selectable rectangle in   https://konvajs.org/docs/select_and_transform/Basic_demo.html .  Thanks for putting up the example. 
It works well. However, I am unable to get the correct coordinates while I am zoomed in. I guess I will have to change the x and y. Any idea?

https://user-images.githubusercontent.com/4952904/109809538-66dd3b00-7c4e-11eb-947c-b1937d276155.mov

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html

**Comment by roshansachan** [comment]
Thanks. It worked.
```
const relativePointerPosition = getRelativePointerPosition(currentStageRef);
const updatedShape = {
	...selectedShape,
	x: Math.min(liveDrawingCoordinates.x1, relativePointerPosition.x),
	y: Math.min(liveDrawingCoordinates.y1, relativePointerPosition.y),
	width: Math.abs(relativePointerPosition.x - liveDrawingCoordinates.x1),
	height: Math.abs(relativePointerPosition.y - liveDrawingCoordinates.y1)
};

const getRelativePointerPosition = (node) => {
        const transform = node.getAbsoluteTransform().copy();
        // to detect relative position we need to invert transform
        transform.invert();
        
        // get pointer (say mouse or touch) position
        const pos = node.getStage().getPointerPosition();
        
        // now we can find relative point
        return transform.point(pos);
};
```
