### ISSUE TITLE
How to add React SVG Components inside react-konva

### ISSUE THREAD

**Issue by jide07** [konvajs/react-konva#562]
From this example https://konvajs.org/docs/react/Shapes.html , it says we can use SVG Path to draw inside the Layer, However what I'm trying to accomplish is to Add a React SVG components inside the layer, i tried doing so here [https://codesandbox.io/s/inspiring-lumiere-ut6oe?file=/src/index.js](url) with no success yet.

**Comment by lavrton** [comment]
`react-konva` can't render SVG directly into the canvas. You can use `<Path />` component to render SVG path data: https://konvajs.org/docs/shapes/Path.html

If you want full SVG you have two ways:
1. Display it on top of the stage with absolute position
2. Or generate svg string, convert it into base64 URL, use that URL to draw as an `<Image />`.

**Comment by jide07** [comment]
Hi @lavrton 
I have been able to use svg image on the Konva Layer,  however i'm stuck and need some ideas on how to proceed.
so i have to svg images on Konva layer, what i want is when i drag the content on top of the images, i want to display information on the image. 
![oRmfgbricn](https://user-images.githubusercontent.com/67075513/113606071-6534d780-963f-11eb-96d0-31f43d960c3a.gif)

**Comment by lavrton** [comment]
You may need to use the native drag&drop feature (or a library). Check intersection on the drop. Apply new attributes if it is your shape.

For native drag&drop see https://konvajs.org/docs/react/Drop_Image.html
