### ISSUE TITLE
Free Drawing example works slowly (and weird) when CPU usage is high

### ISSUE THREAD

**Issue by adithyavis** [konvajs/react-konva#567]
I tried the React-konva Free Drawing example on a PC with a poor CPU performance. It was laggy, and when I tried to draw curvy alphabet (like 'w'), the curve got distorted due to the tension factor.

It would be helpful if you could provide some methods/hacks to improve performance for the specific use-case of Free Drawing.

Ways to reproduce:
[Codesandbox Example](https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/free-drawing?from-embed=&file=/src/index.js)

Artificially throttle the CPU to 6x slowdown, using the chrome devtools (Performance tab)
![image](https://user-images.githubusercontent.com/40817254/112834277-c0f8e100-90d2-11eb-8338-c503a8c49eff.png)

**Comment by lavrton** [comment]
First, take a look here: https://konvajs.org/docs/performance/All_Performance_Tips.html

For "for the specific use-case of Free Drawing" I think you can try to avoid react and konva calls while drawing. For example:
1. On mouse down create an external canvas, put it on top of the stage
2. Listen to mousemove event
3. Draw line into the canvas manually with 2d canvas API (without calling react setState and without Konva)
4. On mouseup you can "finish" that line by moving it back into react state and draw it with Konva
5. Remove external canvas
