### ISSUE TITLE
Weird lines when transformer rotation is 0

### ISSUE THREAD

**Issue by vincaslt** [konvajs/react-konva#569]
When I add transformer and it's at rotation=0, some weird lines appear:

![image](https://user-images.githubusercontent.com/944727/113521144-361b5900-95a0-11eb-867e-ffa4df62289e.png)

It's fine when rotated to any other rotation, and goes back to bad when rotated to 0 again.

![image](https://user-images.githubusercontent.com/944727/113521158-4af7ec80-95a0-11eb-94d9-5f7f218c030b.png)

**Comment by lavrton** [comment]
Demo?

**Comment by vincaslt** [comment]
Maybe just a browser glitch or something, I restarted everything this morning and I've no issues...
