### ISSUE TITLE
The Free drawing tool goes to top left on intersecting with any shape

### ISSUE THREAD

**Issue by roshansachan** [konvajs/react-konva#571]
https://user-images.githubusercontent.com/4952904/113932534-5aca3780-9811-11eb-952b-fb495ff99114.mov

I am using a pen tool to do a free drawing on canvas. The line goes to the top left whenever I bring the cursor on any other shape on the canvas.
[Here](https://codesandbox.io/s/react-konva-basic-demo-forked-zjp5z) is a working example.

**Comment by lavrton** [comment]
Because you are calculating position relative to the target:

```js
 const handleMouseMove = (e) => {
    // no drawing - skipping
    if (!isDrawing.current) {
      return;
    }
    if (tool === "Pen") {
      const point = getRelativePointerPosition(e.target);
   }
   /// other code
}
```

When you move the mouse over shape `e.target` will be that shape. I don't think that is what you need. I guess you need just use stage node here or `e.currentTarget` (stage too, if you attach event to the stage).
