### ISSUE TITLE
Reordering of Images (to update zIndex) forces rerender

### ISSUE THREAD

**Issue by maaft** [konvajs/react-konva#580]
Hi,
I have an Art-Gallery and I want to raise an image when the user hovers his mouse over the image.

According to this [link](https://konvajs.org/docs/react/zIndex.html), the zIndex is determined by the order of elements. So I also followed this approach:
```typescript
          images.map(i => <Image
              onMouseEnter={() => {
              const currentImages = images.slice();
              const item = currentImages.find((i) => i.idx === idx);
              currentImages.splice(item.idx, 1);
              currentImages.push(item);
              setImages(currentImages);
            }}
            image={i.image}
         ...
          />)
```

Unfortunately, this forces all images between the onMouseLeave and on onMouseEnter to be re-rendered which looks not very nice (please watch until end, the screen recording misses most of the transitions):
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2518993/118375070-a2d23c00-b5bf-11eb-810e-d09dc560adab.gif)

The re-render happens on every transition of my mouse from one to another image. My screen recording software was not able to sample all of the occurrences.

What are my options here?

I'd love to be able to just set the zIndex per element.

**Comment by lavrton** [comment]
It looks like you are not using `key` properly. React must warn you about it. Do you have any warnings in the console?

**Comment by maaft** [comment]
Thank you so much! That was the issue here. My console didn't show any errors for whatever reason.
