### ISSUE TITLE
React.useRef on KonvaTransformer (typescript)

### ISSUE THREAD

**Issue by Schokoo** [konvajs/react-konva#581]
Hey,
i am playing with the Konva.Transformer on a textfield component but i get this error on transformRef?.current?.nodes([**textRef.current**]);:

`Type 'Text | undefined' is not assignable to type 'Node<NodeConfig>'.
  Type 'undefined' is not assignable to type 'Node<NodeConfig>'.`

```
const Textfield: React.FC<ITextFieldProps> = ({textProps, isSelected, onSelect, onChange}) => {
    const textRef = React.useRef<Konva.Text>(null);
    const transformRef = React.useRef<Konva.Transformer>(null);

    React.useEffect(() => {
        if(isSelected && textRef) {
            transformRef?.current?.nodes([textRef.current]);
            transformRef?.current?.getLayer()?.batchDraw();
        }
    }, [isSelected])
```

I used this example as a reference: 
https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/transformer?from-embed

Any idea how I can fix this?

**Comment by lavrton** [comment]
There are many ways to fix it.

1. Just ignore it. It is an type error, but not a syntax error. Typescript will output javascript just fine.
2. Force type with `transformRef?.current?.nodes([textRef.current as Konva.Text]);`
2. Or make sure `textRef.current` not null:  `if(isSelected && textRef.current)`
