### ISSUE TITLE
React konva Html node should not visible outside of Stage

### ISSUE THREAD

**Issue by kyle-hensoon** [konvajs/react-konva#582]
in this Demo ... how i could fix the input box that only visible  inside the Stage ... (during Dragging) https://codesandbox.io/s/prod-snowflake-7ko5i?file=/src/index.js

**Comment by lavrton** [comment]
```html
<Stage
        style={{
          overflow: "hidden",
          background: "green",
          position: "relative",
          display: 'inline-block'
        }}
        width={100}
        height={100}
>
```

https://codesandbox.io/s/crazy-brattain-eqtfo?file=/src/index.js
