### ISSUE TITLE
Question: How to change Y position/orientation?

### ISSUE THREAD

**Issue by viniciuszim** [konvajs/react-konva#583]
The default coordinates XY are from top to bottom, for example... (0,0) is rendering on the top left... (500,500) is rendering on the bottom right...

is there a way to change the coordinates orientation to render from bottom to top?

(0,0) on the bottom left and (500,500) on the top right?

**Comment by lavrton** [comment]
(1) The best solution is to just calculate such coordinates manually. It is not that hard.

```js
node.y(stage.height() - desiredYPositionFromBottom)
```

(2) or you can use negative scale, but you should be careful will text, because everything will be flipped vertically

```js
stage.setAttrs({
  y: stage.height(),
  scaleY: -1
});
```
