### ISSUE TITLE
konva/lib/Core got esm issue with vite

### ISSUE THREAD

**Issue by wjs** [konvajs/react-konva#589]
Version: 
react-konva@^17.0.2-4
konva@^8.0.1
vite@^2.3.4

Error message:
```
ReactKonvaHostConfig.js:67 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at node_modules/react-konva/lib/ReactKonvaHostConfig.js (ReactKonvaHostConfig.js:67)
    at __require (chunk-KYLA5N2V.js?v=64c43219:12)
    at node_modules/react-konva/lib/ReactKonvaCore.js (ReactKonvaCore.js:27)
    at __require (chunk-KYLA5N2V.js?v=64c43219:12)
    at dep:react-konva_lib_ReactKonvaCore:1
```

Reason: (in `ReactKonvaHostConfig.js`)
```js
// **the following require, _Core is not an esModule, make _Core2 has more than one default warp it**
var _Core = require('konva/lib/Core');

var _Core2 = _interopRequireDefault(_Core);

var _makeUpdates = require('./makeUpdates');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var NO_CONTEXT = {};
var UPDATE_SIGNAL = {};

// for react-spring capability
_Core2.default.Node.prototype._applyProps = _makeUpdates.applyNodeProps;

```

I'm not sure it is a bug of `konva/lib/core` or `vite`. Since I'm not familiar with vite and ESM. I'm just tring vite.

Now I add `export const __esModule = true;` into `node_modules/konva/lib/Core.js` to prevent this error in my local env. But I think it should not be the solution. So I need your help, thank you!

**Comment by lavrton** [comment]
Can you make a very small repo where I can reproduce the issue?

**Comment by wjs** [comment]
I'm sorry that may be my mistake. I found that import from `react-konva/lib/ReactKonvaCore` will case error, but import from `react-konva` will not.

```
import React from "react";
// import { Stage, Layer, Star, Text } from "react-konva";   // <--- works fine
import { Stage, Layer, Star, Text } from "react-konva/lib/ReactKonvaCore";   // <--- will cause error
```

Demo: https://codesandbox.io/s/silly-water-nnx06?file=/src/App.tsx

**Comment by lavrton** [comment]
If you want to use minimal bundle, then you need to import required shapes. https://github.com/konvajs/react-konva#minimal-bundle

```js
import { Stage, Layer, Star, Text } from "react-konva/es/ReactKonvaCore";
import "konva/lib/shapes/Star";
import "konva/lib/shapes/Text";
```

Our just use `react-konva` for import.
