### ISSUE TITLE
JSX element type (anything from react-konva) does not have any construct or call signatures

### ISSUE THREAD

**Issue by PhilippHelfenritter** [konvajs/react-konva#591]
Hello, maybe someone can help me with this.

I am importing Konva like this into the project;

```import Konva from 'konva';```
```import { Stage, Layer, Circle , Group, Text, Image, Rect, Line, Star} from 'react-konva';```

I create an exported constant like this;

``` export const MyName : React.FC<MyProps> = (props) => ```

later I call 

``` return( ```

and then my Stage etc. follows. I get these errors:

![grafik](https://user-images.githubusercontent.com/82237317/120663693-8a509580-c48a-11eb-81e6-3e8199aa2a83.png)

Any idea why this is happening or any fix? Thanks very much.

**Comment by lavrton** [comment]
Can you make a codesandbox demo?

**Comment by PhilippHelfenritter** [comment]
sure, it might be important to note that I use .tsx files. I will work on the sandbox tomorrow.

**Comment by PhilippHelfenritter** [comment]
Okay, I just created a codesandbox and it seems to work there? I am not really sure what the problem could be.

**Comment by lavrton** [comment]
🤷‍♂️ do you have typescript in codesandbox too? Exactly the same code? What `react-konva` and `konva` versions you have in your app? Same as in the demo?

**Comment by PhilippHelfenritter** [comment]
Okay, I solved the problem by reinstalling both konva and react-konva, I have no clue why it didnt work before 🤷 I'll close this, sorry for wasting your time.

**Comment by lavrton** [comment]
No problem. There were some issues with Typescript files on previous version.
