### ISSUE TITLE
Error on Gatsby Build

### ISSUE THREAD

**Issue by jdozierezell** [konvajs/react-konva#592]
I'm getting the following error when trying to build a Gatsby site using react-konva. 

```
Can't resolve 'canvas' in 'konva/node_modules/konva/lib'
```

Based on a much older issue (https://github.com/konvajs/react-konva/issues/102), I'm thinking this may be related to Gatsby's SSR. Is there a fix for this?

I've set up a new repo at https://github.com/jdozierezell/konva to demonstrate the issue.

**Comment by lavrton** [comment]
You can just manually install `canvas` package.

Or disable SSR rendering for canvas elements. Sinse `react-konva` doesn't support SSR rendering and will render just blank div as the result.

**Comment by jdozierezell** [comment]
Thanks @lavrton. 

I had tried installing ```canvas``` manually, but that continued to throw an error, and there's not really a way to disable SSR in Gatsby. 

The solution I found was to tell Webpack to ignore the canvas package. There are more details at https://github.com/gatsbyjs/gatsby/issues/17661#issuecomment-537564388 for anyone else who might run into this issue.

**Comment by Steven24K** [comment]
I also had the same issue, i solved by installing canvas as a dev dependency and ignoring the canvas plugin. 

`yarn add canvas --dev` 

and add this code to gatsby-node.js 

```
// Thanks to https://github.com/gatsbyjs/gatsby/issues/17661#issuecomment-665800908
exports.onCreateWebpackConfig = ({
    stage,
    rules,
    loaders,
    plugins,
    actions,
}) => {
    // if (stage === "build-html") {
        actions.setWebpackConfig({
            externals: ['canvas']
        })
    // }
};
```
