### ISSUE TITLE
Open context menu on mobile devices

### ISSUE THREAD

**Issue by DarkBitz** [konvajs/react-konva#593]
I have a line on which I want to open a context menu. With 
```
<Line onContextMenu={superFunction} />
```
 this works great in the browser. But when I try that on the tablet nothing happens. I have read that you do a "long touch" on mobile devices instead, what would that look like in react konva? Because I already need the information on which point was clicked or pressed.

Versions:
konva: ^7.2.5
react-konva: ^17.0.2-0

**Comment by lavrton** [comment]
There is no `contextMenu` event on mobile. It is up to you to implement long press. It can be something like this:

```js
const timeoutRef = React.useRef();

const handleLongPress = (e) => {
   console.log('long press');
}

const handleTouchStart = (e) => {
   timeoutRef.current = setTimeout(() => {
    handleLongPress(e);
   }, 600);
}

const handleTouchEnd = () => {
  clearTimeout(timeoutRef.current);
}

return <Line onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd} />
```
