### ISSUE TITLE
How can multiple images be presented like GIF?

### ISSUE THREAD

**Issue by marco5069** [konvajs/react-konva#596]
I'm using this great library, but I'm having some problems。。。
<img width="741" alt="截屏2021-06-24 下午4 48 12" src="https://user-images.githubusercontent.com/44725746/123232755-0b400180-d50c-11eb-95c9-5434e1a04e39.png">

Now this can only show a static picture, how to do multiple dynamic display，And the number of frames can be adjusted dynamically？

Thank you！！

**Comment by lavrton** [comment]
Why did you try? Why do you need this?

**Comment by marco5069** [comment]
https://user-images.githubusercontent.com/44725746/123377398-9da0dd80-d5be-11eb-8531-080d25682c78.mov

ng…]()

Because you need to make this item, you need to upload multiple photos to show the animation

**Comment by marco5069** [comment]
> 你为什么要尝试？你为什么需要这个？

The effect is like some dynamic item on TikTok

**Comment by lavrton** [comment]
In the simplest scenario, you just need to use [Konva.Sprite](https://konvajs.org/docs/shapes/Sprite.html).

If you don't have one image, that has all frames inside of it, you can try to generate it on the client side. Just make a big canvas and draw all images manually into it.

If you don't want to use `Sprite`, you can just place a lot of Konva.Image objects and manually show/hide them. You will need to implement dynamic frames by yourself.

**Comment by marco5069** [comment]
> In the simplest scenario, you just need to use [Konva.Sprite](https://konvajs.org/docs/shapes/Sprite.html).
> 
> If you don't have one image, that has all frames inside of it, you can try to generate it on the client side. Just make a big canvas and draw all images manually into it.
> 
> If you don't want to use `Sprite`, you can just place a lot of Konva.Image objects and manually show/hide them. You will need to implement dynamic frames by yourself.

OK，Let me try！Thank you！！
