### ISSUE TITLE
How to drag and drop HTML components

### ISSUE THREAD

**Issue by dansmog** [konvajs/react-konva#597]
So i have custom html components, and i am Using Html from React-konva-utils, how can i make sure i can drag and drop this html components like i would drag and drop konva nodes

**Comment by lavrton** [comment]
What do you need it? What do you have for your HTML component?
Probably you will have to implement it manually.
1. listen mousedown on html element
2. listen mousemove on window
3. update html element position based inside mousemove event

**Comment by dansmog** [comment]
There is no way for it be done using konva? just like the way konva nodes are easily draggable, when i just pass onDragStart and onDragEnd? @lavrton

**Comment by lavrton** [comment]
No. DOM elements are not part of Konva scene tree. `<Html />` component is some magic on top of React and `react-konva`. Konva itself knows nothing about these HTML elements.

If you don't have any interactivity on DOM elements (you don't need events for them), you can set `pointerEvents: "none"` for DOM, so underlying Konva object will trigger pointer events.

```js
<Group
  draggable
  onDragStart={() => {
    console.log("dragstart");
  }}
>
  <Html divProps={{ style: { pointerEvents: "none" } }}>
    <div
      style={{
        width: "100px",
        height: "100px",
        border: "1px solid black"
      }}
    >
      I am HTML element. You can move me by dragging Konva shape.
    </div>
  </Html>
  <Rect width={100} height={100} fill="red" shadowBlur={5} />
</Group>
```

https://codesandbox.io/s/admiring-firefly-6oby4?file=/src/index.js

If that is not ok, you have to implement dragging on your own.

**Comment by dansmog** [comment]
This works.. thank you, but then is there no percentage styling? 

Instead of  ```<Rect width={100} height={100} fill="red" shadowBlur={5} />```  I can do  <Rect width={"100%"} height={"100%"} fill="red" shadowBlur={5} />

**Comment by k1nnx** [comment]
> No. DOM elements are not part of Konva scene tree. `<Html />` component is some magic on top of React and `react-konva`. Konva itself knows nothing about these HTML elements.
> 
> If you don't have any interactivity on DOM elements (you don't need events for them), you can set `pointerEvents: "none"` for DOM, so underlying Konva object will trigger pointer events.
> 
> ```js
> <Group
>   draggable
>   onDragStart={() => {
>     console.log("dragstart");
>   }}
> >
>   <Html divProps={{ style: { pointerEvents: "none" } }}>
>     <div
>       style={{
>         width: "100px",
>         height: "100px",
>         border: "1px solid black"
>       }}
>     >
>       I am HTML element. You can move me by dragging Konva shape.
>     </div>
>   </Html>
>   <Rect width={100} height={100} fill="red" shadowBlur={5} />
> </Group>
> ```
> 
> https://codesandbox.io/s/admiring-firefly-6oby4?file=/src/index.js
> 
> If that is not ok, you have to implement dragging on your own.

You sir, are a saint. 🙏

I was pretty much implementing the same thing, but using ``react-draggable``. I had no clue why i was using that, but it appeared to work, until i realized that it was offsetting the actual component in kanva.
