### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by KhalusIvan** [konvajs/react-konva#599]
Can't find and install version for react 16.14.0
I found different versions of react-konva for different react versions but for this one (16.14.0) I can't found

**Comment by KhalusIvan** [comment]
Probably I just can't found this version
Can you help me?

**Comment by lavrton** [comment]
Looks like the last `react-konva` works just fine with `react@16.14.0`. I think you can ignore the warning message.

https://codesandbox.io/s/react-konva-test-with-old-react-version-33iof?file=/package.json

**Comment by KhalusIvan** [comment]
Ok, thanks a lot)
