### ISSUE TITLE
Peer dependency on react, react-dom

### ISSUE THREAD

**Issue by nsharma1396** [konvajs/react-konva#600]
Hi

Amazing work on the whole library, really thankful for all that you do

Just needed to understand why do the `react` and `react-dom` peerDependencies have a minimum version requirement of v17+? Also, why is an update needed in the min version of react for every release of the library?

Is it feasible to have a min version requirement of 16.8 instead?

Would love to understand more about how that might affect the implementation since it can be an issue as the user will have to update react and react-dom versions for every `react-konva` update which may not be feasible to do in some situations

**Comment by lavrton** [comment]
Probably we can change it to `16.8`. Previously, `react-konva` was extremely sensitive to `react` version (due to its implementation). So I followed `react` updates strictly.

But looks like with the last `react-konva` release that issue is resolved. I didn't try it with `react@16.8`. If you can, please test it and let me know how it works.

**Comment by nsharma1396** [comment]
Awesome, thanks a lot for the quick response!

I will do some tests and let you know

Could you let me know if there were some major pain points/issues during the previous implementation?
That will help me with the testing

**Comment by nsharma1396** [comment]
@lavrton I have done some tests using examples from [react-konva docs](https://konvajs.org/docs/react/Intro.html)

You can find the tested code here:

* [Basic shapes/custom shapes/events](https://codesandbox.io/s/react-konva-basic-demo-forked-nj9y7)
* [Images](https://codesandbox.io/s/images-qc5x8)
* [Filters](https://codesandbox.io/s/filters-pucid)
* [Drag and drop](https://codesandbox.io/s/drag-and-drop-7ru0p)
* [Refs and konva nodes](https://codesandbox.io/s/refs-and-konva-nodes-ciu29)
* [Transformer](https://codesandbox.io/s/transformer-j81gz)
* [Simple animations](https://codesandbox.io/s/simple-animations-4dvyj)
* [Complex animations](https://codesandbox.io/s/complex-animations-mtvci)

Do let me know if this works? If not, please let me know if you would like this to be tested for some other scenarios
I can raise a PR to update the relevant fields, etc if things work out well

Thanks!

**Comment by lavrton** [comment]
Yes, please send a PR.

**Comment by souldjl** [comment]
can you give me a version to run it well ?
 "react": "^16.13.0",
"react-dom": "^17.0.2",
what should i have in react-konva version & konva version?
