### ISSUE TITLE
events propagation between elements in the same layer

### ISSUE THREAD

**Issue by fjpedrosa** [konvajs/react-konva#601]
I hava a stage with one layer. This layer has several elements, for instance a square and a circle. When I click on the square it should change color. The circle is on top of the square. I want to click on the circle, propagate that event to the square and change the square color. But I can't achieve this result because the event is not propagated.

I observed that the onClick event can be propagated from the circle to the Stage (if I add an onClick event to the stage, it is executed)

Is it possible that events are nor propagated between components of the same layer?

Thanks in advance.

**Comment by lavrton** [comment]
Events bubble from child to parent. From shape to group (optional) to layer to stage. The same way it works in regular DOM.

Looks like for you use case, you need to make circle "invisible" for events. You can use `listening: false` for that. It is similar to `pointer-events: none` in CSS.

If you don't want to hide circle from clicks, you will need to manually check intersection of pointer with rectangle and trigger click manually. But I am not sure that is a good pattern.
