### ISSUE TITLE
Using transformer to resize repositions elements on canvas

### ISSUE THREAD

**Issue by JimBroad** [konvajs/react-konva#602]
When using Transformer to resize a shape, if you cross shape's x and/or y position, the shape's x/y position is changed.

It is visible on demo here:
https://konvajs.org/docs/react/Transformer.html

It does not happen with vanilla KonvaJS:
https://konvajs.org/docs/select_and_transform/Basic_demo.html

There appears to be a 'threshold' when transformer 'crosses' its own x/y on resize.

Adding a video to better demonstrate:
https://youtu.be/d8-4jOgvr8s

**Comment by lavrton** [comment]
React demo has a bit different logic with rounding. So such behavior is ok.

**Comment by JimBroad** [comment]
Maybe I'm missing something, but I'm still seeing the same behavior at:

https://konvajs.org/docs/react/Transformer.html

Also really dig the library. And thanks for managing to keep up with all the support requests.

**Comment by lavrton** [comment]
Yes. What I mean is that demo itself is implemented differently. As side effect, it has a different behavior. I don't plan to fix the demo, because it is just a small tutorial to show basic transformer usage.

**Comment by DanielGotIt** [comment]
@lavrton Is there a way to prevent changing position when resizing in ReactJs?
