### ISSUE TITLE
Rotation in path component is not working

### ISSUE THREAD

**Issue by fjpedrosa** [konvajs/react-konva#605]
Using this sandbox as example: [https://codesandbox.io/s/flh19?file=/src/index.js](https://codesandbox.io/s/flh19?file=/src/index.js)

If rotation is added to Path, then no image is shown in canvas.

**Comment by lavrton** [comment]
What rotation? Where did you add it? What value?

All notes are rotated around its origin. The origin of that path shape is it {0, 0} point. In your example, it is top left of the canvas element.

**Comment by fjpedrosa** [comment]
Ok, Im sorry, it is working fine, however looks like the origin is not exactly on top left corner... probably I am wrong. I tried 90deg and it dissapeared.
