### ISSUE TITLE
How do you save your canvas / manipulated image as a gif?

### ISSUE THREAD

**Issue by Jstack1001** [konvajs/react-konva#606]
Trying to save a picture with animations as a gif? Is there a way to do this?

Right clicking and saving in the browser defaults as a .png file

**Comment by lavrton** [comment]
There are many ways. The basic solution is:

1. Create Konva stage
2. Export each frame into image
3. Generate GIF from a set of images with any external library. Probably https://github.com/yahoo/gifshot will do the work.

**Comment by Jstack1001** [comment]
Hi!

Thank you very much for replying! I'm currently using the React framework, do you know if this library will work with the framework? Thanks
________________________________

**Comment by lavrton** [comment]
I think it will. It is not related to `react` framework. With `react` and `react-konva` you just render something on the screen. Then you can use direct access to canvas element with `ref` API to make an export.
