### ISSUE TITLE
Adding drag properties to custom components

### ISSUE THREAD

**Issue by paulmbw** [konvajs/react-konva#607]
Hi there,

I'd like to add the `draggable` property to custom react components. For example, I am building a React component that renders a calendar. I'd like to import this component into the `Stage` component from `react-konva`, and I should be able to drag the calendar around in the canvas. Is this achievable? I noticed the `draggable` is only available on components export from `react-konva` e.g. `Rect` and `Shape` - is it possible to use some sort of wrapper so custom components are similar to those of Konva nodes?

**Comment by lavrton** [comment]
So, do you want to render regular DOM element inside canvas? If so, why do you need that? There are many limitations when you do that. https://konvajs.org/docs/react/DOM_Portal.html

**Comment by paulmbw** [comment]
Hey @lavrton thanks a lot for your response.

I'm working on a side project that uses react-konva to build the canvas, but I'd like to build more complex custom components like text editors and pdf documents that can be dragged across the canvas. The components konva provides e.g. Rect, Text etc are great, but I'm looking to build more interactive and complex components.

You mentioned there are many limitations to doing this, are you able to elaborate more on this?

**Comment by lavrton** [comment]
Mostly about events. You can read a bit more here: https://github.com/konvajs/react-konva/issues/597

Or you can just implement drag&drop of DOM elements manualy.
