### ISSUE TITLE
Add a hook `use2DContext`

### ISSUE THREAD

**Issue by nowlow** [konvajs/react-konva#610]
It may be a great feature to add some hooks like `use2DContext` to use the canvas.getContext('2d').
Hooks are more and more used by react developers and I think this addition would be appreciated by the community.

**Comment by lavrton** [comment]
How it can be used?

**Comment by nowlow** [comment]
If I want to add features specific to my project, for example a component that changes the background color of my canvas. Or extend the library for specific cases.
The closest hook is [`useThree`](https://github.com/pmndrs/react-three-fiber/blob/master/markdown/api.md#useThree) for react-three-fiber, it is very useful in many cases.

**Comment by nowlow** [comment]
I'll be glad to help you on this, but I did not found how to setup a demo project with nwb

**Comment by lavrton** [comment]
> changes the background color of my canvas

You already can do this: https://konvajs.org/docs/sandbox/Canvas_Background.html. Do you want to do it differently? How?

> Or extend the library for specific cases

Extend how? What cases?

> The closest hook is useThree for react-three-fibe

That hook provides access to some three js API and its object model. Three.js works on top of `webgl` context. `Konva` works on top of `2d` context. So from your comparison you want to have `useKonva` hook. But I have no idea what you want to do with it.

**Comment by nowlow** [comment]
In my case, I need to set the background color of my canvas in a component in my `Stage`. I don't have and can't access the canvas size from this component, which prevents the `Rect` method from working.
So `useKonva` could provide several pieces of information, like the canvas size, the context or the DOM element.
More generally, this kind of hook would allow to develop more components and to extend konva.

**Comment by lavrton** [comment]
Closing the issue because I don't see how the feature will work.
