### ISSUE TITLE
layer cache performance about konva/React konva

### ISSUE THREAD

**Issue by duidae** [konvajs/react-konva#613]
Hi thanks for providing this fantastic library, really love it and appreciate your wonderful work!
Currently I am trying to optimize dragging the stage with many polygons on layers using React konva via layer caching mentioned in the konva tutorial, but seems not working as good as purely using konva,

demo here: https://codesandbox.io/s/konva-react-konva-compare-3u9zb?file=/index.js

As we can see, the move of dragging the stage with konva is much smoother than with React konva, so I am wondering is the performance gap due to React or am I not doing things right? Is there any other way I can improve the dragging with React konva?

Thanks again!

**Comment by lavrton** [comment]
I guess you need to cache layer on `componentDidMount()`, and not inside `componentDidUpdate()`. In your example, layer is not cached (as there is no update yet). Performance will be the same when you fix that.

**Comment by duidae** [comment]
@lavrton it works! Thank your for the great help! :+1:
