### ISSUE TITLE
customized scale of shape for zoom

### ISSUE THREAD

**Issue by duidae** [konvajs/react-konva#617]
Hi thanks for providing this fantastic library, really love it and appreciate your wonderful work!
Currently I am trying to implement zooming without resizing the strokes & points

demo here: https://codesandbox.io/s/react-konva-zoom-xz6py

thanks to `strokeScaleEnabled={false}`, strokes work perfectly when zoom-in & zoom-out for staying the same stroke width, but the rects will also scale-up or down at the same time when zooming, so wonder is there a way to keep those rects stay in the same size when zoom-in/out? 

Thanks again!

**Comment by lavrton** [comment]
Konva has no API to do that.

You can use "reversed scale" for rectangles `1 / stageScale`. It means you will have to update all of them on every zoom.

Or you may try to use custom shape, to avoid setting scaling via props.

```js
<Shape
  key={`p1-${i}`}
  x={x1}
  y={y1}
  sceneFunc={(ctx, shape) => {
    const scale = 1 / shape.getStage().scaleX();
    ctx.beginPath();
    ctx.rect(-3 * scale, -3 * scale, 6 * scale, 6 * scale);
    ctx.fillStrokeShape(shape);
  }}
  fill={color}
/>
```

https://codesandbox.io/s/react-konva-zoom-forked-394ut?file=/index.js:842-1210

**Comment by duidae** [comment]
@lavrton thanks for the nice solution!
