### ISSUE TITLE
Why is Text component not supported?

### ISSUE THREAD

**Issue by Amoodaa** [konvajs/react-konva#618]
https://github.com/konvajs/react-konva/blob/b08ac251f026881595f619e162f71db36dca1ec1/src/ReactKonvaHostConfig.js#L176

**Comment by lavrton** [comment]
Layout of Konva nodes is very different from DOM.

It is unclear what to do with an inline text. What attributes should it have? Size? Position? If you want to display text on the canvas, you should just use `<Text />` component. It will be consistent with all other nodes.
