### ISSUE TITLE
how to get stage via children nodes in react?

### ISSUE THREAD

**Issue by duidae** [konvajs/react-konva#621]
Hi thanks for providing this fantastic library, really love it and appreciate your wonderful work!
I am trying to get the stage position via child

demo here: https://codesandbox.io/s/react-konva-get-stage-tthwl

I tried passing the stage as a prop to child or using child ref to getStage(), but neither works, so wonder is there a way to access the stage information inside the child?

Thanks again!

**Comment by duidae** [comment]
> Why do you need it? Why do you need position of the stage inside a child?

my shape has a coordinate system unrelated to the stage coordinate, so we will need to do a coordinate transformation to show the correct position on the stage, so that's why we want to know the stage's position & scale when rendering.

**Comment by lavrton** [comment]
Using reference to access properties of a stage is not a "react-way". Also, such ref is not defined on the first render (as the stage is not mounted yet).

If you need to use position inside the render logic, you can use props.

```js
const stageX = 10;
const stageY = 10;
<Stage
  x={stageX}
  y={stageY}
  height={window.innerHeight}
  width={window.innerWidth}
>
  <Layer>
     <CustomRect stageX={stateX} stageY={stageY} />
   </Layer>
</Stage>
```

If you need to access position temporary inside some events of the child, you can use Konva API

```js
<Rect
  x={10}
  y={10}
  fill="black"
  draggable
  onDragEnd={(e) => {
    const stagePos = e.target.getStage().position();
  }}
/>
```
