### ISSUE TITLE
Error updating tranformer with multiple nodes.

### ISSUE THREAD

**Issue by dmemot** [konvajs/react-konva#626]
I'm setting multiples nodes (Class: Text - Konva) by their reference to a parent  transformer using: 

`parentTransformerRef.current.nodes(elements);`

The first time it adds correctly the nodes  and their individual transformers, I can drag the parent transformer and all the nodes inside including their individual transfomer:

![Screen Shot 2021-11-08 at 18 08 13](https://user-images.githubusercontent.com/93952334/140832529-1ed40698-bac2-452d-a5dd-7cb9e2f564a0.png)

But the second time, if I add or remove nodes using again "parentTransformerRef.current.nodes(elements)" to update the nodes list, I can drag all the nodes inside, but the old node's tranformers doens't move:

![Screen Shot 2021-11-08 at 18 11 28](https://user-images.githubusercontent.com/93952334/140832839-4a218f85-616a-4d9d-9f41-e301f9b11926.png)

I tried updating every node transformer after, but then the parent transformer shows a weird behavior it can be drag but returns to the initial position.

**Comment by lavrton** [comment]
Make online demo.

**Comment by dmemot** [comment]
Thanks for answer!! 

You can see the demo here: [https://codesandbox.io/s/kova-tranformer-container-93oud](url)

**Comment by lavrton** [comment]
Looks like using several transformers produces a conflict, an event. The new transformer is removing events of the old transformer. So old transformer is staying on the same place because it doesn't know about updates.

So that looks like a bug in Konva.

Are you sure you need to use several transformers at the same time?

**Comment by dmemot** [comment]
Yes, I have to show the border and anchors in every selected element, just for a visual thing and in some elements there are validations depending the active anchor.

I thought it was a bug from konva and as all the individual transformers are render in base a list on a state, I resolved it cleaning the selected element list state so the transformers won't be rendered/disappear and after reloading the list I kept in a auxiliary variable, the bad thing is I need to do it every time I add o remove and element, not the best solution but enought for now.

**Comment by lavrton** [comment]
Fixed with `konva@8.2.4`
