### ISSUE TITLE
Pointer Events - pointerup might not be getting triggered when unmounting a node (use-gesture involved)

### ISSUE THREAD

**Issue by rafaelchiti** [konvajs/react-konva#627]
Sorry if this is a bit high level, I tried to narrow as much as I could the issue but still not fully certain if this is a problem with the pointer events impl in Konva or an issue with use-gesture (I tried to mimic the issue with use-gesture in DOM nodes and I don't see the problem, that's why Im asking here).

**The problem:**
If I drag a node and I remove it on 'pointerup', like dropping an object on a delete zone. When I try later to drag the stage, the stage thinks that we are 'pinching', I believe this is because for some reason pointer ids might be messed up? meaning that the node I just deleted didn't get to trigger the pointer up and therefore the gesture library didn't get to clean the cache of pointer ids under action. 
A quick fix is to trigger the 'remove' inside a setTimeout. This way it seems like the 'up' event gets triggered and the pointer state is cleaned up.

Here a way to reproduce.
https://codesandbox.io/s/konva-delete-pinch-issue-r85zw?file=/src/App.js:3310-3498
Only way to test it is with a real device. The stage at first is draggable, then if you drag the box into the red area to 'remove it', after that the stage is not draggable, but rather perceives a 'pinching' event from use-gesture.

Here a demo:
https://user-images.githubusercontent.com/1154663/140928890-d6facfa9-ea80-4988-8a32-73c559c455d8.mp4

Feel free to close this ticket if is not worth the investigation, I have that quick work around, but I was curious to whether this could be an issue in the pointer events impl inside Konva. Happy to do more digging or help in any way possible!.

Thanks!

**Comment by lavrton** [comment]
I think it is possible that the event is not triggered on the stage. The event is bubbling from the target to all its parents. But if we remove it, the bubble will stop. So, no event on the parent.

That is a bug, but I am not sure how to easily fix it. So, your workaround looks valid to me.

**Comment by rafaelchiti** [comment]
ohhh I see, thanks for clarifying!. Feel free to change the ticket or close it. At best it stays as reference for someone else bumping into similar issues.
