### ISSUE TITLE
I have 30,000 rect to draw, and the page is too slow. can anyone help me?

### ISSUE THREAD

**Issue by weixuefeng** [konvajs/react-konva#631]
```
landData.length = 30000

<Group>
            {landData.length > 0 ? (
              landData.map((rectInfo: RectInfo) => {
                return <ColorRect key={`${rectInfo.key}`} rectInfo={rectInfo} onItemClick={onLandClick} />
              })
            ) : (
              <></>
            )}
            {mark}
</Group>
```

and about `{mark}`, first click i add Rect to mark, if i click it again, i have to remove it from group, can i implement it?

**Comment by lavrton** [comment]
30k shapes is a lot for both Konva and react. Are they all visible at the same time on the screen?

**Comment by weixuefeng** [comment]
Maybe, because I want to make my screen zoomable and draggable, just like this:
![image](https://user-images.githubusercontent.com/25627103/142626746-0609da3d-dca9-42ef-8785-332d920e63b1.png)

**Comment by lavrton** [comment]
I am not certain if it will be simply possible to handle that much. 
Probably you should try direct 2d canvas API and just draw with it, without react and Konva abstractions.

**Comment by weixuefeng** [comment]
ok. i had resolved it by [react-virtualized]

**Comment by d-pollard** [comment]
@weixuefeng how did you use react-virtualized to solve this?

**Comment by weixuefeng** [comment]
> @weixuefeng how did you use react-virtualized to solve this?

yes. you can try it. https://github.com/bvaughn/react-virtualized or https://github.com/bvaughn/react-window
