### ISSUE TITLE
Changing zIndex by ordering components not working

### ISSUE THREAD

**Issue by noamackerman** [konvajs/react-konva#632]
Hi, 
I have a line that I want to draw between 2 anchor points. I first render the anchors and then the line itself, and it works, but for some reason the line appears above the anchor points, even tough it is being rendered after them in the render function. Not sure if I'm missing something here. Please see an example that reproduces this issue:
https://codesandbox.io/s/react-konva-custom-shape-demo-forked-cmohi?file=/src/index.js

Appreciate your help!

**Comment by lavrton** [comment]
> the line appears above the anchor points, even tough it is being rendered after them in the render function

Looks correct to me. You see it **above** (on top) because you render **after**.

**Comment by noamackerman** [comment]
Got it! my bad 🙈
Thanks!
