### ISSUE TITLE
Get position of a node relative to another node on a scaled & moved stage

### ISSUE THREAD

**Issue by noamackerman** [konvajs/react-konva#633]
Hi, 
I'm calculating the position of 1 node (e.g. circle) relative to another (e.g. rect) by inverting the transform and it works as expected when the scale and position of the stage do not change. however, when scaling and moving the stage, the results change and become incorrect. I'm trying to understand what I'm missing here. Here is a codesandbox that reproduces this issue:
https://codesandbox.io/s/react-konva-pan-zoom-forked-wyrm5?file=/src/App.js

Appreciate your help!

**Comment by noamackerman** [comment]
I changed getAbsoluteTransform to getTransform and it seems to solve it, is that the right solution?

**Comment by lavrton** [comment]
Why do you need to mess up with transforms? Why don't just compare `x` and `y`?

**Comment by noamackerman** [comment]
hmm, yeah I might over complicated it, will try the to just compare the x and y.
Thanks!
