### ISSUE TITLE
Use strict mode does not work

### ISSUE THREAD

**Issue by ps1x** [konvajs/react-konva#634]
Reproduction from example: https://codesandbox.io/s/zealous-jasper-hxcu6

notice useStrictMode(true) and coords commented out in <Text> props.

Even though useStrict set to true, one can still drag text and it will stay where drag was stopped.

**Comment by lavrton** [comment]
I don't understand the demo. 

> Even though useStrict set to true, one can still drag text and it will stay where drag was stopped.

And that looks correct to me, because state is updated on dragend:

```js
            onDragEnd={(e) => {
              this.setState({
                isDragging: false,
                x: e.target.x(),
                y: e.target.y()
              });
            }}
```

**Comment by ps1x** [comment]
> I don't understand the demo....
> 

My bad, but even if you comment it out dragged text does not jump back to 0, 0

As far as i understand useStrict(true) it means that coordinates of dragged object are managed by programmer and not by library?

**Comment by ps1x** [comment]
> And that looks correct to me, because state is updated on dragend:

Also it does not matter, because this state is not used for anything, because props x and y of <Text was commented out.

**Comment by lavrton** [comment]
`useStrict` just do one simple job:

> When component is re-renderer (state is updated or new props are passed) it will set all passed props to node's attibutes. Doesn't matter if they are changed or now.

You are removing `x` and `y` props, then `react-konva` is doing nothing with them. In that case default Konva logic is working for drag&drop. It is managing its internal state inside node attributes.

**Comment by ps1x** [comment]
Okay, thank you, now its clear.
