### ISSUE TITLE
How to restrict dragmove 

### ISSUE THREAD

**Issue by ps1x** [konvajs/react-konva#635]
Its not clear from the docs how can one restrict dragmove in some bounding box, for example canvas itself.

Also which x and y should one take from onDragMove event parameter?

https://konvajs.org/docs/drag_and_drop/Complex_Drag_and_Drop.html

**Comment by ejarzo** [comment]
There may be multiple ways depending on the context but I believe the `dragBoundFunc` will allow you to do this -- https://konvajs.org/api/Konva.Node.html#dragBoundFunc
