### ISSUE TITLE
Seeking through video causes flashing on Firefox

### ISSUE THREAD

**Issue by abdwebus** [konvajs/react-konva#637]
Playing the video works well on Firefox. But manually seeking through the video causes flashing effect.
This happens only on Firefox. Playing and seeking works well on Chrome.

This is a [demo](https://codesandbox.io/s/zen-galois-i0gqc?file=/src/App.tsx). Try clicking Backward / Forward buttons on Firefox

**Comment by lavrton** [comment]
I don't think there is anything to do from `konva` or `react-konva` side.

As a workaround you may try to seek video, wait until it is loader/ready and then redraw a layer.
That worked for me https://codesandbox.io/s/gracious-perlman-rqgl4?file=/src/App.tsx:1456-1791

```js
<button
  onClick={() => {
    animRef.current.stop();
    Konva.Util.requestAnimFrame(() => {
      videoElement.currentTime = videoElement.currentTime - 0.5;
    });

    // not sure how to check that video is ready
    // so just put a timeout
    setTimeout(() => {
      animRef.current.start();
    }, 300);
  }}
>
  Backward
</button>
```
