### ISSUE TITLE
White seam in between images and shapes

### ISSUE THREAD

**Issue by Thanos0252** [konvajs/react-konva#638]
Hello, and thank you to everyone who works on this project.

**Problem:**
When placing an image or shape side by side a seam line appears in between objects.

Chrome doesn't seem to have this issue with images, but Safari and Firefox do. Shapes such as Rect have this issue on Chrome (96.0), Safari (15.1), and Firefox (95.0).

My ultimate goal is to have images and shape side by side without any lines in between. I've added some zoom functionality in order see the lines a little more clearly in the sandbox below.

https://codesandbox.io/s/withered-sea-xgzg1

![LineIssue](https://user-images.githubusercontent.com/97198387/148296790-a554502d-7e04-4f21-bfd9-e4719a2c54ff.png)

Thank you!

**Comment by lavrton** [comment]
I don't think we can do much here from Konva side. This is how browser rendering works. You may try to slightly increase size of images and shapes to have a tiny overlap. Or add a stroke.
