### ISSUE TITLE
How to to define a custom react component

### ISSUE THREAD

**Issue by motionrus** [konvajs/react-konva#639]
I have custom Konva class, 
```
import { _registerNode } from 'konva/lib/Global';
import { Shape, ShapeConfig } from 'konva/Shape';

class MyShape extends Shape {}

MyShape.prototype.className = 'MyShape';
_registerNode(MyShape);
```
How can i update ReactKonvaCore? I want use `MyShape` like react component. Thanks!

**Comment by lavrton** [comment]
Just make a variable that will have string with your className. Then use this variable as a component. 

```js
// in shape definition
import { _registerNode } from 'konva/lib/Global';
import { Shape, ShapeConfig } from 'konva/Shape';

class MyShapeClass extends Shape {}

MyShapeClass.prototype.className = 'MyShape';
_registerNode(MyShapeClass);
export const MyShape = 'MyShape`;
```

Then when you need to use it:
```js
import { MyShape } from './my-shape';
<MyShape />
```

I didn't try it, but I think it should work if you registered shape.

**Comment by motionrus** [comment]
Thanks, it works!

**Comment by dadlaniTarun** [comment]
@motionrus could you please share the implementation for a custom shape in a sandbox/codepen, I am trying to implement the same. This will really help me, thanks.

**Comment by motionrus** [comment]
@dadlaniTarun hi! See answer example please

https://stackoverflow.com/questions/70676321/konva-js-resize-rect-by-bounds-in-transform-js
