### ISSUE TITLE
When image are rotated there is a fine line between 2 images 

### ISSUE THREAD

**Issue by akashraj9828** [konvajs/react-konva#644]
I was trying to break up images and load them in a grid.
When Image is loaded in grid and grid is rotated there is a fine line between all image elements

![image](https://user-images.githubusercontent.com/29796785/152812225-7cefaa5d-dfa6-43cd-81f7-74037c7c4256.png)

The line shows up only when the rotation angle is not a multiple of 90.

Here is an example code to reproduce the issue.
https://codesandbox.io/s/konva-image-rotation-vr83w

**Comment by lavrton** [comment]
I don't think there is anything we can do from `konva` or `react-konva` side. It is how browser rendering is working. 

As a workaround, just increase image size a bit.

```js
 <Image
      image={img}
      width={grid_size + 1}
      height={grid_size + 1}
      x={image.grid_col * image.grid_size}
      y={image.grid_row * image.grid_size}
    />
```

**Comment by akashraj9828** [comment]
When we zoom out the lines again become visible after some point... What I did instead is that I created a duplicate image under the original image but with a slightly bigger width, height like 
```
 <>
          {renderTwice ? (
            <KonvaImage
              name="image"
              width={grid_size + 2}
              height={grid_size + 2}
              ref={imageRef}
              image={img }
              offset={offset}
            />
          ) : null}
          <KonvaImage
            name="image"
            width={grid_size}
            height={grid_size}
            ref={imageRef}
            image={img}
            offset={offset}
          />
        </>
```

the amount of images I was using is small so it was fine to render 2x tiles just to coverup the white gaps

Hope this helps someone...
