### ISSUE TITLE
React konva really slow in safari with tabIndex={1} in the container

### ISSUE THREAD

**Issue by noamackerman-monday** [konvajs/react-konva#645]
Hi,
To handle keyDown events I'm using  tabIndex={1} on the Stage's div container.
When using safari, it makes konva really slow. When removing tabIndex={1} the performance is back to normal.

To reproduce, try this demo with and without tabIndex={1} in safari.
https://codesandbox.io/s/react-konva-basic-demo-forked-p0cfz

Thanks

**Comment by lavrton** [comment]
How do you test the performance?

I don't think there is anything we can do from `react-konva` or `konva` side.

You may try to listen to keyboard differently, e.g. on `window`.
