### ISSUE TITLE
Text adding

### ISSUE THREAD

**Issue by Chiranjeevi9** [konvajs/react-konva#652]
How to add Text inside any shape which is made by react -konva

**Comment by lavrton** [comment]
Just place a text on top of another shape. If you want, you can use groups to organize that. 

```html
<Group>
  <Rect
    width={100}
    height={100}
    fill="red"
  />
  <Text
    width={100}
    height={100}
    textAlign="center"
    verticalAlign="middle"
    text="hello"
  />
</Group>
```

**Comment by lavrton** [comment]
Just move it to the left as much as you need.

**Comment by Chiranjeevi9** [comment]
@lavrton Thank you for the quick Response.

**Comment by Chiranjeevi9** [comment]
@lavrton how can I can move it to Little bit left , and it should place centre of the ellipse , I am using browser window as X- axis
There is notl exact value to  move that could pls suggest.
