### ISSUE TITLE
Stage `onMouseMove` not calling when a node/transformer is being dragged

### ISSUE THREAD

**Issue by arielpollack** [konvajs/react-konva#654]
Reproduce steps:
1. Listen to mouse events on the `Stage` directly.
2. Start dragging a `draggable` node

You'll notice that `onMouseMove` is being called only a few number of times, and then stops.
It looks like the dragged node takes the `mousemove` event and prevent it from being called on the stage.

I've set up a quick demo on top of one of Konva's demos that increase a counter every time `onMouseMove` is being called so can see the issue.
https://codesandbox.io/s/react-konva-multiple-selection-forked-htkjiq?file=/src/index.js

Thanks!

**Comment by lavrton** [comment]
This is intentional for better performance.

If you want enabled this event back use `Konva.hitOnDragEnabled = true`;
