### ISSUE TITLE
Error when importing react-konva in nextjs

### ISSUE THREAD

**Issue by OdifYltsaeb** [konvajs/react-konva#655]
So my error message is this 

`Error: require() of ES Module /app/node_modules/konva/lib/Core.js from /app/node_modules/react-konva/lib/ReactKonvaCore.js not supported. Instead change the require of Core.js in /app/node_modules/react-konva/lib/ReactKonvaCore.js to a dynamic import() which is available in all CommonJS modules.`

Not quite the same as with #588 and the fixes suggested there (dynamic loading of components with ssr disabled) Seem to do nothing for me. 

I did this for my app component:
```

import React from 'react';
import dynamic from 'next/dynamic';

import { wrapper } from '../stores';

import '../styles/globals.css';
import MainLayout from '../components/layouts/mainLayout';
import AuthLayout from '../components/layouts/authLayout';

const layouts = {
    default: MainLayout,
    auth: AuthLayout,
};

// eslint-disable-next-line react/prop-types
const PortalApp = function ({ Component, pageProps }) {
    // eslint-disable-next-line react/prop-types
    const { layout } = Component;

    switch (layout) {
        case 'auth':
            return React.createElement(layouts.auth, null, <Component {...pageProps} />);
        default:
            return React.createElement(layouts.default, null, <Component {...pageProps} />);
    }
};

export default dynamic(() => Promise.resolve(wrapper.withRedux(PortalApp)), {
    ssr: false,
});
```

But I still get  the error. Not sure what do to here or how to fix this.

**Comment by lavrton** [comment]
Are you certain that using `dynamic` in the same module works? I was thinking you must use it in a parent module (as in the suggested solution in linked issue).

**Comment by OdifYltsaeb** [comment]
No, I'm not sure about anything here.

**Comment by komarnicki-elp** [comment]
Same problem here 👍. I tried to import it dynamically either inside and outside the stage component.

Current code causing problems: 

### Definition:
```
import React from 'react';
import { Stage } from 'react-konva';

const TeamTrendsBarChart = () => {
  return <Stage width={200} height={100} />;
};

export default TeamTrendsBarChart;

```

### Usage:
```
const TeamTrendsBarChart = dynamic(
  () => import('../../Team/components/TeamTrendsBarChart'),
  { ssr: false }
);

export const Page = () => {
  return <TeamTrendsBarChart />;
}

```

**Comment by lavrton** [comment]
I need a minimal repository to reproduce.

**Comment by jmcoder1** [comment]
Same issue here

**Comment by jmcoder1** [comment]
> Same problem here 👍. I tried to import it dynamically either inside and outside the stage component.
> 
> Current code causing problems:
> ### Definition:
> 
> ```
> import React from 'react';
> import { Stage } from 'react-konva';
> 
> const TeamTrendsBarChart = () => {
>   return <Stage width={200} height={100} />;
> };
> 
> export default TeamTrendsBarChart;
> ```
> 
> ### Usage:
> 
> ```
> const TeamTrendsBarChart = dynamic(
>   () => import('../../Team/components/TeamTrendsBarChart'),
>   { ssr: false }
> );
> 
> export const Page = () => {
>   return <TeamTrendsBarChart />;
> }
> ```

I did this instead:
```
export const Stage = dynamic(() => import("./Stage").then((mod) => mod.Stage), {
  ssr: false,
});
```

**Comment by ein1x3x** [comment]
Hello, i am tried solutions from the previous comments and it kinda worked but now i am getting 

TypeError: Cannot read properties of undefined (reading 'isBatchingLegacy')

Call Stack
ensureRootIsScheduled
node_modules/react-reconciler/cjs/react-reconciler.development.js (17721:0)
scheduleUpdateOnFiber
node_modules/react-reconciler/cjs/react-reconciler.development.js (17572:0)
Object.updateContainer
node_modules/react-reconciler/cjs/react-reconciler.development.js (20950:0)
eval
node_modules/react-konva/es/ReactKonvaCore.js (47:0)
commitHookEffectListMount
node_modules/react-dom/cjs/react-dom.development.js (20573:0)
commitLifeCycles
node_modules/react-dom/cjs/react-dom.development.js (20634:0)
commitLayoutEffects
node_modules/react-dom/cjs/react-dom.development.js (23426:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4056:0)
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js (23151:0)
unstable_runWithPriority
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11276:0)
commitRoot
node_modules/react-dom/cjs/react-dom.development.js (22990:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (22329:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (11327:0)
unstable_runWithPriority
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js (11322:0)
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js (11309:0)
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js (21893:0)
dispatchAction
node_modules/react-dom/cjs/react-dom.development.js (16139:0)
checkForUpdates
node_modules/use-subscription/cjs/use-subscription.development.js (85:0)
eval
node_modules/next/dist/shared/lib/loadable.js (183:44)
Set.forEach
<anonymous>
LoadableSubscription._update
node_modules/next/dist/shared/lib/loadable.js (183:24)
eval
node_modules/next/dist/shared/lib/loadable.js (164:17)

Any way to resolve this?

**Comment by lavrton** [comment]
@ein1x3x make sure `react`, `react-dom` and `react-konva` versions are matched. `17.x` or `18.x`

**Comment by jbc-deve** [comment]
> The issue should be resolved with `konva@8.3.6`.
<img width="961" alt="image" src="https://user-images.githubusercontent.com/80460154/166234836-9db0cad9-add9-46eb-9fab-f92136595093.png">

After upgrade, still got this error

**Comment by lavrton** [comment]
Looks like you are using unmatched `react` and `react-konva` version. Make sure they have the same major version. Both 17 or both 18.

**Comment by OdifYltsaeb** [comment]
@ayazhussain1 yes. My solution was to use pure canvas without any package. Have not tested react-konva again.

**Comment by ayazhussain1** [comment]
Hi, @lavrton I solved the above issue, but can you help me in one of my use cases? I want to fill the Rect with but there should be some space between two pixels (Pixel Pitch).
![image](https://user-images.githubusercontent.com/26005642/168051771-54e97459-1476-4385-af4d-c3726a83ed6b.png)

**Comment by Sounav201** [comment]
@lavrton  I tried using the fix as suggested in  #588  but I'm facing the following error
ReactKonva.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename ReactKonva.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs"
My code is as follows 
In the parent component, ie the page
`const NoSSRComponent = dynamic(() => import("../components/UploadCanvas"), {
  ssr: false,
});`

In the UploadCanvas component, importing modules from react-konva
`import { Stage, Layer, Image, Transformer } from 'react-konva';
import Konva from 'konva';
    <Stage width={CANVAS_WIDTH} height={CANVAS_HEIGHT}>
      <Layer>
        <Image
          ref={canvasRef}
          image={image}
          onMouseDown={handleMouseDown2}
        />
        <Transformer
          ref={canvasRef}
          keepRatio
        />
      </Layer>
</Stage>
`
I cannot wrap my head around this. Please let me know if you have a solution

**Comment by lavrton** [comment]
@Sounav201 Can you dive in into `node_modules/react-konva` and `node_modules/konva` change change file names or `package.json` to see how it can be resolved?

**Comment by Sounav201** [comment]
@lavrton  If I change `ReactKonva.js` to `ReactKonva.cjs` and change the type in `package.json` from `module` to `commonjs` and then import the following dynamically,
` const Stage = dynamic(() => import('react-konva').then(mod => mod.Stage), { ssr: false });`
` const Layer = dynamic(() => import('react-konva').then(mod => mod.Layer), { ssr: false });`
` const Image = dynamic(() => import('react-konva').then(mod => mod.Image), { ssr: false });`
and so on, I receive the following error. 
**error - ./node_modules/react-konva/es/ReactKonva.js
Module build failed: Error: ENOENT: no such file or directory,**
I am new to this so please excuse me if I have misunderstood the fix

**Comment by thrive-charlie** [comment]
I was having the same issue as @michael-harley, my example worked perfectly in CodeSandbox as a react app. As soon as I put it into NextJS I was getting several errors. Initially I had SSR issues, examples of which to fix that have already been shown [in this thread](https://github.com/konvajs/react-konva/issues/655#issuecomment-1070864640). 

It's worth noting that I am using NextJS 13.4.2 with React 18.2.0 and react-konva 18.2.9. I am also using the NextJS app directory as well.  

The first main error was: 

>  Error: Cannot find module 'canvas'

Running `npm install --save canvas` introduced a new problem:

> Error: Cannot find module 'relative "../build/Release/canvas.node"'

I have just come across [this Reddit post](https://www.reddit.com/r/nextjs/comments/13hahc1/comment/jn4zf2g) which had the fix for me. 

When adding the `canvas` module to your project, add it manually to your package.json with the following URL:
```
"canvas": "https://registry.yarnpkg.com/@favware/skip-dependency/-/skip-dependency-1.2.1.tgz"
```

**Comment by lavrton** [comment]
I recently added this note: https://github.com/konvajs/react-konva#usage-with-nextjs
I hope it will be useful. If it doesn't work, or you have new information, please let me know.
