### ISSUE TITLE
Not changing object dimensions on transform(interacting with transformer)

### ISSUE THREAD

**Issue by SDE-ADNAN** [konvajs/react-konva#657]
### this is my first issue raised on whole github

The problem is when we transform any object on the stage with the help of  transformer , the transformer is only capable of changing objects ScaleX and ScaleY ,perhaps it must change height and width for rect , inner radius and outer radius of star, radius of circle, and fontSize of Text 

There are solutions to this by changing dimensions of objects by calculating height, width, radius by referring to ScaleX and ScaleY properties.... But this causes performance issues ..

**Comment by lavrton** [comment]
Changing only scale values is by design. There are no plans to change it.
