### ISSUE TITLE
DragBoundFunc position incorrect on transformed stage

### ISSUE THREAD

**Issue by jellohouse** [konvajs/react-konva#661]
I implemented emulated screen scrolling of the canvas, using method 4 here: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#How-to-display-and-scroll-a-very-big-html5-canvas

Esentially the stage is re-positioned when we scroll like this:

```javascript
      const PADDING = 500;
      function repositionStage() {
        var dx = scrollContainer.current.scrollLeft - padding;
        var dy = scrollContainer.current.scrollTop - padding;
        stage.current.container().style.transform = 'translate(' + dx + 'px, ' + dy + 'px)';
        stage.current.x(-dx);
        stage.current.y(-dy);
      }
``` 

Then I have a draggable rectangle with a dragBoundFunc like this:

```javascript
<Rect
          height={32}
          width={120}
          fill={'red'}
          cornerRadius={8}
          draggable
          dragBoundFunc((pos) => { 
             console.log('position rectangle: ', pos) 
          }
/>
```

When the stage is initial (top: 0 , left: 0) the dragboundfunc returns the correct position.
But as soon  as I scroll the stage a bit , the position provided by the dragboundfunc is incorrect...

With the normal scrolling (not emulated) the dragBoundFunc position is always correct (even when the stage is scrolled)

**Comment by lavrton** [comment]
I need a demo.

**Comment by jellohouse** [comment]
I'm trying to build the demo. Having some minor issues right now but almost works: https://codesandbox.io/s/react-konva-dragboundfunc-transformed-stage-znd5p2?file=/src/index.js

**Comment by lavrton** [comment]
To me, the position looks correct. Remember that `dragBoundFunc` operates in ABSOLUTE POSITION. Not relative position.

**Comment by jellohouse** [comment]
Ok sorry the example was not working well. Please have a look now. Same link: https://codesandbox.io/s/react-konva-dragboundfunc-transformed-stage-znd5p2?file=/src/index.js

If you drag the rectangle initially the position is provided properly from dragBoundFunc.

But then if you scroll the screen just a bit, and drag the rectangle again. 
The position returned from dragBoundFunc is clearly wrong...

**Comment by lavrton** [comment]
> But then if you scroll the screen just a bit, and drag the rectangle again.
> The position returned from dragBoundFunc is clearly wrong...

Why is it wrong? I just tried to scroll a bit. For me, it reports `position x = 500`. And that look correct to me, because that is what you do in your scroll handler:

```js
 const padding = 500;

  function repositionStage() {
    var dx = scrollContainer.current.scrollLeft - padding;
    var dy = scrollContainer.current.scrollTop - padding;
    stage.current.container().style.transform =
      "translate(" + dx + "px, " + dy + "px)";
    stage.current.x(-dx);
    stage.current.y(-dy);
  }
  ```
  
  When scroll there is not scrolling, you stage will be moved by padding value.

**Comment by jellohouse** [comment]
Well if you move the rectangle initially without scrolling the screen:
It starts at {x : 12, y: 12} and when you move it, it stays around the values as expected. 

But try it again: let's say you drag it to { x : 40, y: 40 } and then you scroll the screen just a bit. Then move the rectangle again, and it jumps to something like { x : 540, y: 540 }...

But I would expect it to stay around the values { x : 40, y: 40 } because that's where it just was before scrolling... How does it jump like this?

Maybe this method 4 described here: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#How-to-display-and-scroll-a-very-big-html5-canvas
is not correct?? Or is definitely not working as we would expect?

**Comment by jellohouse** [comment]
Just to play around I forked my example and I made another where the Padding = 0

Example with padding = 0: https://codesandbox.io/s/react-konva-dragboundfunc-transformed-stage-padding-0-nv1c9c?file=/src/index.js

Example with padding = 500: https://codesandbox.io/s/react-konva-dragboundfunc-transformed-stage-padding-500-znd5p2?file=/src/index.js

Even with the one with padding = 0. We see a strange behavior when you drag the rectangle and then scroll the canvas, and drag again a few times. We see the position returned from dragBoundFunc jumps around...

**Comment by lavrton** [comment]
Again, `dragBoundFunc` is working with **absolute position** of the rectangle. That absolute position is calculated from top-left corner of the stage container.

```js
<Rect
              x={rectPos.x}
              y={rectPos.y}
              width={120}
              height={60}
              fill="red"
              draggable
              dragBoundFunc={(pos) => {
                console.log("position", pos);
                setRectPos(pos);
              }}
/>
```

This usage is not correct. You are using **absolute position** from `dragBoundFunc` as relative position in `x` and `y` attributes. If it is confusing for you, don't use `dragBoundFunc`. Instead just use `dragmove` event.

It should be expected that you see jumping in position value. It is always close to 0 when you drag the rectangle near top-left at any scroll position.

**Comment by jellohouse** [comment]
Ok makes sense. I understand - the `dragBoundFunc` returns a position absolute from the top left of stage that we see on screen.

----

So here's really what I'm trying to do at the same of this emulated scrolling. I want the rectangle to snap to a grid when I drag it.

Here is an example of what I have so far: https://codesandbox.io/s/react-konva-dragboundfunc-transformed-stage-grid-6z3yz0?file=/src/index.js

As you can see, once we scroll the canvas, the snap is off the grid. (Because of this absolute position returned by the `dragBoundFunc`)

Any ideas on how to approach this issue?
Thanks in advance!

**Comment by lavrton** [comment]
Just use `dragmove` event. Work with relative coordinates. They are much simpler to understand.

```js
 onDragmove={(e) => {
                const pos = e.target.position();
                let newPosXgrid = Math.round(pos.x / 80) * 80;
                let newPosYgrid = Math.round(pos.y / 80) * 80;
                e.target.position({
                  x: newPosXgrid,
                  y: newPosYgrid
                });
}}
```

**Comment by jellohouse** [comment]
Ok that works great! Makes sense - I will start using onDragMove instead.

Thanks so much for everything @lavrton - you we're super helpful!
