### ISSUE TITLE
Getting the shapes that comes inside rectangle

### ISSUE THREAD

**Issue by syed-gamd** [konvajs/react-konva#664]
Hi guys!

I was experimenting react-konva and I am facing performance issue while getting the shapes that comes inside the rectangle.

I wanted to know is there is any better way to get all the shapes that comes inside the rectangle without looping all the shapes on each pixel move and performance issue? Please advice

Note: Might I have 3k of shapes (circles and lines)

**Comment by lavrton** [comment]
1. do throttle intersection check. Not every mousemove, but every [x] ms instead.
2. cache calculations. Do you need to recalculate all shapes? Are they all moving? If not, probably you can reuse previous calculations.
