### ISSUE TITLE
can  raphael-lib based svg be manipulated with react-konva

### ISSUE THREAD

**Issue by biotech7** [konvajs/react-konva#665]
in a chemical sketcher, chemical bonds and other symbols are depicted in svg format on canvas based on raphael lib. 
my question is : all the depicted objects mentioned above could be munipulated(useState, useRef,useContext, hook....etc) with react-konva in a same instance/app?
if so, are there any examples or hints to follow?

Regards!

**Comment by lavrton** [comment]
I don't understand what you are trying to achieve. Do you have any specific example of what you want to do?

**Comment by biotech7** [comment]
for example:  as drawing a chemical structure on the raphael-lib based canvas, when hovering on the circle area and press key R，mouse event is caught and the text 'CH3' is replace with 'R'.
![snap](https://user-images.githubusercontent.com/49674341/165216493-d419fc6c-d056-45f9-b504-78b1ebfc8c71.jpg)

**Comment by biotech7** [comment]
![snap](https://user-images.githubusercontent.com/49674341/165227596-639b1337-623d-41d9-a5e7-7afa7a5557d0.jpg)

**Comment by lavrton** [comment]
IF you already control canvas with `raphael`, I don't think there is a space for `react-konva`.

**Comment by biotech7** [comment]
Ok, let me take a second thought on how to reconstruct a 'connection' between raphael and konva.

**Comment by biotech7** [comment]
failed to replace raphael with react-konva. cannot connect DOM-based toolbars with reac-konva canvas in terms of states,refs,contexts....etc. a reasonable framework is preferred.
