### ISSUE TITLE
How to maintain the order of images in a layer when drag and drop

### ISSUE THREAD

**Issue by climber2002** [konvajs/react-konva#666]
Hello, I have a Konva react application which on a layer it renders a list of images. And the images can be dragged and dropped. To improve the performance I followed the tutorial that when drag the image, it will be moved to another layer, and when drag ends it will be moved back to original layer.  The main code is as below,

```typescript
function RoomCanva({ room, editable, onAssetEdit, selectedAssetId, selectAssetWithId }: RoomCanvaProps) {

  let photosLayer: any = useRef(null);
  let dragLayer: any = useRef(null);

  const onDragStart = (photo: Shape<ShapeConfig>) => {
    photo.moveTo(dragLayer.current);
  }

  const onDragEnd = (photo: Shape<ShapeConfig>) => {
    photo.moveTo(photosLayer.current);
  }
  ...

  return (
    <div>
      <Stage ...>
         <Layer ref={photosLayer}>
           { photos.map(photo => <Image onDragStart={...} onDragEnd={...} ... /> }
        </Layer>
        <Layer  ref={dragLayer}>
       </Layer>
     </Stage>
   </div>
  )
}
```

It works perfectly and there is no drag lagging anymore. However I found that when the dragged image is moved back to the photos layer, it will get a high zIndex and be on top of other images. What I want is that when the image is moved back to the photos layer it maintains the original order. I tried to trigger a forceUpdate after drag ends by following [this tutorial](https://blog.logrocket.com/how-when-to-force-react-component-re-render/), however it seems it doesn't work. Any help is appreciated, thanks in advance.  🙏

**Comment by lavrton** [comment]
When you move the image back to the original layer, you need to manually restore its zIndex. Something like this:

```js
const zIndex = React.useRef();

const onDragStart = (photo: Shape<ShapeConfig>) => {
    zIndex.current = photo.zIndex();
    photo.moveTo(dragLayer.current);
}
  
const onDragEnd = (photo: Shape<ShapeConfig>) => {
    photo.moveTo(photosLayer.current);
    photo.zIndex(zIndex.current);
}
```
