### ISSUE TITLE
Please recomment package version

### ISSUE THREAD

**Issue by MinChanSike** [konvajs/react-konva#668]
Hello,
I'm using react, react-dom 17.0.2, got issue after added `react-konva` follow by  https://konvajs.org/docs/react/Intro.html

Any way, could you share recomment package version for react version 16, 17, 18, please?
For Example: `react 18.1.0  , konva@8.3.7 ,  react-konva@18.0.0-0`
Thanks

**Comment by lavrton** [comment]
For react version 17 do this:

```bash
npm install react-konva@17.0.2-6
```
