### ISSUE TITLE
onDragMove event only triggers once on Rect component

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#670]
Hey dude, I have been stuck on this problem for days. Hope you will be able to help me out. I am using react-konva. Users can draw a lot of polygons by connecting the points on Canvas with react-konva. They can also drag the rect to adjust the points. But, when user drags that rect, the onDragMove event only triggers once. So, the lines just move slightly. What are the possible reasons for that? But, for some reasons, if I had selected the entire polygon, the onDragMove event gets triggered as long as I don't let go of the click. But, the points are not moving correctly. I have attached the video of what I mean by that. Please take a look. So, what I need is, I need the onDragMove event to be triggered as user drags the rectangle.

https://user-images.githubusercontent.com/78017969/168206447-3c564ee6-219d-42e7-b99f-2f30b538743c.mp4

This is the Polygon which is wrapped with Stage and Layer
```
<Group
      draggable
      onClick={() => setSelectedShape({ type: 'polygons', id: polygon.id })}
      onMouseEnter={() => setFill(hexToRGB(polygon.chosenTagColor))}
      onMouseLeave={() => setFill('transparent')}
      ref={groupRef}
    >
      {polygon.isFinished && isSelected && (
        <Image
          x={lesserYArr[0]}
          y={lesserYArr[1] - 20}
          onClick={handleDeletePolygon}
          height={15}
          width={15}
          image={deleteBtn}
          onMouseEnter={() => {
            document.body.style.cursor = 'pointer';
          }}
          onMouseLeave={() => {
            document.body.style.cursor = 'default';
          }}
        />
      )}
      <Line
        ref={polRef}
        fill={fill}
        points={flattenedPoints}
        stroke={polygon.chosenTagColor}
        strokeWidth={3}
        closed={isFinished}
      />
      {points.map((point, index: number) => {
        const width = 6;
        const x = point[0] - width / 2;
        const y = point[1] - width / 2;
        const startPointAttr =
          index === 0
            ? {
                hitStrokeWidth: 12,
                onMouseOver: handleMouseOverStartPoint,
                onMouseOut: handleMouseOutStartPoint,
              }
            : null;
        return (
          <Rect
            key={polygon.id + x + y}
            x={x}
            y={y}
            width={width}
            height={width}
            fill="white"
            stroke={polygon.chosenTagColor}
            strokeWidth={3}
            onDragMove={handleDragMovePoint}
            draggable
            {...startPointAttr}
          />
        );
      })}
    </Group>
```

This is the **handleDragMovePoint** that gets called when user drags the Rect

```
const handleDragMovePoint = (
  state: ShapesReducerType,
  event: any,
  polId: string,
) => {
  const updatedState = { ...state };
  const updatedPolygons = [...updatedState.polygons];
  const polIndex = updatedPolygons.findIndex((pol) => pol.id === polId);
  const pos = [event.target.attrs.x, event.target.attrs.y];
  const index = event.target.index - 1;

  updatedPolygons[polIndex] = {
    ...updatedPolygons[polIndex],
    points: [
      ...updatedPolygons[polIndex].points.slice(0, index),
      pos,
      ...updatedPolygons[polIndex].points.slice(index + 1),
    ] as [number, number][],
  };

  updatedState.polygons = updatedPolygons;
  return updatedState;
};
```

I would really appreciate it if you can help me out with this problem. Thanks a lot

**Comment by nnha19** [comment]
I think it's the problem with updating the points. I put delay before calling the function to update the points. The onDragMove function gets called every time I drag before the points are updated. Could you please help me why it's being that way?? FYI, I took reference for drawing polygons from this codesandbox https://codesandbox.io/s/oxwx9q9ko6.

**Comment by lavrton** [comment]
@nnha19 make a small demo of your issue with minimal code.
