### ISSUE TITLE
How to perform rotation of a rectangle at a given point on the image.

### ISSUE THREAD

**Issue by itzavinashcodes** [konvajs/react-konva#673]
I am trying to get the Rotation of the rectangle shape placed on the image when an onClick event is called. 
I am using React-konva library where I have placed an image layer on top of the canvas stage, and for the shape I have used react-konva  rectangle shape. I am stuck at a point where integrating the react-konva shape on the image that is clickable. The issue is with the placing of rectangle at the pointer location (As shown in the image) Please help me with this. I am giving the CodeSandbox link where u can go through the code and guide me. 

[https://codesandbox.io/s/mapediting-87mx4y?file=/src/Rectangle.js](url)

![Screenshot (33)](https://user-images.githubusercontent.com/46845291/170254500-10f5d1c4-3948-4922-b077-1332821123c9.png)

**Comment by lavrton** [comment]
Don't put a rectangle inside `<Label>` component.

**Comment by lavrton** [comment]
You are using `x` and `y` props from `shapeProps` for both `<Label>` and `<Rect>` components. As `<Rect>` is nested inside `<Label>` you applied position twice.

https://codesandbox.io/s/mapediting-forked-gzs5gi?file=/src/Rectangle.js
