### ISSUE TITLE
Konva Arrow

### ISSUE THREAD

**Issue by bearkillerPT** [konvajs/react-konva#677]
Hey! I'm currently finishing a project that makes great use of this marvelous tool. My project manager asked me to make it so that the user can click anywhere on the arrow and drag to create a new intermidiate point (no longer a straight line). I'm having some issues understanding how I should go about the part of clicking and dragging the new point... 
Can you tell me if it's possible and how please?

**Comment by lavrton** [comment]
What did you try?

I think you should:
1. Listen to click event
2. Calculate at what segment of the arrow is clicked
3. Add new point to that segement
4. Create a draggable circle (or another shape) at this point
5. Start its dragging, update points of arrow from "dragmove" event.

**Comment by bearkillerPT** [comment]
> What did you try?
> 
> I think you should:
> 
> 1. Listen to click event
> 2. Calculate at what segment of the arrow is clicked
> 3. Add new point to that segement
> 4. Create a draggable circle (or another shape) at this point
> 5. Start its dragging, update points of arrow from "dragmove" event.

Sorry I didn't close the issue sooner. Should have probably just have created a discussion. In any case thank you for your suggestion! 
I've since then buid a pretty fun diagram design tool that I'm pretty proud of. 
![image](https://user-images.githubusercontent.com/59414986/200603101-e706bbd4-3b14-44c1-885e-1547772e24db.png)
It's not perfect but the boss was pleased! 🤣
