### ISSUE TITLE
How do I make the shapes stay at the same place regardless of the width of the image

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#680]
Hello, I have the **stage** which width is inherited from it's parent by percentage. Inside the canvas we have image and, let's say a rectangle at 200 x and 200 y coordinates, indicating something is there. I also need the entire thing to be responsive. In smaller screens, the rectangle's position changes. I want it to stay the same regardless of the width. Is there any way to achieve that? If the width is fixed like 1000px, then it's ok. Nothing moves. But, I need to make it smaller on smaller screens without having affect on the shapes inside it. 

Here is a demo for that
https://codesandbox.io/s/react-konva-pan-zoom-forked-hf0b96?file=/src/App.js

I have drawn a polygon highlighting a person. But, if you resize the screen, the polygon is no longer indicating the person. It moves. I want those shapes to be fixed.

Thanks

**Comment by lavrton** [comment]
What do you mean by "the polygon moves"? In your demo, the polygon stays at the same place when I resize the window.
Do you want to move it when you scale the image? When I resize a window, the image is stretched. Is it expected for you?

**Comment by nnha19** [comment]
I want the polygon to stay at the same place relative to the image when the image scales. I guess, I want the polygon to scale as the image scales.  In the demo, I have drawn a polygon around a person, when I resize, the stage width and the image width changes. But, I want the polygon to still highlighting the person. Not move. Perhaps you should try refreshing after resizing the window to see the behavior

**Comment by lavrton** [comment]
For that case, just scale the image and your polygons. Use the same coordinate system for them. 
In this demo I am scaling whole stage: https://codesandbox.io/s/react-konva-pan-zoom-forked-ohzncm?file=/src/App.js

But you can put them all into group and scale it instead.
