### ISSUE TITLE
How to make the polygon not draggable outside of the container/canvas.

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#682]
I have a draggable polygon. I want it to always stay inside the canvas. It's draggable but not outside of the stage. With rectangle and ellipse, it was relatively simple. But, with polygon, I am not sure where to start. Please take a look at the demo below. We can also drag the rectangle that connects the point to adjust the points. I also want that to be within the container. Draggable but not outside of the box.

https://codesandbox.io/s/react-konva-draw-polygon-forked-nzwj2c?file=/src/index.js

1. Drag the entire polygon outside of the border ( I want it to stop when it touches the border)
2. Drag the circle to adjust the points ( same, I also want that to stop as it touches the border)

Thanks in advance

**Comment by lavrton** [comment]
So what you try?

You have `dragmove` event. Inside, you can control `x` and `y` attributes. Just calculated required limits and set them.

**Comment by nnha19** [comment]
I can calculate the limits, but when the limit has reached, I am not sure how to stop the dragging. At first I thought setting dragging to false will do the trick. But, we are only going to limit the dragging to one side, right? For instance, user drags the polygon all the way to the right and when it touches the right border, only dragging to the right side should not be allowed. All the other directions should work. Is there any way to achieve that? Like, allowing the dragging to false specificying the direction? Or what would be the other alternatives?

**Comment by lavrton** [comment]
Just set position according to limits:

```js
const minX = calculateMinX();
const maxX = calculateMaxX();
const oldX = node.x();
const newX = Math.min(Math.max(minX, x), maxX);
node.x(newX);
```

**Comment by nnha19** [comment]
minX and maxX of what? Group or the points? And what is x ?Did you mean oldX?

**Comment by nnha19** [comment]
Thank you. It's working. For those who might need this in the future, here is the working demo of it

https://codesandbox.io/s/react-konva-draw-polygon-forked-nzwj2c?file=/src/index.js
