### ISSUE TITLE
Making the stage responsive, but keep image export size

### ISSUE THREAD

**Issue by agonist** [konvajs/react-konva#686]
I'm building a tool where user can save the content of the stage to an image, so far everything works smooth, the only thing I'm trying to figure out right now is how do I make my stage responsive to any screen size without affecting the image export resolution which is 1500x500.

So far my component in itself is very simple. As it is, it has the expected behaviour. 
I don't really mind if it doesn't scale on resize, but if it can at least scale properly when the page is open and still reach the desired functionality it would be god enough.

```
<Stack>
            <Stage width={1500} height={500} ref={stageRef}>
                <Layer>
                // layer logic here
                </Layer>
            </Stage>

           <Button variant="contained" onClick={handleExport}>Save banner</Button>

        </Stack>
```

Any simple approach to achieve this ?

**Comment by lavrton** [comment]
Resize and scale the stage as you want.
Export not the stage, but internal node, like layer or group. I think it will simplify the process a lot.

**Comment by agonist** [comment]
I just tried to scale the stage and use a ref on my Layer instead of the Stage to save the image.
The saved image have the resolution I set 1500 x 500, but the content have the size of the scaled stage.

I'm probably missing something simple.

currently I'm saving it by specifying the resolution 
```
            const uri = layerRef.current!!.toDataURL({width: 1500, height: 500});
```
