### ISSUE TITLE
images rerenders on each click

### ISSUE THREAD

**Issue by Yogeshwar267** [konvajs/react-konva#687]
i have around 50 images displayed in a grid, and on each click a side bar opens, so when i click on any image, all images rerenders. how to resoles this, i am using konva with react.!

**Comment by lavrton** [comment]
Make a demo.
How did you implement the sidebar? Is it part of the canvas? How do you see that images are re-rendered?

**Comment by Yogeshwar267** [comment]
side bar is just a simple modal type, i have checked rendering and it always shows a flick as i am using loop to display multiple images

**Comment by lavrton** [comment]
Then please make a small demo.
