### ISSUE TITLE
Draggable Line is not firing dragEnd event

### ISSUE THREAD

**Issue by ufukomer** [konvajs/react-konva#688]
When I create a simplest draggable Line with react-konva, Line dragEnd event is not firing a the selected line is following the cursor even after the mouseUp event called. I can't figure it out and I never seen an example of draggable Line created with react-konva.

```jsx
<Stage
      width={700}
      height={400}
    >
      <Layer>
          <Line
              x: 20,
              y: 200,
              fill: 'red',
              draggable
              points: [100, 10, 200, 30],
              stroke: 'red',
              strokeWidth: 10,
              lineCap: 'round'
          />
     </Layer>
</Stage>
```

**Comment by lavrton** [comment]
Make a demo. How do you add listener?

**Comment by ufukomer** [comment]
@lavrton I have realized that it is working in a demo or in my app if it is not on a modal. Do you have an idea why that might be? Modal is preventing the dragEnd event to be called. It is really difficult to figure it out. I will try to create a basic version of my modal to create a demo.

**Comment by ufukomer** [comment]
I've found the issue, react-spring Transition is breaking its functionality. I don't know why, yet.

**Comment by ufukomer** [comment]
It was nothing about Transition, but the parent was calling:

`onMouseUp={(e) => e.stopPropagation()}`

Sorry for the inconvenience.
