### ISSUE TITLE
How to select the innermost shape without having to move the outermost shape when shapes are overlapping?

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#689]
Hello, I have two shapes which are overlapping. I need to make it so that the innermost shape can be selected without having to drag the outermost shape out of the way. Right now, the shape that was drawn last will have the higher zIndex. So, if two shapes are overlapping, only the shape that was drawn last can be hovered, dragged and clicked. Since I have a lot of shapes and I don't know which shapes are overlapping, rearranging the shapes array is not an option for me, I guess. Please, take a look at the demo. I need to make the inner polygon draggable and clickable without having to change the outer polygon.

https://codesandbox.io/s/react-konva-draw-polygon-forked-nzwj2c?file=/src/index.js

If I were to rearrange the order of the shapes array, I will have to know which ones are overlapping and if there are 2 of them, I need to find the one that is smaller, right? I guess, that would be quite hard. Plus, there could be more than 2 shapes that can overlap in my use canse. So, I was wondering if there is any solution to achieve that?

**Comment by lavrton** [comment]
The small polygon is not clickable because it is under the large polygon. As you used `closed` property, the line works as blob. It means its fill area (internal part) will trigger events.

There are two solutions.

1. You have to move a small polygon on top.

2. Or avoid using `closed` property. Close line manually by adding the first point into the end of points:

```js
<Line
  points={flattenedPoints.concat(flattenedPoints[0], flattenedPoints[1])}
  stroke={"green"}
  strokeWidth={3}
  hitStrokeWidth={10}
/>
```

https://codesandbox.io/s/react-konva-draw-polygon-forked-rs9dr1

**Comment by nnha19** [comment]
That solution doesn't really work for me though. I still need to be able to drag the polygon by dragging the empty space inside the lines. Plus, it doesn't work for other shapes like Rectangle and Ellipse. So, moving a small polygon/shape(Since polygon is not the only thing I am dealing with) on top, is there any way to detect the overlapped shapes and finding out the smaller one?? Is there any available solution for that or do I have to do that manually??

Thanks

**Comment by lavrton** [comment]
You may use this for overlapping calculations: https://konvajs.org/docs/sandbox/Collision_Detection.html#How-to-find-overlapping-objects-on-the-canvas. But that method is not accurate. You may need your own math (or a library) for accurate results.

It is up to you to calculate what shape is bigger/smaller.
