### ISSUE TITLE
Is there any available way for selecting the overlapping shapes. 

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#690]
Hello again, I am struggling to select the overlapping shapes. There are 3 shapes I am using. Rectangle, Polygon and Ellipse. When they overlap each other, I should be able to hover, click or trigger any events on the smaller shape as well as on the bigger shape. Must I rearrange the shapes inside an array?? Since, that is quite a common use case, I was wondering if there is any example out there. If someone has already done it

https://user-images.githubusercontent.com/78017969/175210404-a86824bf-9275-47b7-9d93-1cb0e0ec3ab1.mp4

Please look at the video file. That is exactly what I want to achieve. But, the shapes could be anything. Rectangle, Ellipse or Polygon. Rectangle insdie Polygon, Rectangle inside Ellipse or they can literally overlap in anyway. But, I should always be able to select the inner shape inside the bigger one.

Thanks

**Comment by lavrton** [comment]
So what is your question/issue? Just put a smaller shape on top.

**Comment by nnha19** [comment]
I dont know which one is smaller or which ones are overlapping cuz if two shapes are overlapping, none of the events get triggered on the smaller one.

**Comment by lavrton** [comment]
I am sorry. I don't understand your issue. Usually in such apps, the order of shapes is just defined by the order of their creation.
