### ISSUE TITLE
Dragging the end point of the polygon and everything else starts to lag after drawing over 7000 circles on Canvas

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#691]
Hi there, I have to draw over 7000 small circles/dots on Canvas. But, after drawing them, everything starts to become lag and no one is gonna be able to use it anymore. Is there any way to make it possible to display over 7000 circles and still make it work as before? Please look at the demo I have built and help me out.

https://codesandbox.io/s/react-konva-draw-polygon-forked-nzwj2c?file=/src/index.js

Everything works great before displaying these circles. I want to keep it that way. Please, click the button **display points** to see the behavior.

Thank you very much

**Comment by lavrton** [comment]
https://konvajs.org/docs/performance/All_Performance_Tips.html

**Comment by lavrton** [comment]
Caching usually is the simplest tool for good performance. You can put all circles into a group and then cache that group.

**Comment by VegetaWithoutBle** [comment]
> Caching usually is the simplest tool for good performance. You can put all circles into a group and then cache that group.

hi I think i meet the same problem, if i draw to many line, then i will become slow. How to use cache to make the render quickly? I try to cache line when i draw one , but i doesn't work even become more slower, I think i go to wrong way.

has any solution to cache the line ? and when to cache and clearcache the lines ?

**Comment by lavrton** [comment]
Caching individual shapes is not very helpful.

Caching is converting an object into a static image.

It is better to cache groups of shapes.

**Comment by nnha19** [comment]
I put all the shapes into group and cached the group. But, after caching, everything just dissapears. Why is that?? All the circles are gone.

**Comment by nnha19** [comment]
I have applied most of the suggestions on the doc to improve the performance and it got much better. But, surprisingly, having chrome dev tool open also impacts the performance significantly in my case. Not sure why though. Anyway, thanks for the help.
