### ISSUE TITLE
componentDidCatch TypeError: Cannot read properties of undefined (reading 'isBatchingLegacy')

### ISSUE THREAD

**Issue by BouncyKnight-LQ** [konvajs/react-konva#695]

**Comment by Ambition-J** [comment]
`
react-konva: ^17.0.2-5;
konva:^8.0.1
`

**Comment by lavrton** [comment]
What react version do you have? It looks like a mismatch between `react` and `react-konva` version. Make sure they have the same major version.

**Comment by mianmalife** [comment]
The downgrade to version 17 is back to normal. The latest version only supports react18. I feel that it should be supported to 17.
