### ISSUE TITLE
About type definition of shape-props 

### ISSUE THREAD

**Issue by naomei** [konvajs/react-konva#696]
## What is the correct way to get the props type of shape?

Is it correct below?

```ts
import React from "react";

// There is no "export" called Circle Props?
import { Circle } from "react-konva";

type CircleProps = React.ComponentProps<typeof Circle>;
```

## Why does the "NodeConfig" type use an index signature?

The definition is as follows.

```ts
// konva/lib/Node.d.ts
export interface NodeConfig {
    [index: string]: any;
}
```

Due to this effect, even non-existent fields can be specified.
How can this be resolved?

**Comment by lavrton** [comment]
> Due to this effect, even non-existent fields can be specified.

This is intentional. Because any Konva node may have any custom attribute.

For types probably this will work:
```js
import Konva from 'konva';
type CircleProps = React.ComponentProps<Konva.CircleConfig>;
```

But I am not sure what is the use case to create type for these props. All components should already have typed props when you use them.

**Comment by naomei** [comment]
@lavrton 

Thank you for your reply.

> But I am not sure what is the use case to create type for these props.

Needed as a wrapper-component in my project.
The purpose of the wapper-component is to have `transformer` built-in.
(want to use the transformer easily)

https://konvajs.org/docs/react/Transformer.html
