### ISSUE TITLE
container rotation is effecting the layer interactions

### ISSUE THREAD

**Issue by hashinclude72** [konvajs/react-konva#697]
rotating the `Stage` Container is rotating the stage and items are rendering properly in stage. But interactions(drag, hover, tap) with the items are not working properly, They are behaving as if they are in their original position.

 [Here is a sandbox link](https://codesandbox.io/s/magical-silence-7vmpct?file=/src/index.js)

you can try here to drag the stars

**Comment by lavrton** [comment]
Transforming stage with CSS is not supported. If you want to rotate it, use Konva methods. E.g. `rotation={90}
