### ISSUE TITLE
Konva warning: [object Undefined] is a not valid value for "crop" attribute

### ISSUE THREAD

**Issue by mordv** [konvajs/react-konva#699]
Despite it's declaration: `crop?: IRect;`, Image's `crop` can't handle an `undefined` value.

**Comment by lavrton** [comment]
You are right, Konva can't handle it. It doesn't expect undefined value. It is option in declaration because you may still use `node.crop()` function without any arguments.

**Comment by mordv** [comment]
On client's side it looks like it does, since by default `tsc` don't throw any errors with 
```tsx
<Image offset={undefined} crop={undefined}/>
```
Striclty speaking `crop?: IRect;` isn't the same as `crop?: IRect | undefined;` , but as far as I'm concerned, you only feel that with flag `exactOptionalPropertyTypes": true` (false by default, false in CRA)

In fact, if I recall, this is the first library in my practice where such differentiation is taken place. 

I used to work with r3f, and props there [are difined](https://github.com/pmndrs/react-three-fiber/blob/f882b4023ef67457e69e1000c6aa547b2b4af404/packages/fiber/src/three-types.ts#L38) exactly the same way - everything work as one would expect.

Considering this, I think an extra work should be done to filter out undefined props where needed. Currently otherwise intuitive and familiar operations like
```tsx
<Image crop={applyCrop ? crop : undefined}/>
```
become unnecessary complex.

**Comment by lavrton** [comment]
Probably. I think it will be expected that Konva will reset all crop values with it is `undefined`.
But personally, I prefer not to use componented attributes (such as `offset` and `crop`). Instead, I am using each attribute separatly. E.g. `<Rect offsetX={10} offsetY={10} />`

**Comment by mordv** [comment]
> I am using each attribute separatly

This would work as a workaround, thanks!

If someone would be interested in creating a PR, I believe it's enough to filter out undefined values from `updatedProps` before [this invocation](https://github.com/konvajs/react-konva/blob/950925060d5fd9cca748f570f8edc9f5f3cbfb91/src/makeUpdates.ts#L119).

**Comment by scottostler** [comment]
I ran into a variant of this, when transitioning an image component from having a crop to no longer having a crop. Essentially the following:

```
if (applyCrop) {
    return <Image crop={...} />
} else {
    return <Image />
}

I didn't set an `undefined` crop in my code, but this line would cause that to happen regardless: 
https://github.com/konvajs/react-konva/blob/950925060d5fd9cca748f570f8edc9f5f3cbfb91/src/makeUpdates.ts#L79

I can work around this by setting the four crop attributes individually (or alternatively, instead of removing the crop, using a no-op crop with the full image dimensions), but figured it was worth reporting

**Comment by lavrton** [comment]
Just pushed a little fix to konva for that case.
