### ISSUE TITLE
issues while positioning / changing z index of konva objects on stage

### ISSUE THREAD

**Issue by printmycopy** [konvajs/react-konva#704]
first of all great  lib , 
I am using react konva for developing an editor for memes but while i am changinh the z-index of the stage objects other predefined shapes in konva's docs are behaving properly but custom shapes made by using the line class do not work as needed I dunno if I am doing it right but on the predefined shapes like rect ,star,circle I am updating the height-width ontransform and x,y ondragEnd which works fine with zero issues while changing the z-index by changing the objects array-index as provided by u lavrton , but the real problem arises when i try to change the z-index of custom shapes with line class by providing points-coordinates to each point and then if i resize or change the z-index of the object they dont work properly perhaps I am using all the ontransform and ondragEnd functionalities with these custom shapes also....

**Comment by lavrton** [comment]
Make online demo to reproduce the issue.
