### ISSUE TITLE
Cancel dragging shape

### ISSUE THREAD

**Issue by maxaug999** [konvajs/react-konva#705]
With Konva for React, I am trying to cancel the dragging shape back to the position it was first clicked at (when it enters collision with another shape). I was wondering if there was a method (or event maybe?) for onDragEnd() specially

e.cancelBubble = true; does not work for me

**Comment by lavrton** [comment]
There are many ways. They may change depending on how you track position of a node into state.

The simplest is manual position set:
```js
onDragStart={(e) => {
  setInitialPosition(e.target.position());
}}
onDragEnd={(e) => {
  e.target.position(initialPosition);
}}
```
