### ISSUE TITLE
Mouse events sometimes not firing in Production Build on Brave Browser

### ISSUE THREAD

**Issue by SteveBenz** [konvajs/react-konva#708]
In this project:

https://stevebenz.github.io/ScrapMechanicLogicGateSimulator/index.html

sometimes the mouse events don't fire.  Easiest way to see it is to hover over the button rack at the bottom.  On the Brave browser (1.42.86) only some of the buttons will react to mouseover and click events.  Of those that do react, they often seem to be getting the mouse-enter events even when the cursor is outside of their boundaries.  But I can see no pattern at all in the buttons that do or don't see the mouse events or the boundary thing.  This also can happen to the objects you can create in the field - sometimes they see mouse events, sometimes they don't.  No particular pattern to it at all that I can see, but my best guess is that the boundary thing is key to it.  (E.g. the ones that don't highlight at all might have a zero extent.)

Also, the thing works fine in the debug build; no problem at all.

I think I'm using the latest version of everything:

    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-konva": "^18.2.1",

I'd appreciate any pointers you can give me.  The things I'm reporting seem completely impossible -- why would it repro in Brave and not Chrome or Edge when they're all based on Chromium?  Why only in the production build?  Makes no sense to me.  Any clue at all would be greatly appreciated.

**Comment by lavrton** [comment]
Probably this: https://github.com/konvajs/konva/issues/1132#issuecomment-867339732

**Comment by SteveBenz** [comment]
Thanks so much!  Yes.  That's it alright.  I went to Brave Settings -> Shields -> Block Fingerprinting and set that to 'Disabled' and boom, site works.
