### ISSUE TITLE
Jest and konva exports dont play well together

### ISSUE THREAD

**Issue by Amoodaa** [konvajs/react-konva#710]
https://github.com/konvajs/react-konva/issues/608#issuecomment-1222302573
I made a repro repo, this is a fresh create-react-app with typescript template
https://github.com/Amoodaa/konva-jest-repro
check the first few commits, and check the branch thats working by taking the build files from node_modules and letting jest export them

Questions?
- is there something wrong with my package.json test script?
- Is there a potential to allow for 0 configuration build version of the lib, as im using barebones create-react-app, and it doesn't work out of the box, which is an expectation i had because usually its the case
I've never done a library so i understand exporting and publishing good versions could be a whole big topic

**Comment by Amoodaa** [comment]
@lavrton

**Comment by lavrton** [comment]
Somehow, `jest.config.json` doesn't work for me. But it works if you set config via `package.json`:

```json
"jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(konva)/)"
    ]
  },
  ```
  
  
  But still react-konva may not be optimized for jest testing. It is design for DOM env. It may not render nodes without effect hooks.
