### ISSUE TITLE
'same props' error

### ISSUE THREAD

**Issue by vincentx** [konvajs/react-konva#713]
Hello there, 

I encountered a really strange problem. The StageWrap will log error 'same props' on the console, while I am resizing the window.  I dig into the source code, turns out that the usePrevious hook returns the exact same instance as the current props. It is really weird, since I have a resize listener registered to the window instance, and update the stage width and height with useState hook. Anything I am missing here? 

Best regards

**Comment by lavrton** [comment]
Demo?

**Comment by vincentx** [comment]
Here are a quick demo:

https://codesandbox.io/s/naughty-wiles-rm8zfv

I'm using Cloudscape design system. When I put the stage into the content slot, the 'same props' error logged. Without Cloudscape design system, it works fine without any errors.

**Comment by vincentx** [comment]
Thanks！
