### ISSUE TITLE
How can I render circles around rectangle in Konva js?

### ISSUE THREAD

**Issue by LuizProject46** [konvajs/react-konva#715]
I need to render table and chairs like in this picture:
![Captura de Tela 2022-10-19 às 16 38 49](https://user-images.githubusercontent.com/43315377/196789598-43343520-1baa-4ba0-ae86-ed23e1166c34.png)

I dont know how to calculate position of circles around rect. I tried some code, but its not working...Anybody knows how to solve it?

**Comment by lavrton** [comment]
Can you show what did you try?

**Comment by LuizProject46** [comment]
let smallCircleRadius = 20
    let tableSize = { 
        width: 120,
        height: ((seats-4/2)*(smallCircleRadius))
    }
    console.log(tableSize)
    let restartIndex = false
    let indexLetter = 0
    let controlY = 0
    let totalCircleSide = (seats-4)/2
    let controlX = 0
    let distanceY = 0
    let distanceX = 0
    let letters = alphabet()
    let table = new Konva.Rect({
        width: tableSize.width,
        height: tableSize.height,
        fill: '#fff',
        stroke: '#c3c6cf',//'#b2cfcf',
        strokeWidth: 8,
        x:150,
        y: 150
    });
    let count = 0

    group.add(table)


    for (var i = 0; i < seats; i++) {
        

        // let distanceToTable =  tableSize.width/2;
        // let x = i <= 2 ? table.x() + distanceToTable * i + (smallCircleRadius + 8) : count > totalCircleSide ? distanceToTable + distanceX+smallCircleRadius:  controlX
        // let y = i < 2 ? table.y() - distanceToTable/2: count > totalCircleSide ? controlY : distanceToTable + distanceY*smallCircleRadius

        
        //if(count > totalCircleSide) count = 0
        let x = table.x()
        let y = table.y()
        
        group.add(new Konva.Circle({ radius: smallCircleRadius, fill: '#d2d6df', stroke: '#c3c6cf',strokeWidth: 3, x, y }));
        
        //if(i > 0) count++ 

        // if((count+1) > totalCircleSide){
        //     controlY = y
        //     distanceX -=3
        // }else{
            //controlY+=i*smallCircleRadius/2
            // distanceY+=3
            // controlX = x
        //}
    }

**Comment by LuizProject46** [comment]
i dont have idea how to calculate :/

**Comment by lavrton** [comment]
Closing, as it is not really relevant to `react-konva`. It just pure math.
