### ISSUE TITLE
Setting a stroke width >1 on a <Text/>  introduces artifacts

### ISSUE THREAD

**Issue by liam-k** [konvajs/react-konva#716]
Hi, I just noticed an error while using react-konva (though the issue is likely with Konva itself). When setting a stroke width higher than 1 or 2, there are artifacts introduced in the stroke of some letters.

This is what it looks like:
<img width="586" alt="Screenshot 2022-11-11 at 16 55 05" src="https://user-images.githubusercontent.com/34057943/201381097-8a76e80e-70e8-4dc4-a0cf-45a0409ed8ba.png">

These are my settings:
(But I can also reproduce it in the demo from the readme of this repo: https://codesandbox.io/s/react-konva-basic-demo-forked-6nubhy?file=/index.js)
```
import { Text } from "react-konva";

      <Text
        text={"ABCDEFGHIJKLMNOPXYZ"}
        fontSize={26}
        fontFamily="sans-serif"
        fill="black"
        stroke="white"
        strokeWidth={8}
        fillAfterStrokeEnabled
        perfectDrawEnabled
      />
```
(In my screenshots there’s also a transformer attached to the text, but removing it doesn’t change anything. Neither does activating or deactivating perfectDrawEnabled or fillAfterStrokeEnabled)

However, I can reproduce this with a serif font...
<img width="479" alt="Screenshot 2022-11-11 at 16 55 18" src="https://user-images.githubusercontent.com/34057943/201381128-cea57f68-abaa-4fc5-9d13-7d1101bbff22.png">

... and also with a stroke width of four ...
<img width="475" alt="Screenshot 2022-11-11 at 16 55 41" src="https://user-images.githubusercontent.com/34057943/201381311-079f12c0-80e9-4e47-bb39-e30b3f490e9b.png">

... and even with a stroke width of 2, albeit the effect is only barely noticeable:
<img width="211" alt="Screenshot 2022-11-11 at 16 56 03" src="https://user-images.githubusercontent.com/34057943/201381840-a79be51f-0131-49a1-8c82-7be6c1c76b5d.png">

I can reproduce it in the latest versions of Chrome, Firefox and Safari (all on Mac).

Versions:
```
    "konva": "^8.3.11",
    "react": "^18.2.0",
    "react-konva": "^18.2.1",
    "react-konva-utils": "^0.3.0",
```

**Comment by lavrton** [comment]
That is out of Konva or react-konva control. That is how canvas rendering works.

**Comment by lavrton** [comment]
Possible workaround white custom filters for that. Detect text edges, draw pixels around them: https://konvajs.org/docs/sandbox/Image_Border.html#How-do-draw-a-stroke-around-image-with-alpha-channel
The demo is tricky use of shadows. But there are other algorithmic approaches.
