### ISSUE TITLE
Type information missing for onPointer events

### ISSUE THREAD

**Issue by bryndsey** [konvajs/react-konva#717]
Unlike other event types, onPointerUp/Down/Move events don't have corresponding props in the exported `KonvaNodeEvents` interface. This leads to issues in Typescript projects, like TS complaining about implicit typing, and those event handlers don't appear in auto-complete (initially leading me to believe they weren't supported, though in my limited testing it seems to work if I force my way around the missing type information).

You can see the issue [here in this codesandbox demo](https://codesandbox.io/s/jovial-zeh-4mvqu9?file=/src/App.tsx).

Is it possible to include these events in the props as well? Or is there a reason they were left out?

**Comment by lavrton** [comment]
It is just missing types. Do you want to make a Pull Request to fix it?
