### ISSUE TITLE
onTap does not fire on Samsung's mobile browser

### ISSUE THREAD

**Issue by willcrisis** [konvajs/react-konva#718]
Here's an example: https://codesandbox.io/s/exciting-morning-uiyfwg?file=/src/index.js

In Chrome Mobile and Firefox Mobile, when I tap the rectangle, it shows the alert without any problem. However, in Samsung's mobile browser it does not show it. `onTap` seems to work directly in the `Stage` tho, but does not work for any of its children.

Any idea on how I can get it working?

**Comment by lavrton** [comment]
What about `pointerclick` event? Do you have it?

**Comment by willcrisis** [comment]
Tried with `pointerclick`, `pointerdown` and `pointerup`. None of them seems to work. Might be a problem in how Samsung Internet browser handles Canvas rendering, as per https://github.com/konvajs/konva/issues/1398

I'll try to workaround it by detecting if there's a component in the clicked position.
