### ISSUE TITLE
how to fix yarn install react-konva konva run fail

### ISSUE THREAD

**Issue by markLabel9822** [konvajs/react-konva#722]
Server Error
Error: konva tried to access canvas, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: canvas
Required by: konva@npm:8.3.14 (via /Users/nitithorn/Desktop/flow/frontend/.yarn/cache/konva-npm-8.3.14-37d7faf6ad-a14ace4b62.zip/node_modules/konva/cmj/)

Require stack:
- /Users/nitithorn/Desktop/flow/frontend/.yarn/cache/konva-npm-8.3.14-37d7faf6ad-a14ace4b62.zip/node_modules/konva/cmj/index-node.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/react-konva-virtual-0eb93ea69c/0/cache/react-konva-npm-18.2.3-225def8889-b18868527e.zip/node_modules/react-konva/lib/ReactKonva.js
- /Users/nitithorn/Desktop/flow/frontend/.next/server/pages/workflow/builder.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/require.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/next-server.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/next.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/lib/start-server.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/cli/next-dev.js
- /Users/nitithorn/Desktop/flow/frontend/.yarn/__virtual__/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/bin/next

**Comment by lavrton** [comment]
Looks like you are trying to use konva inside nextjs env. Search for nextjs in react-konva package. You may find a lot of information.

But default Konva ready-to-use for browser environment. For NodeJS, you have to manually install `canvas` package.
