### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'hook')

### ISSUE THREAD

**Issue by ssrizkynugraha** [konvajs/react-konva#723]
I just installed react-konva to my ReactJS app and then this error appears rapidly even I move to another page. 

```
TypeError: Cannot set properties of undefined (setting 'hook')
    at d (<anonymous>:10:949)
    at c (<anonymous>:10:1426)
    at e (<anonymous>:10:1913)
    at e (<anonymous>:10:1931)
    at e (<anonymous>:10:1931)
    at e (<anonymous>:10:1918)
    at e (<anonymous>:10:1931)
    at e (<anonymous>:10:1918)
    at e (<anonymous>:10:1931)
    at e (<anonymous>:10:1931)
```
![image](https://user-images.githubusercontent.com/102504610/210295362-88848a17-2c81-4ccc-bb67-7858fe364a51.png)

**Comment by lavrton** [comment]
Demo? Most likely, it is a `react` and `react-konva` versions mismatch.

**Comment by ssrizkynugraha** [comment]
> Demo? Most likely, it is a `react` and `react-konva` versions mismatch.
Hi @lavrton, thanks for the response 
I'm using `react 18.2.0` and `react-konva 18.2.3`, are there any version requirements?

**Comment by lavrton** [comment]
What about `react-dom`?

**Comment by ssrizkynugraha** [comment]
Hi @lavrton 
My `react-dom` is `"18.2.0"`

**Comment by lavrton** [comment]
Then please make online demo.
