### ISSUE TITLE
How to make filters work together with custom transform logic

### ISSUE THREAD

**Issue by afdallah** [konvajs/react-konva#726]
Hi, 
I have images with filters in it and I want the transformer to only change the `width` and `height` instead of scale value.
But the problem is whenever I resize it with transformer, there is  flashing/glitch (see the video). I realize it's because of the node cache I applied to it under the useEffect.

I was thinking that maybe I need to clear the image cache but not really sure where or how to do it correctly. My current guess is onTransformEnd, which kinda work but then. we will see that the filter will not work, the filter removed for a split second after the transform and then it came back. Hope you can advice

Thanks so much

**Logic to update the width and height**
```javascript
 onTransformEnd={(e) => {
      const node = e.target;
      const scaleX = node.scaleX();
      const scaleY = node.scaleY();
      //node.clearCache(); <-- where should I put this?

      node.scaleX(1);
      node.scaleY(1);
      onChange({
        ...imageProps,
        x: node.x(),
        y: node.y(),
        scaleX: node.scaleX(),
        scaleY: node.scaleY(),
        width: node.width() * scaleX,
        height: node.height() * scaleY
      });
  }}
```

**Implement the cache to allow the filters**
```javascript
  React.useEffect(() => {
    if (image) {
      imageRef?.current?.cache();
    }
  }, [image, imageProps]);
  ```
  
  **The glitch**
video: https://www.loom.com/share/022912c44ecc4501a6c4b827d1a83136

**Demo**
https://codesandbox.io/s/konva-transformer-to-update-width-and-height-filters-j5rvbk?file=/src/index.js:545-669

**Comment by lavrton** [comment]
The issue is here:

```js
  React.useEffect(() => {
    if (image) {
      imageRef?.current?.cache();
    }
  }, [image, imageProps]);
  ```
  
  You re-cache image in effect. Regular effects are triggered in an async way after UI update. So you have that glitch effect for a moment. You see it because scale is reset back to 1, but width change is not applied yet because it is cached.
  
  Probably the most simple solution is this:
  
  ```js
    React.useLayoutEffect(() => {
    if (image) {
      imageRef?.current?.cache();
    }
  }, [image, imageProps]);
  ```

**Comment by lavrton** [comment]
But need to check performance here. Usually you don't need to re-cache on any update. Only when "non-transform" properties of images are changed, ignoring transform properties: x, y, scaleX, scaleY, skewX, skewY and rotation.

**Comment by afdallah** [comment]
You are awesome man, I was not really understand how the caching work earlier. thanks so much.

> But need to check performance here. Usually you don't need to re-cache on any update. Only when "non-transform" properties of images are changed, ignoring transform properties: x, y, scaleX, scaleY, skewX, skewY and rotation.

Just to make sure I understand it right. So basically we only need to cache on the first time and when something like filters changed right?

**Comment by lavrton** [comment]
Right. Filters, width, height or other visually attributes.

You don't need to re-cache when you change: x, y, scaleX, scaleY, skewX, skewY and rotation.

**Comment by afdallah** [comment]
Thank you so much @lavrton 
love your work and your support to the community
