### ISSUE TITLE
Rectangle TransformEnd function not working with React 18, strict mode and reducer

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#727]
Hello, I just recently upgraded  React version to 18 as well as react-konva and my rectangle and ellipse transforming is no longer working. I am using `useReducer` to update the rectangle attrs on transform end. As far as I understand, if we used `React.StrictMode`, reducer function gets invoked twice. In my react app, I am dispatching an action that updates the rectangle attrs when transformation has ended. Like this

```
 <Rect
        onClick={onSelect}
        onTap={onSelect}
        ref={shapeRef}
        {...shapeProps}
        draggable
        onDragEnd={(e) => {
          onChange({
            ...shapeProps,
            x: e.target.x(),
            y: e.target.y()
          });
        }}
        onTransformEnd={(e) => {
          handleTransformEnd();
          handleTransformEnd();
        }}
      />
```

So, due to `React.StrictMode`, `handleTransformEnd` function gets called twice and it causes the bug. I have heard that as long as the function is pure, it shouldn't cause any bugs. Have a look at the

 [codesandbox demo](https://codesandbox.io/s/optimistic-fermat-vw0ncv?file=/src/index.js:950-1579)

After the transformation, the rectangle size goes back to it's old state. 

**Note** : I intentionally called `handleTransformEnd` function twice, because in my react app, it's being invoked twice

**Comment by lavrton** [comment]
Can you make a demo with React.StrictMode and reducer?

Your demo doesn't work, because on the second call of `handleTransformEnd`, `node.width()` and `node.height()` has still old values because React didn't update the state and components.

**Comment by lavrton** [comment]
I think you need to find why it is called twice. I don't think StrictMode triggers events twice. It should be something else. Can't tell much with direct demo.
