### ISSUE TITLE
Canvas size is fix still when drawing points are different on two different browsers

### ISSUE THREAD

**Issue by vipulSoni458** [konvajs/react-konva#728]
Hello, first of all thank you so much for this amazing library. It's really awesome. Actually I am using react-konva for free drawing in my react application and I have Fixed the canvas size so that when I draw on one side it will reflect other side at the same place and it works perfectly. But suddenly this is not the case whenever I am drawing on one side and then it is not drawing at the same place on another browser and there is misalignment in points while drawing. The drawing made from 1st browser is not reflecting at the same place at second browser and vice-versa even I have fixed the canvas height and width. Like I am not understanding this, is this related to any browser dependency so that I am not getting correct coordinated of canvas using stage.getPointerPosition() or it is something related to device. If anyone has any idea about this please suggest how can I resolve this issue. Thank you

**Comment by lavrton** [comment]
Can you show how it looks in browser 1 and browser 2? Did you check the numbers?
