### ISSUE TITLE
onImageChange event not firing

### ISSUE THREAD

**Issue by simoami** [konvajs/react-konva#731]
Hello, specifying a handler for the `imageChange` event never fires. 

```
<Image
    image={image}
    onImageChange={(e: any) => {
        console.log(`Image change event fired`, e);
    }}
 />

```

Upon investigation this looks like a string case issue. Konva expects to receive `imageChange` in camel case form, however, react-konva, turns the whole event name into a lower case `imagechange`.

Proof that Konva expects `imageChange`: https://github.com/konvajs/konva/blob/master/src/shapes/Image.ts#L45

Proof that react-konva transforms all to lowercase and registers `imagechange` instead:  https://github.com/konvajs/react-konva/blob/master/src/makeUpdates.ts#L93

```
var eventName = key.substr(2).toLowerCase(); // sting case lost after lowercase 

...
for (var eventName in newEvents) {
 instance.on(eventName + EVENTS_NAMESPACE, newEvents[eventName]); <-- lower cased event name used to register event
}

```

The code does make an [exception](https://github.com/konvajs/react-konva/blob/master/src/makeUpdates.ts#L94) to the lowercase rule for events that begin with `onContent...` but it looks like a similar exception is needed for `onImageChange`.

Using a debugger, I was able to verify that registering a listener with the proper event name does fire the event.

Using react-konva v18.2.4

**Comment by lavrton** [comment]
You are right. But I would ignore that. I don't like "change" events and I don't recommend using them in any Konva apps. I would remove all mentions of these events from the docs.

In React app you should use `useEffect` for such scenarious.

**Comment by simoami** [comment]
Hi Lavrton, Thanks for the quick response. 
This decision will tax us in terms of performance. For example, the substitute for xChange in terms of useEffect is to continuously check for node.x(). This represents continuous execution of x(). In some cases, calculations are expensive, like with `node.getClientRect()` which returns accurate dimensions. 

Don't you think that your approach for transforming event names could be improved? The code assumes that all event names are comprised of one word after `on`. For example onSomeEvent is transformed into `node.on('someevent', ...)`. There's gotta be an improvement to the existing logic to preserve casing and only modify the first character.

**Comment by lavrton** [comment]
I don't understand the performance issue. Can you give a clear example?

> I recommend removing the .toLowerCase()

It will be a major breaking change. Some user (like me) are using `onMouseDown`. Without lowering the case, it will stop working.

We can handle "change" event as special case similar to "content".

**Comment by simoami** [comment]
I see the challenge. I'll blame Konva core for mixing naming conventions :)

I'm proposing to replace the following logic:

```
      var eventName = key.substr(2).toLowerCase();
      if (eventName.substr(0, 7) === 'content') {
        eventName =
          'content' +
          eventName.substr(7, 1).toUpperCase() +
          eventName.substr(8);
      }
```

with:
```
const customEventNamePrefixes = ['content', 'imageChange', 'xChange'];

function getEventName(propName: string): string {
  const eventName = propName.startsWith('on') ? propName.substring(2) : propName;
  const isCustomEvent = customEventNamePrefixes.some(name => eventName.toLowerCase().startsWith(name.toLowerCase()))
  if(isCustomEvent) return eventName.charAt(0).toLowerCase() + eventName.substring(1);
  return eventName.toLowerCase()
}

// TEST
console.log(
['onClick', 'onWheel', 'onDblClick', 'onMouseMove', 'onContentClick', 'onImageChange', 'onXChange'].map(prop => getEventName(prop))
)
> ['click', 'wheel', 'dblclick', 'mousemove', 'contentClick', 'imageChange', 'xChange']
```

A function is useful here because you have this logic twice in the same file.

**Comment by lavrton** [comment]
We can do this. If you are interested, you can make a Pull Request.

But as I mentioned, I believe usage of "change" is an antipattern and should be avoided. Especially in react app, where effects can do that job.

**Comment by simoami** [comment]
Thanks @lavrton I think the function I'm proposing will improve the existing code regardless of pattern. at a minimum, it will remove duplication in the current code and you can still control the events you want to support in the  `customEventNamePrefixes` array.

And regarding the reactive effect, are you sure that `node.x()`, `node.width()`, `node.scale()` and imageNode.image() are all reactive elements that would trigger a re-render ? I saw that you have a state that's used purely for reactivity, but is it being triggered for image change and other types of changes not directly supported as event listeners in react-konva? 

For background, I'm working on a Canvas component that is paired with a min preview canvas, like a small map within the map. For this to work, I need to synchronize the mini preview canvas to all sort of interactions on the main canvas. That includes image change, drag and wheel operations, updates to the main content is to be reflected on the preview in real time. A good example of this is the minimap view in VS Code, where you can see highlighted code redrawn as small rectangles. This requires a good amount of reactivity from all the elements in the main canvas.

**Comment by lavrton** [comment]
Closing the issue for now. As I still think listening to "change" event is an antipattern. There are hooks for that.

For "mine preview" case you still just need to use state of your app. And then render in "full" for main view and from the same store render into "minima" view.
