### ISSUE TITLE
Messy <Text /> alignment using webfont on Google Chrome

### ISSUE THREAD

**Issue by flavea** [konvajs/react-konva#736]
Hello, I am having a problem with the text component on Google Chrome. On the font I am using, it appears that there is something wrong with the text alignment when I am using center or right, but when I change it to another font, it seems normal. This also only happens on Google Chrome while it appears normally on Firefox.

With font Proxima Nova (the one I am using, self-hosted)
![image](https://user-images.githubusercontent.com/22873843/220073876-757ac273-2291-42f1-92fa-f6090c976799.png)

With Arial
![image](https://user-images.githubusercontent.com/22873843/220074844-01352636-264e-4921-a064-6759ee99b8e0.png)

I am stuck on this and not sure if this is a browser, font, or a library problem. Thank you.

react-konva version: 17.0.2-6
konva version: 8.3.5
react: 17.0.2
nextjs: 11.1.4

**Comment by lavrton** [comment]
Can you make online demo?

**Comment by flavea** [comment]
Hi! After a lot of digging turns out it's just a CSS problem, I was using ant-design which set font-variant and font-feature-settings to tabular num. And after setting them to normal the problem is gone and now they are aligning correctly. Thank you for responding!
