### ISSUE TITLE
JSX element type Stage/Layer/React does not have any construct or call signatures.

### ISSUE THREAD

**Issue by mixj93** [konvajs/react-konva#737]
![image](https://user-images.githubusercontent.com/12998118/222625933-14d447ae-278b-49e3-9560-8dec1a65447d.png)

Error occurs when using React 17.

```
  "dependencies": {
    "konva": "^8.4.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-konva": "17.0.2-6"
  },
```

Codesandbox: https://codesandbox.io/p/sandbox/konva-react-17-r2b0z0

**Comment by thatdevsherry** [comment]
I've encountered a similar error. What's interesting is that I had just tested konva using Create React App, and I never encountered an issue.

Now that I'm trying to use konva in a Vite project (which is what's also being used in the OP's codesandbox link), I'm getting the following error.

Using React 18.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/40890226/222722043-501546bd-bfe8-4089-a6d9-c12e7500a002.png">

**Comment by lavrton** [comment]
It looks like the issue because of mismatched `@types/react` and `react` version.

When I downgraded, It started to work just fine:

```js
npm install @types/react@17 @types/react-dom@17
```

Also, when I updated react + types and react-konva to the last version it worked ok.

**Comment by thatdevsherry** [comment]
@lavrton I looked at my `tsconfig` and found out that when I use `node16` for `moduleResolution`, the error I mentioned popped up.

Switching it back to `node` removed the error.

**Comment by mixj93** [comment]
> It looks like the issue because of mismatched `@types/react` and `react` version.
> 
> When I downgraded, It started to work just fine:
> 
> ```js
> npm install @types/react@17 @types/react-dom@17
> ```
> 
> Also, when I updated react + types and react-konva to the last version it worked ok.

Thanks a lot, install 17 version of types resolve this problem.
