### ISSUE TITLE
Transforming Text without changing font-size

### ISSUE THREAD

**Issue by jorge0136** [konvajs/react-konva#738]
### Problem: 

I want to be able to transform a `Text` node's size without impacting it's font-size but am unsure how to organize my `Transformer` to do so in `react-konva`. This request seems very similar to this other non-react [konva issue](https://github.com/konvajs/konva/issues/631).

### Attempted Solution: 
 Using the idea from the issue above I have built a [simple demo](https://codesandbox.io/s/brave-rui-7xj5iu?file=/src/index.js) (built on top of the [react-konva transformer example](https://konvajs.org/docs/react/Transformer.html)) showing the problem. When applying a reversed scale to the `Text` via `onTransform` it seems to move the `Text` node rather than scaling it. 

Any help would be greatly appreciated, thanks!

**Comment by lavrton** [comment]
```js
onTransform={(e) => {
  const node = e.target;
  node.setAttrs({
    width: Math.max(node.width() * node.scaleX(), 20),
    height: Math.max(node.height() * node.scaleY(), 20),
    scaleX: 1,
    scaleY: 1
  });
}
  ```
