### ISSUE TITLE
Konva Text - Text Orientation "Upright" not supported?

### ISSUE THREAD

**Issue by sprobejames** [konvajs/react-konva#740]
## Problem
Text Component has no text-orientation props.

## Question
Is it possible to achieve this(see image below) using the Text component of Konva? I read the documentation but it seems it has no option for `textOrientation`.

## Goal
Render a word 1 letter per line using the Konva Text Component.
![image](https://user-images.githubusercontent.com/72171823/224585997-8544a150-cac2-4ab9-a906-94f95ad17e74.png)

Any help would be greatly appreciated, thanks!

**Comment by lavrton** [comment]
Konva doesn't support that.
