### ISSUE TITLE
Cannot Set id Property of Stage

### ISSUE THREAD

**Issue by dlamprey** [konvajs/react-konva#745]
I am creating something based on this example, which is where I found that setting an id to the stage is not getting rendered:

https://codesandbox.io/s/react-konva-blur-part-of-image-forked-v0tb1y?file=/src/BlurImageTool.tsx

I added the id property as shown below to <Stage> without success:

...  
return (
    <div ref={containerRef}>
      <Stage
        id="canvas-konva"
        width={600}
...

Also tried:

...
return (
  <div ref={containerRef}>
    <Stage
      id={"canvas-konva"}
      width={600}
...

In both cases, the rendered <canvas> element has no id attribute. I also tried the latest and older versions of Konva and the results were the same.

Thanks for confirming whether this is an issue or if it is an error on my part.

**Comment by lavrton** [comment]
It should be fixed in `react-konva@18.2.8`. Please confirm.

**Comment by dlamprey** [comment]
belated thanks! i will confirm as i had come up with a workaround.
