### ISSUE TITLE
Redraw when moving layers or stage

### ISSUE THREAD

**Issue by mastern2k3** [konvajs/react-konva#746]
From the [docs] it states that each Konva layer has its own canvas:

> Konva stand out from other canvas libraries is that it enables us to create
> individual layers, each with their own canvas elements. This means that we can
> animate, transition, or update some stage elements, while not redrawing others.

But moving a layer around (setting its x or y props) or its containing stage causes
expensive redraw events, which in turn, slows down the frame rate.

The layer being moves doesn't undergo any changes other than repositioning.

What could I be missing?

p.s. I memoized everything under the layer which improved performance (since it was re-rendering the konva-react components too, but I still see the individual items on the layer taking time to be redrawn although no element on the layer is being altered) 

[docs]: https://konvajs.org/docs/performance/Layer_Management.html

**Comment by lavrton** [comment]
Please make a small demo.

**Comment by mastern2k3** [comment]
I've made a small demo.

It basically has one layer with a callback for mouse wheel movement.
When scrolling the mouse wheel, it updates the global stage's offsetX.
I was hoping that konva / konva-react will avoid redrawing, since each layer is cached, and we're basically just moving their x / y.

In this demo the layer is static and the mouse wheel moves the stage but the same happens when you
have the stage be static and the layer moving. 

Demo:
https://react-ts-85k9ff.stackblitz.io
Editor:
https://stackblitz.com/edit/react-ts-85k9ff?file=style.css

**Comment by lavrton** [comment]
Changing attributes of stage, will redraw all layers. 

You need to optimize canvas rendering. The first approach is to use caching. https://stackblitz.com/edit/react-ts-adiptv?file=App.tsx

Looks for other konva-related optimizations here: https://konvajs.org/docs/performance/All_Performance_Tips.html

**Comment by mastern2k3** [comment]
@lavrton Amazing thanks!

I couldn't find any in-depth information about how caching works, just this page: https://konvajs.org/docs/performance/Shape_Caching.html

I understand that once `element.cache()` is used, further renderings won't redraw the shape just copy the cached image.
Does that mean i'm only allowed to modify positioning from that moment on?
Can you explain when does it get invalidated or what will cause it to get invalidated?

**Comment by lavrton** [comment]
I updated the post with details. I hope it will help.
