### ISSUE TITLE
Stage issue with Suspense / lazy loaded components

### ISSUE THREAD

**Issue by alessandrotilli** [konvajs/react-konva#747]
Hi, I've encountered an issue when updating an app to React 18.

In a page there's a `Stage` component rendering some shapes. The stage is draggable and everything is ok until a lazy loaded component is mounted.
After the `Suspense` fallback is shown and the Stage is resumed drag doesn't work anymore.

I created a minimal [sandbox](https://codesandbox.io/s/konva-with-lazy-components-nkhjqx) to reproduce the problem.

Inspecting `window.Konva` it seems that when the stage is shown again after the Suspense it looses some listeners 

![Screenshot 2023-05-05 at 12 11 10](https://user-images.githubusercontent.com/2563389/236431839-7e8b428d-7e00-4e02-a651-738d305b3bc1.png)

Any hint?

**Comment by lavrton** [comment]
Released a fix with version `18.2.0`. Thanks for the detailed report and the demo.
