### ISSUE TITLE
Child components update before parent during updates

### ISSUE THREAD

**Issue by youking-lib** [konvajs/react-konva#748]
Description:
When using React-Konva library, I noticed an issue where the child components are updated before the parent during updates. This behavior can cause unexpected results and may affect the rendering of the application.

To reproduce the issue, please follow these steps:

Visit the following link: [Reproducible Example](https://ommu1g.csb.app/)
Open the browser developer tools.
Wait for the 3s timer to trigger an update.

You will notice that the "renderViewText" log appears before the parent component updates, indicating that the child components are updated ahead of the parent component.

Reproducible Example:
You can find the source code for the issue in the following CodeSandbox project: [Source Code](https://codesandbox.io/s/youthful-chebyshev-ommu1g?file=/src/index.js:843-847)

Please investigate this issue and provide a solution or workaround to ensure that the parent component updates before its child components during updates.

Thank you for your attention to this matter.

**Comment by lavrton** [comment]
Interesting. I added a unit test for that case. It is failing. I am not sure yet how to fix it.

**Comment by lavrton** [comment]
Looks like fixed with `react-konva@19`, `react@19`, `react-dom@19`
