### ISSUE TITLE
Shapes clustering support

### ISSUE THREAD

**Issue by jandresampaio** [konvajs/react-konva#749]
I've looked into documentation but don't find a way to automatically group or create a cluster based on the scale (zoom) level and proximity of the shapes.

I suppose this is not supported out of the box (with some setting) but, is there some example that can do this?
Thanks

**Comment by lavrton** [comment]
Konva has not built-in tools for that. You have to make your own implementation.
It is up to you to decide what and when to cluster. I don't have any konva examples.
