### ISSUE TITLE
Can't resolve 'canvas' with NextJS

### ISSUE THREAD

**Issue by MGMehdi** [konvajs/react-konva#750]
Hello,

I try to use Konva with NextJS but I've got this error
```
./node_modules/konva/lib/index-node.js:4:0
Module not found: Can't resolve 'canvas'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/react-konva/lib/ReactKonva.js
./src/app/page.tsx
```

I try to install `canvas` but it add more errors
Here is my dependecies list :
```json
"dependencies": {
    "@types/node": "20.2.5",
    "@types/react": "18.2.7",
    "@types/react-dom": "18.2.4",
    "autoprefixer": "10.4.14",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.4",
    "konva": "^9.0.2",
    "next": "13.4.4",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-konva": "^18.2.8",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
  }
```
### Step to reproduce

1. Create a NextJS project
2. Install and import Konva and React-Konva
3. Paste the exemple from the React-Konva intro page
4. Run de developpment server

**Comment by lavrton** [comment]
https://github.com/konvajs/react-konva#usage-with-nextjs

**Comment by MGMehdi** [comment]
Quick update, thanks for your work and the description for NextJS.
I use the latest version of NextJS (v13) and on top of dynamic import I have to put "use client" on the parent component to make it work

**Comment by lavrton** [comment]
@MGMehdi are you sure it is in parent? Not in child where stage is used?

**Comment by MGMehdi** [comment]
Yes I tried setting "use client" only on the child and got this error
```
Failed to compile
./node_modules/canvas/build/Release/canvas.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```
But if I put "use client" only on the parent or on both, it works
