### ISSUE TITLE
UseRef not updating Rect based on width of Text

### ISSUE THREAD

**Issue by hoetmaaiers** [konvajs/react-konva#753]
Hi,

I want a `<Text />` wrapped with a `<Rect/>` and have the rect width based on the text width.
Using a `ref={}` inside the text works but only if the Stage is rerendered. In this standalone example it only fallbacks to the `|| 50` value.

What am I missing?

CodeSandBox: https://codesandbox.io/p/sandbox/optimistic-bird-ntwnks

**Comment by lavrton** [comment]
This is how React works. You need to check text width on any updates:

```js

const [textWidth, setTextWidth] = useState(0);
useEffect(() => {
  if (textWidth !== textRef.current.width()) {
    setTextWidth(textRef.current.width());
  }
});

return (
  <>
    <Rect
      x={props.x}
      y={props.y - 20}
      width={textWidth}
      height={20}
      fill={props.color}
    />

    <KonvaText
      ref={textRef}
      text={displayName}
      x={props.x}
      y={props.y - 20}
      height={20}
      fill="black"
      alian="left"
      verticalAlign="middle"
      fontSize={12}
      padding={5}
      // @ts-expect-error Type 'string' is not assignable to type 'number'.
      width="auto"
    />
  </>
);
```

https://codesandbox.io/p/sandbox/blazing-haze-r358xn?file=%2Fsrc%2FApp.tsx%3A119%2C17
