### ISSUE TITLE
How to detect if all layers are drawn?

### ISSUE THREAD

**Issue by m1ker1n** [konvajs/react-konva#756]
Hi!

Can I somehow determine if all the layers are drawn? Or can I pass a callback function to be executed after layer.draw() (as if I were using non-React version of Konva)?

A little context. Our canvas sometimes renders for 2-5 seconds, and we would like to show the user a modal loader at this time.

**Comment by lavrton** [comment]
Layers have `draw` events. `layer.on('draw', callback);`

Why your canvas render that long? Do you mean like actual render of all shapes? Or also time for loading, etc?

**Comment by m1ker1n** [comment]
Time for loading included

**Comment by lavrton** [comment]
Then, I am not certain why you may need to listen to draw event. In regular apps (if you don't have too many shapes) rendering itself on the canvas takes a very short time.

So, you need to handle loading tracking by yourself.
