### ISSUE TITLE
How to set a Shape's Fillrule

### ISSUE THREAD

**Issue by mkusold** [konvajs/react-konva#757]
I'm trying to use the `Shape` component to support drawing polygons that have cutouts / holes in them. I'd like to use the `fillRule` value of `evenodd`, however I can't get the Shape to respect this setting. Any ideas? (I'm looking to avoid having to detect clockwise vs counterclockwise since the data I'll be getting is unreliable)

```
...
const drawCustomShape = (
    context: Context,
    shape: ShapeType<ShapeConfig>
  ): void => {
    for (let i = 0; i < coordinates.length; i++) {
      const shape = coordinates[i];
      context.beginPath();
      for (let j = 0; j < shape.length; j++) {
        const { x, y } = shape[j];
        if (j === 0) {
          context.moveTo(x, y);
        } else {
          context.lineTo(x, y);
        }
      }
      context.closePath();
    }
    // necessary Konva specific method that fill and stroke the shape based on its properties
    context.fillStrokeShape(shape);
  };

 <Shape
        sceneFunc={drawCustomShape}
        fill={"red"}
        stroke={"red"}
        strokeWidth={1}
        closed={true}
        fillRule="evenodd"
      />
```

**Comment by lavrton** [comment]
Can you make a full demo of what you are trying?

**Comment by atomAltera** [comment]
I have the same issue here, I have a Path with some text:
`          
<Path
            fill="white"
            data="M18.5001 14C18.5001 12.8954 19.3955 12 20.5001 12H24.5001C26.7092 12 28.5001 13.7909 28.5001 16V19C28.5001 21.2091 26.7092 23 24.5001 23H23.0001C22.7239 23 22.5001 23.2239 22.5001 23.5V26C22.5001 27.1046 21.6046 28 20.5001 28C19.3955 28 18.5001 27.1046 18.5001 26V21V14ZM24.5001 15H23.0001C22.7239 15 22.5001 15.2239 22.5001 15.5V19.5C22.5001 19.7761 22.7239 20 23.0001 20H24.5001C25.0523 20 25.5001 19.5523 25.5001 19V16C25.5001 15.4477 25.0523 15 24.5001 15ZM30.5 14C30.5 12.8954 31.3954 12 32.5 12C33.6046 12 34.5 12.8954 34.5 14V26C34.5 27.1046 33.6046 28 32.5 28C31.3954 28 30.5 27.1046 30.5 26V14ZM5.5 17.5C5.5 14.4624 7.96243 12 11 12C14.0376 12 16.5 14.4624 16.5 17.5V23V26C16.5 27.1046 15.6046 28 14.5 28C13.3954 28 12.5 27.1046 12.5 26V23.5C12.5 23.2239 12.2761 23 12 23H10C9.72386 23 9.5 23.2239 9.5 23.5V26C9.5 27.1046 8.60457 28 7.5 28C6.39543 28 5.5 27.1046 5.5 26V23V17.5ZM9.5 17.5C9.5 16.6716 10.1716 16 11 16C11.8284 16 12.5 16.6716 12.5 17.5V19.5C12.5 19.7761 12.2761 20 12 20H10C9.72386 20 9.5 19.7761 9.5 19.5V17.5Z"
          />`

In original SVG there are fill-rule and clip-rule attributes both set to evenodd, but when I try to set this attributes for Path element, it takes no effect.

**Comment by lavrton** [comment]
@atomAltera please also make a demo with the sample of expected rendering.
