### ISSUE TITLE
Why the event source of the transformer exhibits asynchronous behavior

### ISSUE THREAD

**Issue by CNsixgod** [konvajs/react-konva#759]
Hello, I have a question.why the event source of the transformer exhibits asynchronous behavior.
![图片](https://github.com/konvajs/react-konva/assets/40452908/8a07c25c-81b0-4294-a333-c4d7e1a5a422)
@lavrton 
https://codesandbox.io/s/busy-currying-vpqkjk

**Comment by lavrton** [comment]
I don't understand your question. Why do you think it is async?

**Comment by CNsixgod** [comment]
Sorry, I have a problem with my expression. Why is it that when I transform, the width and height of the shape obtained from the event source of the onTransform event do not change?

**Comment by lavrton** [comment]
Transformer is no changing width and height properties. Instead it is changing scaleX and scaleY.
