### ISSUE TITLE
React-konva / Konva is not working with single-spa

### ISSUE THREAD

**Issue by EasyBreezy97** [konvajs/react-konva#760]
I am facing this [issue](https://github.com/single-spa/single-spa/issues/1128) when I am using react-konva with single-spa. I think it is related to mostly **single-spa**. That's why I opened an issue on their GitHub page before opening it here. Is there some workaround to this problem that I configure with konva/react-konva?  @lavrton

**Comment by lavrton** [comment]
Closing as I don't know what I can do from `react-konva` side.
