### ISSUE TITLE
why does Arabic text appear contrariwise in <Text/>?

### ISSUE THREAD

**Issue by hosseinmobarakian** [konvajs/react-konva#763]
I use Arabic text in react-konva but when I write something this happens to me:
![image](https://github.com/konvajs/react-konva/assets/70088310/ddd2af1a-17c9-461b-95d5-d70927aa2ca4)

But I want something like this:
![image](https://github.com/konvajs/react-konva/assets/70088310/de7219f0-b859-466a-b102-846970663399)

**Comment by lavrton** [comment]
Can you make a demo? Do you use `letterSpacing` property?

**Comment by hosseinmobarakian** [comment]
Yes I used letterSpacing, now is fixed
