### ISSUE TITLE
How to make the Stage take up the entire Image width and height and prevent abrupt cropping of Image

### ISSUE THREAD

**Issue by z-piyushm** [konvajs/react-konva#764]
Hello.
How to prevent the cropping of Image to the Stage ?
https://codesandbox.io/s/react-konva-create-draw-rect-forked-n9snt5?file=/src/index.js

Inspite of calculating the image height and width  and  matching  it to the Stage width and height, the image is getting cropped out at a certain point.

How can I match the Range width to Image width ?

``` 

`const loadImage = (setImageDimensions, imageUrl) => {
  const img = new Image();
  img.src = imageUrl;

  img.onload = () => {
    setImageDimensions({
      height: img.height,
      width: img.width
    });
  };

  img.onerror = (err) => {
    console.log("img error");
    console.error(err);
  };
};


const [imageDimensions, setImageDimensions] = useState({});
const imageWidth = imageDimensions.width
const imageHeight = imageDimensions.height

<Stage
      className={classes.KnovaImage}
      style={{background:`url(${imgUrl})`}}
      onMouseDown={handleMouseDown}
      onMouseUp={handleMouseUp}
      onMouseMove={handleMouseMove}
      width={imageWidth}
      height={imageHeight}>
      <Layer>
        <Rect/>
        <Rect/>
      </Layer>
</Stage>

```

<img width="674" alt="Screenshot 2023-08-24 at 11 53 35 PM" src="https://github.com/konvajs/react-konva/assets/112086348/23c6f99e-4950-40bb-b623-9297081fa2ca">

**Comment by lavrton** [comment]
Can you make a small demo of your issue?

**Comment by z-piyushm** [comment]
> Can you make a small demo of your issue?

https://codesandbox.io/s/react-konva-create-draw-rect-forked-n9snt5?file=/src/index.js

i have created a codesandbox link. Thank you!

**Comment by z-piyushm** [comment]
> Can you make a small demo of your issue?

I have updated my issue,can you help me with it ? Thanks

**Comment by lavrton** [comment]
I am not certain how to reproduce that. How can I reproduce in that sandbox?

**Comment by z-piyushm** [comment]
> Can you make a small demo of your issue?

https://codesandbox.io/s/react-konva-create-draw-rect-forked-n9snt5?file=/src/index.js

I have reproduced it in this codesandbox link

**Comment by z-piyushm** [comment]
> I am not certain how to reproduce that. How can I reproduce in that sandbox?

https://codesandbox.io/s/react-konva-create-draw-rect-forked-n9snt5?file=/src/index.js
I have reproduced the issue in this codesandbox link. Thank you
