### ISSUE TITLE
Loading local svg file into Image not working

### ISSUE THREAD

**Issue by udarts** [konvajs/react-konva#765]
I have a svg file which is stored locally and I am trying to load that into the Image component of react-konva.
Somehow I am not getting anything shown. 

I try to load it like:

    import { Stage, Layer, Image } from 'react-konva';
    import useImage from 'use-image';

    import local_svg from '../path_to_local_svg_image.svg';

    const CanvasImage = () => {
        const [localSvg] = useImage(local_svg);

        return (
            <Stage>
                <Layer>
                    <Image image={localSvg} />
                </Layer>
            </Stage>
        );
    };

    export default CanvasImage;

Do I miss anything?

**Comment by lavrton** [comment]
Code looks good. Can you make a demo? Are you sure your `local_svg` is a correct image path that is available?
