### ISSUE TITLE
canvas in full screen

### ISSUE THREAD

**Issue by devPhysics** [konvajs/react-konva#767]
Hello, 
I am currently utilizing react-konva to draw on a canvas. I have successfully made the canvas full-screen by implementing react-full-screen. While it works efficiently with a mouse, I have noticed some sluggishness when using a touchscreen.  This difference is not apparent when I simulate touch screen on chrome inspect element, but it becomes more noticeable when using a real touch screen device, particularly one with a larger screen.
you can find [code here](https://codesandbox.io/s/react-konva-draw-q5r9gk) and [test here](https://q5r9gk.csb.app/)

**Comment by lavrton** [comment]
When do you see it slow? Immediately? After you draw some lines (how many?)?
Did you try to run a profiler to see what is slow?

**Comment by devPhysics** [comment]
https://github.com/konvajs/react-konva/assets/89291171/cd1f54da-ddbb-47db-b41f-e6784a073dff

You can see in the above screen capture that it misses some points in the path. You can see the diffrence in first 'are' and in second 'you'.

Honestly, I don't know how to run profiler

**Comment by lavrton** [comment]
Closing as I am not sure how to help. You need to check performance with profiler. If it is slow because of the canvas rendering, you can use some konva tips to make it faster: https://konvajs.org/docs/performance/All_Performance_Tips.html#HTML5-Canvas-All-Konva-performance-tips-list
