### ISSUE TITLE
Object snapping with multiple nodes in transformer

### ISSUE THREAD

**Issue by Skyleen77** [konvajs/react-konva#768]
Hello,

Is it possible to do a snap (like [link](https://codesandbox.io/s/react-konva-snap-1mq1g2?file=/src/App.tsx)) of a group of elements selected by `trRef.current?.nodes(selectedRefs)` ?

I would like the snap to work for the selected element group.

Thanks

**Comment by lavrton** [comment]
In the link there is `getObjectSnappingEdges` function that calculates bounding box of a konva node and find snapping. I am using this for transformer:

```js
function getObjectSnappingEdges(transformer: Konva.Transformer) {
  const trRect = transformer.__getNodeRect();
  const box = getClientRect({
    ...trRect,
    rotation: Konva.Util.radToDeg(trRect.rotation),
  });
  const absPos = transformer.getAbsolutePosition();

  return {
    vertical: [
      {
        guide: box.x,
        offset: absPos.x - box.x,
        snap: 'start',
      },
      {
        guide: box.x + box.width / 2,
        offset: absPos.x - box.x - box.width / 2,
        snap: 'center',
      },
      {
        guide: box.x + box.width,
        offset: absPos.x - box.x - box.width,
        snap: 'end',
      },
    ],
    horizontal: [
      {
        guide: box.y,
        offset: absPos.y - box.y,
        snap: 'start',
      },
      {
        guide: box.y + box.height / 2,
        offset: absPos.y - box.y - box.height / 2,
        snap: 'center',
      },
      {
        guide: box.y + box.height,
        offset: absPos.y - box.y - box.height,
        snap: 'end',
      },
    ],
  };
}
```

I hope it will help.

**Comment by Skyleen77** [comment]
> Hello,
> 
> Is it possible to do a snap (like [link](https://codesandbox.io/s/react-konva-snap-1mq1g2?file=/src/App.tsx)) of a group of elements selected by `trRef.current?.nodes(selectedRefs)` ?
> 
> I would like the snap to work for the selected element group.
> 
> Thanks

If I understand correctly, it is more interesting to use snapping on the transformer rather than on the nodes directly?

However, what is the `getClientRect` function here?

Thank you for the quick reply !

**Comment by Skyleen77** [comment]
Should I also modify `getLineGuideStops` so that the lines correspond to the transformer?

**Comment by Skyleen77** [comment]
Do you have an example or a codepen so I can understand a little better how it works?

Sorry for all these questions

**Comment by Skyleen77** [comment]
> Do you have an example or a codepen so I can understand a little better how it works?
> 
> Sorry for all these questions

J'ai fait ce codesandbox pour illustrer mon problème : [link](https://codesandbox.io/s/react-konva-snap-forked-5wkdgv?file=/src/App.tsx)

**Comment by Skyleen77** [comment]
Let me remind you @lavrton about this problem.

Thank you in advance for your help 🙏

**Comment by lavrton** [comment]
`getClientRect` is just a math function to calculate bounding boxes. I am using this:

```js
function getCorner(pivotX, pivotY, diffX, diffY, angle) {
  const distance = Math.sqrt(diffX * diffX + diffY * diffY);

  /// find angle from pivot to corner
  angle += Math.atan2(diffY, diffX);

  /// get new x and y and round it off to integer
  const x = pivotX + distance * Math.cos(angle);
  const y = pivotY + distance * Math.sin(angle);

  return { x: x, y: y };
}

export function getClientRect(element: ShapeType) {
  const { x, y, width, height } = element;
  const rad = Konva.Util.degToRad(element.rotation);

  const p1 = getCorner(x, y, 0, 0, rad);
  const p2 = getCorner(x, y, width, 0, rad);
  const p3 = getCorner(x, y, width, height, rad);
  const p4 = getCorner(x, y, 0, height, rad);

  const minX = Math.min(p1.x, p2.x, p3.x, p4.x);
  const minY = Math.min(p1.y, p2.y, p3.y, p4.y);
  const maxX = Math.max(p1.x, p2.x, p3.x, p4.x);
  const maxY = Math.max(p1.y, p2.y, p3.y, p4.y);

  return {
    x: minX,
    y: minY,
    width: maxX - minX,
    height: maxY - minY,
    minX,
    minY,
    maxX,
    maxY,
  };
}
```

**Comment by jezikk** [comment]
@lavrton thank you for your reply. Second question is how to force object position to the Transformer as a whole. Because the following logic is not working for transformer with more nodes.

```
 const absPos = node.absolutePosition();

          for (const lg of guides) {
            switch (lg.orientation) {
              case "V": {
                absPos.x = lg.lineGuide + lg.offset;
                break;
              }
              case "H": {
                absPos.y = lg.lineGuide + lg.offset;
                break;
              }
            }
          }

          node.absolutePosition(absPos);

```
