### ISSUE TITLE
TypeScript issue

### ISSUE THREAD

**Issue by divmgl** [konvajs/react-konva#770]
```
JSX element type 'Stage' does not have any construct or call signatures.ts(2604)
```

Happens in a brand new Vite installation with a `Stage` component.

**Comment by lavrton** [comment]
Please make a very minimal repository to reproduce it. I just created a new project with vite, and the import was working just fine.

**Comment by jonaskello** [comment]
Just to add one more datapoint: I have the exact same error in a larger monorepo project. Tried to reproduce it in a small repo but then the error did not appear.

**Comment by divmgl** [comment]
Apologies, yes, this is in a monorepo. And we ended up moving away from the Konva solution. Sorry about that.

**Comment by jonaskello** [comment]
I think it is related to `@types/react` package versions being mixed in a monorepo. In our case one package was using version 18 and importing another using 17 that hade the react-konva stuff in it and that triggered this error. It would probably work if all packages in the monorepo has the exact same version of `@types/react` as the packages they are importing.

**Comment by GeoMarkou** [comment]
In my case I updated the `package.json` to target a specific version of React and React-DOM. It seems NPM was resolving the `^` to a slightly different version, which caused subtle errors like this. Leaving this here in case it helps anyone else, thank you @jonaskello for the hint.

```diff
- "react": "^18.2.0",
+ "react": "18.2.0",
- "react-dom": "^18.2.0",
+ "react-dom": "18.2.0",
- "@types/react": "^18.2.21",
+ "@types/react": "18.2.21",
- "@types/react-dom": "^18.2.7",
+ "@types/react-dom": "18.2.7",
```
