### ISSUE TITLE
OnMouseMove not working on a Layer

### ISSUE THREAD

**Issue by MaxWilson** [konvajs/react-konva#771]
OnMouseMove doesn't always fire on a layer but does on a stage. Might be related to #590.

**Repro:** check out https://github.com/MaxWilson/Arena/tree/konva/repro590 and run startAll.cmd. Navigate to http://localhost:8080, hit the Execute button, and then try to interact with the display at the bottom. (Screenshot below.)

**Expected:** onMouseMove triggers whenever you move the mouse over the display, and the name of the monster you're closest to is highlighted.
**Actual:** onMouseMove seems to only trigger occasionally, basically at the same time as onMouseOver.

**Known workaround:** refactor the code so that onMouseMove lives on the stage instead of the layer. See https://github.com/MaxWilson/Arena/commit/c9db2ee86106553d9405ceb2ce832dd27e392eea

<img width="651" alt="image" src="https://github.com/konvajs/react-konva/assets/6829565/5949d8d3-d8fc-4564-b9b5-5d55813d7fbf">

**Comment by lavrton** [comment]
Please make a minimal demo. Also please remember that layer doesn't trigger `mousemove` events when the mouse is over empty space. All layer events are starting from the shapes. So you can just listen events on the stage or place transparent shape as the background.

**Comment by MaxWilson** [comment]
RE: <<Also please remember that layer doesn't trigger mousemove events when the mouse is over empty space.>> Oh, I didn't know that. That must be it then.
