### ISSUE TITLE
Blur Image in react konva

### ISSUE THREAD

**Issue by phamlam2k** [konvajs/react-konva#772]
I see in the docs we have blurRadius for set blur in the Image but in the Image tag now I don't see that props and I don't know how to get blur on that Image. Please help me

**Comment by lavrton** [comment]
It is for blur filter: https://konvajs.org/docs/filters/Blur.html#sidebar
Here how to use filters with react-konva: https://konvajs.org/docs/react/Filters.html

**Comment by phamlam2k** [comment]
Thanks for your answer, It work! but what is pixelRatio use for in cache `imageRef.current.cache({ pixelRatio: displaySetting['anonymization'] ? 0.5 : 1 })`

**Comment by lavrton** [comment]
pixelRatio controls the size of the cached image, it is like cache quality.
