### ISSUE TITLE
Is a native Text Editor coming soon?

### ISSUE THREAD

**Issue by jonathanrstern** [konvajs/react-konva#773]
@lavrton Right now, I'm using react-konva-utils's Html element to add a textarea to my Konva when a user double clicks.

It works, but I'm looking for something better.

Do you know of any Konva projects with full, rich text editor functionality?

**Comment by lavrton** [comment]
In Konva discord community there is a is person who is working on a Rich Text library on the canvas.
I also have plans to play with https://github.com/Hufe921/canvas-editor and possible make an integration.

**Comment by jonathanrstern** [comment]
Thank you @lavrton!!
