### ISSUE TITLE
Best way to draw a handle

### ISSUE THREAD

**Issue by nnha19** [konvajs/react-konva#776]
Hello, what would be the best way to draw a handle like the one in the image below? 

My requirement is, I have a `rectangle` as a stick like a handle bar and now I need to draw a handle. The rectangle is draggable and x coordinate is updated as user drags the rectangle.

What I have tried so far is displaying fontawesome icons with `Html wrapper` which works just fine (picture below).

**What I want**
![image](https://github.com/konvajs/react-konva/assets/78017969/73f16fa4-bf7f-461d-9847-1d8b259139cd)

**My Attempt with Html wrapper**
![image](https://github.com/konvajs/react-konva/assets/78017969/1ae6795c-fd74-42bc-acce-69a6c7f22062)

**Issue with Html wrapper**
When I zoomed in, the coordinates of the handle are messed up. Plus, I am not sure if there is a better ideal way of doing this.

![image](https://github.com/konvajs/react-konva/assets/78017969/f0534226-a5b1-4f81-a5c3-2fd148ea0545)

**Comment by lavrton** [comment]
May it be simpler to just use Konva shapes? Once circle and two triangles inside of it?
