### ISSUE TITLE
Advice for `cache` usage w.r.t memory leak

### ISSUE THREAD

**Issue by jack-tutor** [konvajs/react-konva#777]
Hi, I am working on a web app that frequently has images streamed to it.  We render these images using `react-konva` - and on one set of images, we are applying a filter a la: https://konvajs.org/docs/react/Filters.html

This means that we are consistently calling `.cache()` though on the same `useRef` attached to the same `KonvaImage` component.

The web app has a memory leak which appears to be due to images, though not necessarily react-konva.  I'm lookiing to find out:
* would this use of `.cache` be expected to cause a memory leak in this scenario
* are there ways to wipe the cache globally or prior to caching a new item (I see there is a method `clearCache` but the impact of this function is unclear to me)

Thanks

**Comment by lavrton** [comment]
Calling `node.cache()` should not produce any leaks. A new cache just overwrite the old one. There is no global cache, only cache per node. So if a node is destroyed, or you cleared cache manually with `node.clearCache()` all should be ok.

You need to run a memory profile to see what is leaking.
