### ISSUE TITLE
Same `Module not found: Can't resolve 'canvas'` in nextjs 13.5.5

### ISSUE THREAD

**Issue by wjlee2020** [konvajs/react-konva#778]
I followed https://github.com/konvajs/konva/issues/1458 this issue to try and solve this error, but none of the solutions worked.
I remember having it ran on a slightly older version (next 13.4.19), so I downgraded my next dependency and it seems to work now.

If this isn't the right place, please close this issue and I apologize for making noise.

**Comment by lavrton** [comment]
I updated docs again: https://github.com/konvajs/react-konva#usage-with-nextjs

Just tested with the last version. Worked ok for me. Please try it.
