### ISSUE TITLE
Poor performance in production build

### ISSUE THREAD

**Issue by SBenni** [konvajs/react-konva#779]
Hi,
my react-konva renders nearly by 60fps in debug mode (react scripts start).
But in production mode (react-scripts build) renders the same app only by 20fps?

https://codesandbox.io/s/lucid-ganguly-4lgqrx

This is the app, scrolling by horizontal scrollbar ist very fast, but on production build very slow?

Thank you

**Comment by lavrton** [comment]
I don't see a difference on my machine.

**Comment by lavrton** [comment]
BTW. Instead of using `visible=false` on a Konva node, it will be better to remove if from the scene. Like this:

```js

  function createTimebarTextItem(xId, xVisible, x, y, xWidth, xTask) {
    if (!xVisible) {
      return null;
    }
    return (
      <TimebarTextItem
        key={xId}
        index={xId}
        x={x}
        y={y + 25}
        title={xTask.title}
        visible={xVisible}
        timebarTextRefs={timebarTextRefs}
        width={xWidth}
      ></TimebarTextItem>
    );
  }
```

When you change a transform attribute of any container (like `y` of `Layer`), Konva is doing plenty of recalculations. Even for invisible nodes. So removing that should be simpler for Konva to handle.

**Comment by SBenni** [comment]
http://myplanner365.s3-website.eu-central-1.amazonaws.com/

This is the same project build by react-scripts build

![performance](https://github.com/konvajs/react-konva/assets/9156628/f12035f3-a273-4cd8-8f3f-fe41de016a80)

**Comment by lavrton** [comment]
I don't know. That url works good to me. I have the same 13fps, when I set 4x CPU slowdown.

**Comment by SBenni** [comment]
okay, seems to be a problem by my pc, on another machine the problem doesn't exists, sorry!

**Comment by SBenni** [comment]
Find out the problem in package.json
Very fast:
![performanceFast](https://github.com/konvajs/react-konva/assets/9156628/e36ac864-3682-4ba7-bf3e-dda9de13bd72)

Very slow:
![performanceSlow](https://github.com/konvajs/react-konva/assets/9156628/6c3f4aef-31e7-41d3-9083-edf5d8f8366d)
