### ISSUE TITLE
Shapes with opacity do not correctly apply layer pixelRatio and can appear blurry on zoom in

### ISSUE THREAD

**Issue by florton** [konvajs/react-konva#784]
In order to prevent blurriness on browser zoom with shapes I use the following code on the window resize handler

```
  Konva.pixelRatio = window.devicePixelRatio
  layerRef.current.canvas.setPixelRatio(Konva.pixelRatio)
  layerRef.current.draw()
```

This works as expected however I noticed this seems to break if the shape has an `opacity` of less than 1.
I was able to reproduce with a minimal example in react-konva, however, I do not see this behavior when I tried to make a minimal example with just konva.

Reproduction steps:
- Open the following examples
- Zoom the browser out all the way and reload / click run
- Zoom the browser in all the way
- Notice on the react-konva demo the transparent circle is very blurry, but the normal circle is not

![image](https://github.com/konvajs/react-konva/assets/8818749/f722f2ac-05c1-4a22-a384-ed2da0f6bf63)

React-Konva Demo:
https://codesandbox.io/p/sandbox/gracious-water-xvn4h7

Konva Demo: (Could not reproduce)
https://jsfiddle.net/ws3vtzd4/2/

**Comment by lavrton** [comment]
Why are you changing pixel ratio?

On don't see any blur in MacOs on Chrome. What is your system?

**Comment by florton** [comment]
@lavrton The layer pixel ratio does not automatically update when the user zooms in or out with the browser. Without changing it, all the shapes will be blurry in the examples if the page is zoomed in. I am using chrome on windows. 

It is possible the issue is not present on macOS. However, please confirm that on the codesandbox example, you zoomed out all the way, clicked refresh in the browser preview tab, and the zoomed all the way in. 
![image](https://github.com/konvajs/react-konva/assets/8818749/bcfc2166-ead1-456a-a73c-033fc41166f3)

**Comment by lavrton** [comment]
I see now.

Shapes with (1) stroke and (2) fill and (3) opacity are rendered via special "buffer render".  More about this behavior here: https://konvajs.org/docs/performance/Disable_Perfect_Draw.html

There are two solutions for your issue:

1. First, you can just follow the tip from the documentation and disable "perfectDraw".

2. Or you can just update pixelRatio of the stage's buffer canvas: 

```js
layerRef.current
        .getStage()
        .bufferCanvas.setPixelRatio(window.devicePixelRatio);
```

**Comment by florton** [comment]
@lavrton Thank you for the information, I was also able to fix the issue by removing opacity and instead using hex colors with alpha values for transparency on stroke and fill.
