### ISSUE TITLE
Asynchronous drawing will exceed the cropping area

### ISSUE THREAD

**Issue by kampiu** [konvajs/react-konva#790]
![截屏2024-02-05 00 41 16](https://github.com/konvajs/react-konva/assets/23185852/89df070f-12db-4f92-b5a5-fef472532117)

This should be the original problem with Konva. I don't see any changes to Konva's original logic in Konva react. In theory, the cropped part in the image should not be drawn to the cropped part, but due to asynchronous drawing, the boundary was still drawn. Is this reasonable?

**Comment by kampiu** [comment]
> What is this `Image` function? Where and how do you use it? It looks like you just shouldn't do async call there. Instead, download image in a separate way and just pass loaded result inside.

I drew using canvas context natively in<Shape/>, here.

**Comment by kampiu** [comment]
> What is this `Image` function? Where and how do you use it? It looks like you just shouldn't do async call there. Instead, download image in a separate way and just pass loaded result inside.

Just like this

```typescript
import React, { useCallback } from "react"
import { Shape } from "react-konva"

function Demo() {
  const getImage = useCallback(
    async (url) =>
    // getCanvasImageSource
      Promise.resolve(/** CanvasImageSource */),
    [],
  )

  return (
    <Shape
      sceneFunc={(context, shape) => {
        context.beginPath()

        // getImage: () => Promise<CanvasImageSource>
        getImage()
          .then((image) => {
            context.drawImage(image, x, y, width, height)
          })
          .catch(() => {})
      }}
    />
  )
}

```

**Comment by lavrton** [comment]
You just shouldn't do that. `sceneFunc` must be synchronous. I it shouldn't load any data. Only rendering on the canvas. You can use `useImage` hook instead.

```js
const Demo = () => {
  const [image] = useImage(url);
  return <Image image={image} />;
};
```
