### ISSUE TITLE
Free drawing performance

### ISSUE THREAD

**Issue by TerraStudio** [konvajs/react-konva#791]
I am currently building a whiteboard app with konva in react. 

I looked at the free drawing example and took it as the base code. 
But when I create like 80 lines, the performance on my iPad starts to drop rapidly.
I made a few optimizations like not always updating the state when a new point is added to the currently drawn line. Instead I have another state just for the currently drawn line which gets updated. After the touch ends, the currently drawn line gets added to overall state with the canvas data. The currently drawn line is in a separate layer.

I also deactivated listening for the layers. The state is managed by "zustand" and currently I am using a lot to "memo". According to the console output, the lines don't get re-rendered, while I draw a new line. After the new line is added to the other lines, all of them get unfortunately rendered. I couldn't figure out a way to prevent this yet.

Question: 

Do you have recommendations, how I could increase the performance? The app shall be used for exams, hence the free drawing part is very important and can become rather big.

**Comment by lavrton** [comment]
1. You have to measure the performance. What exactly is slow? React reconciler? Konva rendering?
2. Konva is not ideal for heavy free handle renders, by default Konva re-renders full scene. Usually, it is not very necessary for drawing apps
3. Use full power cache. For example, when you finish drawing, you can cache all previous lines, so Konva don't have re-render them again. Or you can convert all lines into bitmap image with external canvas manually.

**Comment by TerraStudio** [comment]
So instead of working with memo and so on, would you rather recommend going with the cache? 
Do you have a short example, how to work with cache in react?

**Comment by lavrton** [comment]
> So instead of working with memo and so on, would you rather recommend going with the cache?

First, you need to measure what is slow. it doesn't make sense to optimize Konva rendering if React part is slow.

> Do you have a short example, how to work with cache in react?

Access node via https://konvajs.org/docs/react/Access_Konva_Nodes.html
Then use Konva mathods for cache.

**Comment by TerraStudio** [comment]
Thanks so far. Interestingly, caching the background image (Din A4 paper) made the performance even worse and the image wasn't shown on my iPad anymore.

I guess I will try to measure the performance in a next step.. Currently it feels like whenever I tried to optimize something, I got worse.

Do you think, that a whiteboard app with free drawing on multiple Din A4 size pages is possible with Konva and React in general?

**Comment by lavrton** [comment]
Without knowing the details, I can't say whether it is really possible or not. Sounds like yes, but may depend on some use cases.

**Comment by TerraStudio** [comment]
I gave every Line component a ref:

`<Line key={value.id} ref={value.ref} .../>`

Whenever the objects updates, I try to cache the line, so that I won't get re-rendered again.

```
useEffect(() => {
    for(let i = 0; i < objects.length; i++) {
      objects[i].ref.current.cache();
    }
  }, [objects]);
```
  
  Is this is a correct way to do I and is there a way to see, If they are actually won't be re-rendered again?

**Comment by TerraStudio** [comment]
Nice I followed your advise with caching:

```
useEffect(() => {
    linesRef.current.getLayer().cache({pixelRatio: 1, width: PAGE_WIDTH, height: PAGE_HEIGHT});
    bgRef.current.cache({pixelRatio: 1, width: PAGE_WIDTH, height: PAGE_HEIGHT});
  }, [objects]);
```

Made a big difference.
