### ISSUE TITLE
Arrow Drag and Transform using anchors not working

### ISSUE THREAD

**Issue by MichaelMjc** [konvajs/react-konva#796]
I have this [codesandbox](https://codesandbox.io/p/sandbox/arrow-transformer-forked-j5dvn?file=/index.js:103,42) example that is pretty perfect for something I'm building, but I can't seem to figure out how to fix one little bug. Steps to reproduce:

1. Move arrow point using anchor. Snaps into place as expected.
2. Drag arrow, gets dragged into place as expected.
3. Now go and move the arrow point using anchor again and the snap is off.

Why is this happening and how can I fix it?

**Comment by lavrton** [comment]
I think your state is confusing. The position of the arrow/line should be defined by just two points. But you have points in `arrowPos` and another position in `xAndY`. In the case, I would prefer to reset the position of a line back to `{0, 0}` and adjust `points`.

If you prefer to keep both, then you need to account `xAndY` in `onDragEnd` of anchor.

**Comment by MichaelKic** [comment]
> I think your state is confusing. The position of the arrow/line should be defined by just two points. But you have points in `arrowPos` and another position in `xAndY`. In the case, I would prefer to reset the position of a line back to `{0, 0}` and adjust `points`.
> 
> If you prefer to keep both, then you need to account `xAndY` in `onDragEnd` of anchor.

Thanks for the speedy response! This is a sandbox I found from someone else so I didn't originally write it. Whatever works I'm going to use. So how would the state change if we removed the xAndY state piece?

**Comment by MichaelMjc** [comment]
> I think your state is confusing. The position of the arrow/line should be defined by just two points. But you have points in `arrowPos` and another position in `xAndY`. In the case, I would prefer to reset the position of a line back to `{0, 0}` and adjust `points`.
> 
> If you prefer to keep both, then you need to account `xAndY` in `onDragEnd` of anchor.

Thanks for the speedy response @lavrton ! This is a sandbox I found from someone else so I didn't originally write it. Whatever works I'm going to use. So how would the state change if we removed the xAndY state piece?

**Comment by lavrton** [comment]
Something like this: https://codesandbox.io/p/sandbox/konva-arrow-anchor-j5dvn?file=%2Findex.js%3A88%2C21

**Comment by MichaelMjc** [comment]
> Something like this: https://codesandbox.io/p/sandbox/konva-arrow-anchor-j5dvn?file=%2Findex.js%3A88%2C21

Fantastic. Exactly what I need. Thank you so much @lavrton !
