### ISSUE TITLE
load data to stage

### ISSUE THREAD

**Issue by Komodood** [konvajs/react-konva#797]
I want to implement data loading in Stage, but I can't figure out how to do it in the right way

More specifically: Konva.Stage.create() does its job perfectly, but can I use the JSX format correctly in this case?

p.s. Perhaps the answer already exists, but I don't remember where it was discussed.

**Comment by lavrton** [comment]
In react-konva you should do it the same way, as you do it in regular react application. By just loading state. If you already have existing JSON's from konva, I recommend convert them into state data.
