### ISSUE TITLE
Breaking changes in React experimental branch

### ISSUE THREAD

**Issue by jackpope** [konvajs/react-konva#799]
React is preparing changes, including some breaking, for the [next major release](https://react.dev/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024#the-next-major-version-of-react). There are changes to the Reconciler that break `react-konva`.

To repro:
- Install react and react-dom @experimental
- Load react-konva demo
- Observe error

sandbox: https://codesandbox.io/p/sandbox/react-konva-experimental-mvwcqq

To prepare for the new versions, `react-konva` should build against the latest changes by upgrading `react-reconciler`, which requires new methods since 0.29.0. [See all](https://github.com/facebook/react/blob/main/packages/react-reconciler/src/forks/ReactFiberConfig.custom.js#L44-L78)

You'll likely need to update `its-fine` to the latest patch as well to fix `useContextBridge`

**Comment by lavrton** [comment]
Released `react-konva@19`
