### ISSUE TITLE
Trouble with Drag-and-Drop on Mobile Devices in React (with react-konva)

### ISSUE THREAD

**Issue by dayoolacodes** [konvajs/react-konva#801]
I'm encountering an issue where drag-and-drop functionality implemented with elements within a react-konva canvas in a React application works perfectly on desktop browsers but fails on mobile devices. Despite setting the draggable attribute on the elements, dragging doesn't initiate on touch events.

I have a React application that includes components for displaying icons ( elements) within a grid (IconsGrid) and on a canvas (react-konva). These icons should be draggable using the HTML5 drag-and-drop feature facilitated by react-konva. While this works flawlessly on desktop browsers, it doesn't respond to touch events on mobile devices.

More context here [https://stackoverflow.com/questions/78276646/trouble-with-drag-and-drop-on-mobile-devices-in-react-with-react-konva](url)

**Comment by lavrton** [comment]
I don't think this is related to react-konva.
You may need some extra js to enable drag&drop of DOM elements on mobile. This may help: https://www.horuskol.net/blog/2020-08-15/drag-and-drop-elements-on-touch-devices/
