### ISSUE TITLE
Transformer spatial propeties based on a specific child

### ISSUE THREAD

**Issue by dodeca-6-tope** [konvajs/react-konva#810]
Can I transform a group of shapes but have the transformer compute its spatial properties based only on one of those shapes?

**Comment by dodeca-6-tope** [comment]
Thanks for the lib BTW it's great!

**Comment by lavrton** [comment]
That is current not supported and I don't have any plans for that. The workaround:
1. Attach transformer only into one shape (it can be an invisible "fake" shape).
2. Recalculate transformation of group based on new properties of attached shape.
