### ISSUE TITLE
Zindex of components being generated from seperate arrays

### ISSUE THREAD

**Issue by harrysayers** [konvajs/react-konva#811]
I've looked through docs and see that controlling the zIndex is best controlled using order of components in the renderer. How do I control the zIndex when I have many components that are all iterating through separate arrays? 

App.js is rendering two components which produce multiple shapes from separate arrays.
```
// Rect will have zIndex = 0
// Circle will have zIndex = 1
const App = () =>
   <Stage>
     <Component1>
     <Component2>
   <Stage>
```

```
// RectArr is an array of objects containing properties for rect
const Component1 = () =>
   <Group>
     {
             RectArr.map((item, i) => (
                 <Rect item={item}>
             ))
     }
   <Group>
```
   
```
// CircleArr is an array of objects containing properties for circle
const Component2 = () =>
   <Group>
     {
             CircleArr.map((item, i) => (
                 <Circle item={item}>
             ))
     }
   <Group>
```

Re-arranging the order of all component1 or component2 shapes makes sense, it's just changing the order of the array... however what if I want component1 then component2 then component1 etc to be rendered so they overlap each other? I can't see any documentation for this situation?

Any help would be greatly appreciated.

**Comment by lavrton** [comment]
Make a combined array where all items are mixed in correct order.

```js
TotalArray.map((item) => {
  if (item.type === 'circle') {
    return <Circle item={item} />
  }
  if (item.type === 'rect') {
    return <Rect item={item} />
  }
})
```

**Comment by harrysayers** [comment]
Are you saying merge both arrays into one ? or make a third array which is a reference to all components in both arrays?

**Comment by lavrton** [comment]
It depends on your app and your preferences. I don't know what is simpler for you.
Most likely, I would use just one array with a list of everything.

**Comment by harrysayers** [comment]
Thank you!
