### ISSUE TITLE
react-konva is breaking with nextjs 15. Cannot read properties of undefined (reading 'ReactCurrentOwner')

### ISSUE THREAD

**Issue by heyletscode** [konvajs/react-konva#814]
The library works well with nextjs 14 but breaks with next 15. I have tried back and forth with next version 14 and 15 to make sure thats the only variable and yeah it only breaks with version 15. 

![Screenshot 2024-11-02 132752](https://github.com/user-attachments/assets/ff9b1df4-0474-41de-9b2c-d584c5f3e5bd)

**Comment by lavrton** [comment]
You can try `npm install react-konva@19.0.0-1`.
But I am waiting for official release of react@19.

**Comment by Fearless09** [comment]
@lavrton I also had the same issue, and `npm install react-konva@19.0.0-1` fixed the error. But now I am having a `Cannot find module 'canvas` error and I have tried:

```
const nextConfig = {
  webpack: (config) => {
    config.externals = [...config.externals, { canvas: 'canvas' }]; // required to make Konva & react-konva work
    return config;
  },
};

module.exports = nextConfig;
```

But it didn't fixed the error, please how can I fix this error?
