### ISSUE TITLE
Minimum Size and flipping

### ISSUE THREAD

**Issue by vcalle47** [konvajs/react-konva#822]
Hello,

I'm using the excellent Konva library in my project where I'm trying to draw rectangles with a label. Now, I have achieved that the rectangle and label move like group. Also I'm allowing resize only the rectangle, always with a minimum size of 50x50.

However, when I arrive to the minimum and I am still moving the cursor pointer, the rectangle moves like a flip move, so the label separates from the rectangle and it's a behaviour some strange. 

I have tested a lot of combinations to control the movement, flipEnabled on the transformer, minimum size... but I can't control the flip.

Do you have some suggestions?

Thank you!

Normal rectangle:
![image](https://github.com/user-attachments/assets/4bb08a98-8117-4a0c-bcaf-3f58a05309ff)

Minimum size (rectangle blocked)
![image](https://github.com/user-attachments/assets/6239862e-a7c4-4f34-84c4-1bfbc91cb5c6)

Cursor on the top left clicking the resize of bottom right:
![image](https://github.com/user-attachments/assets/ab1e868e-88a5-4b08-b428-53decda8b3b4)

**Comment by lavrton** [comment]
Can you make a little demo of your code?

**Comment by vcalle47** [comment]
`import React, { useState, useRef, useEffect } from 'react';
import { Stage, Layer, Rect, Text, Group, Transformer, Tag, Label, Image } from 'react-konva';
import CustomButton from '../CustomButton/CustomButton';
import Konva from 'konva';
import { KonvaEventObject } from 'konva/lib/Node';
import { ClearButton } from '../ClearButton/ClearButton';
import { Dropdown } from '../Dropdown/Dropdown';
import styles from './Canvas.module.scss';
import useModal from '@/hooks/useModal';
import { CanvaTools } from '@/types/UniformObject';
import { closeModal, ModalActionTypes } from '@/contexts/Modal/ModalContext';
import { LabelDirection, NamePosition, PositionLabel, Shape } from '@/types/ErrorConfigurationTypes';
import { useTranslation } from 'react-i18next';
import { v4 } from 'uuid';
import { Box } from 'konva/lib/shapes/Transformer';

const CANVAS_WIDTH = 1200;
const CANVAS_HEIGHT = 750;
const MIN_SIZE = 50;

const Canvas = ({ pictureError }: { pictureError?: string }) => {
  const { t } = useTranslation();
  const [shapes, setShapes] = useState<Shape[]>([]);
  const stageRef = useRef<Konva.Stage | null>(null);
  const transformerRef = useRef<Konva.Transformer | null>(null);
  const { dispatch } = useModal();
  const [tools, setTools] = useState<CanvaTools>({ labelPosition: 'above', color: '#000000' });
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [backgroundImage, setBackgroundImage] = useState<HTMLImageElement | null>(null);

  useEffect(() => {
    if (pictureError) {
      const img = new window.Image();
      img.src = `data:image/png;base64,${pictureError}`;
      img.onload = () => {
        setBackgroundImage(img);
      };
    }
  }, [pictureError]);

  useEffect(() => {
    if (selectedId && transformerRef.current) {
      const stage = transformerRef.current.getStage();

      if (stage) {
        const selectedNode = stage.findOne(`#${selectedId}`);

        if (selectedNode) {
          transformerRef.current.nodes([selectedNode]);
          transformerRef.current.getLayer()?.batchDraw();
        }
      }
    } else {
      transformerRef.current?.nodes([]);
    }
  }, [selectedId]);

  const addRectangle = (e: React.DragEvent<HTMLDivElement>) => {
    const stage = stageRef.current;

    if (stage) {
      const stageBox = stage.container().getBoundingClientRect();
      const position = { x: e.clientX - stageBox.left, y: e.clientY - stageBox.top };

      const newShape: Shape = {
        id: v4(),
        x: position.x,
        y: position.y,
        width: 120,
        height: 80,
        stroke: '#000000',
        color: 'white',
        type: 'text',
        labelConfig: {
          x: 0,
          y: 0,
          opacity: 0.8,
          visible: false,
          text: 'etiqueta',
          position: 'above',
          direction: 'down',
        }
      };
      setShapes([...shapes, newShape]);
    }
  };

  const handleAddShape = (e: React.DragEvent) => {
    e.dataTransfer.setData("text/plain", "rectangle");
  };

  const handleSelect = (shape: Shape) => {
    setSelectedId(shape.id);
    setTools({ labelPosition: shape.labelConfig.position, color: shape.stroke });

    if (transformerRef.current) {
      const selectedNode = stageRef.current?.findOne(`#${shape.id}`);

      if (selectedNode) {
        transformerRef.current.nodes([selectedNode]);
        transformerRef.current.getLayer()?.batchDraw();
      }
    }
  };

  const deselect = (e: KonvaEventObject<MouseEvent>) => {
    if (e.target === e.target.getStage()) {
      setSelectedId(null);
      setTools({ labelPosition: 'above', color: '#000000' });
    }
  };

  const deleteShape = () => {
    setShapes(shapes.filter((shape) => shape.id !== selectedId));
    setSelectedId(null);
    dispatch(closeModal());
  };

  const handleDelete = () => {
    dispatch({
      type: ModalActionTypes.SET_MODAL,
      payload: {
        content: t('ErrorConfigurations.DeleteTreeMessage'),
        handleConfirm: () => deleteShape(),
        title: t('ErrorConfigurations.DeleteTreeTitle'),
      },
    });
  };

  const assignError = ()  => {
    console.log("assign");
  };

  const handleColorChange = (color: string) => {
    setShapes(shapes.map((shape) => shape.id === selectedId ? { ...shape, stroke: color } : shape));
    setTools({ ...tools, color });
  };

  const handleLabelPositionChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setTools({ ...tools, labelPosition: e.target.value as NamePosition });

    if (selectedId) {
      setShapes(shapes.map((s) => s.id === selectedId ? {
        ...s,
        labelConfig: {
          ...s.labelConfig,
          position: e.target.value as NamePosition,
          direction: PositionLabel[e.target.value as NamePosition] as LabelDirection,
         },
        }
        : s
      ));
    }
  };

  const calculateLabelPosition = (shape: Shape) => {
    const { labelConfig, width, height } = shape;
    const offset = 10;

    switch (labelConfig.position) {
      case 'above':
        return { x: width / 2, y: -offset, textAlign: 'center', verticalAlign: 'bottom' };
      case 'below':
        return { x: width / 2, y: height + offset, textAlign: 'center', verticalAlign: 'top' };
      case 'left':
        return { x: -offset, y: height / 2, textAlign: 'right', verticalAlign: 'middle' };
      case 'right':
        return { x: width + offset, y: height / 2, textAlign: 'left', verticalAlign: 'middle' };
      default:
        return { x: width / 2, y: -offset, textAlign: 'center', verticalAlign: 'bottom' };
    }
  };

  const handleTransform = (e: KonvaEventObject<Event>, shape: Shape) => {
    const node = e.target as Konva.Rect;
    const scaleX = node.scaleX();
    const scaleY = node.scaleY();
    let newWidth = Math.max(MIN_SIZE, node.width() * scaleX);
    let newHeight = Math.max(MIN_SIZE, node.height() * scaleY);
    const box = node.getClientRect();

    if (node.x() < 0) {
      newWidth = MIN_SIZE;
    }

    if (node.y() < 0) {
      newHeight = MIN_SIZE;
    }

    node.scaleX(1);
    node.scaleY(1);

    if (newWidth === MIN_SIZE || newHeight === MIN_SIZE) {
      node.getLayer()?.batchDraw();

      return;
    }

    const updatedShapes = shapes.map((s) => s.id === shape.id ? { ...s, width: newWidth, height: newHeight } : s);
    setShapes(updatedShapes);
    node.getLayer()?.batchDraw();
  };

  const limitSize = (oldBox: Box, newBox: Box) => {
      if (newBox.width < MIN_SIZE || newBox.height < MIN_SIZE) {
        return oldBox;
      }

      return newBox;
  };

  const handleDragMove = (e: KonvaEventObject<DragEvent>, shape: Shape) => {
    const stage = stageRef.current;
    const node = e.target;

    if (stage) {
      const labelOffset = 40;
      let newX = node.x();
      let newY = node.y();
      // Left limit
      if (newX < 0 + (shape.labelConfig.position === 'left' ? labelOffset : 0)) {
        newX = 0 + (shape.labelConfig.position === 'left' ? labelOffset : 0);
      }
      // Up limit
      if (newY < 0 + (shape.labelConfig.position === 'above' ? labelOffset : 0)) {
        newY = 0 + (shape.labelConfig.position === 'above' ? labelOffset : 0);
      }
      // Right limit
      if (newX + shape.width > CANVAS_WIDTH - (shape.labelConfig.position === 'right' ? labelOffset : 0)) {
        newX = CANVAS_WIDTH - shape.width - (shape.labelConfig.position === 'right' ? labelOffset : 0);
      }
      // Down limit
      if (newY + shape.height > CANVAS_HEIGHT - (shape.labelConfig.position === 'below' ? labelOffset : 0)) {
        newY = CANVAS_HEIGHT - shape.height - (shape.labelConfig.position === 'below' ? labelOffset : 0);
      }

      node.x(newX);
      node.y(newY);
      setShapes(shapes.map((s) => s.id === shape.id ? { ...shape, x: newX, y: newY } : s));
    }
  };

  return (
    <div onDragOver={(e) => e.preventDefault()} onDrop={addRectangle}>
      <div className={styles.Toolbar}>
        <CustomButton className={styles.ToolGrab} content='+' draggable handleDrag={handleAddShape} />
        <ClearButton className={styles.Tool} handleClick={handleDelete} isDisabled={!selectedId} />
        <div className={selectedId ? styles.ColorPicker : styles.ColorPickerDisabled}>
          <input value={tools.color} className={styles.Tool} type="color" onChange={(e) => handleColorChange(e.target.value)} disabled={!selectedId} />
        </div>
        <Dropdown extraClass={styles.Tool} label='ErrorConfigurations.Forms.NamePosition' onChange={handleLabelPositionChange} value={tools.labelPosition} options={['above', 'below', 'left', 'right']} />
        <CustomButton className={styles.Tool} handleClick={assignError} content='Assign Error' />
      </div>
      <div className={styles.Canvas}>
        <Stage
          width={CANVAS_WIDTH}
          height={CANVAS_HEIGHT}
          style={{ margin: '0 auto', display: 'block' }}
          ref={stageRef}
          onMouseDown={deselect}
        >
          <Layer>
            {backgroundImage && <Image image={backgroundImage} x={0} y={0} listening={false} />}
            {shapes.map((shape) => (
              <Group
                key={shape.id}
                x={shape.x}
                y={shape.y}
                draggable
                onDragMove={(e) => handleDragMove(e, shape)}
                onClick={() => setSelectedId(shape.id)}
                rotation={shape.rotation || 0}
              >
                <Rect
                  width={shape.width}
                  height={shape.height}
                  fill="rgba(0,0,0,0.2)"
                  stroke={shape.stroke}
                  strokeWidth={2}
                  onTransform={(e) => handleTransform(e, shape)}
                  onClick={() => handleSelect(shape)}
                  id={shape.id}
                  rotation={shape.rotation}
                />
                <Label {...calculateLabelPosition(shape)}>
                  <Tag fill="black" pointerDirection={shape.labelConfig.direction} pointerWidth={10} pointerHeight={10} />
                  <Text text={shape.labelConfig.text} fontSize={12} padding={5} fill="white" />
                </Label>
              </Group>
            ))}
            <Transformer ref={transformerRef} rotateEnabled={false} flipEnabled={false} boundBoxFunc={limitSize} />
          </Layer>
        </Stage>
      </div>
    </div>
  );
};

export default Canvas;
`

**Comment by lavrton** [comment]
that is not a demo, it is a large part of the codebase. By the demo, I mean something like this: https://codesandbox.io/p/sandbox/github/konvajs/site/tree/master/react-demos/transformer?from-embed

**Comment by lavrton** [comment]
It is private

**Comment by lavrton** [comment]
I would separate the label from the rect, so it is not part of the draggable group. I think it will make things simpler.

```js
{shapes.map((shape) => (
              <Group key={shape.id}>
                <Rect
                  x={shape.x}
                  y={shape.y}
                  draggable
                  width={shape.width}
                  height={shape.height}
                  fill="rgba(0,0,0,0.2)"
                  stroke={shape.stroke}
                  strokeWidth={2}
                  onTransform={(e) => handleTransform(e, shape)}
                  onClick={() => handleSelect(shape)}
                  id={shape.id}
                  rotation={shape.rotation}
                  onDragMove={(e) => handleDragMove(e, shape)}
                  onClick={() => setSelectedId(shape.id)}
                  rotation={shape.rotation || 0}
                />
                <Group x={shape.x} y={shape.y}>
                  <Label {...calculateLabelPosition(shape)}>
                    <Tag
                      fill="black"
                      pointerDirection={shape.labelConfig.direction}
                      pointerWidth={10}
                      pointerHeight={10}
                    />
                    <Text
                      text={shape.labelConfig.text}
                      fontSize={12}
                      padding={5}
                      fill="white"
                    />
                  </Label>
                </Group>
              </Group>
            ))}
```

https://codesandbox.io/p/sandbox/konva-rectangles-labels-forked-63gv2x?file=%2Fsrc%2FApp.js%3A333%2C22
